### PR TITLE
fix Disabled Default Certifications Still Visible on Assets

### LINKED ISSUE #24583: Disabled Default Certifications Still Visible on Assets
**Affected module**
Does it impact the UI, backend or Ingestion Framework? --UI

**Describe the bug**

- When a default certification is disabled, it is still visible under the Certification section of assets where it was previously applied. The expected behavior is that once a default certification is disabled, it should no longer be visible on assets (at least for non-admin users), or should clearly reflect its disabled state.
- This behavior causes confusion, as users assume disabling a default certification will fully remove or hide it from asset views.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
- Disabled default certifications should not be visible on assets
- They should be clearly marked as inactive/disabled.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by sonika-shah**
### Describe your changes:

Fixes  #24583

- [x] Fix backend logic
- [x]  Backend test - to test various combintaiuon of params in  test_listTagsWithDisabledAndParentParams

    test_disabledCertificationNotVisibleOnAssets - 

-   Data Integrity: Disabled tags/certifications remain on assets where previously applied
-   State Reflection: Tag entities correctly show disabled=true when retrieved
-   Cascading Effect: Disabling classification disables all its tags
-   Selective Impact: Disabling one tag doesn't affect other tags in same classification
-    New Application Prevention: Disabled tags cannot be applied to new assets (BAD_REQUEST)
-   Enabled Tags Remain Available: Non-disabled tags can still be used

I worked on ... because ...

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

---

## Summary by Gitar

- **Backend query refactor:**
  - Extracted `buildTagQueryConditions()` helper in `CollectionDAO.java` to handle dual-level disabled filtering (classification + tag)
  - Changed NULL handling from `IS NULL OR` pattern to `COALESCE(value, FALSE)` for MySQL and PostgreSQL
- **API parameter change:**
  - Removed `@DefaultValue("false")` from `disabled` parameter in `TagResource.java` to make filtering optional
- **Comprehensive backend tests:**
  - Added `test_disabledCertificationNotVisibleOnAssets` and `test_listTagsWithDisabledAndParentParams` with 530+ lines covering tag lifecycle, cascading disables, and query combinations
- **Frontend certification filtering:**
  - Modified `Certification.component.tsx` to request only enabled tags with `disabled: false` parameter
  - Added toggle UI in `ClassificationDetails.tsx` for enabling/disabling tags with permission checks
- **E2E test coverage:**
  - Created `CertificationDropdown.spec.ts`, `SystemCertificationTags.spec.ts` with isolated execution for system tags (Gold/Silver/Bronze)
  - Added test utilities in `certification.ts` and `tag.ts` for tag state management

<sub>This will update automatically on new commits.</sub>

---

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/playwright/utils/certification.ts [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+  const response = await apiContext.get(
+    '/api/v1/classifications/name/Certification'
+  );
+  const classification = await response.json();
+
+  await apiContext.patch(`/api/v1/classifications/${classification.id}`, {
+    data: [{ op: disabled ? 'add' : 'remove', path: '/disabled', value: true }],
+    headers: { 'Content-Type': 'application/json-patch+json' },
+  });
+};
```
Comment (karanh37) [inline openmetadata-ui/src/main/resources/ui/playwright/utils/certification.ts]: will prefer moving them to tag utils and make common for all tags not specific to certification

File: openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Tag.spec.ts [hunk 2]
```diff
@@ -313,6 +313,79 @@ test.describe('Tag Page with Admin Roles', () => {
       dataTestId: 'owner-link',
     });
   });
+
```
Comment (karanh37) [inline openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Tag.spec.ts:316]: Let's also add a test for disabled tags.
Visit disabled tag page and verify we shouldn't be able to attach asset from "Assets" tab

Comment (karanh37) [reply openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Tag.spec.ts:316]: Another test i can think of, make tags disabled and go to table page and check it should not appear in tags component.

**Review by karanh37 — CHANGES_REQUESTED** [review]

File: openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Tag.spec.ts (hunk 2 above)
Comment (siddhant1) [reply openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Tag.spec.ts:316]: >Another test i can think of, make tags disabled and go to table page and check it should not appear in tags component.

This already exists https://github.com/open-metadata/OpenMetadata/pull/18242

**Review by karanh37 — APPROVED** [review]
