### PR TITLE
fix(ui) #10502 dbt tab improvement

### LINKED ISSUE #10502: Show dbt node fields in the UI
**Feature**
Below mentioned fields are captured on the ingestion side but not displayed on the UI for dbt:

- rawSql (Display this field if the sql field is empty)
- path

image

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes:

Fixes #10502

- dbt tab UI improvement
- [updated lineage UI](https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1507915691)

image

image

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.component.tsx [hunk 1]
```diff
@@ -798,13 +797,7 @@ const DatasetDetails: React.FC<DatasetDetailsProps> = ({
...
             )}
             {activeTab === 8 && Boolean(dataModel?.sql) && (
-              <Card className="m-y-md h-full">
-                <SchemaEditor
-                  className="tw-h-full"
-                  mode={{ name: CSMode.SQL }}
-                  value={dataModel?.sql || ''}
-                />
-              </Card>
+              <DbtTab dataModel={dataModel} />
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.component.tsx:800]: We now have fallback to rawSQL so in above condition we can add that too?
Boolean(dataModel?.sql || dataModel?.rawSQL)

File: openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DbtTab/DbtTab.component.tsx [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+  const { t } = useTranslation();
+
+  const sqlQuery = useMemo(
+    () => dataModel?.sql ?? dataModel?.rawSql ?? '',
+    [dataModel]
+  );
+  const queryLine = useMemo(() => {
+    const lineCount = split(sqlQuery, '\n').length;
+
+    return pluralize(lineCount, t('label.line'));
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DbtTab/DbtTab.component.tsx:35]: Let's not use `pluralize` since it's not extensible for localisations

File: openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.component.tsx (hunk 1 above)
Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.component.tsx:800]: nice catch, thanks!

**Review by chirag-madlani — APPROVED** [review]
