### PR TITLE
Fix issue 4701:- Fixed broken tour guide

### LINKED ISSUE #4701: UI: Fix Guided Tour
The guided tour is broken after adding recent changes to the Explore page. 

Check the below screen-shot for the step where the guided tour stops and unable to proceed further.

Screen Shot 2022-05-04 at 1 06 57 AM

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes :

Closes #4701 Fixed broken tour guide

#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/constants/mockTourData.constants.ts [hunk 1]
```diff
@@ -3454,30 +3460,36 @@ export const mockSearchData = {
           {
             _index: 'table_search_index',
             _type: '_doc',
-            _id: 'c0057714-2d87-4bb9-a300-7032676fc6de',
-            _score: 5,
+            _id: '644405ad-60fe-4329-884f-fc3e3ab6c6a5',
+            _score: 5.028171,
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/constants/mockTourData.constants.ts:3464]: Do we need this score to have decimal precision?

Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/constants/mockTourData.constants.ts:3464]: Hey just took updated response from api.

**Review by vivekratnavel — APPROVED** [review]
