### PR TITLE
FIX[#14565]: container and ml models custom property apis are sending wrong payload

### LINKED ISSUE #14565: container and ml models custom property apis are sending wrong payload
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**

**To Reproduce**

Screenshots or steps to reproduce

image

Visit https://sandbox-beta.open-metadata.org/mlmodel/mlflow_svc.eta_predictions/custom_properties and try to update the custom property.

```
Request URL:https://sandbox-beta.open-metadata.org/api/v1/mlmodels/6ef964b1-edb7-4d7c-85f1-51845197206c
Request Method:PATCH
Status Code:500 Internal Server Error
```

**payload**

```js
[
    {
        "op": "remove",
        "path": "/votes"
    },
    {
        "op": "remove",
        "path": "/dataProducts"
    },
    {
        "op": "remove",
        "path": "/domain"
    },
    {
        "op": "remove",
        "path": "/usageSummary"
    },
    {
        "op": "remove",
        "path": "/tags"
    },
    {
        "op": "remove",
        "path": "/followers"
    },
    {
        "op": "remove",
        "path": "/dashboard"
    },
    {
        "op": "add",
        "path": "/extension",
        "value": {
            "testing": "testing"
        }
    }
]
```

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
### Describe your changes:

Fixes #14565 

I worked on issue #14565 

https://github.com/open-metadata/OpenMetadata/assets/59080942/882f8951-7530-450f-b210-a43d3de7a8d6

#
### Type of change:

- [x] Bug fix

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/pages/ContainerPage/ContainerPage.tsx [hunk 1]
```diff
@@ -245,11 +245,17 @@ const ContainerPage = () => {
     }
   };
 
-  const handleUpdateContainerData = (updatedData: Container) => {
-    const jsonPatch = compare(omitBy(containerData, isUndefined), updatedData);
+  const handleUpdateContainerData = useCallback(
+    (updatedData: Container) => {
+      const jsonPatch = compare(
+        omitBy(containerData, isUndefined),
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/pages/ContainerPage/ContainerPage.tsx:251]: Why this `omitBy` required here?

**Review by chirag-madlani — APPROVED** [review]
