### PR TITLE
ISSUE #20962 - Issues with test case alerts

### LINKED ISSUE #20962: Alert Triggered on Both Failure and Success of the Test Case
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
-- backend

**Describe the bug**
-- We have an alert configured to trigger **only on failure**. Earlier today, the alert was triggered correctly due to a failure. However, since that initial failure, we are now receiving notifications **even when the alert passes**, which is not expected behavior.

**To Reproduce**

Screenshots or steps to reproduce

-- 1. Set an alert to trigger only on failure.
2. Trigger a failure (alert correctly fires).
3. Let the condition pass in subsequent runs.
4. Observe that notifications continue even when the condition passes.

**Expected behavior**
--- The alert should only trigger notifications when the condition (failure) is met. Success events should not send notifications if the alert is set to only trigger on failure.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### LINKED ISSUE #21121: Bug: Test case name having issues with alerts not working - REGEX
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

**Describe the bug**

**To Reproduce**
The name should have space in fqn for the test case / test suite + adding it to alerts, the alerts do not get triggered

FQN:
Core Prod.hades.creditApplication.customField.Test NULL PD Scores (pdv2) for Primary Borrower

### PR DESCRIPTION
**Pull request by TeddyCr**
### Describe your changes:

Fixes #20962 && fixes #21121

**What**
- Do not consolidate test case and test suite change events 👉 in local tests, I see change events being consolidated, where the change to the status goes from success to failed but is reverted to success (or inversingly) and hence the alerts is either triggered for a successful test or not triggered for a failing 
**[Maybe a better way to handle it than defaulting to False?]**
- record change to testCase testCaseResult field
- remove non-indexable fields on testSuites field

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [x] I have commented on my code, particularly in hard-to-understand areas. 
- [x] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Review by aji-aju — APPROVED** [review]

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java [hunk 1]
```diff
@@ -754,6 +759,7 @@ public void entitySpecificUpdate(boolean consolidatingChanges) {
           original.getUseDynamicAssertion(),
           updated.getUseDynamicAssertion());
       recordChange("testCaseStatus", original.getTestCaseStatus(), updated.getTestCaseStatus());
+      recordChange("testCaseStatus", original.getTestCaseResult(), updated.getTestCaseResult());
```
Comment (sonika-shah) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java:762]: @TeddyCr , i think it should be` recordChange("testCaseResult"`...

**Review by sonika-shah — APPROVED** [review]
