### PR TITLE
Fix issue-4575: UI: Add total count of user owned or following data entities in profile page and home page

### LINKED ISSUE #4575: UI: Add total count of user owned or following data entities in profile page and home page
There is no way to know the total number of entities owned or followed by any user until the "view all" button is clicked. It will be good to have this count visible in the appropriate sections to improve UX.

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes :

Closes #4575 UI: Add total count of user owned or following data entities in profile page and home page

#
### Type of change :

- [x] Bug fix
- [x] Improvement
- [x] New feature

#
### Frontend Preview (Screenshots) :
Home Page:-
image

User Page:-
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/MyData/MyData.component.tsx [hunk 1]
```diff
@@ -160,7 +160,7 @@ const MyData: React.FC<MyDataProps> = ({
                   data-testid="following-data"
                   to={getLinkByFilter(Ownership.FOLLOWERS)}>
                   <span className="link-text tw-font-normal tw-text-xs">
-                    View All
+                    View All <span>({followedData.length})</span>
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/components/MyData/MyData.component.tsx:163]: @ShaileshParmar11 `followedData.length` will not give us the total count. It will only have up to a maximum of 8 results since the size we request is 8.
Screen Shot 2022-05-02 at 10 20 20 AM

Comment (harshach) [reply openmetadata-ui/src/main/resources/ui/src/components/MyData/MyData.component.tsx:163]: @ShaileshParmar11 are you using the followedData.hits? that will give the right result

Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/components/MyData/MyData.component.tsx:163]: Yes, now I am using the total value from hits!

**Review by vivekratnavel — APPROVED** [review]
