### PR TITLE
Fix #18834: Introduce new setting OpenMetadataBaseUrlConfiguration to set the server endpoint

### LINKED ISSUE #18834: Slack Entity URLs Not Working If OpenMetadata URL Is Not Set in SMTP UI
**Affected module**
- Alerts and Notifications

 **Describe the bug**

- The URLs for entities in Slack messages are dependent on the OpenMetadata URL configured in the SMTP UI. If the OpenMetadata URL is not set, the entity URLs in the Slack messages fail to work.

**To Reproduce**
- Ensure that the OpenMetadata URL is not set in the SMTP UI.
- Send a message to Slack containing an entity link.
- Click on the entity link in Slack.
- Observe that the link does not work and the entity cannot be accessed.

### PR DESCRIPTION
**Pull request by Siddhanttimeline**
### Describe your changes:

Fixes #18834

1. Removed OM Base URL configuration from smtpSettings.
2. Introduced a new OpenMetadataBaseUrlConfiguration to set the server endpoint.

https://github.com/user-attachments/assets/6f1ea1d3-b8d4-4d71-8f9d-a7a66e1ad72f

#
### Type of change:

- [x] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [x] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Comment by mohityadav766** [comment]
@Siddhanttimeline also you need to update openmetadata_test.yaml for the same

File: openmetadata-service/src/main/java/org/openmetadata/service/util/email/EmailUtil.java [hunk 1]
```diff
@@ -440,6 +440,15 @@ public static Boolean isValidEmail(String email) {
     return email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$");
   }
 
+  public static String getOMBaseURL() {
```
Comment (mohityadav766) [inline openmetadata-service/src/main/java/org/openmetadata/service/util/email/EmailUtil.java:443]: we need to add this global config in the yaml as well 
as when we configure cluster this isn't a step that the user needs to be doing

**Review by mohityadav766 — CHANGES_REQUESTED** [review]
please check comments

File: openmetadata-service/src/main/java/org/openmetadata/service/util/email/EmailUtil.java (hunk 1 above)
Comment (Siddhanttimeline) [reply openmetadata-service/src/main/java/org/openmetadata/service/util/email/EmailUtil.java:443]: Noted, addressing.

File: conf/openmetadata.yaml [hunk 2]
```diff
@@ -383,6 +382,9 @@ email:
   transportationStrategy: ${SMTP_SERVER_STRATEGY:-"SMTP_TLS"}
   templates: ${TEMPLATES:-"openmetadata"}
 
+openMetadataBaseUrlConfiguration:
```
Comment (mohityadav766) [inline conf/openmetadata.yaml:385]: @harshach would it make sense to create something like below
global: 
    serverBaseUrl: {}
    other configs: {} 
or we should keep it separate? 
cc @Siddhanttimeline

Comment (harshach) [reply conf/openmetadata.yaml:385]: @mohityadav766 @Siddhanttimeline this shouldn't be part of server configs, we should let them configure in system settings and provide openmetadata-ops.sh to configure to help with devops automation

**Review by mohityadav766 — APPROVED** [review]
