### PR TITLE
fix: domain assignment for glossary term

### LINKED ISSUE #13792: Unable to add domain on glossary term
when adding domain on glossary term, 404 not find error occurred

### PR DESCRIPTION
**Pull request by karanh37**
### Describe your changes:

Fixes #13792 

I worked on ... because ...

https://github.com/open-metadata/OpenMetadata/assets/33024356/f7e655dc-eb57-4524-90fb-c40583e2c33b

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/pages/Glossary/GlossaryPage/GlossaryPage.component.tsx [hunk 1]
```diff
@@ -143,7 +143,7 @@ const GlossaryPage = () => {
     try {
       const response = await getGlossaryTermByFQN(
         glossaryFqn,
-        'relatedTerms,reviewers,tags,owner,children,votes'
+        'relatedTerms,reviewers,tags,owner,children,votes,domain'
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/pages/Glossary/GlossaryPage/GlossaryPage.component.tsx:146]: It will impact cypress tests, Have you verified this locally?

Comment (karanh37) [reply openmetadata-ui/src/main/resources/ui/src/pages/Glossary/GlossaryPage/GlossaryPage.component.tsx:146]: Yes we are not passing query params in intercept.

**Review by chirag-madlani — APPROVED** [review]
