### PR TITLE
Fix #3402: Inconsistency in activity feed for services activities

### LINKED ISSUE #3402: Inconsistency in activity feed for services activities
**Affected module**
Backend

**Describe the bug**
Inconsistency in the activity feed for services activities bug

**To Reproduce**
- Create a database service
- Edit ingestion config
- Check activity feed on my-data page

Screenshot 2022-03-14 at 5 44 52 PM

**Expected behavior**
Consistent activity feed

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
NA

### PR DESCRIPTION
**Pull request by vivekratnavel**
### Describe your changes :
See #3402 

#
### Type of change :

- [x] Bug fix

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [ ] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java [hunk 1]
```diff
@@ -107,7 +107,19 @@
...
   // List of entities whose changes should not be published to the Activity Feed
   //
-  public static final List<String> ACTIVITY_FEED_EXCLUDED_ENTITIES = List.of(USER, TEAM, ROLE, POLICY, BOTS);
+  public static final List<String> ACTIVITY_FEED_EXCLUDED_ENTITIES =
+      List.of(
+          USER,
+          TEAM,
+          ROLE,
+          POLICY,
+          BOTS,
```
Comment (harshach) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java:116]: BOTs should be there @vivekratnavel

**Review by harshach — CHANGES_REQUESTED** [review]

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java (hunk 1 above)
Comment (vivekratnavel) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java:116]: @harshach Yes, this is bit entity and not not the bot users

**Review by harshach — APPROVED** [review]
