### PR TITLE
Fix(UI)#8659: Fixed issue with wrong link for custom attributes in activity feed

### LINKED ISSUE #8659: Table link in the Activity feed notifications appears to be wrong
**Affected module**

UI

**Describe the bug**

The `table` link in the Activity feed notifications appears to be wrong.

I think it should link to
`/settings/customAttributes/tables`
but instead it is currently linking to
`/custom-properties/table`

**To Reproduce**

Add a custom property to type `table` and check the Activity feed.

Screen Shot 2022-11-10 at 7 26 42 PM

**Expected behavior**

I think it should link to
`/settings/customAttributes/tables`
but instead it is currently linking to
`/custom-properties/table`

**Version:**
 - OS: iOS
 - Python version:
 - OpenMetadata version: 0.12.2
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

None

### PR DESCRIPTION
**Pull request by aniketkatkar97**
Fixes #8659 
### Describe your changes :

I worked on fixing issue with wrong link for custom attributes in activity feed

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :
<p align="center">

https://user-images.githubusercontent.com/51777795/201313742-c60b44e1-fcd7-47c4-9c76-dcad6049272c.mov

</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

Frontend: @open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/constants/constants.ts [hunk 1]
```diff
@@ -458,9 +458,14 @@ export const getAddCustomPropertyPath = (entityTypeFQN: string) => {
...
-  let path = ROUTES.CUSTOM_ENTITY_DETAIL;
-  path = path.replace(PLACEHOLDER_ENTITY_TYPE_FQN, entityTypeFQN);
+export const getCustomPropertyPath = (entityTypeFQN: string) => {
+  let path = ROUTES.SETTINGS_WITH_TAB;
+  path = path
+    .replace(
+      PLACEHOLDER_SETTING_CATEGORY,
+      GlobalSettingsMenuCategory.CUSTOM_ATTRIBUTES
+    )
+    .replace(PLACEHOLDER_ROUTE_TAB, entityTypeFQN);
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/constants/constants.ts:468]: We might have a method in route.utils to get path for CustomProperty
It will be getGloablSettingsPath something

Comment (aniketkatkar97) [reply openmetadata-ui/src/main/resources/ui/src/constants/constants.ts:468]: It's the same function as before but the path it was returning was the old one. I just updated it and changed its name.

Comment (aniketkatkar97) [reply openmetadata-ui/src/main/resources/ui/src/constants/constants.ts:468]: Done

**Review by Sachin-chaurasiya — APPROVED** [review]
