### PR TITLE
Fix issue-600: UI: doesn't allow table level tags to be added

### LINKED ISSUE #600: UI: doesn't allow table level tags to be added

### LINKED ISSUE #3543: Tags dropdown is going out side of screen area for entity level tags
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
tags dropdown is going out side of screen area.

**To Reproduce**
go to explore => dashboard entity => click on any dashboard entity => try to add tags in dashboard entity.

Screenshots or steps to reproduce
image

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes :

Closes #600 UI: doesn't allow table level tags to be added.
Closes #3543 Tags dropdown is going out side of screen area for entity level tags 

#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :
image
image
image
image
image
image

#3543 
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

@harshach @vivekratnavel @darth-coder00 @Sachin-chaurasiya

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx [hunk 1]
```diff
@@ -244,10 +251,9 @@ const DatasetDetailsPage: FunctionComponent = () => {
         setEntityThread(data);
       })
       .catch(() => {
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx:253]: @ShaileshParmar11 , Please check the API response error message here too.

File: openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx [hunk 2]
```diff
@@ -226,10 +233,10 @@ const DatasetDetailsPage: FunctionComponent = () => {
         setEntityLineage(res.data);
       })
       .catch((err: AxiosError) => {
-        showToast({
-          variant: 'error',
-          body: err.message ?? 'Error while fetching lineage data.',
-        });
+        const msg =
+          err.response?.data.message ??
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx:237]:
```suggestion
          err.response?.data?.message ||
```

File: openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx [hunk 3]
```diff
@@ -226,10 +233,10 @@ const DatasetDetailsPage: FunctionComponent = () => {
         setEntityLineage(res.data);
       })
       .catch((err: AxiosError) => {
-        showToast({
-          variant: 'error',
-          body: err.message ?? 'Error while fetching lineage data.',
-        });
+        const msg =
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx:236]:
```suggestion
        const message =
```
Please make this change in other places too.

File: openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx [hunk 4]
```diff
@@ -358,10 +363,9 @@ const DatasetDetailsPage: FunctionComponent = () => {
               setSampleData(sampleData);
             })
             .catch(() =>
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx:365]: @ShaileshParmar11 , Please check the API response error message here too.

File: openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx [hunk 5]
```diff
@@ -392,10 +396,9 @@ const DatasetDetailsPage: FunctionComponent = () => {
               setTableQueries(tableQueries);
             })
             .catch(() =>
-              showToast({
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx:395]: @ShaileshParmar11 , Please check the API response error message here too.

File: openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx [hunk 6]
```diff
@@ -430,10 +433,9 @@ const DatasetDetailsPage: FunctionComponent = () => {
         setEntityFieldThreadCount(res.data.counts);
       })
       .catch(() => {
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx:435]: @ShaileshParmar11 , Please check the API response error message here too.

File: openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx [hunk 7]
```diff
@@ -500,16 +518,16 @@ const DatasetDetailsPage: FunctionComponent = () => {
...
           reject();
-          showToast({
-            variant: 'error',
-            body: msg,
-          });
         });
     });
   };
 
+  // TODO: move all the error from below code to en.ts and use handleShowErrorToast to show error.
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx:529]: @ShaileshParmar11, Can you make the required changes for this entity page.

**Review by Sachin-chaurasiya — CHANGES_REQUESTED** [review]

File: openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx (hunk 7 above)
Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx:529]: It would be great if this will be handle in separate PR.

File: openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx (hunk 5 above)
Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx:395]: For this code is updated. but its not showing here as its commented on deleted line.

File: openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx [hunk 8]
```diff
@@ -391,12 +397,12 @@ const DatasetDetailsPage: FunctionComponent = () => {
...
             })
-            .catch(() =>
-              showToast({
-                variant: 'error',
-                body: 'Error while getting table queries',
-              })
-            )
+            .catch((err: AxiosError) => {
+              const errMsg =
+                err.response?.data.message ||
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx:402]:
```suggestion
                err.response?.data?.message ||
```

File: openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx [hunk 9]
```diff
@@ -458,11 +464,8 @@ const DatasetDetailsPage: FunctionComponent = () => {
       .catch((err: AxiosError) => {
         const msg =
           err.response?.data.message ||
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx:466]:
```suggestion
          err.response?.data?.message ||
```

File: openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx [hunk 10]
```diff
@@ -473,16 +476,35 @@ const DatasetDetailsPage: FunctionComponent = () => {
...
+          getEntityFeedCount();
+        } else {
+          handleShowErrorToast(
+            jsonData['api-error-messages']['update-tags-error']
+          );
+        }
+      })
+      .catch((err: AxiosError) => {
+        const errMsg =
+          err.response?.data.message ||
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx:505]:
```suggestion
          err.response?.data?.message ||
```

File: openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx [hunk 11]
```diff
@@ -500,16 +522,16 @@ const DatasetDetailsPage: FunctionComponent = () => {
         })
         .catch((err: AxiosError) => {
           const msg =
-            err.response?.data.message || `Error while updating entity.`;
+            err.response?.data.message ||
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx:525]:
```suggestion
            err.response?.data?.message ||
```

**Review by Sachin-chaurasiya — CHANGES_REQUESTED** [review]

**Review by Sachin-chaurasiya — APPROVED** [review]

**Review by vivekratnavel — APPROVED** [review]

**Comment by vivekratnavel** [comment]
@ShaileshParmar11 Can you resolve conflicts?

**Review by darth-coder00 — APPROVED** [review]
