### PR TITLE
Fix: Fixing #2306 Links in team description is considered as a page.

### LINKED ISSUE #2306: Links in team description is considered as a page.
https://user-images.githubusercontent.com/83201188/150313640-977d9804-3040-46fa-9174-6b5212b5d081.mov

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
Fixes #2306 
### Describe your changes :

I worked on Fixing #2306 Links in team description is considered as a page.

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@shahsank3t, @darth-coder00

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/common/rich-text-editor/RichTextEditorPreviewer.tsx [hunk 1]
```diff
@@ -51,6 +52,23 @@ const RichTextEditorPreviewer = ({
               </ul>
             );
           },
+          a: ({ node, children, ...props }) => {
+            let link = '';
+            const href = props.href;
+            if (
+              href?.indexOf('http://') == 0 ||
```
Comment (mithmatt) [inline openmetadata-ui/src/main/resources/ui/src/components/common/rich-text-editor/RichTextEditorPreviewer.tsx:59]: Should we add a check with some util function `isValidUrl(href)`?

isValidUrl could be a regex check

Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/components/common/rich-text-editor/RichTextEditorPreviewer.tsx:59]: Okay. I will add the `isValidUrl` util.

**Review by mithmatt — APPROVED** [review]
