### PR TITLE
Fixes #2942 - Fix bugs reported by Sonar issue on release 0.9

### LINKED ISSUE #2942: Fix bugs reported by Sonar issue on release 0.9
**Affected module**
Backend

**Describe the bug**
Fixing many issues reported by Sonar

**Version:**
 - Python version:
 - OpenMetadata version: 0.9
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

### PR DESCRIPTION
**Pull request by sureshms**
### Describe your changes :

See #2942 for more details

#
### Type of change :

- [x] Bug fix

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

### CODE REVIEW

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/permissions/PermissionsResource.java [hunk 1]
```diff
@@ -38,7 +37,7 @@
 public class PermissionsResource {
   private final Authorizer authorizer;
 
-  public PermissionsResource(CollectionDAO dao, @NonNull Authorizer authorizer) {
+  public PermissionsResource(@NonNull Authorizer authorizer) {
```
Comment (mithmatt) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/permissions/PermissionsResource.java:40]: This will result in runtime error  from CollectionRegistry to register this resource, since it looks for constructor with two args in the order Config and Authorizer

Comment (mithmatt) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/permissions/PermissionsResource.java:40]: https://github.com/open-metadata/OpenMetadata/blob/main/catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/CollectionRegistry.java#L202

Comment (sureshms) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/permissions/PermissionsResource.java:40]: Okay reverted that change with suppress unused warning annotation...

**Review by mithmatt — APPROVED** [review]

**Comment by sureshms** [comment]
SonarCloud issues are unrelated to this patch.
