### PR TITLE
fix(ui): mentions in notification box

### LINKED ISSUE #23223: Mentions not shown when tagging somoeoe in incidents, conversations..
**Affected module**
UI
**Describe the bug**
When tagging a user in an Incident or Conversation, This makes it difficult for users to track when they have been tagged in discussions, since the Mentions tab should centralize all mentions across the platform

**To Reproduce**

Create an Incident or Conversation.

Tag a user 

Go to Notifications → Mentions.

Observe that the mention is missing from the list.
Screenshots or steps to reproduce

Image

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: 1.9.5
 - OpenMetadata Ingestion package version: [1.9.5.0

**Additional context**

### PR DESCRIPTION
**Pull request by shrushti2000**
Fixes #23223 and #23042

Fix NotificationFeedCard to show actual mentioning user and timestamp and redirection glitch on Activity Feed for notification feeds.

  Problem

  The NotificationFeedCard component was incorrectly displaying the thread creator (createdBy) and thread creation timestamp
  instead of the actual user who made the mention and when the mention occurred. This caused confusion in notification feeds
  where users would see outdated information like "admin mentioned you 15 days ago" when it was actually "stevegreen" who
  mentioned them "just now".

  Root Cause

  In NotificationBox.component.tsx, the notification dropdown logic was using:
  - feed.createdBy (original thread creator) instead of the actual mentioning user
  - feed.threadTs (thread creation time) instead of when the mention was posted

  For mention notifications, we need to extract both the user and timestamp from the specific post in the posts array where the
   mention occurred.

  Solution

  Modified the notificationDropDownList logic in NotificationBox.component.tsx to:

  1. Detect mention notifications: Check if feed.type === ThreadType.Conversation and posts exist
  2. Find mention posts: Filter posts containing user mentions (<#E::user:: pattern) with valid timestamps
  3. Get most recent mention: Sort by timestamp and take the latest mention post
  4. Extract correct data: Use mentionPost.from (actual mentioning user) and mentionPost.postTs (when mention occurred)
  5. Maintain accuracy: Show both who mentioned and when it actually happened

  Changes

  File: openmetadata-ui/src/main/resources/ui/src/components/NotificationBox/NotificationBox.component.tsx

  Key modifications:
  - Added mention detection logic (lines 71-92)
  - Extract actualUser from mentionPost.from instead of feed.createdBy
  - Extract actualTimestamp from mentionPost.postTs instead of feed.threadTs
  - Added TypeScript safety with null checks and nullish coalescing for undefined postTs

  Before vs After

 

Before;-

https://github.com/user-attachments/assets/22346165-d0ab-436b-a113-2f2a8c8e7adf

After fix:-

https://github.com/user-attachments/assets/fabce612-a723-4f0b-9069-dd42074a41f4

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/NotificationBox/NotificationBox.component.tsx [hunk 1]
```diff
@@ -68,15 +68,38 @@ const NotificationBox = ({
...
+              post.message.includes('<#E::user::') && post.postTs !== undefined
+          )
+          .sort((a, b) => (b.postTs ?? 0) - (a.postTs ?? 0))[0];
+
+        if (mentionPost && mentionPost.postTs !== undefined) {
+          actualUser = mentionPost.from;
+          actualTimestamp = mentionPost.postTs;
+        }
+      }
+
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/src/components/NotificationBox/NotificationBox.component.tsx:93]: @shrushti2000, this needs to be handled properly. There are different scenarios possible here. Ex. what happens when the mention is in the Feed itself, not the `posts`? Let's figure out what all scenarios possible here and handle it properly.

Comment (shrushti2000) [reply openmetadata-ui/src/main/resources/ui/src/components/NotificationBox/NotificationBox.component.tsx:93]: To reproduce the case where the mentions is in the feed, I tried creating a task by adding mentions in the desc of some entity and assigning it to some user, but in that case, i cant see any mentions in the notifications list.
Is there any other way I can get the mentions in the feed itself and not in posts?

Comment (aniketkatkar97) [reply openmetadata-ui/src/main/resources/ui/src/components/NotificationBox/NotificationBox.component.tsx:93]: You can start a conversation thread from the right icon in the description section

Screenshot 2025-09-30 at 7 15 26 PM

Also, check if there are any other possibilities there. The goal is that nothing should break in case the data is not coming as we are assuming.

Comment (shrushti2000) [reply openmetadata-ui/src/main/resources/ui/src/components/NotificationBox/NotificationBox.component.tsx:93]: Tested this for mentions in feed


https://github.com/user-attachments/assets/a75a4449-468c-4b3a-bd1d-f25578c9ad87

File: openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts [hunk 2]
```diff
@@ -375,3 +376,196 @@ test.describe('FeedWidget on landing page', () => {
...
+    const { apiContext, afterAction } = await performAdminLogin(browser);
+
+    try {
+      await entity.delete(apiContext);
+      await user1.delete(apiContext);
+      await adminUser.delete(apiContext);
+    } finally {
+      await afterAction();
+    }
+  });
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts]: Can we remove this?

File: openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts [hunk 3]
```diff
@@ -375,3 +376,196 @@ test.describe('FeedWidget on landing page', () => {
...
+
+  test('Mention notification shows correct user details in Notification box', async ({
+    browser,
+  }) => {
+    const { page: adminPage, afterAction: afterActionAdmin } =
+      await performUserLogin(browser, adminUser);
+    const { page: user1Page, afterAction: afterActionUser1 } =
+      await performUserLogin(browser, user1);
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts]: We can use fixtures for such stuff.

File: openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts [hunk 4]
```diff
@@ -375,3 +376,196 @@ test.describe('FeedWidget on landing page', () => {
...
+        ).toBeVisible();
+        await expect(
+          adminPage.locator('[data-testid="send-button"]')
+        ).not.toBeDisabled();
+
+        const postConversation = adminPage.waitForResponse(
+          (response) =>
+            response.url().includes('/api/v1/feed') &&
+            (response.url().endsWith('/posts') ||
+              !response.url().includes('/posts'))
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts]: Why these 2 conditions?

File: openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts (hunk 2 above)
Comment (shrushti2000) [reply openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts]: addressed, removed

File: openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts (hunk 3 above)
Comment (shrushti2000) [reply openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts]: done, used fixtures

File: openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts (hunk 4 above)
Comment (shrushti2000) [reply openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts]: addressed

File: openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts [hunk 5]
```diff
@@ -395,177 +394,170 @@ test.describe('Mention notifications in Notification Box', () => {
...
-          )
-          .fill('Initial conversation thread for mention test');
-
-        await expect(
-          adminPage.locator('[data-testid="send-button"]')
-        ).toBeVisible();
-        await expect(
-          adminPage.locator('[data-testid="send-button"]')
-        ).not.toBeDisabled();
+    try {
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts]: Check out the `fixtures` for playwright. We should avoid try-catch for such things. We have some tests already using the fixtures.

Comment (shrushti2000) [reply openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts]: addressed
