### PR TITLE
fix #14292: Tags Page UI issues

### LINKED ISSUE #14292: Tags Page UI issues
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**

- Button overflow issue for an in-markdown box of description
- Unwanted API call is triggered on the `Add` and `Edit` cases if we close the modal and data disappears in form while saving the changes
- when hit the delete button in the table, the delete button shows loading.

**To Reproduce**

Screenshots or steps to reproduce

image (1)

image (2)

https://github.com/open-metadata/OpenMetadata/assets/66266464/9a82650c-ab9d-4e49-bd22-fb2e3fa9b4bc

https://github.com/open-metadata/OpenMetadata/assets/66266464/202ea455-2c3a-493c-9e52-afd91bee77c9

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by harsh-vador**
### Describe your changes:

Fixes  #14292 

https://github.com/open-metadata/OpenMetadata/assets/58542468/3eb950fd-4a2e-4bba-a110-1ad24cda8553

#
### Type of change:

- [x] Bug fix

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/Modals/EntityDeleteModal/EntityDeleteModal.tsx [hunk 1]
```diff
@@ -92,12 +90,15 @@ const EntityDeleteModal = ({
...
-        <Typography className="mb-2">
-          {bodyText ||
-            t('message.delete-entity-permanently', {
-              entityType: getTitleCase(entityType),
-            })}
-        </Typography>
+        <div className="mb-2">
+          <Transi18next
+            i18nKey="message.permanently-delete-metadata"
+            renderElement={<strong data-testid="username" />}
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Modals/EntityDeleteModal/EntityDeleteModal.tsx:96]:
```suggestion
            renderElement={<strong data-testid="entityName" />}
```

Also strong will add `font-weight: 700` we are not using it in our application can you make it 500?

File: openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json [hunk 2]
```diff
@@ -1514,7 +1514,7 @@
     "password-error-message": "Password must be a minimum of 8 and a maximum of 16 characters long and contain at least one uppercase character (A-Z), one lowercase character (a-z), one number, and one special character (such as !, %, @, or #)",
     "password-pattern-error": "Password must be of minimum 8 and maximum 16 characters, with one special , one upper, one lower case character",
     "path-of-the-dbt-files-stored": "Path of the folder where the dbt files are stored",
-    "permanently-delete-metadata": "Permanently deleting this {{entityName}} will remove its metadata from OpenMetadata permanently.",
+    "permanently-delete-metadata": "Permanently deleting this <0>{{entityName}}</0> will remove its metadata from OpenMetadata permanently.",
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json:1517]: Can you run `yarn i18n` to update other local files and pushed those as well?

File: openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx [hunk 3]
```diff
@@ -498,12 +498,12 @@ export const getEntityPlaceHolder = (value: string, isDeleted?: boolean) => {
 export const getEntityDeleteMessage = (entity: string, dependents: string) => {
   if (dependents) {
     return t('message.permanently-delete-metadata-and-dependents', {
-      entityName: getTitleCase(entity),
+      entityName: entity,
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx:501]: Why we removed `getTitleCase` here?

File: openmetadata-ui/src/main/resources/ui/src/components/ClassificationDetails/ClassificationDetails.tsx [hunk 4]
```diff
@@ -86,493 +93,510 @@ export interface ClassificationDetailsProps {
...
+        fetchClassificationChildren(currentClassification.fullyQualifiedName);
+      }
+    }, [
+      currentClassification?.fullyQualifiedName,
+      pageSize,
+      deleteTags?.state,
+    ]);
+
+    useImperativeHandle(ref, () => ({
+      getTags() {
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/ClassificationDetails/ClassificationDetails.tsx:443]:
```suggestion
      refreshClassificationTags() {
```

**Review by chirag-madlani — CHANGES_REQUESTED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/Modals/EntityDeleteModal/EntityDeleteModal.tsx (hunk 1 above)
Comment (harsh-vador) [reply openmetadata-ui/src/main/resources/ui/src/components/Modals/EntityDeleteModal/EntityDeleteModal.tsx:96]: yes addressed

File: openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx (hunk 3 above)
Comment (harsh-vador) [reply openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx:501]: getTitleCase doesnt handle well the case where the entity name has a dot(.) in it, it removes the dot and title cases the entity name. With this change, it will allow the user to see the entityName as it is

File: openmetadata-ui/src/main/resources/ui/src/components/ClassificationDetails/ClassificationDetails.tsx (hunk 4 above)
Comment (harsh-vador) [reply openmetadata-ui/src/main/resources/ui/src/components/ClassificationDetails/ClassificationDetails.tsx:443]: Done

File: openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json (hunk 2 above)
Comment (harsh-vador) [reply openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json:1517]: it does not show any changes on my local after running this command

Comment (harsh-vador) [reply openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json:1517]: added locale files manually

File: openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx [hunk 5]
```diff
@@ -727,6 +714,26 @@ export const Transi18next = ({
...
+    return t('message.permanently-delete-metadata-and-dependents', {
+      entityName: entity,
+      dependents,
+    });
+  } else {
+    return (
+      <Transi18next
+        i18nKey="message.permanently-delete-metadata"
+        renderElement={
+          <span data-testid="entityName" style={{ fontWeight: 500 }} />
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx:728]:
```suggestion
          <span data-testid="entityName" className="font-medium" />
```

File: openmetadata-ui/src/main/resources/ui/src/components/common/DeleteWidget/DeleteWidgetModal.tsx [hunk 6]
```diff
@@ -90,9 +90,14 @@ const DeleteWidgetModal = ({
...
-        description: `${
-          deleteMessage || getDeleteMessage(entityName, entityType)
-        } ${hardDeleteMessagePostFix}`,
+        description: (
+          <>
+            <span>
+              {deleteMessage ?? getDeleteMessage(entityName, entityType)}
+            </span>
+            <span>{hardDeleteMessagePostFix}</span>
+          </>
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/common/DeleteWidget/DeleteWidgetModal.tsx:99]:
```suggestion
          <>

              {deleteMessage ?? getDeleteMessage(entityName, entityType)}

{hardDeleteMessagePostFix}
          </>
```

File: openmetadata-ui/src/main/resources/ui/src/components/Modals/EntityDeleteModal/EntityDeleteModal.interface.ts [hunk 7]
```diff
@@ -19,7 +19,7 @@ export interface EntityDeleteModalProp extends HTMLAttributes<HTMLDivElement> {
   entityName: string;
   entityType: string;
   loadingState: string;
-  bodyText?: string;
+  bodyText?: string | JSX.Element;
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Modals/EntityDeleteModal/EntityDeleteModal.interface.ts:22]:
```suggestion

```

File: openmetadata-ui/src/main/resources/ui/src/components/ClassificationDetails/ClassificationDetails.tsx [hunk 8]
```diff
@@ -86,493 +93,502 @@ export interface ClassificationDetailsProps {
     updatedClassification: Classification
   ) => Promise<void>;
 }
+export interface ClassificationDetailsRef {
+  refreshClassificationTags: () => void;
+}
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/ClassificationDetails/ClassificationDetails.tsx:98]: Can we move this & other interface to interface file?

**Review by chirag-madlani — DISMISSED** [review]

**Review by chirag-madlani — APPROVED** [review]
