### PR TITLE
#12678 - Add SAP Hana Backend Converter

### LINKED ISSUE #12678: [Bug] HANA DB Integration Shows Password in Plaintext on the Connection Details Ui
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

- Ui

**Describe the bug**

- The connection details Ui of the HANA DB integration displays the password unmasked in plain text

**To Reproduce**

Screenshots or steps to reproduce

- Cannot add a screenshot to prove it shows the password. To reproduce, connect to a HANA DB and view connection details in the Ui

**Expected behavior**

- The password would be masked in the connection details Ui

**Version:**
 - OS: [e.g. iOS] Chrome browser/MacOS - OM Deployed on K8s
 - Python version: 3.9
 - OpenMetadata version: [e.g. 0.8] 1.1.0
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`] 1.1.0

### PR DESCRIPTION
**Pull request by pmbrull**
### Describe your changes:

Fixes #12678

SAP Hana was missing the converter class, which takes care of masking the sensitive fields

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/secrets/converter/ClassConverterFactory.java [hunk 1]
```diff
@@ -46,25 +46,26 @@ private ClassConverterFactory() {
...
             Map.entry(GCSConnection.class, new GcpConnectionClassConverter()),
-            Map.entry(ElasticSearchConnection.class, new ElasticSearchConnectionClassConverter()),
+            Map.entry(HiveConnection.class, new HiveConnectionClassConverter()),
+            Map.entry(IcebergConnection.class, new IcebergConnectionClassConverter()),
+            Map.entry(IcebergFileSystem.class, new IcebergFileSystemClassConverter()),
             Map.entry(LookerConnection.class, new LookerConnectionClassConverter()),
-            Map.entry(SSOAuthMechanism.class, new SSOAuthMechanismClassConverter()),
+            Map.entry(MysqlConnection.class, new MysqlConnectionClassConverter()),
+            Map.entry(PostgresConnection.class, new PostgresConnectionClassConverter()),
+            Map.entry(SapHanaConnection.class, new SapHanaConnectionClassConverter()),
```
Comment (pmbrull) [inline openmetadata-service/src/main/java/org/openmetadata/service/secrets/converter/ClassConverterFactory.java:61]: Just added `SapHanaConnection` as new and sorted the list alphabetically for easier scan

File: openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/sapHana/sapHanaSQLConnection.json [hunk 2]
```diff
@@ -0,0 +1,38 @@
+{
+  "$id": "https://open-metadata.org/schema/entity/services/connections/database/sapHana/sapHanaConnection.json",
+  "$schema": "http://json-schema.org/draft-07/schema#",
+  "title": "SapHanaSQLConnection",
+  "description": "Sap Hana Database SQL Connection Config",
+  "type": "object",
+  "javaType": "org.openmetadata.schema.services.connections.database.sapHana.SapHanaSQLConnection",
```
Comment (pmbrull) [inline openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/sapHana/sapHanaSQLConnection.json:7]: These classes were before a definition. However, I could not get a java object generated out of that. Shape is the same, just moved to their own file

**Review by mohityadav766 — APPROVED** [review]
Looks good @pmbrull
