### PR TITLE
Fix : Ingestion workflow changes are not being updated on Airflow.

### LINKED ISSUE #1257: Ingestion workflow changes are not being updated on Airflow
After updating the Ingestion workflow from UI, changes are not reflected on the Airflow.
for e.g, if I update the schedule interval then on our backend it is changing but on airflow, it's not.

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
Fixes #1257 
### Describe your changes :

I worked on the Ingestion update API integration because of the need to change API calls from PATCH to PUT.

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@shahsank3t, @darth-coder00

### CODE REVIEW

File: catalog-rest-service/src/main/resources/ui/src/pages/IngestionPage/IngestionPage.component.tsx [hunk 1]
```diff
@@ -121,14 +122,42 @@ const IngestionPage = () => {
     });
   };
 
-  const updateIngestionById = (
+  // code for updating ingestion with patch api
```
Comment (shahsank3t) [inline catalog-rest-service/src/main/resources/ui/src/pages/IngestionPage/IngestionPage.component.tsx:125]: Why are we keeping this commented code? If not required, should we clean up and remove it?

Comment (Sachin-chaurasiya) [reply catalog-rest-service/src/main/resources/ui/src/pages/IngestionPage/IngestionPage.component.tsx:125]: @shahsank3t Yeah we can remove it.

**Review by darth-coder00 — APPROVED** [review]
LGTM!
