### PR TITLE
fix(ui): add pagination in sub domains table

### LINKED ISSUE #22792: New subdomains are not listed under Domain, when subdomain count >50
**Affected module**
Impact UI

**Describe the bug**
Newly created 'Sub-domains' are not listed under the parent in the 'Domain' page if the sub-domain count is  >50.
And the count of the subdomains also doesn't change

 The user could not navigate to the newly created subdomain to create 'dataProducts' under it

**To Reproduce**

1. Create a sub-domain (51st) under domain which have already 50 subdomains
2. Observe that sub-domain count not increase to '51' and in the list also the new sub-domain was not reflected

Screenshots or steps to reproduce

Image

**Expected behavior**
1. New sub domain should successfully create and 'user' should be able to navigate

**Version:**
 - OS: [ubuntu]
 - OpenMetadata version: 1.8.6

**Additional context**
Ref link to slack on the same issue -> https://openmetadata.slack.com/archives/C02B6955S4S/p1754476567608579

### PR DESCRIPTION
**Pull request by karanh37**
### Describe your changes:

Fixes #22792

This pull request refactors how subdomains are loaded and displayed in the Domain Details page, moving from eager loading of all subdomain data to an efficient paginated approach. Instead of fetching all subdomains and passing them around, the code now only fetches the subdomain count for summary purposes and loads subdomain data page-by-page in the table. This improves performance and scalability, especially for domains with many subdomains.

**Subdomain Data Loading and Pagination**

* Refactored subdomain loading in `DomainDetailsPage.component.tsx` to fetch only the count of subdomains for summary display, removing the previous eager loading of all subdomain data. (`openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainDetailsPage/DomainDetailsPage.component.tsx`) [[1]](diffhunk://#diff-abcc40c0a84146075a2d085de7c8aebfaf71c9f53bf7204cd24e4f5ddd02dd94L155-R150) [[2]](diffhunk://#diff-abcc40c0a84146075a2d085de7c8aebfaf71c9f53bf7204cd24e4f5ddd02dd94L248-L273) [[3]](diffhunk://#diff-abcc40c0a84146075a2d085de7c8aebfaf71c9f53bf7204cd24e4f5ddd02dd94L287-R279) [[4]](diffhunk://#diff-abcc40c0a84146075a2d085de7c8aebfaf71c9f53bf7204cd24e4f5ddd02dd94L305-R297) [[5]](diffhunk://#diff-abcc40c0a84146075a2d085de7c8aebfaf71c9f53bf7204cd24e4f5ddd02dd94L562-L567) [[6]](diffhunk://#diff-abcc40c0a84146075a2d085de7c8aebfaf71c9f53bf7204cd24e4f5ddd02dd94L596-R587) [[7]](diffhunk://#diff-abcc40c0a84146075a2d085de7c8aebfaf71c9f53bf7204cd24e4f5ddd02dd94L609-R600)
* Updated the subdomains tab to use the new paginated `SubDomainsTable` component, passing only the domain FQN and count, not the full subdomain list. (`openmetadata-ui/src/utils/DomainUtils.tsx`) [[1]](diffhunk://#diff-67120166e6ab8ed9305f9de9d6f273f8ab32c7b05bf2d26ca2421aead18cf45eL360-L365) [[2]](diffhunk://#diff-67120166e6ab8ed9305f9de9d6f273f8ab32c7b05bf2d26ca2421aead18cf45eL392-R391) [[3]](diffhunk://#diff-67120166e6ab8ed9305f9de9d6f273f8ab32c7b05bf2d26ca2421aead18cf45eL401-L403)

**SubDomainsTable Component Refactor**

* Modified `SubDomainsTable` to fetch subdomain data page-by-page using the domain FQN, implement internal pagination logic, and handle loading/error states. (`openmetadata-ui/src/main/resources/ui/src/components/Domain/SubDomainsTable/SubDomainsTable.component.tsx`) [[1]](diffhunk://#diff-72c197eaa2c5968ddc0f442a1deaa3f20b87f8858a7d00b250745d2a92f1404aR14-R107) [[2]](diffhunk://#diff-72c197eaa2c5968ddc0f442a1deaa3f20b87f8858a7d00b250745d2a92f1404aR174-R182)
* Updated the `SubDomainsTableProps` interface to require `domainFqn` instead of a list of subdomains and removed the `isLoading` prop. (`openmetadata-ui/src/main/resources/ui/src/components/Domain/SubDomainsTable/SubDomainsTable.interface.ts`)

**Supporting Type and API Changes**

* Updated types and function signatures throughout the codebase to use `subDomainsCount` (number) instead of an array of subdomains, and removed the `isSubDomainsLoading` flag. (`openmetadata-ui/src/utils/Domain/DomainClassBase.ts`, `openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainDetailsPage/DomainDetailsPage.component.tsx`) [[1]](diffhunk://#diff-b4247f6d97bb7026448244f6fb1216c1e402b15ee9fa3aeb9930c5d5173358d5L38-L44) [[2]](diffhunk://#diff-abcc40c0a84146075a2d085de7c8aebfaf71c9f53bf7204cd24e4f5ddd02dd94L562-L567) [[3]](diffhunk://#diff-abcc40c0a84146075a2d085de7c8aebfaf71c9f53bf7204cd24e4f5ddd02dd94L596-R587)

**Test Improvements**

* Added a new Playwright E2E test for subdomain pagination, verifying subdomain count, pagination navigation, and count updates when adding a subdomain. (`openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/SubDomainPagination.spec.ts`)
* Fixed subdomain FQN construction in the test support class to use `fullyQualifiedName` for parent domains. (`openmetadata-ui/src/main/resources/ui/playwright/support/domain/SubDomain.ts`)

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Review by ShaileshParmar11 — DISMISSED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/Domain/SubDomainsTable/SubDomainsTable.component.tsx [hunk 1]
```diff
@@ -99,6 +171,15 @@ const SubDomainsTable = ({
...
       containerClassName="m-md"
+      customPaginationProps={{
+        currentPage,
+        pageSize,
+        paging,
+        pagingHandler: handlePagingClick,
+        showPagination,
+        isNumberBased: true,
+        isLoading,
+      }}
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Domain/SubDomainsTable/SubDomainsTable.component.tsx]: Can we pull this outside of render?

**Review by chirag-madlani — DISMISSED** [review]
