### PR TITLE
- Removed Logo Configuration from the openmetadata.yaml

### LINKED ISSUE #13618: Logo not getting set when env vars are set
**Affected module**
This impacts UI due to an inconsistency on which endpoint is being used for setting the Logo

**Describe the bug**
When the env vars(OM_CUSTOM_MONOGRAM_URL_PATH and CUSTOM_LOGO_URL_PATH) are set when deploying the helm chart, we do see the correct values reflecting when querying _/api/v1/system/config/applicationConfig_ but the UI is setting the logos querying the  _/api/v1/system/config/customLogoConfiguration_ which are set manually set from the UI

**To Reproduce**
1. Deploy the openmetadata helm chart with the vars OM_CUSTOM_MONOGRAM_URL_PATH and CUSTOM_LOGO_URL_PATH as described in https://docs.open-metadata.org/v1.1.x/how-to-guides/how-to-add-custom-logo 
2. observe that the custom logs do not come up in the UI

Screenshots or steps to reproduce

**Expected behavior**
There should be a single point to set the config 

**Version:**
 - OpenMetadata version: 1.1.14
 - OpenMetadata Ingestion package version: docker.getcollate.io/openmetadata/server:1.1.7

**Additional context**

### LINKED ISSUE #13892: Update favicon when logo is customized
**Affected module**
Does it impact the UI, backend or Ingestion Framework? NO

**Describe the bug**
When the openmetadata logo is replaced, the favicon that appears on browser tab still points to openmetadata favicon.

**To Reproduce**
Screen Shot 2023-11-07 at 5 09 48 PM

Screenshots or steps to reproduce
1. In the openmetadata UI page, go to settings, add custom logo.
2. Check the favicon on the tab with openmetadata page.

**Expected behavior**
1. When custom logo is added, favicon on browser tab changes as well.

**Version:**
 - OS: [e.g. iOS] - iOS
 - Python version: 3.10
 - OpenMetadata version: [e.g. 0.8] 1.1.5
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`] 1.1.5

**Additional context**

### PR DESCRIPTION
**Pull request by mohityadav766**
- Migrated Login Configuration to the UI

### Describe your changes:

- Fixes #13618
- Moves login Configuration to UI
- Fixes #13892

I worked on ... because ...

[x] Support custom favicon from settings page

https://github.com/open-metadata/OpenMetadata/assets/12962843/c2391483-f083-45d8-8a0e-fc2dc5c49835

[x] support login configuration from settings page
Screenshot 2023-11-08 at 5 40 31 PM

[x] support edit for login configuration from settings page
Screenshot 2023-11-08 at 5 40 25 PM

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Review by akash-jain-10 — APPROVED** [review]

**Comment by mohityadav766** [comment]
@chirag-madlani let me know if we need to wait for UI changes in this PR , or they will be coming in separate PR?

**Comment by chirag-madlani** [comment]
Hi @mohityadav766 I will work on this tomorrow. Since it has braking changes let's wait for my changes to be in this PR only thanks

File: openmetadata-ui/src/main/resources/ui/src/components/ApplicationConfigProvider/ApplicationConfigProvider.tsx [hunk 1]
```diff
@@ -66,14 +68,28 @@ const ApplicationConfigProvider: FC<ApplicationConfigProviderProps> = ({
...
+  );
 
   useEffect(() => {
     fetchApplicationConfig();
   }, []);
 
+  useEffect(() => {
+    const faviconHref = isEmpty(applicationConfig.customFaviconUrlPath)
+      ? ''
+      : applicationConfig.customFaviconUrlPath ?? '';
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/ApplicationConfigProvider/ApplicationConfigProvider.tsx:85]: IsEmpty will check for both empty and undefined.
```suggestion
    const faviconHref = isEmpty(applicationConfig.customFaviconUrlPath)
      ? ''
      : applicationConfig.customFaviconUrlPath;
```

File: openmetadata-ui/src/main/resources/ui/src/pages/Configuration/LoginPage/EditLoginConfigurationPage.tsx [hunk 2]
```diff
@@ -0,0 +1,230 @@
...
+    {
+      name: 'maxLoginFailAttempts',
+      label: t('label.max-login-fail-attampt-plural'),
+      type: FieldTypes.NUMBER,
+      required: false,
+      id: 'root/maxLoginFailAttempts',
+      props: {
+        'data-testid': 'maxLoginFailAttempts',
+        size: 'default',
+        style: { width: '100%' },
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/Configuration/LoginPage/EditLoginConfigurationPage.tsx:98]: Do we need this style prop?

**Review by Sachin-chaurasiya — COMMENTED** [review]
Left a few comments, thanks

File: openmetadata-ui/src/main/resources/ui/src/components/ApplicationConfigProvider/ApplicationConfigProvider.tsx (hunk 1 above)
Comment (chirag-madlani) [reply openmetadata-ui/src/main/resources/ui/src/components/ApplicationConfigProvider/ApplicationConfigProvider.tsx:85]: It's to make `faviconHref ` type as string instead `string | undefined`

File: openmetadata-ui/src/main/resources/ui/src/pages/Configuration/LoginPage/EditLoginConfigurationPage.tsx (hunk 2 above)
Comment (chirag-madlani) [reply openmetadata-ui/src/main/resources/ui/src/pages/Configuration/LoginPage/EditLoginConfigurationPage.tsx:98]: Yes else it will be of just 90px which wasn't good

**Review by Sachin-chaurasiya — DISMISSED** [review]

**Review by chirag-madlani — APPROVED** [review]

**Review by Sachin-chaurasiya — APPROVED** [review]
