### PR TITLE
Fix soft-delete and restore handling for charts linked to dashboards during dashboard delete/restore operations

### LINKED ISSUE #21713: Charts within deleted dashboards appear in explore page
**Affected module**
backend

**Describe the bug**
When we soft delete a dashboard, charts within the dashboard still appear in the explore page which may mislead the user

### PR DESCRIPTION
**Pull request by sonika-shah**
### Describe your changes:

Fixes #21713

A chart can belong to multiple dashboards, or can be present independently . Earlier when deleting/restoring dashboard the associated charts delete status were not affected.

### Changes Introduced
- 	Override deleteChildren in DashboardRepository to support the HAS relationship instead of the default CONTAINS flow.
- 	Implemented logic for deletion: “For deletion: get charts whose linked dashboards (excluding the current dashboard) have no other non‑deleted dashboards.”
- 	Implemented logic for restore: “For restore: get charts whose linked dashboards (excluding the current dashboard) are all non‑deleted.”
- 	Added backend tests to validate delete and restore behavior for dashboards with charts linked via HAS relationships.

https://github.com/user-attachments/assets/43cb260e-a74c-4eed-8e39-7528141995de

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardRepository.java [hunk 1]
```diff
@@ -132,6 +138,144 @@ public void clearFields(Dashboard dashboard, Fields fields) {
...
+                    .collect(Collectors.toList()),
+                Relationship.HAS.ordinal(),
+                DASHBOARD);
+
+    Set<UUID> nonDeletedDashboards =
+        daoCollection
+            .dashboardDAO()
+            .findEntitiesByIds(
+                dashboardRelationships.stream()
+                    .map(rel -> UUID.fromString(rel.getFromId()))
```
Comment (sonika-shah) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardRepository.java:238]: In the database, dashboards and charts are linked via the HAS relationship:
Entity.DASHBOARD --HAS--> Entity.CHART

so rel.getFromId() will give dashboard Id and not chartId

**Review by harshach — DISMISSED** [review]

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardRepository.java [hunk 2]
```diff
@@ -132,6 +138,144 @@ public void clearFields(Dashboard dashboard, Fields fields) {
...
+          break;
+        }
+      }
+
+      if (!hasOtherNonDeletedDashboard) {
+        filteredChartRecordsToBeDeleted.add(record);
+      }
+    }
+
+    deleteChildren(filteredChartRecordsToBeDeleted, hardDelete, updatedBy);
```
[the remark this answers is not in the document]
Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardRepository.java:270]: Both are diffrent method one has EntityRelationshiprecord input 

protected void deleteChildren(
      List<EntityRelationshipRecord> children, boolean hardDelete, String updatedBy) {
      
      while other has different input param :
      protected void deleteChildren(UUID id, boolean recursive, boolean hardDelete, String updatedBy) {

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardRepository.java [hunk 3]
```diff
@@ -132,6 +138,144 @@ public void clearFields(Dashboard dashboard, Fields fields) {
         fields.contains("usageSummary") ? dashboard.getUsageSummary() : null);
   }
 
+  // Override soft delete behavior to handle charts through HAS relation.
+  @Transaction
+  @Override
+  protected void deleteChildren(
```
[the remark this answers is not in the document]
Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardRepository.java:208]: to keep steps in a single transaction and maintain readability, not moving to a common helper method

File: openmetadata-service/src/main/java/org/openmetadata/service/Entity.java [hunk 4]
```diff
@@ -576,7 +576,7 @@ public static void deleteEntity(
 
   public static void restoreEntity(String updatedBy, String entityType, UUID entityId) {
     EntityRepository<?> dao = getEntityRepository(entityType);
-    dao.restoreEntity(updatedBy, entityType, entityId);
+    dao.restoreEntity(updatedBy, entityId);
```
Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/Entity.java:592]: @sonika-shah why are we changing this?

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardRepository.java [hunk 5]
```diff
@@ -197,6 +202,144 @@ public void clearFields(Dashboard dashboard, Fields fields) {
...
+            .map(Dashboard::getId)
+            .filter(id -> !id.equals(dashboardId)) // (excluding the current dashboard
+            .collect(Collectors.toSet());
+
+    // For restore: get charts whose linked dashboards (excluding the current dashboard)
+    // are all non‑deleted.
+    List<CollectionDAO.EntityRelationshipRecord> filteredChartRecordsToBeRestored =
+        new ArrayList<>();
+
+    for (CollectionDAO.EntityRelationshipRecord chartRecord : chartRecords) {
```
Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardRepository.java:319]: why are we doing this inner loops? @sonika-shah

File: openmetadata-service/src/main/java/org/openmetadata/service/Entity.java (hunk 4 above)
Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/Entity.java:592]: @harshach we already have entityType variable associated with the EntityRepository, so we can directly use that instead of passing it as parameter in function
image

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardRepository.java (hunk 5 above)
Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardRepository.java:319]: this is done , because for each chart we need to filter it on the based on the other dashboards it’s linked to

**Comment by sonika-shah** [comment]
Update : will hold of including the pr in 1.8.2 as currently  after soft  deleteing dashboard the soft deleted charts do not show in UI
image

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardRepository.java [hunk 6]
```diff
@@ -197,6 +202,144 @@ public void clearFields(Dashboard dashboard, Fields fields) {
         fields.contains("usageSummary") ? dashboard.getUsageSummary() : null);
   }
 
+  // Override soft delete behavior to handle charts through HAS relation.
+  @Transaction
+  @Override
+  protected void deleteChildren(
+      UUID dashboardId, boolean recursive, boolean hardDelete, String updatedBy) {
```
Comment (mohityadav766) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardRepository.java:209]: @sonika-shah can you check if they needs to be run in Transaction like we are doing cleanup?

Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardRepository.java:209]: I can check for this separately , currently the behaviour is same as defaultChildren method with @Transaction annotation
