### PR TITLE
#14127 Timestamp statistical measurements is not being computed and UI Time Filter get reset to default (Last 3 Days)

### LINKED ISSUE #14127: Timestamp statistical measurements is not being computed and UI Time Filter get reset to default (Last 3 Days)
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**
1. UI still show **Last 3 days** when switched to other page especially from table profile to column profile, vice-versa (after I changed into other option such as yesterday or custom date). 
2. Timestamp data types cant get statistical measurements such as max, min, mean, etc.

**To Reproduce**

Please change the time filter then switch to other page and try to profile timestamp column with max, mean, min, etc.

**Expected behavior**
It should be fixed with latest time filter state and timestamp column can have their statistical measurements same with numeric  columns.

**Version:**
 - OS: MacOS BigSur 11.7.10 or Linux Debian 5.10.197-1 (2023-09-29) x86_64
 - Python version: 3.10
 - OpenMetadata version: 1.2.0
 - OpenMetadata Ingestion package version: openmetadata-ingestion[bigquery-usage,bigquery]==1.2.0.1

**Additional context**
Slack Thread : https://openmetadata.slack.com/archives/C02B6955S4S/p1700795227772619

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes:

Fixes #14127 Timestamp statistical measurements is not being computed and UI Time Filter get reset to default (Last 3 Days)

https://github.com/open-metadata/OpenMetadata/assets/71748675/fd2433e2-1b22-4ee5-aacd-4630c4528372

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/DatePickerMenu/DatePickerMenu.component.tsx [hunk 1]
```diff
@@ -35,42 +36,39 @@ import {
...
   showSelectedCustomRange?: boolean;
   handleDateRangeChange: (value: DateRangeObject, days?: number) => void;
   options?: DateFilterType;
-  defaultValue?: string;
   allowCustomRange?: boolean;
   handleSelectedTimeRange?: (value: string) => void;
 }
 
-function DatePickerMenu({
+const DatePickerMenu = ({
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/DatePickerMenu/DatePickerMenu.component.tsx:47]: As we are making changes in this common component, it would be good if you check all the places where it is being used.

Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/components/DatePickerMenu/DatePickerMenu.component.tsx:47]: Yes, I have verified the scenarios, and it's working as expected. once this merges I need to make some changes in the collate side.

**Review by chirag-madlani — APPROVED** [review]
