### PR TITLE
Fix: #21729 Test Cases Not Returned When Service Name Contains Spaces

### LINKED ISSUE #21729: Test Cases Not Returned When Service Name Contains Spaces
**Affected module**
Does it impact the UI, backend or Ingestion Framework? -- UI

**Describe the bug**
-- We’ve encountered an issue where test cases are not returned when the service name contains spaces.

```
GET http://localhost:8585/api/v1/dataQuality/testCases/search/list?q=* && testSuite.fullyQualifiedName:Object platform box.default.openmetadata_db.ACT_EVT_LOG.testSuite&limit=25&offset=0
```

**To Reproduce**

Screenshots or steps to reproduce
-- This is reproducible on the sandbox environment as well:
🔗 [Sandbox Repro Link](https://sandbox-beta.open-metadata.org/test-suites/Gyo%20local%20test%20mysql%2020240324.dev.information_schema.ADMINISTRABLE_ROLE_AUTHORIZATIONS.testSuite/add-ingestion)

It seems the space in the service name (e.g., "Object platform box") is not being handled correctly by the search API.

**Expected behavior**
-- Test cases should be returned even if the service or test suite name includes spaces.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes:

Fixes #21729 

For below screenshort I have created a service with name of `multi pipeline !@#$%^&*()_-+=test-e9795787`.

Issue:
image

Fix:
image

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/components/AddTestSuitePipeline.tsx [hunk 1]
```diff
@@ -182,9 +182,9 @@ const AddTestSuitePipeline = ({
                   <AddTestCaseList
                     filters={
                       !testSuiteId
-                        ? `testSuite.fullyQualifiedName:${escapeESReservedCharacters(
+                        ? `testSuite.fullyQualifiedName:"${escapeESReservedCharacters(
                             testSuite?.fullyQualifiedName ?? fqn
```
Comment (harshach) [inline openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/components/AddTestSuitePipeline.tsx:186]: shouldn’t this be handled in escapeESReservedCharacters method in itself?

Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/components/AddTestSuitePipeline.tsx:186]: That utility function is designed to escape reserved characters, but the input string does not necessarily have to be a fullyQualifiedName.
