### PR TITLE
Fix #1876: Allow dots in entity names

### LINKED ISSUE #1876: Database Page fails to load
Hello, 

Visiting the database page gives a "TypeError: i is undefined" error and the page goes completely blank rendering the application unusable.  Please see the attached video for details.

https://user-images.githubusercontent.com/42276144/146967518-7ed17066-774c-415a-8b74-fb3c6569e6fc.mov

### PR DESCRIPTION
**Pull request by amiorin**
### Describe your changes :

See #1876

# Requirements
1. Users can ingest entities containing dots in their names.
2. Entity services MUST not have dots in their entity names. OM will throw a validation error.
3. User must provide the FQN encoded with `_DOT_`. For example `service.sche.ma.tab.le` needs to searched as `service.sche_DOT_ma.tab_DOT_le`

## Entites escaping dots
1. AirflowPipeline
2. Chart
3. Dashboard
4. Database
5. Location
6. Metrics
7. MlModel
8. Pipeline
9. Table
10. Topic

## Entities rejecting dots
1. Database Service
2. Dashboard Service
3. Messaging Service
4. Pipeline Service
5. Storage Service

## Entities accepting dots
1. Bots
2. Policy
3. Report
4. Role
5. Team
6. User
7. Webhook

## Fields escaping dots
1. Column
2. Task

# Progress
- [x] Implement escaping for field column
- [x] for Task
- [x] for TableData (addSampleData, skipped because the user should use the column name received after the POST)
- [x] for TableConstraint
- [x] for ColumnConstraint (skipped because it's just an ENUM)
- [x] for ColumnJoin and TableJoin (addJoins, skipped because the user should use the column name received after the POST)
- [x] for ColumnProfile (addDataProfiler, skipped because the user should use the column name received after the POST)
- [x] Remove the other Python code. It will code in a second PR.

# Limitations
1. TableJoin works only with columns and not with nested columns. Trino supports joins on nested columns.
2. ColumnProfile works only with columns and not with nested columns. It's very likely that our users need support for nested column profiles, checks, and alerts.

# Solution
1. Create[Entity] should only allow specifying the entity `name` but not the entity `displayName`.
1. We escape `.` with `_DOT_`.

# Notes
## Joins
It has been tested that Trino supports joins on fields of structs.
```sql
select * from t1 join t2 on t1.customer.id = t2.customer[1];
```
## Unnamed fields in structs
Structs in Trino and BigQuery can have unnamed fields that can be accessed with the `[]` notation.

## Repeated
BigQuery doesn't support arrays of arrays. Repeated is a struct that can be repeated multiple times. This is the `create` statement for Trino of the table used in the BigQuery [examples](https://cloud.google.com/blog/topics/developers-practitioners/bigquery-explained-working-joins-nested-repeated-data).

```sql
create table memory.default.t1 as
SELECT *
FROM (
         VALUES (1, 'a',
                 cast(row(1, 'Joe', 'New York') as row(id bigint, name varchar, location varchar)),
                 array[cast(row(1, 1, 2) as row(sku bigint, quantity bigint, price bigint))])
     ) AS t (order_id, order_time, customer, product);
```

# Q&A
Q: Why are we not replacing the `_DOT_` with `~` like in JSON Pointer.
A: To avoid breaking with the past.

#
### Type of change :

- [x] Improvement

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

### CODE REVIEW

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/util/EntityUtil.java [hunk 1]
```diff
@@ -467,4 +467,10 @@ public static void addSoftDeleteFilter(List<EventFilter> filters) {
                     .withEventType(EventType.ENTITY_SOFT_DELETED)
                     .withEntities(eventFilter.getEntities())));
   }
+
+  public static void escapeReservedChars(EntityInterface entityInterface) {
+    entityInterface.setDisplayName(
+        entityInterface.getDisplayName() != null ? entityInterface.getDisplayName() : entityInterface.getName());
+    entityInterface.setName(entityInterface.getName().replace("~", "~0").replace(".", "~1"));
```
Comment (harshach) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/util/EntityUtil.java:474]: replace "." with "_DOT_"

**Comment by harshach** [comment]
@amiorin "." with _DOT_ is a decision we made a longtime ago. Users may have this already ingested the data.
Let's continue to replace "." with _DOT_ instead of adding new character that will throw off existing installations.
1. replace entity names like Table, Topic, Pipeline, Dashboard etc..
2. Do not allow "." in service names . We don't need to replace it here as these services are user/admin created hence we can throw a validation error and let the user correct it

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/util/EntityUtil.java (hunk 1 above)
Comment (amiorin) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/util/EntityUtil.java]: Done.

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/DashboardRepository.java [hunk 2]
```diff
@@ -262,6 +263,11 @@ public String getDisplayName() {
       return entity.getDisplayName();
     }
 
+    @Override
```
Comment (harshach) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/DashboardRepository.java:266]: can't these methods moved to EntityRepository, instead of adding to all the extended classes?

Comment (amiorin) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/DashboardRepository.java:266]: Doing so, the signature of this method will become more complicated, right?
image

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/ChartRepository.java [hunk 3]
```diff
@@ -59,6 +59,7 @@ public static String getFQN(Chart chart) {
 
   @Override
   public void prepare(Chart chart) throws IOException, ParseException {
+    EntityUtil.escapeReservedChars(getEntityInterface(chart));
```
Comment (harshach) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/ChartRepository.java:62]: Instead of passing Object and List of Objects. Then doing type casting why not just send the strings.
Since you are calling this method explicitly anyway in the each of the Repository. Might as well call all the names example table and table columns can looped and call with escapeReservedChars

Comment (harshach) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/ChartRepository.java:62]: Lets merge this in, we can refactor later.

Comment (amiorin) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/ChartRepository.java:63]: Ok, let's refactor later.

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/util/EntityUtil.java [hunk 4]
```diff
@@ -476,4 +476,32 @@ public static void addSoftDeleteFilter(List<EventFilter> filters) {
                     .withEventType(EventType.ENTITY_SOFT_DELETED)
                     .withEntities(eventFilter.getEntities())));
   }
+
+  public static void escapeReservedChars(EntityInterface entityInterface) {
+    entityInterface.setDisplayName(
+        entityInterface.getDisplayName() != null ? entityInterface.getDisplayName() : entityInterface.getName());
+    entityInterface.setName(entityInterface.getName().replace(".", "_DOT_"));
```
Comment (pmbrull) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/util/EntityUtil.java:483]: Should we have the string`_DOT_` as a constant in EntityUtil?

**Review by darth-coder00 — APPROVED** [review]

**Review by pmbrull — APPROVED** [review]
LGTM, only one comment if you have the time
