### PR TITLE
Fix #3028: Add filter support for Feed API

### LINKED ISSUE #3028: Add filter support for Feed API
The Feed api (/api/v1/feed) should support filter by threads on user/team owned data, user followed data, and user mentioned threads.

- [x] Threads on User/Team owned data
- [x] Threads on User followed data
- [x] Threads on User mentioned data

### LINKED ISSUE #3078: Getting <span> tag in threads after updating description
**Affected module**
UI

**Describe the bug**
Getting <span> tag in threads after updating description

**To Reproduce**

Screenshot 2022-03-02 at 5 43 00 PM

**Expected behavior**
Tags should not be visible on UI.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
NA

### PR DESCRIPTION
**Pull request by vivekratnavel**
- Closes #3078 

### Describe your changes :

See #3028 

This patch also includes the required UI changes to show the filter options on the home page.

#
### Type of change :

- [ ] Bug fix
- [ ] Improvement
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation
#
### Frontend Preview (Screenshots) :
Screen Shot 2022-03-02 at 6 23 00 PM
Screen Shot 2022-03-02 at 6 22 46 PM
Screen Shot 2022-03-02 at 6 22 24 PM

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [ ] I have tagged my reviewers below.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/FeedRepository.java [hunk 1]
```diff
@@ -292,25 +349,62 @@ private boolean fieldsChanged(Thread original, Thread updated) {
...
-            .findTo(
-                user.getName(),
-                user.getType(),
-                Relationship.REPLIED_TO.ordinal(),
-                Entity.THREAD,
-                toBoolean(Include.NON_DELETED)));
+    switch (filter) {
+      case OWNER:
+        // add threads on user or team owned entities
+        List<String> teamIds =
```
Comment (harshach) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/FeedRepository.java:357]: moving these into methods would be good. Instead of adding code under each case

**Review by harshach — CHANGES_REQUESTED** [review]
LGTM. left one minor comment

File: openmetadata-ui/src/main/resources/ui/src/axiosAPIs/feedsAPI.ts [hunk 2]
```diff
@@ -26,6 +27,26 @@ export const getAllFeeds: Function = (
...
 };
 
+export const getFeedsWithFilter: Function = (
+  userId?: string,
+  filterType?: FeedFilter
+): Promise<AxiosResponse> => {
+  let config = {};
+  if (typeof userId != 'undefined' && userId) {
+    // if filter type is ALL, then skip the config
+    if (filterType != FeedFilter.ALL) {
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/axiosAPIs/feedsAPI.ts:37]:
```suggestion
    if (filterType !== FeedFilter.ALL) {
```

File: openmetadata-ui/src/main/resources/ui/src/components/MyData/MyData.component.tsx [hunk 3]
```diff
@@ -171,7 +171,7 @@ const MyData: React.FC<MyDataProps> = ({
         <ErrorPlaceHolderES errorMessage={error} type="error" />
       ) : (
         <Fragment>
-          {feedData?.length > 0 ? (
+          {feedData?.length > 0 || feedFilter != FeedFilter.ALL ? (
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/MyData/MyData.component.tsx:174]:
```suggestion
          {feedData?.length > 0 || feedFilter !== FeedFilter.ALL ? (
```

**Review by Sachin-chaurasiya — CHANGES_REQUESTED** [review]
Few changes are required, otherwise LGTM.
@darth-coder00, please review once.

File: openmetadata-ui/src/main/resources/ui/src/axiosAPIs/feedsAPI.ts [hunk 4]
```diff
@@ -26,6 +27,26 @@ export const getAllFeeds: Function = (
   });
 };
 
+export const getFeedsWithFilter: Function = (
+  userId?: string,
+  filterType?: FeedFilter
+): Promise<AxiosResponse> => {
+  let config = {};
+  if (typeof userId != 'undefined' && userId) {
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/axiosAPIs/feedsAPI.ts:35]: Use ` isUndefined` helper method from lodash.
```suggestion
  if (!isUndefined(userId)) {
```

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/feeds/FeedResource.java [hunk 5]
```diff
@@ -142,9 +141,21 @@ public ThreadList list(
...
+          String entityLink,
+      @Parameter(
+              description =
+                  "Filter threads by user id. This filter requires a 'filterType' query param. The default filter type is 'OWNER'",
+              schema = @Schema(type = "string"))
+          @QueryParam("userId")
+          String userId,
+      @Parameter(
+              description =
+                  "Filter type definition for the user filter. It can take one of 'OWNER', 'FOLLOWS', 'MENTIONS'. This must be used with the 'user' query param",
```
Comment (mithmatt) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/feeds/FeedResource.java:153]: Make this an enum and use the enum in the schema?

```
              schema = @Schema(implementation = FilterType.class))

```

Comment (vivekratnavel) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/feeds/FeedResource.java:154]: I have made the Schema change to the API as you suggested. It looks neat now. Thank you!

**Review by Sachin-chaurasiya — APPROVED** [review]

**Review by darth-coder00 — APPROVED** [review]

File: catalog-rest-service/src/main/resources/json/schema/entity/feed/thread.json [hunk 6]
```diff
@@ -45,6 +45,10 @@
       "description": "Data asset about which this thread is created for with format <#E/{entities}/{entityName}/{field}/{fieldValue}.",
       "$ref": "../../type/basic.json#/definitions/entityLink"
     },
+    "entityId": {
+      "description": "Entity Id of the entity that the thread belongs to.",
+      "type": "string"
```
Comment (mithmatt) [inline catalog-rest-service/src/main/resources/json/schema/entity/feed/thread.json:50]: Use the following instead - since we use it for all entity ids (it still resolves to string)

`      "$ref": "../../type/basic.json#/definitions/uuid"`
