### PR TITLE
Fix: Persist filters in query string for all tabs

### LINKED ISSUE #2274: While checking usage of tag, entities shows 0 results but when clicked shows all the results without tag filter
https://user-images.githubusercontent.com/83201188/150073679-cb0d0420-94ce-481e-a1e1-7398e2146fdb.mov

### PR DESCRIPTION
**Pull request by darth-coder00**
### Describe your changes :
Closes #2274 

I worked on the Explore page url filters persistence across tabs

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :
<p align="center">
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@Sachin-chaurasiya @shahsank3t

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx [hunk 1]
```diff
@@ -151,17 +151,18 @@ const Explore: React.FC<ExploreProps> = ({
...
       }, {});
-      setIsFilterSelected(false);
+      const queryParamFilters = getQueryParam(location.search);
+      setIsFilterSet(false);
 
       return {
         ...prevFilters,
-        ...getQueryParam(location.search),
         ...updatedFilter,
+        ...(isForceClear ? {} : queryParamFilters),
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx:165]:
```suggestion
        ...(isForceClear ? [] : queryParamFilters),
```

**Review by Sachin-chaurasiya — APPROVED** [review]
LGTM.
