### PR TITLE
Fixed: Add job definition id field for dbt cloud in UI #10269

### LINKED ISSUE #10269: Add job definition id field for dbt cloud in UI
**Feature**
With reference to https://github.com/open-metadata/OpenMetadata/issues/9734
Add a field in UI for dbt cloud to input the job definition id

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes :

Add job definition id field for dbt cloud in UI #10269
Closes #10269 

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

**Review by Ashish8689 — APPROVED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTCloudConfig.tsx [hunk 1]
```diff
@@ -140,6 +144,23 @@ export const DBTCloudConfig: FunctionComponent<Props> = ({
           onChange={(e) => handleDbtCloudProjectId(e.target.value)}
         />
       </Field>
+      <Field>
+        <label className="block tw-mb-1 tw-form-label" htmlFor="dbtCloudJobId">
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTCloudConfig.tsx:148]: Can we avoid tailwind CSS here?

File: openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTCloudConfig.tsx [hunk 2]
```diff
@@ -140,6 +144,23 @@ export const DBTCloudConfig: FunctionComponent<Props> = ({
...
+          {t('label.dbt-cloud-job-id')}
+        </label>
+        <p className="text-grey-muted m-t-xss m-b-xs text-xs">
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTCloudConfig.tsx:151]: Can we use `Typography` here instead of `<p>` tag?

Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTCloudConfig.tsx:151]: just to avoid inconsistency in the visual part I haven't changed anything here, We will altogether going to update this file, with ANTD component and going to remove the tailwind

**Review by aniketkatkar97 — APPROVED** [review]
