### PR TITLE
Fix issue #2037- Use lombok Slf4j annotation to initialize logger

### LINKED ISSUE #2037: Use lombok Slf4j annotation to initialize logger
In a lot of classes we use LoggerFactory to initialize logger
```
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DefaultAuthorizer implements Authorizer {
  private static final Logger LOG = LoggerFactory.getLogger(DefaultAuthorizer.class);
```

This could be simplified to the following, with no need to initialize logger using LoggerFactory
```
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class DefaultAuthorizer implements Authorizer {

   // log.info("hello world")
```

By default the logger object is called `log` 
It is possible to have a custom logger object `LOG`. Check `lombok.log.fieldName`

Reference: https://www.projectlombok.org/features/log

### PR DESCRIPTION
**Pull request by Shreshtha13**
### Describe your changes :

Fixes #2037 
Used lombok Slf4j to initialize logger instead of LoggerFactory to simplify the code.

#
### Type of change :

- [x] Improvement

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] All new and existing tests passed.

#
### Reviewers
@sureshms @harshach

### CODE REVIEW

**Comment by harshach** [comment]
@Shreshtha13 Awesome!! work. Thanks for persisting on this. 
I pushed one small fix on your PR to add annotation to Test resources. 
Merging it now.

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java.orig [hunk 1]
```diff
@@ -0,0 +1,276 @@
+/*
```
Comment (mithmatt) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java.orig:1]: Can we remove this file

**Review by mithmatt — CHANGES_REQUESTED** [review]

**Review by mithmatt — APPROVED** [review]

**Comment by harshach** [comment]
Thanks @mithmatt for helping @Shreshtha13 . 
@Shreshtha13 hope this helps you adding more contributions
