### PR TITLE
Fix #10814: Improve parsing logic for union fields in topic

### LINKED ISSUE #10814: Parse children of union in avro schema
**Affected module**
Ingestion Framework

**Describe the bug**
Parse children of union in avro schema, currently if the type is union we just diplay union but if it's of type union of null & array or null & record we must show the record to user

### PR DESCRIPTION
**Pull request by ulixius9**
### Describe your changes:

Fix #10814: Improve parsing logic for union fields in topic

I worked on ... because ...

Before 

image

After 

image

#
### Type of change:

- [x] Bug fix
- [x] Improvement

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Review by NiharDoshi99 — APPROVED** [review]

**Review by OnkarVO7 — APPROVED** [review]

**Review by NiharDoshi99 — APPROVED** [review]

**Review by OnkarVO7 — APPROVED** [review]

**Review by shahsank3t — DISMISSED** [review]

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TopicRepository.java [hunk 1]
```diff
@@ -353,5 +355,15 @@ private void updateFieldDisplayName(Field origField, Field updatedField) throws
...
       recordChange(field, origField.getDisplayName(), updatedField.getDisplayName());
     }
+
+    private void updateFieldDataTypeDisplay(Field origField, Field updatedField) throws JsonProcessingException {
+      if (operation.isPut() && !nullOrEmpty(origField.getDataTypeDisplay()) && updatedByBot()) {
+        // Revert the non-empty field description if being updated by a bot
+        updatedField.setDataTypeDisplay(origField.getDataTypeDisplay());
+        return;
+      }
+      String field = getSchemaField(original, origField, FIELD_DISPLAY_NAME);
```
Comment (ayush-shah) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TopicRepository.java:365]:
```suggestion
      String field = getSchemaField(original, origField, FIELD_DATA_DISPLAY_TYPE);
```

Define FIELD_DATA_DISPLAY_TYPE Field here

**Review by ayush-shah — CHANGES_REQUESTED** [review]

**Comment by ayush-shah** [comment]
Merging it as requested changes are resolved and tested
