### PR TITLE
Fix - 21204 inconsistent domain reassignment in bulkAsset API

### LINKED ISSUE #21204: Inconsistent behavior when reassigning asset to a different domain via bulkAsset API
**Affected module**
Application

**Describe the bug**
If asset is part of some domain, and then added to some other domain (using bulkasset) , the behaviour is inconsistent

**To Reproduce**

Screenshots or steps to reproduce

https://github.com/user-attachments/assets/70780f80-d7e9-43ff-87c4-c02c53c639b2

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: 1.7.0
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by sonika-shah**
### Describe your changes:

Fixes #21204 

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataProductRepository.java [hunk 1]
```diff
@@ -147,6 +153,99 @@ public BulkOperationResult bulkRemoveAssets(String domainName, BulkAssets reques
...
+  protected BulkOperationResult bulkAssetsOperation(
+      UUID entityId,
+      String fromEntity,
+      Relationship relationship,
+      BulkAssets request,
+      boolean isAdd) {
+    BulkOperationResult result =
+        new BulkOperationResult().withStatus(ApiStatus.SUCCESS).withDryRun(false);
+    List<BulkResponse> success = new ArrayList<>();
+    // Validate Assets
```
Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataProductRepository.java:166]: remove unnecessary permissions

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataProductRepository.java [hunk 2]
```diff
@@ -147,6 +153,99 @@ public BulkOperationResult bulkRemoveAssets(String domainName, BulkAssets reques
     return result;
   }
 
+  @Override
+  protected BulkOperationResult bulkAssetsOperation(
```
Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataProductRepository.java:157]: should this be wrapped in @Transaction

Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataProductRepository.java:157]: smaller methods in Java

**Review by harshach — CHANGES_REQUESTED** [review]

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataProductRepository.java (hunk 1 above)
Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataProductRepository.java:166]: permission check is already done here - https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-service/src/main/java/org/openmetadata/service/resources/domains/DataProductResource.java#L340 , this is an internal function to 

https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataProductRepository.java#L124

**Review by harshach — APPROVED** [review]

**Review by mohityadav766 — APPROVED** [review]

**Comment by sonika-shah** [comment]
cherry-picked in 1.7.1
