### PR TITLE
UI : Remove the text ellipses and wrap the content to next line

### LINKED ISSUE #8346: Column name only display 20 characters and is cut off after that
**Affected module**
UI

**Describe the bug**
Full column name is not displayed but cut off after 20 characters

**To Reproduce**

image

**Expected behavior**
Display full column name

**Version:**
 - OS: Windows, Chrome
 - OpenMetadata version: 0.12.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes :

- Issue: Closes #8346
- Remove the text ellipses and wrap the content to the next line
- Increases column width and added horizontal scroll in the table of profiler and data quality

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :
image
image
image

https://user-images.githubusercontent.com/66266464/214551315-c9492472-60dd-4835-a1b5-a940cecdedd1.mov

https://user-images.githubusercontent.com/66266464/214566912-84550788-d2aa-4bc8-b58c-fb1916a62640.mov

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/DataQualityTab.tsx [hunk 1]
```diff
@@ -227,6 +235,7 @@ const DataQualityTab: React.FC<DataQualityTabProps> = ({
         }}
         pagination={false}
         rowKey="id"
+        scroll={{ x: 1550 }}
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/DataQualityTab.tsx:238]: Why we are adding scroll?

File: openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/ColumnProfileTable.tsx [hunk 2]
```diff
@@ -278,6 +280,7 @@ const ColumnProfileTable: FC<ColumnProfileTableProps> = ({
         columns={tableColumn}
         dataSource={data}
         pagination={false}
+        scroll={{ x: 1500 }}
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/ColumnProfileTable.tsx:283]: Why scroll?

**Review by chirag-madlani — DISMISSED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/DataQualityTab.tsx (hunk 1 above)
Comment (Ashish8689) [reply openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/DataQualityTab.tsx:238]: @chirag-madlani  currently it is very congested in the table and even for any column if the data comes larger then it will shrink another column and will create bad UX.

File: openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/ColumnProfileTable.tsx (hunk 2 above)
Comment (Ashish8689) [reply openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/ColumnProfileTable.tsx:283]: https://github.com/open-metadata/OpenMetadata/pull/9903#discussion_r1086276441

**Comment by Ashish8689** [comment]
@chirag-madlani  @devyani-kaushik  changes done as per comments!

**Comment by devyani-kaushik** [comment]
Looks good to me @chirag-madlani @Ashish8689

**Review by chirag-madlani — APPROVED** [review]

**Review by chirag-madlani — APPROVED** [review]
