### PR TITLE
Segregation of assets count on landing page and corresponding navigation to explore page

### LINKED ISSUE #345: Tags usage link which redirects to explore page is broken
Tag usage link "7" redirects
image

image

Similarly, the elastic search results are returning Tier in tags section again causing duplication

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
Closes #345 
### Describe your changes :

I worked on the my-data page because need add different entities count with clickable text

#
### Type of change :

- [x] New feature

#
### Frontend Preview (Screenshots) :
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@shahsank3t, @darth-coder00

### CODE REVIEW

**Review by shahsank3t — APPROVED** [review]
LGTM

File: catalog-rest-service/src/main/resources/ui/src/components/my-data/MyDataHeader.tsx [hunk 1]
```diff
@@ -63,40 +88,62 @@ const MyDataHeader: FunctionComponent<Props> = ({
 
   useEffect(() => {
     setdataSummary({
```
Comment (darth-coder00) [inline catalog-rest-service/src/main/resources/ui/src/components/my-data/MyDataHeader.tsx:90]: This object should be coming from a method,
Also while initialising state at top, we can set this state to `{}`, as this useEffect will be executed on mount and set these values before rendering

File: catalog-rest-service/src/main/resources/ui/src/pages/explore/index.tsx [hunk 2]
```diff
@@ -192,7 +234,7 @@ const ExplorePage: React.FC = (): React.ReactElement => {
       searchText,
       0,
       0,
-      getFilterString(filters),
+      emptyValue,
```
Comment (darth-coder00) [inline catalog-rest-service/src/main/resources/ui/src/pages/explore/index.tsx:237]: Why did we remove filter from here?

Comment (Sachin-chaurasiya) [reply catalog-rest-service/src/main/resources/ui/src/pages/explore/index.tsx:237]: because we don't want to change the count's of other tabs when we select a filter on one tab.

File: catalog-rest-service/src/main/resources/ui/src/components/my-data/MyDataHeader.tsx (hunk 1 above)
Comment (Sachin-chaurasiya) [reply catalog-rest-service/src/main/resources/ui/src/components/my-data/MyDataHeader.tsx:90]: Ohh, I missed this. will change it.

**Review by darth-coder00 — APPROVED** [review]
LGTM
