### PR TITLE
Fixes #4503 - GET lineage by ID returns no nodes

### LINKED ISSUE #4503: GET lineage by ID returns no nodes
**Affected module**
backend

**Describe the bug**
GET lineage by ID returns no nodes, while fetching by FQN works properly.

**To Reproduce**

This works:
```
http GET http://localhost:8585/api/v1/lineage/table/name/sample_data.ecommerce_db.shopify.raw_customer
```

This does not:
```
http GET http://localhost:8585/api/v1/lineage/table/b74049f8-2c20-4e0d-8829-f03224d69013
```

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by sureshms**
### Describe your changes :

Additional tests for #4503. With these additional tests, still the issue can't be duplicated.

#
### Type of change :

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

### CODE REVIEW

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/lineage/LineageResource.java [hunk 1]
```diff
@@ -90,9 +90,17 @@ public EntityLineage get(
...
           int upstreamDepth,
-      @Parameter(description = "Downstream depth of lineage (default=1, min=0, max=3)") @QueryParam("downstreamDepth")
+      @Parameter(description = "Upstream depth of lineage (default=1, min=0, max=3)")
+          @DefaultValue("1")
+          @Min(0)
+          @Max(3)
+          @QueryParam("downstreamDepth")
           int downStreamDepth)
       throws IOException {
     upstreamDepth = Math.min(Math.max(upstreamDepth, 0), 3);
```
Comment (harshach) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/lineage/LineageResource.java:106]: I think we remove the Math.min, Math.max ops

**Review by harshach — APPROVED** [review]
