### PR TITLE
Fix #8993 Add Datainsight ingestion option available even after a pipeline already running

### LINKED ISSUE #8993: Add Datainsight ingestion option available even after a pipeline already running
**Affected module**
UI

**Describe the bug**
image

having that button option allow users to click and we get a bad error

image

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
We should disable the button if the pipeline already deployed

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
Fixes #8993 
### Describe your changes :

I worked on issue #8993 

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx [hunk 1]
```diff
@@ -252,6 +252,17 @@ const Ingestion: React.FC<IngestionProps> = ({
     }
   };
 
+  const isDataSightIngestionExists = useMemo(
+    () =>
+      !isEmpty(
+        !isEmpty(ingestionData) &&
+          ingestionData.filter(
+            (ingestion) => ingestion.pipelineType === PipelineType.DataInsight
+          )
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx:261]: https://lodash.com/docs/4.17.15#some
This is what you are looking for and this will probably reduce complexity over here

**Review by chirag-madlani — CHANGES_REQUESTED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx (hunk 1 above)
Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx]: Thanks, Updated the code.
