### PR TITLE
fix 10883: quick filter dropdown improvements and bug fixes

### LINKED ISSUE #10883: ui: search dropdown bugs and improvements
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**

- [ ] The default options for tasks and charts dropdowns do not show display names which contradicts the options after searching where we show display names.
Screenshot 2023-04-01 at 1 32 53 PM
Screenshot 2023-04-01 at 1 32 59 PM

- [ ] The schemaFields filter dropdown for topics is not working properly.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by aniketkatkar97**
### Describe your changes:

Fixes #10883 

I worked on search dropdown improvements and bug fixes:

- [x] Added the logic to display the `displayName` for the options of the possible fields.
- [x] changed the API call made to fetch default options for the `tasks` and `charts` quick filter dropdowns to show the `displayName` instead of the name.
- [x] Added DataModel filter in Dashboard entity

https://user-images.githubusercontent.com/51777795/229536461-7d69e1a7-7749-4aeb-ad0c-daef6326adf0.mov

- [x] Fixed bug where default options for owner dropdown in Advanced Search Modal were not showing.

https://user-images.githubusercontent.com/51777795/229835835-ab4f9a39-0985-4e6a-baa0-079ae7dd0ba1.mov

https://user-images.githubusercontent.com/66266464/230850236-71098468-15af-4691-bad1-44415082bd95.mov

#
### Type of change:

- [x] Bug fix
- [x] Improvement

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [x] I have commented on my code, particularly in hard-to-understand areas.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/utils/AdvancedSearchUtils.tsx [hunk 1]
```diff
@@ -221,72 +239,141 @@ export const getSelectedOptionLabelString = (
...
-      (chart) =>
-        chart.displayName === uniqueOption.text ||
-        chart.name === uniqueOption.text
-    );
+export const getDisplayNameFromEntity = (
+  text: string,
+  entity?: ChartEntityReference | Task | Column | Field
+) => {
+  return entity ? entity.displayName ?? entity.name ?? text : text;
+};
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/utils/AdvancedSearchUtils.tsx:247]: see if getEntityName(entity) ?? text will help here instead a new function

**Review by chirag-madlani — APPROVED** [review]
