### PR TITLE
Fix #21563: Explore page count mismatch

### LINKED ISSUE #21563: Explore page count mismatch
**Affected module**
Backend

**Describe the bug**
sometimes the explore page shows different count then the actual results

for example:  https://sandbox.open-metadata.org/explore/tables?search=fs&sort=_score&page=1&size=10&sortOrder=desc

the table count is showed as 10 but the actual count is only 7

### PR DESCRIPTION
**Pull request by harshach**
### Describe your changes:

Fixes <issue-number>

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java [hunk 1]
```diff
@@ -224,7 +223,7 @@ public void run(OpenMetadataApplicationConfig catalogConfig, Environment environ
     Fernet.getInstance().setFernetKey(catalogConfig);
 
     // Initialize Workflow Handler
-    WorkflowHandler.initialize(catalogConfig);
+    // WorkflowHandler.initialize(catalogConfig);
```
Comment (sonika-shah) [inline openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java]: I guess `WorkflowHandler.initialize(catalogConfig); `needs to be uncommented

File: openmetadata-service/src/test/java/org/openmetadata/service/search/SearchSourceBuilderFactoryTest.java [hunk 2]
```diff
@@ -0,0 +1,285 @@
...
+    fieldBoost.setBoost(boost);
+    if (matchType != null) {
+      fieldBoost.setMatchType(FieldBoost.MatchType.fromValue(matchType));
+    }
+    return fieldBoost;
+  }
+
+  @Test
+  public void testConsistentSearchBuilderSelection() {
+    // Test that both OpenSearch and ElasticSearch factories use the same logic
```
Comment (sonika-shah) [inline openmetadata-service/src/test/java/org/openmetadata/service/search/SearchSourceBuilderFactoryTest.java:123]: all test failing in the Test file with below error

```
java.lang.NullPointerException: Cannot invoke "org.openmetadata.service.search.SearchRepository.getIndexNameWithoutAlias(String)" because the return value of "org.openmetadata.service.Entity.getSearchRepository()" is null

	at org.openmetadata.service.search.SearchSourceBuilderFactory.getSearchSourceBuilder(SearchSourceBuilderFactory.java:77)
	at org.openmetadata.service.search.SearchSourceBuilderFactory.getSearchSourceBuilder(SearchSourceBuilderFactory.java:69)
	
```
