### PR TITLE
ISSUE #3058 - Bulk Endpoint For Bundle TestSuite Selection

### LINKED ISSUE #3058: Sort users within teams page
**Affected module**
UI 

**Describe the bug**
The list of users in the teams page is not sorted. 
To make it easily readable, we should sort it in lexicographical order

**To Reproduce**

Navigate to teams page and check Users tab
image

**Expected behavior**
Users are sorted

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
We may need to do this for all entities which are displayed on tabs within an entity page.

Eg:
- Users for a Team (this issue)
- Assets for a Team
- Roles for a Team

This could be possibly fixed from the backend by returning all entity reference lists as sorted lists.

cc: @harshach  @sureshms @vivekratnavel

### PR DESCRIPTION
**Pull request by TeddyCr**
### Describe your changes:

Fixes #3058   
  - Add new bulk endpoint PUT /v1/dataQuality/testCases/logicalTestCases/bulk that supports adding test cases to a logical test suite by explicit IDs (mode: "ids") or  selecting all test cases with optional filter (right now supports id exclusions (mode: "all"))
  - Deprecate the existing PUT /logicalTestCases endpoint with Deprecation and Sunset response headers (removal in 2.0)
  - Replace N+1 individual postUpdate calls with batch processing: bulk Entity.getEntities() fetch, postUpdateMany(), and bulk search index updates via SearchIndexHandler.onEntitiesUpdated()
  - Add onEntitiesUpdated to the lifecycle event system (EntityLifecycleEventHandler, EntityLifecycleEventDispatcher) with per-entity fallback for backward compatibility

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [x] I have commented on my code, particularly in hard-to-understand areas. 
- [x] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

Improvement
- [x] I have added tests around the new logic.
- [x] For connector/ingestion changes: I updated the documentation.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestCaseResource.java [hunk 1]
```diff
@@ -1141,7 +1145,7 @@ public Response deleteFailedRowsData(
   @PUT
   @Path("/logicalTestCases")
   @Operation(
-      operationId = "addTestCasesToLogicalTestSuite",
+      operationId = "addTestCasesToBundleTestSuite",
```
Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestCaseResource.java:1148]: @TeddyCr why is this operationId changing?

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java [hunk 2]
```diff
@@ -992,21 +993,68 @@ public void isTestSuiteBasic(String testSuiteFqn) {
...
+        findTo(testSuite.getId(), TEST_SUITE, Relationship.CONTAINS, TEST_CASE);
+
+    Set<UUID> originalIds =
+        originalTestCaseReferences.stream().map(EntityReference::getId).collect(Collectors.toSet());
+    List<EntityReference> newTestCaseReferences =
+        updatedTestCaseReferences.stream()
+            .filter(ref -> !originalIds.contains(ref.getId()))
+            .toList();
+
+    int batchSize = 100;
```
Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java:1051]: should this be hard-coded?

File: openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestCaseResource.java (hunk 1 above)
Comment (TeddyCr) [reply openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestCaseResource.java:1148]: it is just to aligned with the renaming. They used to be called logical test suite but now are called bundle test suite from the ui. If I am not mistaking this is just openapi semantic right?

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java (hunk 2 above)
Comment (TeddyCr) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java:1051]: Since it is internal logic I replicated the approach we have here https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/sink/SinkTaskDelegate.java, LMK if you are thinking about a different approach

Comment (harshach) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java:1051]: Lets check how are doing in other import/export. I beleive we are hard-coding the value to 1000 or something but need to check
