### PR TITLE
Fix #6318 UI : Delete widget is showing wrong entity type

### LINKED ISSUE #6318: UI : Delete widget is showing wrong entity type
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
For every entity delete widget is showing entity types as `table` and `glossary term`.

**To Reproduce**

Screenshots or steps to reproduce
image

image

**Expected behavior**
Should show corresponding entity types.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.12]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
Fixes #6318 
### Describe your changes :

I worked on issue #6318 

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :
image

image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/EntityPageInfo.tsx [hunk 1]
```diff
@@ -499,11 +492,10 @@ const EntityPageInfo = ({
               </div>
             ) : null}
             <Button
-              className="tw-rounded tw-mb-1 tw-flex bg-[#D9CEEE] tw-ml-2"
+              className="tw-rounded tw-mb-1 tw-flex bg-[#D9CEEE] tw-ml-2 tw-border tw-border-primary"
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/EntityPageInfo.tsx:495]: Not sure why we need this class if it's imported form antD

File: openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/EntityPageInfo.tsx [hunk 2]
```diff
@@ -499,11 +492,10 @@ const EntityPageInfo = ({
...
               data-testid="manage-button"
               size="small"
-              theme="primary"
-              variant="outlined"
+              type="default"
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/EntityPageInfo.tsx:498]: See if type `Primary` eliminate classes or not

File: openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/EntityPageInfo.tsx [hunk 3]
```diff
@@ -513,9 +505,10 @@ const EntityPageInfo = ({
                 position="bottom-end"
                 theme="light"
                 onRequestClose={() => setShowActions(false)}>
-                <span>
-                  <FontAwesomeIcon icon="ellipsis-vertical" />
-                </span>
+                <FontAwesomeIcon
+                  className="tw-text-primary"
+                  icon="ellipsis-vertical"
+                />
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/EntityPageInfo.tsx:511]: Can we replace it with AntD? So that in future we can remove fontAwesome lib?

File: openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/EntityPageInfo.tsx (hunk 1 above)
Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/EntityPageInfo.tsx:495]: @chirag-madlani , This is for adding an outline to the button.

File: openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/EntityPageInfo.tsx (hunk 2 above)
Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/EntityPageInfo.tsx:498]: If we give the primary then it will `contained` button but here we need an `outlined` button.

File: openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/EntityPageInfo.tsx (hunk 3 above)
Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/EntityPageInfo.tsx:511]: @chirag-madlani, Sure, I will have a look into this.

**Review by chirag-madlani — APPROVED** [review]
