### PR TITLE
Fixed #4203: Do not show empty items in Recent Views

### LINKED ISSUE #4203: UI: Do not show empty items in Recent Views
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
If a service does not exist or the table does not exist, we should not show an empty item in the "Recent Views" widget in the homepage

image (1)

### PR DESCRIPTION
**Pull request by darth-coder00**
Closes #4203
### Describe your changes :

I worked on removing recently viewed entities missing name

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :
<p align="center">
Screenshot 2022-04-19 at 10 17 48 PM
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui @harshach

### CODE REVIEW

**Comment by vivekratnavel** [comment]
@darth-coder00 Can you please take care of the code smell?

File: openmetadata-ui/src/main/resources/ui/src/components/recently-viewed/RecentlyViewed.tsx [hunk 1]
```diff
@@ -25,14 +25,16 @@ const RecentlyViewed: FunctionComponent = () => {
...
       setIsloading(true);
-      const formatedData = recentlyViewedData.map((data) => {
-        return {
-          serviceType: data.serviceType,
-          name: data.displayName || prepareLabel(data.entityType, data.fqn),
-          fullyQualifiedName: data.fqn,
-          index: data.entityType,
-        };
-      });
+      const formatedData = recentlyViewedData
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/components/recently-viewed/RecentlyViewed.tsx:28]: Nit: typo
```suggestion
      const formattedData = recentlyViewedData
```

**Review by vivekratnavel — APPROVED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/recently-viewed/RecentlyViewed.tsx [hunk 2]
```diff
@@ -25,14 +25,16 @@ const RecentlyViewed: FunctionComponent = () => {
...
+        .map((data) => {
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/components/recently-viewed/RecentlyViewed.tsx:29]: Need to refactor the local variable "data"

**Review by vivekratnavel — APPROVED** [review]
