### PR TITLE
fix(teams): team header layout, heading truncation, hierarchy overflow, and teams tab empty state

### LINKED ISSUE #27074: Team name truncation not respecting available space on teams settings page
## Problem
Team names are being cut off on the teams settings page even when there is sufficient space to render the full name.

## Current Behavior
Team names are truncated prematurely, not utilizing available screen space effectively.

## Expected Behavior
Team names should display fully when space is available, with truncation limited to half the page width to maintain visual consistency (similar to entity names).

### PR DESCRIPTION
**Pull request by harsh-vador**
### Describe your changes:
This PR improves the Settings → Teams team detail experience: header layout and display-name heading, sub-team table overflow, and a bug where the Teams tab showed an empty state after editing the display name.

### Changes
1. **Team header row (`TeamDetailsV1.tsx`)**  
  - Reworked the collapsible header so breadcrumb uses full width and the row with avatar, title, **Join team** / actions, and **Manage** sits on one line (`justify-between`), with a flexible, shrinkable title area (`tw:flex-1 tw:min-w-0`) so buttons no longer wrap unnecessarily.
2. **Team display name heading (`TeamsHeadingLabel.component.tsx`)**  
  - Replaced Ant Design `Typography.Title` (with `w-max-200`) with `Typography` from `@openmetadata/ui-core-components`.  
  - Truncation uses `tw:truncate` with a wider cap: `tw:max-w-1/3` in read-only mode only (not applied while inline editing).  
  - Empty display name still uses core `Typography` for consistency.  
  - Wrapped the heading in `Tooltip` + overflow container so the full name is available on hover when truncated.
3. **Team hierarchy table (`TeamHierarchy.tsx` + `teams.less`)**  
  - Removed `whitespace-nowrap` on the Teams column, set `table-layout: fixed`, constrained the name column width, and used flex on the expandable first cell so long names ellipsis instead of overlapping the **Type** column.  
  - Added `Tooltip` on the team name link for the full display name on hover.
4. **Teams tab empty placeholder (`TeamDetailsV1.tsx`)**  
  - Fixed incorrect empty state when `childrenCount` from a PATCH response did not match loaded children (e.g. after saving display name): show the add-team placeholder only when search is empty, `childTeamList` is empty, `childrenCount` is 0, and basic team data is not loading (`lodash` `isEmpty` for search and list).

https://github.com/user-attachments/assets/8b7e3322-e206-4094-a156-74666d13ad7d

Fixes #27074 

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamsHeaderSection/TeamsHeadingLabel.component.tsx [hunk 1]
```diff
@@ -192,7 +195,14 @@ const TeamsHeadingLabel = ({
     }
   }, [currentTeam]);
 
-  return <Space size={4}>{teamHeadingRender}</Space>;
+  return (
+    <div
+      className={`d-flex items-center tw:gap-1${
+        isHeadingEditing ? '' : ' tw:max-w-1/3'
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamsHeaderSection/TeamsHeadingLabel.component.tsx]: can you please use classNames fn here?
