### PR TITLE
Fixes #20680: Added readTimeout input field

### LINKED ISSUE #20680: Issue with ReadTimeout in Event Subscription
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
When creating event subscription, under destination we need to add input field for readTineout in seconds options

**Describe the bug**

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by dhruvjsx**
### Describe your changes:

Fixes #20680

https://github.com/user-attachments/assets/536deee9-830d-4d3b-b172-cb3b23ef513a

Screenshot 2025-04-11 at 11 27 06 AM
Screenshot 2025-04-10 at 7 24 41 PM

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/utils/Alerts/AlertsUtil.tsx [hunk 1]
```diff
@@ -374,6 +374,30 @@ export const getConnectionTimeoutField = () => (
...
+            defaultValue={10}
+            placeholder={`${t('label.read-type', {
+              type: t('label.timeout'),
+            })} (${t('label.second-plural')})`}
+            type="number"
+          />
+        </Form.Item>
+      </Col>
+    </Row>
+    <Divider className="p-x-xs" />
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/src/utils/Alerts/AlertsUtil.tsx:397]: Let's not add one more Divider, better to keep both timeout fields in a single block.

File: openmetadata-ui/src/main/resources/ui/src/utils/Alerts/AlertsUtil.tsx [hunk 2]
```diff
@@ -111,6 +111,8 @@ import searchClassBase from '../SearchClassBase';
 import { showSuccessToast } from '../ToastUtils';
 import './alerts-util.less';
 
+export const DEFAULT_READ_TIMEOUT = 12;
+
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/src/utils/Alerts/AlertsUtil.tsx:115]: Can we move it to a constants file?

File: openmetadata-ui/src/main/resources/ui/src/constants/constants.ts [hunk 3]
```diff
@@ -420,3 +420,5 @@ export const MAX_VISIBLE_OWNERS_FOR_FEED_TAB = 4;
 export const MAX_VISIBLE_OWNERS_FOR_FEED_CARD = 2;
 
 export const BREADCRUMB_SEPARATOR = '/';
+
+export const DEFAULT_READ_TIMEOUT = 12;
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/src/constants/constants.ts:424]: We are planning to remove this file. Always keep things in specific files, please move this to another constants file, alert-specific constant file if it's present.

**Review by mohityadav766 — APPROVED** [review]
