### PR TITLE
Fixes #27239: Show and edit Cluster Key table constraints in UI

### LINKED ISSUE #27239: Cluster Key Table Constraint not visible in UI
**Affected module**
UI

**Describe the bug**

Image

Image

Table Payload 

```
{
    "id": "a0f04705-0eb8-496a-8cf0-c3ad09c2439b",
    "name": "test_mview_case_v2",
    "fullyQualifiedName": "local_bigquery1.my_bq_project.mayur_test.test_mview_case_v2",
    "version": 0.1,
    "updatedAt": 1775819194270,
    "updatedBy": "admin",
    "href": "http://host.docker.internal:8585/api/v1/tables/a0f04705-0eb8-496a-8cf0-c3ad09c2439b",
    "tableType": "MaterializedView",
    "columns": [
        {
            "name": "Entity_ID",
            "dataType": "INT",
            "dataLength": 1,
            "dataTypeDisplay": "integer",
            "fullyQualifiedName": "local_bigquery1.my_bq_project.mayur_test.test_mview_case_v2.Entity_ID",
            "tags": [],
            "constraint": "NULL",
            "children": []
        },
        {
            "name": "Entity_Type",
            "dataType": "INT",
            "dataLength": 1,
            "dataTypeDisplay": "integer",
            "fullyQualifiedName": "local_bigquery1.my_bq_project.mayur_test.test_mview_case_v2.Entity_Type",
            "tags": [],
            "constraint": "NULL",
            "children": []
        }
    ],
    "tableConstraints": [
        {
            "constraintType": "CLUSTER_KEY",
            "columns": [
                "Entity_ID",
                "Entity_Type"
            ]
        }
    ],
    "owners": [],
    "databaseSchema": {
        "id": "b661bfe7-ac58-43a2-a9e4-5673c2bdc8b7",
        "type": "databaseSchema",
        "name": "mayur_test",
        "fullyQualifiedName": "local_bigquery1.my_bq_project.mayur_test",
        "description": "",
        "displayName": "mayur_test",
        "deleted": false,
        "href": "http://host.docker.internal:8585/api/v1/databaseSchemas/b661bfe7-ac58-43a2-a9e4-5673c2bdc8b7"
    },
    "database": {
        "id": "58c6fc62-f404-45ad-82e0-1e42c66aa482",
        "type": "database",
        "name": "my_bq_project",
        "fullyQualifiedName": "local_bigquery1.my_bq_project",
        "displayName": "my_bq_project",
        "deleted": false,
        "href": "http://host.docker.internal:8585/api/v1/databases/58c6fc62-f404-45ad-82e0-1e42c66aa482"
    },
    "service": {
        "id": "8659df62-a43f-4545-b64b-e5519339e159",
        "type": "databaseService",
        "name": "local_bigquery1",
        "fullyQualifiedName": "local_bigquery1",
        "displayName": "local_bigquery1",
        "deleted": false,
        "href": "http://host.docker.internal:8585/api/v1/services/databaseServices/8659df62-a43f-4545-b64b-e5519339e159"
    },
    "serviceType": "BigQuery",
    "schemaDefinition": "CREATE MATERIALIZED VIEW mayur_test.test_mview_case_v2 AS SELECT\n    Entity_ID as Entity_ID,\n    Entity_Type as Entity_Type\n  FROM `my_bq_project.mayur_test.source_case_test`",
    "tags": [],
    "usageSummary": {
        "dailyStats": {
            "count": 0,
            "percentileRank": 0
        },
        "weeklyStats": {
            "count": 0,
            "percentileRank": 0
        },
        "monthlyStats": {
            "count": 0,
            "percentileRank": 0
        },
        "date": "2026-04-10"
    },
    "followers": [],
    "joins": {
        "startDate": "2026-03-11",
        "dayCount": 30,
        "columnJoins": [],
        "directTableJoins": []
    },
    "incrementalChangeDescription": {
        "fieldsAdded": [],
        "fieldsUpdated": [],
        "fieldsDeleted": [],
        "previousVersion": 0.1
    },
    "deleted": false,
    "sourceUrl": "https://console.cloud.google.com/bigquery?project=my_bq_project&ws=!1m5!1m4!4m3!1smy_bq_project!2smayur_test!3stest_mview_case_v2",
    "domains": [],
    "dataProducts": [],
    "votes": {
        "upVotes": 0,
        "downVotes": 0,
        "upVoters": [],
        "downVoters": []
    },
    "lifeCycle": {
        "created": {
            "timestamp": 1775819083216
        }
    },
    "sourceHash": "2b127837266d941dfeb08cfa13c10cb5",
    "processedLineage": false,
    "entityStatus": "Unprocessed"
}
```

### PR DESCRIPTION
**Pull request by hassaansaleem28**
### Describe your changes:

Fixes #27239 

### What I worked on: 
- Render Cluster Key in Table Constraints card.
- Add Cluster Key in constraint type options and icon mapping.
- Support Cluster Key load and save in Update Table Constraints modal.
- Stop eager suggestions fetch on modal open to avoid the Error while fetching suggestions banner.
- Add regression tests for Cluster Key render and modal save behavior
- Verified Cluster Key is visible on table details page.

### BEFORE : 
Screenshot from 2026-04-10 22-17-56

### AFTER : 
Screenshot from 2026-04-11 22-37-59

#
### Type of change:

- [x] Bug fix
#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [x] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

- [x] I have added a test that covers the exact scenario we are fixing. For complex issues, comment the issue number in the test for future reference.

### CODE REVIEW

**Review by chirag-madlani — DISMISSED** [review]

File: openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableConstraints/ConstraintIcon.tsx [hunk 1]
```diff
@@ -12,6 +12,7 @@
  */
 import Icon from '@ant-design/icons/lib/components/Icon';
 import { Tooltip } from 'antd';
+import { ReactComponent as IconCluster } from '../../../assets/svg/icon-cluster.svg';
 import { ReactComponent as IconDistribution } from '../../../assets/svg/icon-distribution.svg';
 import { ReactComponent as IconKey } from '../../../assets/svg/icon-key.svg';
```
Comment (ulixius9) [inline openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableConstraints/ConstraintIcon.tsx]: @hassaansaleem28 instead of using this new cluster icon can we just reuse the distribution icon?

Comment (hassaansaleem28) [reply openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableConstraints/ConstraintIcon.tsx]: Sure, I will add that again
I changed it coz of bot recommendation
image

**Comment by hassaansaleem28** [comment]
Good day @chirag-madlani @ulixius9, 
I have updated the PR with all changes and issues addressed and now all tests are passing. 
Let me know if any further changes are required. Thanks!

**Review by ulixius9 — APPROVED** [review]

**Review by chirag-madlani — APPROVED** [review]
