### PR TITLE
fixed ui: [UI] Data Insights UI does not show scheduling options and range selector not including last day bug

### LINKED ISSUE #11254: [UI] Data Insights UI does not show scheduling options
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
image

**To Reproduce**
Navigate to settings > Insights edit the existing insights available or create new. Proceed to the last screen where you can configure scheduling activity.

**Expected behavior**
Possible option is to disable the cron scheduling if this is intended to run everyday!

**Version:**
 - OpenMetadata version: 1.0.0-beta

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes:

Fixes #11254 

- [UI] Data Insights UI does not show scheduling options and range
- selector not including last day bug

image

https://user-images.githubusercontent.com/71748675/234528862-3871effd-fadb-4a76-82b2-9e3a5a989664.mov

image
image

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/utils/TimeUtils.ts [hunk 1]
```diff
@@ -196,7 +196,10 @@ export const getPastDaysDateTimeMillis = (days: number) =>
 export const getFormattedDateFromSeconds = (
   timeStamp: number,
   format?: string
-) => DateTime.fromSeconds(timeStamp || 0).toFormat(format || 'dd/MMM HH:mm');
+) =>
+  DateTime.fromSeconds(timeStamp || 0)
+    .toUTC()
+    .toFormat(format || 'dd/MMM HH:mm');
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/utils/TimeUtils.ts:202]: @ShaileshParmar11, Can you share some screenshots of where we are using this method?

**Review by Sachin-chaurasiya — COMMENTED** [review]
Left a few comments, thanks

File: openmetadata-ui/src/main/resources/ui/src/utils/TimeUtils.ts (hunk 1 above)
Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/utils/TimeUtils.ts:202]: updated

**Review by Sachin-chaurasiya — APPROVED** [review]

**Review by chirag-madlani — APPROVED** [review]
