### PR TITLE
Fix: #2437 Table entity page makes a call with all fields.

### LINKED ISSUE #2437: Table entity page makes a call with all fields
Table entity page loads all the data in one call to backend.
We should load the pages incrementally, example schema page only needs base details of table
and for sampledata , we can make another call to get those details

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
Fixes #2437 
### Describe your changes :

I worked on issue #2437 to load entity data when it's needed.

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@shahsank3t, @darth-coder00

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx [hunk 1]
```diff
@@ -131,7 +135,157 @@ const DatasetDetailsPage: FunctionComponent = () => {
...
+        }
+      }
+
+      default:
+        break;
+    }
+  };
+
   useEffect(() => {
+    fetchTabSpecificData(datasetTableTabs[activeTab - 1].field);
```
Comment (darth-coder00) [inline openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx:288]: Should be under separate `useEffect` with dependency of `activeTab`

File: openmetadata-ui/src/main/resources/ui/src/utils/DatasetDetailsUtils.ts [hunk 2]
```diff
@@ -11,6 +11,9 @@
  *  limitations under the License.
  */
 
+export const defaultFields =
+  'columns, usageSummary, followers, joins, tags, owner, dataModel';
```
Comment (darth-coder00) [inline openmetadata-ui/src/main/resources/ui/src/utils/DatasetDetailsUtils.ts:15]: Use values from enum everywhere.

**Review by darth-coder00 — CHANGES_REQUESTED** [review]
Minor changes

**Review by darth-coder00 — APPROVED** [review]
LGTM!
