### PR TITLE
#15650 UI: Not able to select all possible dates range from the custom date picker in the incident manager

### LINKED ISSUE #15650: UI: Not able to select all possible dates range from the custom date picker in the incident manager
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**

- [ ] While selecting the custom date, I'm unable to select the range I want before the current date. I can do that for the dates after the current date.

- [ ] When I select the custom range from tomorrow to any date after. I still see the tests from today.

https://github.com/open-metadata/OpenMetadata/assets/51777795/cb0d976a-fc02-4554-bbc8-b4569373c4e2

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes:

Fixes #15650

- reverted default value changes, keeping old Behaviour the same in the profiler
- Allow users to select start and end date whenever users open the custom date picker

https://github.com/open-metadata/OpenMetadata/assets/71748675/04bf192c-f457-491a-9365-b8e60920fe9b

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Review by Sachin-chaurasiya — APPROVED** [review]
@ShaileshParmar11 , Let's add the the test for the same.

File: openmetadata-ui/src/main/resources/ui/src/components/common/DatePickerMenu/DatePickerMenu.component.tsx [hunk 1]
```diff
@@ -163,10 +162,6 @@ const DatePickerMenu = ({
               <DatePicker.RangePicker
                 bordered={false}
                 clearIcon={<CloseCircleOutlined />}
-                defaultValue={[
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/common/DatePickerMenu/DatePickerMenu.component.tsx:166]: We have removed ability to ser default range, Isn't this cause issue at other place?
Can you add tests for the same?

Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/components/common/DatePickerMenu/DatePickerMenu.component.tsx:166]: It won't create an issue, as we are showing the date on the label, and storing that label in the state, and in case we pass the default value via props it's being stored in the state and shown as a label. I'll check for the unit test!

**Review by chirag-madlani — APPROVED** [review]
