### PR TITLE
Fix UI :- Fix the active tab for explore page after refresh

### LINKED ISSUE #8388: UI: Explore page showing wrong active tab after refresh
Steps to reproduce:-
1. visit explore page.
2. visit any tab other than the table
3. refresh the page and check the active tab

https://user-images.githubusercontent.com/71748675/198281709-65597b4d-6a64-41e0-803c-694379539d28.mov

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes :

- Issue :- Closes #8388
- Fix the active tab for explore page after refresh

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :

https://user-images.githubusercontent.com/66266464/198583582-d6022e66-0b92-4e3d-9365-ec88e8b3b41b.mov

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx [hunk 1]
```diff
@@ -53,7 +58,14 @@ const Explore: React.FC<ExploreProps> = ({
   loading,
 }) => {
   const isMounting = useRef(true);
+  const { tab } = useParams() as Record<string, string>;
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx:61]:
```suggestion
  const { tab } = useParams() as Record<{tab: string}>;
```

File: openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx [hunk 2]
```diff
@@ -53,7 +58,14 @@ const Explore: React.FC<ExploreProps> = ({
...
+
+  // get entity active tab by URL params
+  const defaultActiveTab = () => {
+    const entityName = tab.slice(0, -1).toUpperCase();
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx:65]: Please do safe handling like tab.slice(0, -1) is a string and won't throw an exception

File: openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx [hunk 3]
```diff
@@ -53,7 +58,14 @@ const Explore: React.FC<ExploreProps> = ({
   loading,
 }) => {
   const isMounting = useRef(true);
+  const { tab } = useParams() as Record<string, string>;
+
+  // get entity active tab by URL params
+  const defaultActiveTab = () => {
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx:64]: Should be value instead a function
implement useMemo to memoize values

**Comment by Ashish8689** [comment]
@chirag-madlani  All comments has been addressed!

File: openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx [hunk 4]
```diff
@@ -58,14 +59,15 @@ const Explore: React.FC<ExploreProps> = ({
...
-  const { tab } = useParams() as Record<string, string>;
+  const { tab } = useParams<{ tab: string }>();
 
   // get entity active tab by URL params
-  const defaultActiveTab = () => {
-    const entityName = tab.slice(0, -1).toUpperCase();
+  const defaultActiveTab = useMemo(() => {
+    const entityName = ENTITY_PATH[tab as keyof typeof ENTITY_PATH] ?? 'table';
+
+    return SearchIndex[entityName.toUpperCase() as ExploreSearchIndexKey];
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx:68]: Looks too complicated can we simplify this?

File: openmetadata-ui/src/main/resources/ui/src/constants/constants.ts [hunk 5]
```diff
@@ -507,3 +507,11 @@ export const configOptions = {
...
 export const NOTIFICATION_READ_TIMER = 2500;
 export const TIER_CATEGORY = 'Tier';
+
+export const ENTITY_PATH = {
+  tables: 'table',
+  topics: 'topic',
+  dashboards: 'dashboard',
+  pipelines: 'pipeline',
+  mlmodels: 'mlmodel',
+};
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/constants/constants.ts:517]: We might have this type of data can we double-check before adding it?

**Comment by Ashish8689** [comment]
@chirag-madlani Comments have been addressed.

File: openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx [hunk 6]
```diff
@@ -63,9 +64,9 @@ const Explore: React.FC<ExploreProps> = ({
 
   // get entity active tab by URL params
   const defaultActiveTab = useMemo(() => {
-    const entityName = ENTITY_PATH[tab as keyof typeof ENTITY_PATH] ?? 'table';
+    const entityName = toUpper(ENTITY_PATH[tab as EntityType] ?? 'table');
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx:67]: What's the need of doing `toUpper` here?

Comment (Ashish8689) [reply openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx:67]: @chirag-madlani The object which is using `entityName`  is expecting entity name in Uppercase to return it's value

File: openmetadata-ui/src/main/resources/ui/src/pages/CustomPropertiesPageV1/CustomPropertiesPageV1.tsx [hunk 7]
```diff
@@ -51,8 +54,7 @@ const CustomEntityDetailV1 = () => {
   const [selectedEntityTypeDetail, setSelectedEntityTypeDetail] =
     useState<Type>({} as Type);
 
-  const tabAttributePath =
-    customAttributesPath[tab as keyof typeof customAttributesPath];
+  const tabAttributePath = ENTITY_PATH[tab.toLowerCase() as EntityType];
```
[the remark this answers is not in the document]
Comment (Ashish8689) [reply openmetadata-ui/src/main/resources/ui/src/pages/CustomPropertiesPageV1/CustomPropertiesPageV1.tsx:57]: @chirag-madlani `ENTITY_PATH`  is expecting key in small case and one value `tab` having value in uppercase. Since it's only affecting here that why `toLowerCase`  is used.

**Review by chirag-madlani — APPROVED** [review]

**Comment by chirag-madlani** [comment]
@Ashish8689 Can we rebase this with latest main, as cypress got stuck
