### PR TITLE
[Fix-25563] - Issue in Search Entity By Key 

### LINKED ISSUE #25563: Assets missing from search & lineage not visible
**Affected module**
Does it impact the UI, backend or Ingestion Framework? - Backend

**Describe the bug**
- Some assets intermittently go missing from Search and Lineage, even though they exist in the system and were previously visible. The issue appears to be related to scheduled search indexing not consistently picking up certain entities. A manual reindex restores the missing assets immediately with lower batch size.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
- Assets should not disappear from Search or Lineage without deletion.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by mohityadav766**
### Describe your changes:

[Fix 25563](https://github.com/open-metadata/OpenMetadata/issues/25563)
Fix #25563

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

----
## Summary by Gitar

- **Fixed entity reference resolution:**
  - Modified `Entity.getEntityOrNull()` to catch `EntityNotFoundException` and return null instead of propagating the exception
  - Prevents search indexing failures when broken (orphaned) entity references exist
- **Enhanced search error reporting:**
  - Updated `ElasticSearchSearchManager` to extract and include root cause details from ES error responses
  - Improves debugging visibility for search failures
- **Improved column indexing:**
  - Added separate `columnBulkProcessor` with dedicated lifecycle in `ElasticSearchBulkSink` and `OpenSearchBulkSink`
  - Asynchronously indexes table columns with proper timeout and failure tracking
- **New test suite:**
  - Added `LineageBrokenReferenceIT` integration tests verifying graceful handling of orphaned lineage and FK references during reindex

<sub>This will update automatically on new commits.</sub>

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchEntityManager.java [hunk 1]
```diff
@@ -346,43 +346,75 @@ public void updateEntity(
...
-                  .upsert(params)
-                  .script(
-                      s ->
-                          s.source(ss -> ss.scriptString(scriptTxt))
-                              .lang(ScriptLanguage.Painless)
-                              .params(params)),
-          Map.class);
+    Map<String, JsonData> params = convertToJsonDataMap(doc);
+    int attempt = 0;
+    while (true) {
```
Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchEntityManager.java]: why are we doing while(true)? if this is about retries, there are better libraries then adding while(true) in code

Comment (harshach) [reply openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchEntityManager.java]: can we use the retry lib we already have elsewhere

Comment (mohityadav766) [reply openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchEntityManager.java]: addressed @harshach

**Review by yan-3005 — APPROVED** [review]
