### PR TITLE
Fix: Issue #1348 - My Data and Followers are empty

### LINKED ISSUE #1348: My Data and Followers are empty
It looks like UI changed the calls from landing page to ES to have from and size=0 for all the calls
1. Whenever we are showing counts we should use from and size to 0 to reduce the load on ES
2. whenever we need to show the data assets we should pass size to 10 or higher and use pagination to continue to list the assets like we do in search
Right now its using http://localhost:8585/api/v1/search/query?q=*%20AND%20followers:564cd2ca-06e4-4e5f-aea3-1fd17599d05f&from=0&size=0&index=dashboard_search_index,topic_search_index,table_search_index,pipeline_search_index
for My Data and Follower page. These 2 tabs shows it empty as the data is not being returned from ES

image

### PR DESCRIPTION
**Pull request by darth-coder00**
### Describe your changes :
Closes #1348 

I worked on the My Data and Following tabs to get list of entities if present

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :
<p align="center">
Screenshot 2021-11-25 at 2 33 08 PM
Screenshot 2021-11-25 at 2 33 18 PM

</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@shahsank3t @Sachin-chaurasiya

### CODE REVIEW

**Review by akash-jain-10 — APPROVED** [review]

File: openmetadata-ui/src/main/resources/ui/src/pages/MyDataPage/MyDataPage.component.tsx [hunk 1]
```diff
@@ -40,13 +41,17 @@ const MyDataPage = () => {
   const [searchResult, setSearchResult] = useState<SearchResponse>();
   const [entityCounts, setEntityCounts] = useState<EntityCounts>();
 
-  const fetchData = (value: SearchDataFunctionType, fetchService = false) => {
+  const fetchData = (
+    value: SearchDataFunctionType,
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/MyDataPage/MyDataPage.component.tsx:45]: @darth-coder00 `SearchDataFunctionType` has `size` as an optional field so we can use that instead of passing `pageSize` directly.

**Review by Sachin-chaurasiya — CHANGES_REQUESTED** [review]
One minor change, Otherwise LGTM.

**Review by Sachin-chaurasiya — APPROVED** [review]

**Review by ShaileshParmar11 — APPROVED** [review]
Looks good.!
