### PR TITLE
ui: NO option to edit associated tables  "Query used by other tables:" while editing query #12346

### LINKED ISSUE #12346: Allow updating "Query used by other tables:" while editing query
**Affected module**
Impact on UI (maybe to the backend )

**Describe the bug**
Version (1.1.0  Sandbox)
Problem: Editing query allows to edit query however there is NO option to edit associated tables  "Query used by other tables:".

**To Reproduce**
More details at https://openmetadata.slack.com/archives/C02B6955S4S/p1688888141300939

image

**Expected behavior**
The expected behaviour is to allow editing of the "Query used by other tables:" while editing the query

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes:

Fixes #12346

added support to edit queryUsedIn in query

https://github.com/open-metadata/OpenMetadata/assets/71748675/b4e2344e-0a01-413a-a4fd-55a45fa8e865

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/TableQueries/QueryUsedByOtherTable/QueryUsedByOtherTable.component.tsx [hunk 1]
```diff
@@ -11,83 +11,183 @@
...
+
+  const fetchInitialOptions = async () => {
+    setIsLoading(true);
+    try {
+      const options = await fetchTableEntity();
+      const selectedValue =
+        query.queryUsedIn?.map((table) => ({
+          label: getEntityName(table),
+          value: table.id,
+        })) ?? [];
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/TableQueries/QueryUsedByOtherTable/QueryUsedByOtherTable.component.tsx:146]:
```suggestion
      const { queryUsedIn = [] } = query;
      const selectedValue =
        queryUsedIn.map((table) => ({
          label: getEntityName(table),
          value: table.id,
        }));
```

**Review by Sachin-chaurasiya — COMMENTED** [review]
Left a few comments, thanks

**Review by Sachin-chaurasiya — APPROVED** [review]

**Review by karanh37 — APPROVED** [review]

**Review by karanh37 — APPROVED** [review]

**Review by Sachin-chaurasiya — APPROVED** [review]
