### PR TITLE
fix: missing localization key

### LINKED ISSUE #10298: UI Ingestion Pipeline - label.none schedule
image

If selecting `label.none`, the page dies

image

Also, the wording is not consistent.

Thanks

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes :

fixed missing localization keys
Closes #10298

#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/ColumnProfileTable.tsx [hunk 1]
```diff
@@ -281,7 +281,7 @@ const ColumnProfileTable: FC<ColumnProfileTableProps> = ({
     <div data-testid="column-profile-table-container">
       <div className="tw-w-2/6">
         <Searchbar
-          placeholder={`${t('label.find-in-table')}...`}
+          placeholder={`${t('message.find-in-table')}...`}
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/ColumnProfileTable.tsx:284]: can we remove three dots?

**Comment by chirag-madlani** [comment]
@ShaileshParmar11 Can you make this consistent in terms of case 
Screenshot 2023-02-23 at 7 31 56 PM

**Review by chirag-madlani — APPROVED** [review]
