### PR TITLE
UI : fix the search bar issue having quote in the search text

### LINKED ISSUE #6811: Exact search with quotes does not work
**Affected module**
UI
**Describe the bug**
Use the top search bar to search for any keyword or phrase with quotes:
```
"this is nonsense"
```
for example. It will return all tables in the database.

**To Reproduce**

see description
**Expected behavior**
Results should match exact phrase.

**Version:**
 - OS: [e.g. iOS]: n/a
 - Python version: n/a
 - OpenMetadata version: 0.11.4
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes :

- Closes #6811
- fix the search bar issue of having quotes in the search text
- fix the search text having `/` in it

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :
Before : 
image

After :
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/constants/constants.ts [hunk 1]
```diff
@@ -525,3 +525,7 @@ export const ENTITY_PATH = {
   pipelines: 'pipeline',
   mlmodels: 'mlmodel',
 };
+
+// will add back slash "\" before quote in string if present
+export const getQueryWithSlash = (query: string): string =>
+  query.replace(/["']/g, '\\$&');
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/constants/constants.ts:531]: Move this to search utils.

Comment (Ashish8689) [reply openmetadata-ui/src/main/resources/ui/src/constants/constants.ts]: @Sachin-chaurasiya  updated!

**Review by Sachin-chaurasiya — APPROVED** [review]
