### PR TITLE
fix issue: 4558 UI: Add support to enable debug logging in Metadata Ingestion form

### LINKED ISSUE #4558: UI: Add support to enable debug logging in Metadata Ingestion form

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes :

Closes #4558 UI: Add support to enable debug logging in Metadata Ingestion form

#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/pages/AddIngestionPage/AddIngestionPage.component.tsx [hunk 1]
```diff
@@ -97,6 +98,8 @@ const AddIngestionPage = () => {
                     jsonData['api-error-messages']['deploy-ingestion-error']
                   );
                 } else {
+                  reject();
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/pages/AddIngestionPage/AddIngestionPage.component.tsx:101]: Do we need to reject here if we are already rejecting in the catch block?

Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/pages/AddIngestionPage/AddIngestionPage.component.tsx:101]: Ya correct.! I ll make changes

**Review by vivekratnavel — APPROVED** [review]

**Review by shahsank3t — APPROVED** [review]
