### PR TITLE
fix(ui) UI: Inconsistency in left panel #9431

### LINKED ISSUE #9431: UI: Inconsistency in left panel
- [ ] Inconsistent section headers font styling as shown below. The first one feels more pleasing to my eyes at least.
**As discussed with @harshach we will hold this one for 0.13.1 and do it on 0.13.2**
image
image
image
image

_Originally posted by @sureshms in https://github.com/open-metadata/OpenMetadata/issues/9184#issuecomment-1340283456_

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes:

Fixes #9431 

I have updated style of the left panel of myData & Explore page to keep consistent with setting page

image
image
image

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/EntityList/EntityList.tsx [hunk 1]
```diff
@@ -90,14 +90,17 @@ export const EntityListWithAntd: FunctionComponent<AntdEntityListProp> = ({
...
-    <Card
-      className="panel-shadow-color"
-      extra={headerText}
-      title={headerTextLabel}>
+    <Card className="panel-shadow-color">
       <EntityListSkeleton
         dataLength={entityList.length !== 0 ? entityList.length : 5}
         loading={Boolean(loading)}>
         <>
+          <Space className="w-full justify-between p-b-sm">
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/src/components/EntityList/EntityList.tsx:98]: Instead of giving custom classes to the `Space` component, can we use the `Row/Col` component s instead? This might lead to some overflow issues.

Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/components/EntityList/EntityList.tsx]: Thanks!

**Review by aniketkatkar97 — APPROVED** [review]

**Review by chirag-madlani — APPROVED** [review]

**Review by chirag-madlani — APPROVED** [review]
