### PR TITLE
Fix glossary page performance issue with large number of terms(#19761)

### LINKED ISSUE #19761: Glossary Page Performance Issue with Large Number of Terms
**Affected module**
backend

**Describe the bug**
We found that on the glossary page of the term, when there are many terms, the page loads very slowly.
This is because each term will setFieldsInternal, and looping through these terms will cause the page to load very slowly,
even reaching more than 20s.

**To Reproduce**
Add 2000 terms in glossary page.
Image

**Expected behavior**

**Version:**
 - OS: 
 - Python version:
 - OpenMetadata version: 1.6.1
 - OpenMetadata Ingestion package version: 

**Additional context**

### PR DESCRIPTION
**Pull request by juntaozhang**
### Describe your changes:

Fixes #19761

I worked on optimizing the glossary page performance issue because the page was loading very slowly when there were a large number of terms. 
I modified the code to use batch methods for setting inherited fields, which significantly reduces the page load time.
I tested the optimization by adding 3000 terms to the glossary page and confirmed that the load time was reduced to less than 1 second.

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes 19761: Glossary Page Performance Issue with Large Number of Terms`
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java [hunk 1]
```diff
@@ -692,34 +723,47 @@ public final T findByName(String fqn, Include include, boolean fromCache) {
...
+  public List<T> findByNames(List<String> entityFQNs, Include include) {
+    return dao.findEntityByNames(entityFQNs, include);
+  }
+
   public final List<T> listAll(Fields fields, ListFilter filter) {
     // forward scrolling, if after == null then first page is being asked
     List<String> jsons = dao.listAfter(filter, Integer.MAX_VALUE, "", "");
     List<T> entities = new ArrayList<>();
     for (String json : jsons) {
       T entity = setFieldsInternal(JsonUtils.readValue(json, entityClass), fields);
```
Comment (sonika-shah) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java:735]: hi @juntaozhang , i think we can remove the `setFieldsInternal` from here , as we are already calling `setFieldsInternal` in `setFieldsInBulk` method

**Review by sonika-shah — CHANGES_REQUESTED** [review]

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java [hunk 2]
```diff
@@ -3824,6 +3864,18 @@ private void fetchAndSetExtension(List<T> entities, Fields fields) {
...
+      return;
+    }
+
+    Map<UUID, List<EntityReference>> childrenMap = batchFetchChildren(entities);
+
+    for (T entity : entities) {
+      entity.setChildren(childrenMap.get(entity.getId()));
+    }
+  }
+
```
Comment (sonika-shah) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java:3878]: image
@juntaozhang  we will also need to include fetcherField for `childrenCount`  or directly set childrenCount here along with children field, as the glossary page api (

`eg-v1/glossaryTerms?directChildrenOf=Business%20Glossary&fields=childrenCount%2Cowners%2Creviewers&limit=100000`

) uses `childrenCount` field’s value to display nested glossary terms. Currently, in your PR, all terms are being shown at the top level because childrenCount is not being fetched.


In case of your pr :
image

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java [hunk 3]
```diff
@@ -840,7 +906,7 @@ private void fetchAndSetRelatedTerms(List<GlossaryTerm> entities, Fields fields)
   }
 
   private void fetchAndSetParentOrGlossary(List<GlossaryTerm> terms, Fields fields) {
-    if (terms == null || terms.isEmpty() || (!fields.contains("parent"))) {
+    if (terms == null || terms.isEmpty()) {
```
Comment (sonika-shah) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java:909]: Any reason for emoving this condition `(!fields.contains("parent")) ` ?
we should not be always fetching parent , unless its explicity metioned in the fields , to avoid additional calls to db

Comment (juntaozhang) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java:909]: Keep same behavior with `setFields`:
```java
  @Override
  public void setFields(GlossaryTerm entity, Fields fields) {
    entity.withParent(getParent(entity)).withGlossary(getGlossary(entity));
    entity.setRelatedTerms(
        fields.contains("relatedTerms") ? getRelatedTerms(entity) : entity.getRelatedTerms());
    entity.withUsageCount(
        fields.contains("usageCount") ? getUsageCount(entity) : entity.getUsageCount());
    entity.withChildrenCount(
        fields.contains("childrenCount") ? getChildrenCount(entity) : entity.getChildrenCount());
  }
```

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java (hunk 1 above)
Comment (juntaozhang) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java]: You are right, already fixed, thank you very much for your reminder.

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java [hunk 4]
```diff
@@ -692,34 +723,47 @@ public final T findByName(String fqn, Include include, boolean fromCache) {
...
+  /**
+   * The default behavior is to execute one by one. For batch execution, override this method in the subclass.
+   *
+   * @see GlossaryTermRepository#setFieldsInBulk(Fields, List) for an example implementation
+   */
+  public void setFieldsInBulk(Fields fields, List<T> entities) {
     for (T entity : entities) {
+      setFieldsInternal(entity, fields);
```
Comment (sonika-shah) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java:766]: hey @juntaozhang , i noticed that we are changing the default behavior of `setFieldsInBulk` in EntityRepository to execute one by one, but the whole idea of the method is to perform the operation in batch. The earlier implementation of this method also  we used `fetchAndSetFields(entities, fields)`  instead of  `setFieldsInternal` to set the fields in bulk. 

can we please keep the same batch processing approach as we have in the overridden method of glossaryrepository# setFieldsInBulk ?

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java [hunk 5]
```diff
@@ -371,8 +376,6 @@ protected EntityRepository(
 
       if (supportsField) {
         this.fieldFetchers.put(fieldName, fetcher);
-        this.patchFields.addField(allowedFields, fieldName);
-        this.putFields.addField(allowedFields, fieldName);
```
Comment (sonika-shah) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java:375]:
```
this.patchFields.addField(allowedFields, fieldName);
 this.putFields.addField(allowedFields, fieldName);
```
 will be  required  to maintain a list of fields that are allowed for patch and put operations and help in validating fields that can be updated or modified.

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java (hunk 3 above)
Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java:909]: yes correct

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java (hunk 5 above)
Comment (juntaozhang) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java:375]: I saw that `patchFields`, `putFields` have being performed before in the construction. The logic here is duplicated. The fetchAndSetXXX is not strongly tied to `patchFields`, such as `children` does not require `patchFields`. 
Do you think these two operations should be handled separately (like in my PR, which only handles fetchAndSetXXX here)?

Here is the code `patchFields`, `putFields` in the construction:
```
this.supportsTags = allowedFields.contains(FIELD_TAGS);
if (supportsTags) {
  this.patchFields.addField(allowedFields, FIELD_TAGS);
  this.putFields.addField(allowedFields, FIELD_TAGS);
}
....
this.supportsCertification = allowedFields.contains(FIELD_CERTIFICATION);
if (supportsCertification) {
  this.patchFields.addField(allowedFields, FIELD_CERTIFICATION);
  this.putFields.addField(allowedFields, FIELD_CERTIFICATION);
}
```

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java [hunk 6]
```diff
@@ -3867,6 +3919,15 @@ private Map<String, List<TagLabel>> batchFetchTags(List<String> entityFQNs) {
...
 
+    List<String> tagFQNs =
+        tags.stream()
+            .distinct()
+            .map(CollectionDAO.TagUsageDAO.TagLabelWithFQNHash::getTagFQN)
+            .toList();
+    Map<String, TagLabel> tagFQNLabelMap =
+        EntityUtil.toTagLabels(TagLabelUtil.getTags(tagFQNs).toArray(new Tag[0])).stream()
+            .collect(Collectors.toMap(TagLabel::getTagFQN, Function.identity()));
+
```
Comment (sonika-shah) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java:3930]: the current method seems to work fine, just curious if there’s any specific need for this additional step and additional memory storage.

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java (hunk 4 above)
Comment (juntaozhang) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java:766]: - This is loop approach, used in the `listAll`, `listAfter`, and `listBefore` methods.
```java
  public void setFieldsInBulk(Fields fields, List<T> entities) {
    for (T entity : entities) {
      setFieldsInternal(entity, fields);
      setInheritedFields(entity, fields);
      clearFieldsInternal(entity, fields);
    }
  }
```

- This is a bulk approach, which is more efficient. Currently, I can only ensure that the fields in `GlossaryTermRepository` have implemented `fetchAndSetXXX`. Some fields in other entities have not been implemented yet, so this logic cannot be directly placed into `EntityRepository`.
```java
  public void setFieldsInBulk(Fields fields, List<GlossaryTerm> entities) {
    fetchAndSetFields(entities, fields);
    setInheritedFields(entities, fields);
    for (GlossaryTerm entity : entities) {
      clearFieldsInternal(entity, fields);
    }
  }
```

---
Before my PR, I noticed that `setFieldsInBulk` was only used in listAllForCSV, and only some fields in that scenario had implemented `fetchAndSetXXX`. 
Can't directly use in the scenarios of `listAll`,`listAfter`,`listBefore`. So for `list` the default logic remains unchanged, still using a loop to `setFields` by default. 
If other entities need to use efficient bulk approach, they should make sure all the fields they used are implemented `fetchAndSet` like `GlossaryTermRepository`.

The current logic for `listAllForCSV` still relies on `fetchAndSetFields`, just as it did before.
```java
  public final List<T> listAllForCSV(Fields fields, String parentFqn) {
    ListFilter filter = new ListFilter(Include.NON_DELETED);
    List<String> jsons = listAllByParentFqn(parentFqn, filter);
    List<T> entities = new ArrayList<>();
    for (String json : jsons) {
      T entity = JsonUtils.readValue(json, entityClass);
      entities.add(entity);
    }
    // TODO: Ensure consistent behavior with setFieldsInBulk when all repositories implement it
    fetchAndSetFields(entities, fields);
    setInheritedFields(entities, fields);
    for (T entity : entities) {
      clearFieldsInternal(entity, fields);
    }
    return entities;
  }
```

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java (hunk 6 above)
Comment (juntaozhang) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java:3930]: The unit test is failing due to missing detailed information such as the description and other relevant details for `Tag`.

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java (hunk 4 above)
Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java:766]: okay got it ! thanks for clarification

we should mention in the comment that for efficient bulk processing, all fields used must implement fetchAndSetXXX, like in GlossaryTermRepository.”
/**
   * The default behavior is to execute one by one. For batch execution, override this method in the subclass.
   *
   * @see GlossaryTermRepository#setFieldsInBulk(Fields, List) for an example implementation
   */

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java (hunk 5 above)
Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java:375]: yes right, we can remove it  from here and have separtion of  concerns , as the patchFields, putFields are already getting updated in the earlier steps

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java (hunk 4 above)
Comment (juntaozhang) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java:771]: Thank you for your patience. I've added more comments to demonstrate usage.

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java (hunk 2 above)
Comment (juntaozhang) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java:3883]: Also enhance UT about `childrenCount` in `test_getImmediateChildrenGlossaryTermsWithParentFQN`

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java (hunk 6 above)
Comment (juntaozhang) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java:3935]: FYI, failed UT of `validateTagLabel` in `assertNotNull(label.getDescription(), label.getTagFQN());`
```
127.0.0.1 - - [17/Feb/2025:03:21:33 +0000] "GET /api/v1/glossaryTerms?fields=children%2CrelatedTerms%2Creviewers%2Ctags HTTP/1.1" 200 1313 "-" "Jersey/2.40 (Jetty HttpClient 9.4.53.v20231009)" 82

org.opentest4j.AssertionFailedError: PII.Sensitive ==> expected: not <null>

	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertNotNull.failNull(AssertNotNull.java:49)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:35)
	at org.junit.jupiter.api.Assertions.assertNotNull(Assertions.java:312)
	at org.openmetadata.service.util.TestUtils.validateTagLabel(TestUtils.java:517)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.openmetadata.service.util.TestUtils.validateTags(TestUtils.java:484)
	at org.openmetadata.service.resources.glossary.GlossaryTermResourceTest.assertContains(GlossaryTermResourceTest.java:1145)
	at org.openmetadata.service.resources.glossary.GlossaryTermResourceTest.get_listGlossaryTermsWithDifferentFilters(GlossaryTermResourceTest.java:158)
````

**Review by sonika-shah — DISMISSED** [review]

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java (hunk 2 above)
Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java:3883]: thanks approved, will merge in once required checks are passing

**Comment by juntaozhang** [comment]
hi @sonika-shah , so far any blocks about this PR?

**Comment by sonika-shah** [comment]
> hi @sonika-shah , so far any blocks about this PR?

hi @juntaozhang , i saw that you were still making few updates in the pr, so was waiting on your changes ,if the changes are completed i can do final test at my end and close the pr.

**Comment by juntaozhang** [comment]
Ok got it, currently I finalize this PR.
And an another question, will this PR released in next version?
Thank you for your time.

**Comment by sonika-shah** [comment]
> Ok got it, currently I finalize this PR. And an another question, will this PR released in next version? Thank you for your time.

1.6.5 is already in the build step, if everything goes well, we can have in 1.6.6. Thanks !

**Review by sonika-shah — APPROVED** [review]

**Comment by sonika-shah** [comment]
hi @juntaozhang , since this PR changes common function that’s used across operations, we’ll be holding it for the 1.7 release (which will be created from main and will include all changes from the main branch) to be on the safe side. We don’t want to push this into a minor release. Thanks for your understanding!

**Comment by juntaozhang** [comment]
@sonika-shah Thank you for making me aware.
