### PR TITLE
Fixes #12459 Members of the group, that owns the object, can't resolv…

### LINKED ISSUE #12459: Members of the group, that owns the object, can't resolve a task
**Affected module**
backend

**Describe the bug**
Members of the group, that owns the object, can't accept tasks to change the description (click on "Accept Suggestion" button, but nothing happens)
Also, they can't close these tasks without edit. (can't see "Close" button, only "Accept Suggestion" and "Edit & Accept Suggestion")

**To Reproduce**
group_problem

1) I have created a "TEST GROUP TWO" group with no associated roles and policies. 
2) Added the user "employee_3" to it. 
3) Assigned this group as the owner of the "ERP_USER" table.
4) Another user "employee_1" created a task to change the description and associating it with a group-owner.
5) (look at record) After that, "employee_3" tries to accept the task, presses the "Accept Suggestion" button, but nothing happens. Also, he does not see a button to close task. Only "Accept Suggestion" and "Edit & Accept Suggestion"

**Expected behavior**
Any user of the group that owns the object, if there is an Organization Policy by default and there are no other restrictive policies, should have the right to accept or reject proposals to change the description of the object. (accept or close task)

**Version:**
OpenMetadata version: 1.1.0

### PR DESCRIPTION
**Pull request by sureshms**
…e a task

### Describe your changes:

Fixes #12459

I worked on ... because ...

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java [hunk 1]
```diff
@@ -654,7 +654,7 @@ public void checkPermissionsForResolveTask(Thread thread, boolean closeTask, Sec
     List<EntityReference> teams = user.getTeams();
     List<String> teamNames = teams.stream().map(EntityReference::getName).collect(Collectors.toList());
     if (assignees.stream().anyMatch(assignee -> teamNames.contains(assignee.getName()))
-        && teamNames.contains(owner.getName())) {
+        || teamNames.contains(owner.getName())) {
       return;
```
Comment (sureshms) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java:658]: @harshach this is the bug ^

**Review by harshach — APPROVED** [review]
