### PR TITLE
UI : Added auto-generated password on page load

### LINKED ISSUE #8736: No auto-generated password when the "Automatic Generate" option is selected by default
**Affected module**

UI

**Describe the bug**

The `/create-user` page does not auto-generate a password when the "Automatic Generate" option is selected by default. Also, it may need to be renamed to "Automatically Generate". In order to see an auto-generated password, I need to click the refresh arrows icon at least once.

**To Reproduce**

Screenshot 2022-11-14 at 4 17 54 PM

Screenshot 2022-11-14 at 4 14 56 PM

**Expected behavior**

When the "Automatically Generate" option is selected, or when it is active by default, such as when the create user form first loads, show an auto-generated password in the text box instead of an empty text box.

**Version:**
 - OS: OS X
 - Python version:
 - OpenMetadata version: 0.12.2
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes :

- Issue : Closes #8736
- Added auto-generated password on page load in password field

#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :

https://user-images.githubusercontent.com/66266464/208228499-403fbb29-d64b-4d93-a6ae-431ba7f38381.mov

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers:
@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/CreateUser/CreateUser.component.tsx [hunk 1]
```diff
@@ -515,79 +521,79 @@ const CreateUser = ({
...
             <Form.Item
-              label="Email"
+              label={t('label.email')}
               name="oktaEmail"
               rules={[
                 {
                   required: true,
                   type: 'email',
-                  message: 'Service account Email is required',
+                  message: t('message.service-email-required'),
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/CreateUser/CreateUser.component.tsx:581]: Let's replace it with the below localisation keys
Below are already present in JSON file
```
"field-required": "{{field}} is required",
"field-required-plural": "{{field}} are required",

```

File: openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json [hunk 2]
```diff
@@ -552,7 +557,15 @@
...
-    "latest": "Latest"
+    "latest": "Latest",
+    "create": "Create",
+    "admin": "Admin",
+    "generate": "Generate",
+    "password-type": "{{type}} Password",
+    "automatically-generate": "Automatically Generate",
+    "create-entity": "Create {{entity}}",
+    "domain": "Domain",
+    "privateKey": "PrivateKey"
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json:568]:
```suggestion
    "private-key": "PrivateKey"
```

**Review by chirag-madlani — CHANGES_REQUESTED** [review]

**Comment by Ashish8689** [comment]
@chirag-madlani Changes made as per comments!

**Review by chirag-madlani — APPROVED** [review]

**Review by ShaileshParmar11 — APPROVED** [review]
