### PR TITLE
Fixed issue-5897: UI: Tags usage link is broken

### LINKED ISSUE #5897: UI: Tags usage link is broken
**Affected module**
UI

**Describe the bug**
Clicking on the usage link in Tags page takes user to a blank page

**To Reproduce**
image (6)

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes :

I worked on the fixing Tags usage link
Closes #5897 
#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :

https://user-images.githubusercontent.com/71748675/178054563-3d8f422b-c955-4740-b237-3adf907eaef8.mov

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/utils/RouterUtils.ts [hunk 1]
```diff
@@ -130,7 +130,7 @@ export const getExplorePathWithInitFilters = (
     .replace(PLACEHOLDER_ROUTE_TAB, tab);
 
   return filter
-    ? `${path}?${initialFilterQS}=${encodeURIComponent(filter)}`
+    ? `${path}?${searchFilterQS}=${encodeURIComponent(filter)}`
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/utils/RouterUtils.ts:133]: @ShaileshParmar11 , Any reason why we are changing this to serach filters?

Also can you check if we change the tab does tag filter getting applied or not?

**Review by Sachin-chaurasiya — COMMENTED** [review]
Comment:

File: openmetadata-ui/src/main/resources/ui/src/utils/RouterUtils.ts (hunk 1 above)
Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/utils/RouterUtils.ts:133]: I have updated the code and brought back the `initialFilterQS `, and for the tab switch filters are getting reset! to keep it applied we need to deep dive into the code to apply the functionality we will do it in the next iteration!

**Review by Sachin-chaurasiya — APPROVED** [review]
