### PR TITLE
Fix-22668 Glossary term missing from UI in columns search

### LINKED ISSUE #22668: Glossary term missing from UI in columns searching
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**

After adding glossary terms to a column, after a term is linked, it's not visible when search this column. We have observed that the issue occurs specifically when searching for a particular column. If we scroll down manually instead of using the search function, the glossary term linkage is visible.

**To Reproduce**

Screenshots or steps to reproduce

* Go column glossary terms
* Add a term a update
* Refresh the page and search the column, will see the glossary term is not visible.

**Expected behavior**

**Version:**
 - OpenMetadata version: v1.8.3

**Additional context**

### PR DESCRIPTION
**Pull request by sonika-shah**
### Describe your changes:

Fixes  #22668 

image

I worked on ... because ...

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java [hunk 1]
```diff
@@ -2028,6 +2028,10 @@ private ResultList<Column> searchTableColumnsInternal(
       }
     }
 
+    if (fields.contains("tags") || fields.contains("*")) {
```
Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java:2031]: why are only doing this for "tags" shouldn't this apply to other fields as well. 
Also check if it applies to DashboardDataModel as well

Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java:2031]: For dashboardDataModel it was already present , it was missing only for tables
we’re using  the /column/search api for fetching tags and customMetrics of columns — no other fields

**Review by harshach — APPROVED** [review]
