### PR TITLE
Fixes 23104: Showing validation error if user enter duplicate service name

### LINKED ISSUE #23104: Misleading error while creating a service connection with a name (say "abc") that already exists
**Describe the bug**

- Let's suppose there is an existing service (of any type) with service name as "test service". 

- Now if I create a new service connection (of any type) with same name i.e. "test service", I see an error in test-connection saying - "Cannot convert [LinkedHashMap]...", which is misleading. 

- As a user it's not possible for me to figure out that the issues is duplicate service name (in OMD or Collate)

**Expected behavior**
Ideally there should have been a validation error saying - "duplicate service name" or similar before even letting the user add config for the new service they are trying to setup. 

**Version:**
 - OpenMetadata version: 1.9.2

**Additional context**

Image

### PR DESCRIPTION
**Pull request by Rohit0301**
### Describe your changes:

Fixes #23104 

**Changes Made**
Added a validation check during service creation to prevent duplicate service names.
Displayed a clear and descriptive error message for duplicates.

https://github.com/user-attachments/assets/ed210e2c-0d17-4491-83b6-0d18d05fae06

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtils.tsx [hunk 1]
```diff
@@ -582,3 +584,63 @@ export const getAddServiceEntityBreadcrumb = (
...
+export const searchServiceWithName = async (
+  name: string,
+  serviceName: string
+) => {
+  try {
+    const {
+      hits: { hits },
+    } = await searchService({
+      search: name,
+      limit: 10000,
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtils.tsx]: We should not be putting such large limits without any specific reason. Also can we use constants for such inputs?

File: openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtils.tsx [hunk 2]
```diff
@@ -582,3 +584,63 @@ export const getAddServiceEntityBreadcrumb = (
...
+      searchIndex: getSearchIndexFromService(serviceName),
+    });
+
+    const services = hits.map(
+      ({ _source }) => _source as DatabaseServiceSearchSource
+    );
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtils.tsx:619]: We are also iterating over all the hits, so if there are 10000 results as per the above limit, it this scalable?

File: openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtils.tsx (hunk 1 above)
Comment (aniketkatkar97) [reply openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtils.tsx]: If we are searching for a specific name, should the limit be this big?

Comment (Rohit0301) [reply openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtils.tsx]: Removed the limit

File: openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtils.tsx (hunk 2 above)
Comment (Rohit0301) [reply openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtils.tsx:619]: Updated the search to perform an exact match. Since it’s an exact match, there will be at most one result returned

File: openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtils.tsx [hunk 3]
```diff
@@ -582,3 +584,66 @@ export const getAddServiceEntityBreadcrumb = (
...
+  const searchedServices = await searchServiceByExactName(name, serviceName);
+
+  const isServiceNamePresent = searchedServices.some(
+    (service) => service.name === name
+  );
+
+  if (isServiceNamePresent) {
+    return t('message.entity-already-exists', {
+      entity: t('label.name'),
+    });
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtils.tsx:644]: Instead of `Name already exists`, it should be `Service already exists`

**Review by aniketkatkar97 — APPROVED** [review]
