### PR TITLE
Fix Asset count mismatch for Teams across different views

### LINKED ISSUE #26099: Asset count mismatch for Teams across different views
**Affected module**
Does it impact the UI, backend or Ingestion Framework? - UI

**Describe the bug**
- We have observed a discrepancy in the asset count associated with Teams when comparing two different views in the UI. The asset numbers shown are not consistent across these views, which can lead to confusion and incorrect reporting.

**To Reproduce**

Screenshots or steps to reproduce

Image

Image

**Expected behavior**
- The asset count for a given team should be consistent and match across all views.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by sonika-shah**
<!--
Thank you for your contribution!
Unless your change is trivial, please create an issue to discuss the change before creating a PR.
-->

### Describe your changes:

Fixes #26099

Before :

https://github.com/user-attachments/assets/68bd5a7a-0fdb-4511-814e-96f11e67e53f

After :

https://github.com/user-attachments/assets/8daceb65-cebf-49d1-88ff-bab586eb366e


Summary: Fix Team Asset Count Discrepancy                                                                                                                                     
                                                                                                                                                                                
  Issue                                                                                                                                                                         
                                                                                                                                                                                
  Two different views showed different asset counts for the same team:                                                                                                          
                                                                                                                                                                                
  - Team Listing Page: Used owns.length from /api/v1/teams?fields=owns → showed 2                                                                                               
  - Team Detail Page: Used ES search /api/v1/search/query?owners.id=teamId → showed 27                                                                                          
                                                                                                                                                                                
  Why the difference?                                                                                                                                                           
  - owns field comes from the database entity_relationship table → only direct ownership                                                                                        
  - ES search index includes inherited ownership (e.g., tables inherit owner from their parent schema)                                                                          
                                                                                                                                                                                
  Solution                                                                                                                                                                      
                                                                                                                                                                                
  Instead of using owns.length, the frontend now calls a separate API /api/v1/teams/assets/counts which returns asset counts for all teams using ES aggregation.                
                                                                                                                                                                                
  How it works:                                                                                                                                                                 
                                                                                                                                                                                
<img width="594" height="381" alt="image" src="https://github.com/user-attachments/assets/c442851a-6eb0-4be2-9387-979178095166" />                                                                                                                             
                                                                               
                                                                                                                                                                                
  <img width="662" height="155" alt="image" src="https://github.com/user-attachments/assets/f2cb82bd-5b78-4804-bd13-ce660fbfca87" />                                                       
                                                                                                                                                                                
  NOW BOTH VIEWS SHOW: 27 ✅                                                                                                                                                    
                                                                                                                                                                                
  Backend Changes             
  
   <img width="894" height="188" alt="image" src="https://github.com/user-attachments/assets/638e8812-ce85-426d-b9dd-60ea8edf365e" />                                                                                                                                                       
                                                                                                                                                                                
```
  Optimized /api/v1/teams/assets/counts endpoint:                                                                                                                               
 
                                      
  // Before: N+1 queries                                                                                                                                                        
  for (Team team : allTeams) {                                                                                                                                                  
      count = inheritedFieldEntitySearch.getCountForField(query); // 1 ES query per team                                                                                        
  }                                                                                                                                                                             
                                                                                                                                                                                
  // After: Single aggregation                                                                                                                                                  
  Map<String, Integer> ownerIdCounts = inheritedFieldEntitySearch                                                                                                               
      .getAggregatedCountsByField("owners.id", queryFilter, 10000); // 1 ES query for all             
```                                                                          
                                                                                                                                                                                
  Frontend Changes                                                                                                                                                              
                                                                                                                                                                                
  TeamsPage now fetches asset counts separately and passes to TeamHierarchy:                                                                                                    
                                                                                                                                                                                
  ```
// Fetch asset counts via aggregation API                                                                                                                                     
  const counts = await getTeamsAssetCounts(); // calls /teams/assets/counts                                                                                                     
                                                                                                                                                                                
  // Pass to TeamHierarchy component                                                                                                                                            
  <TeamHierarchy teamAssetCounts={counts} ... />                                                                                                                                
                                                                                                                                                                                
  // TeamHierarchy displays aggregated count instead of owns.length                                                                                                             
  render: (fqn: string) => teamAssetCounts[fqn] ?? 0  // Instead of: owns?.length ?? 0                
```                                                                          
                                                                                                                                                                                


<!--
Short blurb explaining:
- What changes did you make?
- Why did you make them?
- How did you test your changes?
-->

I worked on ... because ...

<!-- For frontend related change, please add screenshots and/or videos of your changes preview! -->

#
### Type of change:
<!-- You should choose 1 option and delete options that aren't relevant -->
- [x] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:
<!-- add an x in [] if done, don't mark items that you didn't do !-->
- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

<!-- Based on the type(s) of your change, uncomment the required checklist 👇 -->

<!-- Bug fix
- [ ] I have added a test that covers the exact scenario we are fixing. For complex issues, comment the issue number in the test for future reference.
-->

<!-- Improvement
- [ ] I have added tests around the new logic.
- [ ] For connector/ingestion changes: I updated the documentation.
-->

<!-- New feature
- [ ] The issue properly describes why the new feature is needed, what's the goal, and how we are building it. Any discussion
    or decision-making process is reflected in the issue.
- [ ] I have updated the documentation.
- [ ] I have added tests around the new logic.
-->

<!-- Breaking change
- [ ] I have added the tag `Backward-Incompatible-Change`.
-->

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java [hunk 1]
```diff
@@ -456,22 +457,28 @@ public Map<String, Integer> getAllTeamsWithAssetsCount() {
...
 
+    // Build team ID -> FQN mapping
+    Map<String, String> teamIdToFqn = new HashMap<>();
+    for (Team team : allTeams) {
+      teamIdToFqn.put(team.getId().toString(), team.getFullyQualifiedName());
+    }
+
+    // Single ES aggregation query for all owner IDs
+    String queryFilter = QueryFilterBuilder.buildTeamAssetsCountFilter();
+    Map<String, Integer> ownerIdCounts =
```
Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java:503]: why are you doing 10,000? whats the goal?

Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java:503]: @harshach the 10000 is the ES terms aggregation bucket size - to return counts for up to 10,000 unique owner team IDs                                                  
                                                                                                                                                                                
in case if we have more than 100 teams, some would be missing from the results

Comment (harshach) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java:503]: you need total document count not get all the dcouments right? why you need to pass any number here?

Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java:503]: we are not using the total document count; the idea is to  use  aggregation on owners.id field to get asset counts per team

This number is for the aggregation bucket size, by default agg size is 100, we have increased it to MAX_AGGREGATE_SIZE

Comment (harshach) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java:503]: are you displaying per user owned items? how does this will scale, what happens to the performance of this request if there are 1M data assets? or higher

Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java:503]: One improvemnet i just realised is , we can filter out only teams in the ES query itself , which will siginficantly reduce the bucket count, and ensure we only get teams in aggregation

On it

Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java:503]: > are you displaying per user owned items? how does this will scale, what happens to the performance of this request if there are 1M data assets? or higher

@harshach  we are just fetching info from aggregation, we are not listing the assets from=0, size=0

Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java:503]: The listing of assets is alreday managed with a paginated api on   /search/query api
q
index: all
from: 0
size: 15

Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java:503]: The above requirement is to fetch the correct asset count on teams listing page

Image

**Review by siddhant1 — DISMISSED** [review]

**Review by harshach — DISMISSED** [review]

**Comment by sonika-shah** [comment]
cherry-picked in 1.12.2

**Comment by sonika-shah** [comment]
Changes have been cherry-picked to the 1.12.2 branch.
