### PR TITLE
Fixes #17718 : Notification Debuggability

### LINKED ISSUE #17718: Notification Debuggability
Currently, we have difficulty tracking the state of a changeEvent in case of failure.
We need the following information to be built so it RCA for failed message become easy.
- [x] Tracking the current state of publisher , the available event in the queue(change_event table) and the current offset run for the publisher.
- [x]  Each publisher can have n destination and it is crucial to differentiate the event failed for which destination , we have consumer_dlq that can be utilized , but as of today that is working at the consumer level and not at the destination level.
- [x] Adding Test Message for all Slack, MsTeams , Email , to allow users to test working functionality while create the alerts.
- [x] Provide api for errored event , with the failureContext and also for which destination that particular event failed

### PR DESCRIPTION
**Pull request by Siddhanttimeline**
### Describe your changes:

Fixes #17718

Created below APIs:

  1. Diagnostic info by eventSubscription ID/Name.
  2. Failed events by eventSubscription ID/Name
  3. List all failed events
  4. List destinations by eventSubscription ID/Name.
  5. List Successfully sent changeEvents by eventSubscription ID/Name.
  6. listEvents API, filtered by 'failed,' 'successful,' and 'unprocessed' events.
  
Failed events can further be filtered by source (errors directed toward the publisher or subscriber).

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [x] I have commented on my code, particularly in hard-to-understand areas. 
- [x] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/AbstractEventConsumer.java [hunk 1]
```diff
@@ -87,6 +91,8 @@ public void handleFailedEvent(EventPublisherException ex) {
         failingSubscriptionId,
         changeEvent);
 
+    String source = errorOnSub ? SUBSCRIBER : PUBLISHER;
```
Comment (mohityadav766) [inline openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/AbstractEventConsumer.java:94]: Let's create these as enums

File: openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/EventSubscriptionScheduler.java [hunk 2]
```diff
@@ -156,62 +164,196 @@ public void deleteEventSubscriptionPublisher(EventSubscription deletedEntity)
...
+    if (eventSubscription != null && Boolean.FALSE.equals(eventSubscription.getEnabled())) {
+      return Collections.emptyList();
+    }
+
+    return eventSubscription.getDestinations();
+  }
+
+  public EventSubscriptionDiagnosticInfo getEventSubscriptionDiagnosticInfo(
+      UUID subscriptionId, int limit) {
+    boolean isAllEventsPublished = checkIfPublisherPublishedAllEvents(subscriptionId);
```
Comment (mohityadav766) [inline openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/EventSubscriptionScheduler.java:222]: Any reason why we are checking this here?

**Review by mohityadav766 — APPROVED** [review]

**Review by mohityadav766 — COMMENTED** [review]
Please check comments

File: openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/EventSubscriptionScheduler.java (hunk 2 above)
Comment (Siddhanttimeline) [reply openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/EventSubscriptionScheduler.java:222]: `isAllEventsPublished` will be part of the `EventSubscriptionDiagnosticInfo`, where we have complete data regarding **pending events and their offsets**. In that data, I thought it would be useful to show a boolean indicating whether all events have been processed. 
EventSubscriptionDiagnosticInfo will have :
1. latest offset
2. current offset
3. isAllEventsPublished
4. unpublishedEventCount
5. unprocessedEvents list

`isAllEventsPublished` can be used by UI if needed.

File: openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/AbstractEventConsumer.java (hunk 1 above)
Comment (Siddhanttimeline) [reply openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/AbstractEventConsumer.java:94]: Noted.

Comment (Siddhanttimeline) [reply openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/AbstractEventConsumer.java]: Addressed.

**Review by sonika-shah — APPROVED** [review]
