### PR TITLE
Fix glossary term relationship issue on updating parent/glossary

### LINKED ISSUE #24843: Exception when viewing child glossary terms after moving them to a new glossary
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**

An exception is thrown when attempting to access child glossary terms that were recently moved from an old glossary to a new glossary.

After the move operation:

`An exception with message [Entity type glossaryTerm 63ee1656-72de-48ee-b494-2eab474d1230 does not have expected relationship has to/from entity type glossary]`

Accessing the child glossary terms results in the above error.

The old glossary has already been deleted and no longer exists.

Image

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8] 1.11.2
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by sonika-shah**
### Describe your changes:

Fixes  #24843  When a parent term moved to a different glossary, only the parent's relationships were updated
 but the Children's glossary relationships (entity_relationship table) were not updated
 
 Added test for the scenarios : 
 
   1. test_moveTermWithChildren_toParentInSameGlossary (1.347s) - Verifies moving a term with children to a different parent within the same glossary
  2. test_moveTermWithChildren_toRootInDifferentGlossary (1.258s) - Verifies moving a term with children to the root of a different glossary, then deletes the original
  glossary
  3. test_moveTermWithChildren_toParentInDifferentGlossary (1.513s) - Verifies moving a term with children under a parent in a different glossary, then deletes original
  glossary and parent
  4. test_moveNestedTermWithChildren_toRootInSameGlossary (1.551s) - Verifies moving a nested term with children to root in the same glossary
  5. test_moveNestedTermWithChildren_toRootInDifferentGlossary (1.887s) - Verifies moving a nested term with children to root in a different glossary, then deletes original
   glossary and parent
  6. test_moveNestedTermWithChildren_toParentInDifferentGlossary - Verifies moving a nested term with children to a different parent in a different glossary
  7. test_moveMiddleTermInHierarchy_toRootInSameGlossary (0.771s) - Verifies moving a middle-level term (with both parent and children) to root in the same glossary
  8. test_moveMiddleTermInHierarchy_toRootInDifferentGlossary (2.028s) - Verifies moving a middle-level term to root in a different glossary, then deletes original parent
  and glossary
  9. test_consecutiveMoves_verifyRelationshipIntegrity (4.128s) - Most critical test - Reproduces the exact customer scenario with consecutive moves, then deletes both
  original and intermediate glossaries

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java [hunk 1]
```diff
@@ -1495,6 +1497,37 @@ private void deleteParentRelationship(GlossaryTerm term) {
       }
     }
 
+    private void updateChildrenGlossaryRelationships(GlossaryTerm original, GlossaryTerm updated) {
+      // When a parent term moves to a different glossary, all nested children must have their
```
Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java]: can we remove these comments @sonika-shah
