### PR TITLE
Fix #2996: ChangeEventHandler throws NPE at times

### LINKED ISSUE #2996: ChangeEventHandler throws NPE at times
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

**Describe the bug**
```
27.0.0.1 - - [26/Feb/2022:01:35:38 +0000] "POST /api/v1/services/dashboardServices HTTP/1.1" 201 363 "-" "Jersey/2.33 (HttpUrlConnection 11.0.12)" 4
ERROR [2022-02-26 01:35:38,406] org.openmetadata.catalog.events.ChangeEventHandler: Failed to capture change event for method POST due to 
! java.lang.NullPointerException: null
! at org.openmetadata.catalog.events.ChangeEventHandler.getThreads(ChangeEventHandler.java:186)
! at org.openmetadata.catalog.events.ChangeEventHandler.process(ChangeEventHandler.java:73)
! at org.openmetadata.catalog.events.EventFilter.lambda$filter$0(EventFilter.java:70)
! at org.openmetadata.catalog.util.ParallelStreamUtil.lambda$runAsync$0(ParallelStreamUtil.java:74)
! at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
! at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
! at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
! at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
! at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
! at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
! at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### PR DESCRIPTION
**Pull request by vivekratnavel**
### Describe your changes :
See #2996 

#
### Type of change :

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

### CODE REVIEW

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/events/ChangeEventHandler.java [hunk 1]
```diff
@@ -182,7 +183,7 @@ private static ChangeEvent copyChangeEvent(ChangeEvent changeEvent) {
     }
 
     var entityInterface = Entity.getEntityInterface(entity);
-    if (entityInterface.getChangeDescription() == null) {
+    if (entityInterface == null || entityInterface.getChangeDescription() == null) {
```
Comment (sureshms) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/events/ChangeEventHandler.java:186]: Entityinterface should not be null, right? That is a bug that we should not ignore.

Comment (vivekratnavel) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/events/ChangeEventHandler.java]: You are right. Fixed it in the latest patch.

**Review by harshach — APPROVED** [review]

**Review by sureshms — APPROVED** [review]
