### PR TITLE
Alert Fixes

### LINKED ISSUE #19685: Alert Issues
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**
- Error or exception in polling and publish does the offset to move ahead 
- we are making unnecessary calls to the database for getting initial and starting offset
- diagnostic information needs to be added on the UI
- allow the fixes or syncing from alerts page in case the publisher falls short

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by mohityadav766**
### Describe your changes:
Fixes  #19685

- Handle poll in try/catch , and error 

I worked on ... because ...

#
### Type of change:

- [x] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/AbstractEventConsumer.java [hunk 1]
```diff
@@ -256,18 +256,34 @@ public List<ChangeEvent> pollEvents(long offset, long batchSize) {
...
+      batchSize = batch.size();
+      eventsWithReceivers.putAll(createEventsWithReceivers(batch));
       // Publish Events
       if (!eventsWithReceivers.isEmpty()) {
         alertMetrics.withTotalEvents(alertMetrics.getTotalEvents() + eventsWithReceivers.size());
         publishEvents(eventsWithReceivers);
       }
     } catch (Exception e) {
-      LOG.error("Error in executing the Job : {} ", e.getMessage());
+      long currentLatest = Entity.getCollectionDAO().changeEventDAO().getLatestOffset();
```
Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/AbstractEventConsumer.java:272]: do we need to make a call to db here?

Comment (harshach) [reply openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/AbstractEventConsumer.java:272]: isnt' offset is the current offset and all we need to increment the batch?

Comment (mohityadav766) [reply openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/AbstractEventConsumer.java:272]: Ex: - Change event has 50 entries table
current offset is let's say 20 , batch size 10
reading from 20 to  with batch size 10 if the fails , then i update the offset to 20 + 10 because 50 (total or latest offset) - current > batch size so we next batch of events
but let's say current is 45 and batch is 10 
reading from 45 there is a failure in this case 50-45 < batch size so the current offset needs to be updated to offset + remanining items(5)

Comment (mohityadav766) [reply openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/AbstractEventConsumer.java:272]: and at any failure we need the latest offset of change_event

Comment (harshach) [reply openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/AbstractEventConsumer.java:272]: we do have offset of the message no? 
if we record what is the offset its failing then we should be able to move currentOffset = failedOffset+1.
Trrying to see if we can avoid polling db

Comment (mohityadav766) [reply openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/AbstractEventConsumer.java:272]: it's in batch , we are reading in batches which are passed , so it is difficult to add per message at that layer

Comment (harshach) [reply openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/AbstractEventConsumer.java:272]: can we throw a custom exception to catch, exception should contain the offset it failed on?

Comment (mohityadav766) [reply openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/AbstractEventConsumer.java]: done , removed the db call as well
