### PR TITLE
Fixes #25067: Delete the secrets only on hard delete

### LINKED ISSUE #25067: [Bug] Secrets are deleted during Service Soft Delete, causing connection failures upon restoration
Soft deletion removes the secrets from the storage where they are stored, on restoring, the test connection or any agent ingestion doesn't work as expected

Potential Root cause:

@Override
  protected void postDelete(T service, boolean hardDelete) {
    super.postDelete(service, hardDelete);
    if (service.getConnection() != null) {
      SecretsManagerFactory.getSecretsManager()
          .deleteSecretsFromServiceConnectionConfig(
              service.getConnection().getConfig(),
              service.getServiceType().value(),
              service.getName(),
              serviceType);
    }
  }

### PR DESCRIPTION
**Pull request by ayush-shah**
This pull request updates the behavior for deleting secrets associated with a service connection. Now, secrets are only removed from the secret manager when a service is hard deleted, making soft deletes reversible and preventing accidental loss of secrets.

Secret deletion logic update:

* Modified the `postDelete` method in `ServiceEntityRepository.java` so that secrets are deleted from the secret manager only when a hard delete occurs, not on soft delete.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ServiceEntityRepository.java [hunk 1]
```diff
@@ -105,11 +105,12 @@ public T addTestConnectionResult(UUID serviceId, TestConnectionResult testConnec
...
   }
 
-  /** Remove the secrets from the secret manager */
+  /** Remove the secrets from the secret manager only on hard delete */
   @Override
   protected void postDelete(T service, boolean hardDelete) {
     super.postDelete(service, hardDelete);
-    if (service.getConnection() != null) {
+    // Only delete secrets on hard delete to allow soft delete to be reversible
+    if (hardDelete && service.getConnection() != null) {
```
Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ServiceEntityRepository.java:113]: lets add some tests for this
