### PR TITLE
Fixed: Struct type columns not expanding in UI #8907

### LINKED ISSUE #8907: Struct type columns not expanding in UI
**Affected module**
UI

**Describe the bug**
Struct type columns not expanding in UI

image

**To Reproduce**
Ingest any table with struct type col

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes :

Fixed: Struct type columns not expanding in UI
Closes #8907

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :

https://user-images.githubusercontent.com/71748675/203007677-36b8fb5e-5aa9-4249-bf43-a6fd5fa33dba.mov

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx [hunk 1]
```diff
@@ -681,19 +681,21 @@ const EntityTable = ({
         dataSource={data}
         expandable={{
           defaultExpandedRowKeys: [],
-          expandIcon: ({ expanded, onExpand, record }) =>
-            record.children ? (
-              <FontAwesomeIcon
-                className="tw-mr-2 tw-cursor-pointer"
-                icon={expanded ? faCaretDown : faCaretRight}
+          rowExpandable: () => true,
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx:684]: We should add condition here instead

File: openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx [hunk 2]
```diff
@@ -681,19 +681,21 @@ const EntityTable = ({
...
+          expandIcon: ({ expanded, onExpand, record }) => {
+            return record.children ? (
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx:686]: Expand icon should just return icon based on expand state and not decided which row should be expanded

**Review by chirag-madlani — CHANGES_REQUESTED** [review]

**Review by chirag-madlani — APPROVED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx [hunk 3]
```diff
@@ -680,20 +680,22 @@ const EntityTable = ({
...
         expandable={{
-          defaultExpandedRowKeys: [],
-          expandIcon: ({ expanded, onExpand, record }) =>
-            record.children ? (
-              <FontAwesomeIcon
-                className="tw-mr-2 tw-cursor-pointer"
-                icon={expanded ? faCaretDown : faCaretRight}
+          rowExpandable: (record) => {
+            return (record.children && record.children.length > 0) || false;
+          },
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx:685]: I would recommend this way to check if the row is expandable or not.

```suggestion
          rowExpandable: (record) => record.children && record.children.length > 0,
```

Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx:685]: Thanks, @Sachin-chaurasiya but we need to pass a boolean value, so if children are undefined it will send undefined and its not accepted in function so we need to give fallback value
image

Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx:685]: Okay, then can we do this?
```suggestion
          rowExpandable: (record) => Boolean(record.children && record.children.length > 0),
```
