### PR TITLE
Fix #6976 UI | cmd + click does not work as expected on the Explore page 

### LINKED ISSUE #6976: UI | cmd + click does not work as expected on the Explore page
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
`cmd + click` does not work as expected on the Explore page, where as it works fine on other pages on OM

**To Reproduce**
* Open Explore page
* Try `cmd + click` on any entity and see the current tab open the entity page as well a new tab instead of opening the entity just on a new tab

Screenshots or steps to reproduce

**Expected behavior**
Only opening the entity home page just on a new tab upon `cmd + click`

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]: `0.11.5`
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
Fixes #6976
### Describe your changes :

I worked on #6976

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :

https://user-images.githubusercontent.com/59080942/187014187-36d04cda-6bbd-49c1-bc4a-5d6892bd21ce.mov

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/common/table-data-card/TableDataCard.tsx [hunk 1]
```diff
@@ -160,12 +157,13 @@ const TableDataCard: FunctionComponent<Props> = ({
             src={serviceTypeLogo(serviceType || '')}
           />
           <h6 className="tw-flex tw-items-center tw-m-0 tw-text-base tw-pl-2">
-            <Link to={getEntityLink(indexType, fullyQualifiedName)}>
+            <Link
+              to={getEntityLink(indexType, fullyQualifiedName)}
+              onClick={handleLinkClick}>
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/common/table-data-card/TableDataCard.tsx:162]: Why we still need onClick handler?

Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/components/common/table-data-card/TableDataCard.tsx:162]: To handle this part.
```js
const handleLinkClick = () => {
    if (location.pathname.includes(ROUTES.TOUR)) {
      AppState.currentTourPage = CurrentTourPageType.DATASET_PAGE;
    }
  };
```

**Review by chirag-madlani — APPROVED** [review]
