### PR TITLE
#14136: duplicate column issue in pipeline execution and date picker clear action

### LINKED ISSUE #14136: Task filter in pipeline execution component create duplicate columns
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**

- Task filter in pipeline execution component creates duplicate columns
- Data Filter is not working on clearing filtered date
- icon misaligned issue

**To Reproduce**

Screenshots or steps to reproduce

https://github.com/open-metadata/OpenMetadata/assets/66266464/b5bcd149-5ccc-4b2b-9dc5-75465b540375

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes:

Fixes #14136

- fix duplicate column issue in pipeline execution 
- fix date picker clear action
- fix icon alignment issue

https://github.com/open-metadata/OpenMetadata/assets/66266464/599458b1-1498-4e0c-9036-e2f0a05cd696

#
### Type of change:

- [x] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/Execution/Execution.component.tsx [hunk 1]
```diff
@@ -12,12 +12,12 @@
  */
 
 import { CloseCircleOutlined } from '@ant-design/icons';
+import Icon from '@ant-design/icons/lib/components/Icon';
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Execution/Execution.component.tsx:15]:
```suggestion
import Icon from '@ant-design/icons';
```

File: openmetadata-ui/src/main/resources/ui/src/components/Execution/Execution.component.tsx [hunk 2]
```diff
@@ -84,22 +84,17 @@ const ExecutionsTab = ({ pipelineFQN, tasks }: ExecutionProps) => {
     }
   };
 
-  const handleMenuClick: MenuProps['onClick'] = (event) => {
-    if (event?.key) {
-      setStatus(MenuOptions[event.key as keyof typeof MenuOptions]);
-    }
-  };
+  const handleMenuClick: MenuProps['onClick'] = (event) =>
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Execution/Execution.component.tsx:87]: wrap it with useCallback so that `statusMenuItems` won't re-assign each time

**Comment by Ashish8689** [comment]
@chirag-madlani  changes made as per comments!

**Review by chirag-madlani — APPROVED** [review]

**Review by chirag-madlani — APPROVED** [review]
