### PR TITLE
Fix UI :- Added Ellipses in tags

### LINKED ISSUE #7925: Tags overflow from UI
**Affected module**
UI

**Describe the bug**
Long text tags are overflowing from UI

**To Reproduce**

image

**Expected behavior**
Long text Tags should contain ' ... '

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes :

- Issues :- Closes  #7925
- fix the long text issue in tags which break UI.

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

**Review by chirag-madlani — APPROVED** [review]

**Review by ShaileshParmar11 — APPROVED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/tags/tags.tsx [hunk 1]
```diff
@@ -45,6 +45,10 @@ const Tags: FunctionComponent<TagProps> = ({
     return tag.startsWith('#') ? tag.slice(1) : tag;
   };
 
+  const getDisplayTag = (tag: string) => {
+    return tag.length > 35 ? `${tag.slice(0, 35)}...` : tag;
+  };
+
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/tags/tags.tsx:51]: Can we move this function to util and name it `getTagDisplay`?
Also, can we use `viewCap` from constant?
```js
const TAG_VIEW_CAP = 35;
```

**Review by Sachin-chaurasiya — APPROVED** [review]
