### PR TITLE
Fix owner propagation for Domain children (subdomains & data products) in search

### LINKED ISSUE #23455: Search indexes not updated when sub-domain shared
**Affected module**
UI, backend, and search Indexes

**Describe the bug**
DataProducts does not inherit the 'owners' when the subdomain is shared.
There is a discrepancy between the owners of the sub-domain and 'dataProduct', as the search indexes are not updated.

**To Reproduce**

Image

Image

**Expected behavior**
Owners of the data product should sync with 'sub-domain' and the indexes should be updated appropriately

**Version:**
 - OpenMetadata version: 1.9.5
 

**Additional context**
Support thread which contains more details on this bug -> https://openmetadata.slack.com/archives/C02B6955S4S/p1756988089122479

### PR DESCRIPTION
**Pull request by sonika-shah**
### Describe your changes:

Fixes #23455

I worked on ... because ...

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java [hunk 1]
```diff
@@ -732,38 +732,66 @@ public void propagateInheritedFieldsToChildren(
...
+  }
+
+  private String resolveParentFieldName(
+      String entityType, Pair<String, Map<String, Object>> updates) {
+    // For service entities, use SERVICE_ID when propagating domains or displayName
+    if (!updates.getValue().isEmpty()
+        && (updates.getValue().keySet().stream()
+                .anyMatch(key -> key.toLowerCase().contains(FIELD_DOMAINS))
+            || updates.getValue().containsKey(FIELD_DISPLAY_NAME))) {
+      if (entityType.equalsIgnoreCase(Entity.DATABASE_SERVICE)
```
Comment (Bhanuagr) [inline openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java]: As list is increasing in condition, can we do it like below ?

```suggestion
      public static final Set<String> SERVICE_ENTITY_SET = Set.of(Entity.DATABASE_SERVICE, Entity.MESSAGING_SERVICE, Entity.DASHBOARD_SERVICE,
      Entity.PIPELINE_SERVICE, Entity.METADATA_SERVICE, Entity.STORAGE_SERVICE, ...);
      
      if (SERVICE_ENTITY_SET.stream().anyMatch(s -> s.equalsIgnoreCase(entityType))) {
        return SERVICE_ID;
      }
```

**Review by Bhanuagr — DISMISSED** [review]
