### PR TITLE
#14317 fix: glossary term broken link

### LINKED ISSUE #14317: Clicking on glossary term while adding throws error
**Affected module**
UI

**Describe the bug**
Clicking on glossary term while adding throws error. It is redirecting to tags page instead of glossary.

https://github.com/open-metadata/OpenMetadata/assets/33024356/0c4dc25d-cf9d-4ee9-8385-7bbbcbe68a62

### PR DESCRIPTION
**Pull request by harsh-vador**
### Describe your changes:

Fixes #14317 

I worked on fixing the broken glossary link in the table.

https://github.com/open-metadata/OpenMetadata/assets/58542468/0eba00df-cd6f-472c-9b36-43d73b3a5804

#
### Type of change:

- [x] Bug fix

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/AsyncSelectList/AsyncSelectList.tsx [hunk 1]
```diff
@@ -222,6 +223,7 @@ const AsyncSelectList: FC<AsyncSelectListProps> = ({
         startWith={TAG_START_WITH.SOURCE_ICON}
         tag={tag}
         tagProps={tagProps}
+        tagType={tagType}
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/src/components/AsyncSelectList/AsyncSelectList.tsx:226]: Instead of passing the additional `tagType` prop, can we directly use the `tag.source` value here?

File: openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainerV2/TagsContainerV2.tsx [hunk 2]
```diff
@@ -152,7 +156,11 @@ const TagsContainerV2 = ({
     () =>
       showAddTagButton ? (
         <Col className="m-t-xss" onClick={handleAddClick}>
-          <TagsV1 startWith={TAG_START_WITH.PLUS} tag={TAG_CONSTANT} />
+          <TagsV1
+            startWith={TAG_START_WITH.PLUS}
+            tag={isGlossaryType ? GLOSSARY_CONSTANT : TAG_CONSTANT}
+            tagType={tagType}
+          />
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainerV2/TagsContainerV2.tsx:163]: same here, can addition of new prop be avoided here?

File: openmetadata-ui/src/main/resources/ui/src/components/AsyncSelectList/AsyncSelectList.tsx (hunk 1 above)
Comment (harsh-vador) [reply openmetadata-ui/src/main/resources/ui/src/components/AsyncSelectList/AsyncSelectList.tsx:226]: The earlier issue which was happening was due to **data.source**,it returned **undefined** incase of already selected tag. This fix will work as expected now.

File: openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainerV2/TagsContainerV2.tsx (hunk 2 above)
Comment (harsh-vador) [reply openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainerV2/TagsContainerV2.tsx:163]: Explained the need above

**Review by aniketkatkar97 — APPROVED** [review]
