### PR TITLE
Lineage Improvements

### LINKED ISSUE #18500: Monster/huge lineages blocking the site
Hi, we have assets that are related to many assets producing a huge lineage as you can see in the picture:

image

This results in crashing the page or taking 1 minute to load the page or sometimes it remains blank for a long time and when it loads it does not allow you to do anything, this produces a very bad user experience, in addition they are usually important gold assets that are highly consulted.
Perhaps, if it would load for these assets the parents and children in the first view, it would load faster and then the user would browse for the other grandchildren and grandparents.

**Version:**
 - Source: Snwoflake
 - OpenMetadata version: 1.5.7

thanks,
Carlos

### PR DESCRIPTION
**Pull request by mohityadav766**
### Describe your changes:

Fixes #18500 

- [x] Updated API 
- [x] Update storage mechanism for api to only store one direction
- [x]  Added direction based lineage fetch
- [x] Added Pagination for apis
- [ ]  Added streamed response api
- [x]  API Export Update  (need to conside new API changes)
- [ ] Add Import for CSV
- [x] UI - Service Layer Additon
- [ ]  Effectively allow 1000s nodes to be drawn and passed as response
- [x] Added createdAt , createdBy , updatedAt and updatedBy
- [x]  add migrations for new field addition
- [x] Filtering for upstream fetch isn't considering query_filter

I worked on ... because ...

https://github.com/user-attachments/assets/ff5bdb59-f143-48f4-886d-6223564f157a

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v170/MigrationUtil.java [hunk 1]
```diff
@@ -1,23 +1,81 @@
...
 import org.openmetadata.service.jdbi3.WorkflowDefinitionRepository;
+import org.openmetadata.service.resources.databases.DatasourceConfig;
 import org.openmetadata.service.util.EntityUtil;
 import org.openmetadata.service.util.JsonUtils;
 
 @Slf4j
 public class MigrationUtil {
+  private MigrationUtil() {}
+
+  private static final String UPDATE_NULL_JSON =
```
Comment (mohityadav766) [inline openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v170/MigrationUtil.java:27]: this needs to work since , we only update for relation type upstream

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java [hunk 2]
```diff
@@ -1110,7 +1112,13 @@ List<EntityRelationshipObject> findFromBatch(
         @BindList("toIds") List<String> toIds, @Bind("relation") int relation);
 
     @SqlQuery(
-        "SELECT fromId, toId, fromEntity, toEntity, relation "
+        "SELECT * FROM ( SELECT *, ROW_NUMBER() OVER (ORDER BY fromId) AS row_num FROM entity_relationship WHERE relation = :relation) AS rec WHERE row_num > :after ORDER BY row_num LIMIT :limit;")
```
Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java:1115]: any reason to change this query

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/LineageRepository.java [hunk 3]
```diff
@@ -140,86 +161,233 @@ public void addLineage(AddLineage addLineage) {
...
+    buildExtendedLineage(from, to, lineageDetails, relationAlreadyExists);
+  }
+
+  private void buildExtendedLineage(
+      EntityReference from,
+      EntityReference to,
+      LineageDetails lineageDetails,
+      boolean childRelationExists) {
+    boolean addService =
+        Entity.entityHasField(from.getType(), "service")
```
Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/LineageRepository.java:175]: we need to add some constants for these strings

**Review by harshach — APPROVED** [review]

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/LineageRepository.java (hunk 3 above)
Comment (mohityadav766) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/LineageRepository.java:175]: sure

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java (hunk 2 above)
Comment (mohityadav766) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java:1115]: i added a new one, but that too i am not user , removing it

File: openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx [hunk 4]
```diff
@@ -2486,3 +2492,31 @@ export const getEntityImportPath = (entityType: EntityType, fqn: string) => {
...
+  }
+  if (node.id === targetNodeId) {
+    return {
+      ...node,
+      type: EntityLineageNodeType.OUTPUT,
+    };
+  }
+
+  return node;
+};
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx:2522]: We can have this for lineage utils right

**Review by chirag-madlani — APPROVED** [review]

**Review by ShaileshParmar11 — APPROVED** [review]
