### PR TITLE
Fix message texts and service icons

### LINKED ISSUE #4685: UI: Wording of "Delete databaseService will also delete database" to be clearer
**Affected module**
UI

**Describe the bug**
The wording can be confusing, informing the user that the database will be deleted.

Similarly for deleting schema.

**To Reproduce**
image
image

**Expected behavior**
The wording needs to be clearer that the meta data in openmetadata will be deleted rather than the "database".

**Version:**
 - OS: osx
 - Python version: 3
 - OpenMetadata version: 0.10
 - OpenMetadata Ingestion package version: can't recall

**Additional context**
NA

### LINKED ISSUE #4731: DBT Configuration Source in Configure DBT tab does not show selected value from dropdown
**Affected module**
UI

**Describe the bug**
DBT Configuration Source in Configure DBT tab does not show the value selected from the dropdown

**To Reproduce**
- Navigate to the Services page from the left panel
- Create a new Mysql service and select the "None" from the DBT Configuration Source dropdown
- Save the service
- Navigate to the created service and edit the ingestion created
- The DBT Configuration Source dropdown in Configure DBT tab does not contain the value selected while creating ingestion.

https://user-images.githubusercontent.com/67048554/166904622-2d93e644-d36d-459c-8d17-f13837062e6a.mov

**Expected behaviour**
The DBT Configuration Source dropdown should contain the selected value.

**Version:**
 - OpenMetadata version: 0.10.1

**Additional context**

### PR DESCRIPTION
**Pull request by darth-coder00**
Closes #4685
Closes #4731
### Describe your changes :

I worked on 

- Updated all texts for Delete Entity Modal
- Updated texts for the Ingestion guides
- Added missing service icons
- DBT Configuration Source persistence

#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :
<p align="center">
Screenshot 2022-05-05 at 8 52 47 PM
Screenshot 2022-05-05 at 8 53 28 PM
Screenshot 2022-05-05 at 8 54 20 PM

https://user-images.githubusercontent.com/86726556/166958812-88f0d1d5-02ea-4704-8d11-06a0c3231707.mov

</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui @harshach @shahsank3t

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx [hunk 1]
```diff
@@ -550,5 +543,5 @@ export const isColumnTestSupported = (dataType: string) => {
 };
 
 export const getTitleCase = (text?: string) => {
-  return text ? startCase(camelCase(text)) : '';
+  return text ? startCase(text) : '';
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx:546]: Why are we making changes to this?

File: openmetadata-ui/src/main/resources/ui/src/pages/service/index.tsx [hunk 2]
```diff
@@ -642,32 +643,28 @@ const ServicePage: FunctionComponent = () => {
...
     switch (serviceName) {
       case ServiceCategory.DATABASE_SERVICES:
-        return `Deleting this ${service} will also delete ${pluralize(
-          instanceCount,
-          'database',
-          's'
-        )}`;
+        return getEntityDeleteMessage(
+          service || 'Service',
+          pluralize(instanceCount, 'Database', 's')
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/pages/service/index.tsx:648]: The default suffix is 's'.  Can we avoid passing the suffix in all of these cases?

```suggestion
          pluralize(instanceCount, 'Database')
```

File: openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx (hunk 1 above)
Comment (darth-coder00) [reply openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx:546]: User messages or description texts should not have `camelCase` in it
CC: @devyani-kaushik

**Review by vivekratnavel — APPROVED** [review]
