### PR TITLE
FIx #7136  UI: Admin is not able to edit an announcement

### LINKED ISSUE #7136: UI: Admin is not able to edit an announcement
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
Admin users are unable to edit announcements made by other users.

**To Reproduce**
Try to edit an announcement made by other users. There is only react and reply option available.

**Expected behavior**
Admin users should be able to edit the announcement details including the start and end time

Screen Shot 2022-09-01 at 10 52 11 AM

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
### Describe your changes :

I worked on issue #7136

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :

image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCard/PopoverContent.tsx [hunk 1]
```diff
@@ -69,7 +69,22 @@ const PopoverContent: FC<Props> = ({
...
+    }
+  }, [threadId, postId, onConfirmation, isAuthor, currentUser]);
+
+  const editCheck = useMemo(() => {
+    if (isAnnouncement) {
+      return isAuthor || currentUser?.isAdmin;
+    } else {
+      return !isThread && isAuthor;
+    }
+  }, [isAnnouncement, isThread, isAuthor, currentUser]);
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCard/PopoverContent.tsx:87]: Admin should have access to delete or edit any thread, not just announcements

Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCard/PopoverContent.tsx:87]: Sure @vivekratnavel .

Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCard/PopoverContent.tsx]: Done.

**Review by chirag-madlani — APPROVED** [review]

**Review by vivekratnavel — APPROVED** [review]

**Review by ShaileshParmar11 — APPROVED** [review]
