### PR TITLE
Fix #6356 Clicking tasks on My Tasks should open up the task details

### LINKED ISSUE #6356: Clicking tasks on My Tasks should open up the task details
**Affected module**
UI

**Describe the bug**
Clicking pending tasks on the home page leads to me to the below page
image

Clicking on the task card page doesn't do anything. Ideally it should open up details and allow me to finis the task right there .

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
Fixes #6356 

### Describe your changes :

I worked on adding support for click-on task cards.

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :

https://user-images.githubusercontent.com/59080942/181464446-5ab0c242-e7a2-4f44-96a0-3387d6910e40.mov

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedEditor/SendButton.tsx [hunk 1]
```diff
@@ -33,7 +33,9 @@ export const SendButton: FC<SendButtonProp> = ({
   onSaveHandler,
 }) => {
   return (
-    <div className="tw-absolute tw-right-2 tw-bottom-2 tw-flex tw-flex-row tw-items-center tw-justify-end">
+    <div
+      className="tw-absolute tw-right-2 tw-bottom-2 tw-flex tw-flex-row tw-items-center tw-justify-end"
+      onClick={(e) => e.stopPropagation()}>
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedEditor/SendButton.tsx:38]: Can we use Affix here? https://ant.design/components/affix/

File: openmetadata-ui/src/main/resources/ui/src/components/common/PopOverCard/EntityPopOverCard.tsx [hunk 2]
```diff
@@ -161,7 +161,10 @@ const EntityPopOverCard: FC<Props> = ({ children, entityType, entityFQN }) => {
   const PopoverTitle = () => {
     return (
       <Link data-testid="entitylink" to={getEntityLink(entityType, entityFQN)}>
-        <button className="tw-text-info" disabled={AppState.isTourOpen}>
+        <button
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/common/PopOverCard/EntityPopOverCard.tsx:164]:
```suggestion
        <Button
```

**Review by chirag-madlani — APPROVED** [review]

**Review by ShaileshParmar11 — APPROVED** [review]
