### PR TITLE
Fix #4013 UI: Support updated EntityReference

### LINKED ISSUE #4011: UI: User Profile popup in activity feed should not show deleted teams
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI 

**Describe the bug**

- [x] User Profile popup in activity feed should not show deleted teams
- [x] Entity Manage tab should not show deleted team as an option to assign an owner
- [x] Show "(Deactivated)" for deleted teams in Activity Feeds as well as owner under "Manage" tab in entity pages

### LINKED ISSUE #4013: UI: Support updated EntityReference
Refer #4012

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
Fixes #4013 
Fixes #4011 
### Describe your changes :

I worked on issue #4013 

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

**Review by harshach — APPROVED** [review]

File: openmetadata-ui/src/main/resources/ui/src/pages/teams/AddUsersModal.tsx [hunk 1]
```diff
@@ -60,9 +60,11 @@ const AddUsersModal = ({
       })
       .map((user, index) => {
         const User = {
-          description: user.displayName || user.description || '',
-          name: user.name || '',
+          displayName: user.displayName || user.name || '',
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/pages/teams/AddUsersModal.tsx:63]: Can we define a static utility to give a name string from EntityReference and use it everywhere instead of `user.displayName || user.name || ''`?

Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/pages/teams/AddUsersModal.tsx:63]: @vivekratnavel , Yeah, I will make the changes.

**Review by vivekratnavel — APPROVED** [review]
