### PR TITLE
#13913: supported test connection api cancellation

### LINKED ISSUE #13913: Cancelling a Test connection doesn't cancel it's API calls
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

Issue from https://github.com/open-metadata/OpenMetadata/issues/13316#issuecomment-1780740852

**Describe the bug**

- Cancelling a Test connection doesn't cancel it's API calls

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

- should cancel all API calls if the test connection was got cancel

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes:

Fixes #13913

- I worked on supporting test connection api cancellation
- delete workflow as well if any cancellation is made in between.
- added useAbortController hook to use it globally

https://github.com/user-attachments/assets/ee647e03-6b63-44d0-bbc5-48dbda9ea2ef

#
### Type of change:

- [x] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/TestConnection.tsx [hunk 1]
```diff
@@ -180,6 +185,10 @@ const TestConnection: FC<TestConnectionProps> = ({
     setMessage(TEST_CONNECTION_TESTING_MESSAGE);
     handleResetState();
 
+    // Create a new AbortController instance
+    const controller = new AbortController();
+    APICancellationControllerRef.current = controller; // Store the controller for later cancellation
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/TestConnection.tsx:190]: @Ashish8689 , can we create a custom hook for abort controller logic and use it here? this way we can reuse the logic in other components as well.


```ts

const useAbortController = () => {
  const controllerRef = useRef<AbortController | null>(null);

  useEffect(() => {
    
    const controller = new AbortController();
    controllerRef.current = controller;

    
    return () => {
      controllerRef.current?.abort();
    };
  }, []);

  return {
    controller: controllerRef.current,
  };
};

export default useAbortController;
```

File: openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/TestConnection.tsx [hunk 2]
```diff
@@ -223,57 +232,71 @@ const TestConnection: FC<TestConnectionProps> = ({
...
-            setTestStatus(StatusType.Successful);
-            setMessage(TEST_CONNECTION_SUCCESS_MESSAGE);
-          } else {
-            const isMandatoryStepsFailing = steps.some(
-              (step) => step.mandatory && !step.passed
-            );
-            setTestStatus(
-              isMandatoryStepsFailing ? StatusType.Failed : 'Warning'
+      // return a promise that wraps the interval and handles errors inside it
+      const workflowPromise = new Promise<void>((resolve, reject) => {
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/TestConnection.tsx:236]: @Ashish8689 , why are we creating a promise here?

File: openmetadata-ui/src/main/resources/ui/src/utils/ToastUtils.ts [hunk 3]
```diff
@@ -11,7 +11,7 @@
  *  limitations under the License.
  */
 
-import { AxiosError } from 'axios';
+import axios, { AxiosError } from 'axios';
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/utils/ToastUtils.ts:14]:
```suggestion
import { AxiosError, isCancel} from 'axios';
```

File: openmetadata-ui/src/main/resources/ui/src/utils/ToastUtils.ts [hunk 4]
```diff
@@ -47,34 +47,36 @@ export const showErrorToast = (
...
-    // except for principal domain mismatch errors
-    if (
-      error &&
-      (error.response?.status === ClientErrors.UNAUTHORIZED ||
-        (error.response?.status === ClientErrors.FORBIDDEN &&
-          method === 'GET')) &&
-      !errorMessage.includes('principal domain')
-    ) {
-      return;
+  if (!axios.isCancel(error)) {
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/utils/ToastUtils.ts:50]: @Ashish8689 , here we can early return if the error is type of `Cancel` interface.
```ts
if(isCancel(error)){
  return;
}

File: openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/TestConnection.tsx (hunk 2 above)
Comment (Ashish8689) [reply openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/TestConnection.tsx:233]: since, we are calling the API after every some interval, so to manage the repeated asynchronous operation (i.e., polling the status), have used promise here to ensure proper error handling as well, if any polling API fails or API aborts, so that can be handled properly with the promise.

**Comment by Ashish8689** [comment]
@Sachin-chaurasiya changes made as per comments!

File: openmetadata-ui/src/main/resources/ui/src/hooks/AbortController/useAbortController.test.tsx [hunk 5]
```diff
@@ -0,0 +1,99 @@
...
+
+// Mock the global AbortController
+beforeAll(() => {
+  global.AbortController = jest.fn().mockImplementation(() => ({
+    signal: {},
+    abort: jest.fn(),
+  }));
+});
+
+describe('useAbortController', () => {
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/hooks/AbortController/useAbortController.test.tsx:30]: @Ashish8689 , can we use `renderHook` for testing the custom hook?

```
import { renderHook } from '@testing-library/react-hooks';
```

**Review by chirag-madlani — APPROVED** [review]

**Review by chirag-madlani — APPROVED** [review]

**Review by pmbrull — APPROVED** [review]
