### PR TITLE
#16477: fix deleted user profile not showing

### LINKED ISSUE #16477: Cannot View Profile of Soft Deleted Users
**Affected module**
UI

**Describe the bug**
When trying to access the profile of a deleted user it returns a 404 not found

**To Reproduce**

https://github.com/open-metadata/OpenMetadata/assets/13626425/c527551d-dc8d-4592-b07e-0a8697e0c0aa

**Expected behavior**
Should show the page. Seems like the request sent is missing the `include=deleted` query params

`https://sandbox.open-metadata.org/api/v1/users/name/teddy.crepineau?fields=profile%2Croles%2Cteams%2Cpersonas%2CdefaultPersona%2Cdomain`

**Version:**
 - OpenMetadata version: 1.4.1

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes:

Fixes #16477

- I worked on fixing deleted user profile not showing in details page
- add manage button in detail page to support delete and restore functionality
- Added playwright test for the feature.

Failure need to work on :- 

- Feed's API are failing for deleted user.
- Admin User deleting himself API also fail, but the user is deleted 
-  Above [issue](https://github.com/open-metadata/OpenMetadata/issues/16588)  assign to @mohityadav766 

https://github.com/open-metadata/OpenMetadata/assets/66266464/c10990e0-9f1a-44d5-9add-a3968a0e02ae

#
### Type of change:

- [x] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Review by ShaileshParmar11 — COMMENTED** [review]
Please add E2E in playwright, overall looks good

**Comment by Ashish8689** [comment]
@ShaileshParmar11 added playwright test for soft & hard deleted and restore user from ProfilePage

File: openmetadata-ui/src/main/resources/ui/playwright/support/entity/UserPageClass.ts [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+
+  async restoreUserProfilePage(page: Page, fqn: string) {
+    await restoreUserProfilePage(page, fqn);
+  }
+  async hardDeleteUserProfilePage(page: Page, displayName: string) {
+    await hardDeleteUserProfilePage(page, displayName);
+  }
+}
+
+export default UserEntityClass;
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/playwright/support/entity/UserPageClass.ts:42]: In my opinion this is not reusable please use utils directly in test

File: openmetadata-ui/src/main/resources/ui/playwright/utils/user.ts [hunk 2]
```diff
@@ -33,3 +34,139 @@ export const generateRandomUsername = () => {
...
+  ).not.toBeVisible();
+};
+
+export const softDeleteUserProfilePage = async (
+  page: Page,
+  userName: string,
+  displayName: string
+) => {
+  await page.getByTestId('searchbar').fill(userName);
+  await page.waitForResponse('/api/v1/search/query?q=**&from=0&size=*&index=*');
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/playwright/utils/user.ts:92]:
```suggestion
const userResponse = page.waitForResponse('/api/v1/search/query?q=**&from=0&size=*&index=*');
  await page.getByTestId('searchbar').fill(userName);
  await  userResponse;
```

File: openmetadata-ui/src/main/resources/ui/playwright/utils/user.ts [hunk 3]
```diff
@@ -33,3 +34,139 @@ export const generateRandomUsername = () => {
...
+
+  await page.waitForSelector('[role="dialog"].ant-modal');
+
+  await expect(page.locator('[role="dialog"].ant-modal')).toBeVisible();
+  await expect(page.locator('.ant-modal-title')).toContainText(displayName);
+
+  await page.fill('[data-testid="confirmation-text-input"]', 'DELETE');
+  await page.click('[data-testid="confirm-button"]');
+
+  await page.waitForResponse(`/api/v1/users/*?hardDelete=false&recursive=true`);
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/playwright/utils/user.ts:110]: same here

File: openmetadata-ui/src/main/resources/ui/playwright/utils/user.ts [hunk 4]
```diff
@@ -33,3 +34,139 @@ export const generateRandomUsername = () => {
...
+  await expect(page.locator('.ant-modal-title')).toContainText('Restore user');
+
+  await expect(
+    page.locator('[data-testid="restore-modal-body"]')
+  ).toContainText(`Are you sure you want to restore ${fqn}?`);
+
+  await page.click('.ant-modal-footer .ant-btn-primary');
+
+  await page.waitForResponse('/api/v1/users/restore');
+
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/playwright/utils/user.ts:137]: here as well

File: openmetadata-ui/src/main/resources/ui/playwright/utils/user.ts [hunk 5]
```diff
@@ -33,3 +34,139 @@ export const generateRandomUsername = () => {
...
+  await expect(page.locator('[role="dialog"].ant-modal')).toBeVisible();
+  await expect(page.locator('.ant-modal-title')).toContainText(displayName);
+
+  await page.click('[data-testid="hard-delete-option"]');
+  await page.check('[data-testid="hard-delete"]');
+  await page.fill('[data-testid="confirmation-text-input"]', 'DELETE');
+  await page.click('[data-testid="confirm-button"]');
+  await page.waitForResponse(
+    `**/api/v1/users/*?hardDelete=true&recursive=true`
+  );
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/playwright/utils/user.ts:165]: here also

**Review by ShaileshParmar11 — COMMENTED** [review]
added comment

**Review by ShaileshParmar11 — DISMISSED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UsersProfile/UserProfileDetails/UserProfileDetails.component.tsx [hunk 6]
```diff
@@ -306,13 +300,32 @@ const UserProfileDetails = ({
...
       handleDefaultPersonaUpdate,
     ]
   );
 
+  const handleRestoreUser = useCallback(async () => {
+    setIsLoading(true);
+
+    try {
+      await restoreUser(userData.id);
+      afterDeleteAction(true);
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UsersProfile/UserProfileDetails/UserProfileDetails.component.tsx:315]: Here we are restoring the soft-deleted user. Then, we are setting the soft-deleted flag to `true` in `afterDeleteAction(true)`. I think it should be set to `false`, right?

File: openmetadata-ui/src/main/resources/ui/src/components/common/DeleteWidget/DeleteWidgetModal.tsx [hunk 7]
```diff
@@ -147,6 +150,10 @@ const DeleteWidgetModal = ({
                 entity: entityName,
               })
           );
+
+          if (entityType === EntityType.USER && entityId === currentUser?.id) {
+            return onLogoutHandler();
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/common/DeleteWidget/DeleteWidgetModal.tsx:155]:
```suggestion
            onLogoutHandler();
            return;
```

File: openmetadata-ui/src/main/resources/ui/src/styles/variables.less [hunk 8]
```diff
@@ -34,7 +34,7 @@
 @yellow-5: #fff8e6;
 @yellow-6: #c18100;
 @yellow-7: #e7b85d;
-@error-light-color: #e5493740;
+@error-light-color: #ff9a8e40;
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/styles/variables.less:37]: @Ashish8689 , let's scan all the places where we are using this color variable.

**Review by Sachin-chaurasiya — COMMENTED** [review]
Left a few comments, thanks

File: openmetadata-ui/src/main/resources/ui/src/styles/variables.less (hunk 8 above)
Comment (Ashish8689) [reply openmetadata-ui/src/main/resources/ui/src/styles/variables.less:37]: @Sachin-chaurasiya we are using this color in only searchIndexStatsTable and have verified with @Rupchavan for same!

File: openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UsersProfile/UserProfileDetails/UserProfileDetails.component.tsx (hunk 6 above)
Comment (Ashish8689) [reply openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UsersProfile/UserProfileDetails/UserProfileDetails.component.tsx:315]: No, it will changes the `prev` state which is `true to false`.  Have also added the comment on the restore call for the same.

image

**Comment by Ashish8689** [comment]
@Sachin-chaurasiya changes made as per comments!

**Review by Sachin-chaurasiya — APPROVED** [review]
