### PR TITLE
Enhanced Tour feature

### LINKED ISSUE #2180: Going back while in-between tour feature deactivates the tables, topics, dashboards etc buttons on home page
Steps to reproduce:
1. Click on the tour icon
2. Go back
3. Try clicking on the entity overview buttons.

https://user-images.githubusercontent.com/83201188/149091095-b00245ee-5999-4ffc-a680-d90de1dd8aa0.mov

### LINKED ISSUE #2182: Tour steps getting skipped
## Scenario 1:
1. Click on the tour icon
2. Go to step 3
3. Type `dim_a`
4. It will display the search results but will still be on step 3
5. Click on the `previous arrow`, it will break the tour.

https://user-images.githubusercontent.com/83201188/149093421-41ad4c67-d8e6-42d6-8337-0e4fc908bcb9.mov

## Scenario 2:
1. Click on the tour icon
2. Go to step 4
3. Then click on the `previous arrow` to come to step 3
4. Type `dim_a`
5. It will directly skip step 5.

https://user-images.githubusercontent.com/83201188/149094042-5340de32-9552-4b5b-b95b-843398223b2b.mov

### PR DESCRIPTION
**Pull request by darth-coder00**
### Describe your changes :
Closes #2180, closes #2182 

I worked on the Tour enhancements like skip functionality and Appbar issues in Tour

#
### Type of change :

- [ ] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :
<p align="center">
Screenshot 2022-01-13 at 7 38 19 PM

</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@shahsank3t @Sachin-chaurasiya

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/nav-bar/NavBar.interface.ts [hunk 1]
```diff
@@ -0,0 +1,16 @@
+import { DropDownListItem } from '../dropdown/types';
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/nav-bar/NavBar.interface.ts:1]: Please add the license file.

File: openmetadata-ui/src/main/resources/ui/src/utils/TourUtils.tsx [hunk 2]
```diff
@@ -0,0 +1,219 @@
+import React from 'react';
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/utils/TourUtils.tsx:1]: Please add the license content

**Review by Sachin-chaurasiya — CHANGES_REQUESTED** [review]
Minor changes requested.

**Review by shahsank3t — APPROVED** [review]
