### PR TITLE
Fixes #23945 : Teams page now relies of BE for all the teams info, instead of frontend filtering

### LINKED ISSUE #23945: deleted teams are displayed in the organization list
**Affected module**
UI
**Describe the bug**
deleted teams are displayed in the organization list

Image

Image

**Expected behavior**
deleted teams are not displayed in the organization list

**Version:**

 - OpenMetadata version: [e.g. 0.8] 1.10.1

**Additional context**
[slack](https://openmetadata.slack.com/archives/C02B6955S4S/p1760693279109319)

### PR DESCRIPTION
**Pull request by siddhant1**
### Describe your changes:

Fixes I worked on adding API call based fetching to the Teams table instead of frontend sorting.

Fixes : [23945](https://github.com/open-metadata/OpenMetadata/issues/23945)

https://github.com/user-attachments/assets/f1bfdb1b-76b2-4e3f-9913-d0f1875e639b

#
### Type of change:

- [x] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/pages/TeamsPage/TeamsPage.tsx [hunk 1]
```diff
@@ -481,6 +481,13 @@ const TeamsPage = () => {
     init();
   }, [fqn]);
 
+  useEffect(() => {
+    if (hasViewPermission && fqn) {
+      // fetchTeamAdvancedDetails(fqn);
```
Comment (siddhant1) [inline openmetadata-ui/src/main/resources/ui/src/pages/TeamsPage/TeamsPage.tsx]: @siddhant1 to renable this for correct count

File: openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamDetailsV1.tsx [hunk 2]
```diff
@@ -267,14 +264,15 @@ const TeamDetailsV1 = ({
...
-                    'name.keyword': 'Organization',
+                    'name.keyword': currentTeam.name,
                   },
                 },
               ],
             },
           },
         },
         searchIndex: SearchIndex.TEAM,
+        includeDeleted: showDeletedTeam,
```
Comment (siddhant1) [inline openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamDetailsV1.tsx]: @Ashish8689 Added this as well to only search within the team

File: openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamDetailsV1.tsx [hunk 3]
```diff
@@ -267,14 +262,15 @@ const TeamDetailsV1 = ({
               must_not: [
                 {
                   term: {
-                    'name.keyword': 'Organization',
+                    'name.keyword': currentTeam.name,
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamDetailsV1.tsx]: I believe the `Organization` team was put here intentionally, so that it won't be returned in the search result. Any reason for changing that to `currentTeam.name`?

**Review by aniketkatkar97 — DISMISSED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamDetailsV1.tsx (hunk 3 above)
Comment (siddhant1) [reply openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamDetailsV1.tsx]: When we are inside an organisation it performs a search in the entire namespace, waiting for @Ashish8689 comment on this one

File: openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamDetailsV1.tsx [hunk 4]
```diff
@@ -200,8 +198,8 @@ const TeamDetailsV1 = ({
   );
 
   const teamCount = useMemo(
-    () => currentTeam.childrenCount ?? childTeamList.length,
-    [childTeamList, currentTeam.childrenCount]
+    () => (isTeamBasicDataLoading ? 0 : childTeamList.length),
```
Comment (Ashish8689) [inline openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamDetailsV1.tsx]: don't we need to check the current team count here ?

File: openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Teams.spec.ts [hunk 5]
```diff
@@ -754,6 +756,76 @@ test.describe('Teams Page', () => {
...
+      // Verify initial state: active team visible, deleted team not visible
+      await expect(
+        page.getByRole('link', { name: activeTeam.data.displayName })
+      ).toBeVisible();
+      await expect(
+        page.getByRole('link', { name: deletedTeam.data.displayName })
+      ).not.toBeVisible();
+
+      // Toggle to show deleted teams
+      await page.locator('[data-testid="show-deleted"]').click();
```
Comment (karanh37) [inline openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Teams.spec.ts]: Are we making API call on toggle of deleted button ?
We should be having API wait

File: openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Teams.spec.ts [hunk 6]
```diff
@@ -754,6 +759,86 @@ test.describe('Teams Page', () => {
...
+
+      const fetchDeletedTeamsResponse = page.waitForResponse(
```
Comment (karanh37) [inline openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Teams.spec.ts:802]: so the general pattern is like, we declare the 

`const fetchDeletedTeamsResponse = page.waitForResponse(
await page.locator('[data-testid="show-deleted"]').click();
await fetchDeletedTeamsResponse()
`
