### PR TITLE
fix: Table list view within service shows `name` instead of `displayName` #10136

### LINKED ISSUE #10136: Table list view within service shows `name` instead of `displayName`
**Affected module**
UI
Table list view within service shows `name` instead of `displayName` even though the `displayName` is available from the response from ES
image

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes :

Closes #10136 

#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx [hunk 1]
```diff
@@ -583,14 +583,14 @@ const DatabaseSchemaPage: FunctionComponent = () => {
         }),
         dataIndex: 'name',
         key: 'name',
-        render: (text: string, record: Table) => {
+        render: (_, record: Table) => {
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx:586]: Can we update dataIndex to displayName and it will work out of the box

Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx:586]: but We won't get a fallback if there is no displayName available, with the use of `{getEntityName(record)}` it will pick displayname and if its not available it will pick name

**Review by chirag-madlani — APPROVED** [review]
