### PR TITLE
Fixes #16442: Store auth tokens on client using service worker + indexedDB

### LINKED ISSUE #16442: [UI] Session Storage should not hold sensitive information
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Currently we are storing sensitive information in session/local cache which should be avoided on UI

**Describe the bug**

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by maulikkotak98**
### Describe your changes:

Fixes #16442

Moved auth token storage from localStorage to a more secure Service Worker + IndexedDB implementation.

- Tokens will now be stored in IndexedDB via Service Worker instead of directly accessible localStorage.
- Added fallback to localStorage for browsers without Service Worker/IndexedDB support.

Note: @azure/msal-react doesn't support custom storage providers for its own internal use, so it will use the localStorage for its own reference of tokens due to its limitations.

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/Auth/AppAuthenticators/OidcAuthenticator.tsx [hunk 1]
```diff
@@ -205,8 +205,10 @@ const OidcAuthenticator = forwardRef<AuthenticatorRef, Props>(
                   handleFailedLogin();
                 }}
                 onSuccess={(user: User) => {
-                  setOidcToken(user.id_token);
-                  handleSuccessfulLogin(user as OidcUser);
+                  (async () => {
+                    await setOidcToken(user.id_token);
+                    handleSuccessfulLogin(user as OidcUser);
+                  })();
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Auth/AppAuthenticators/OidcAuthenticator.tsx:211]: Can't we instead create async callback function for onSuccess

File: openmetadata-ui/src/main/resources/ui/src/index.tsx [hunk 2]
```diff
@@ -27,3 +27,9 @@ root.render(
     <App />
   </React.StrictMode>
 );
+
+if ('serviceWorker' in navigator && 'indexedDB' in window) {
+  window.addEventListener('load', () => {
+    navigator.serviceWorker.register('/app-worker.js');
+  });
+}
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/index.tsx:35]: What happens when these two are false?

File: openmetadata-ui/src/main/resources/ui/src/pages/SamlCallback/index.tsx [hunk 3]
```diff
@@ -35,29 +35,38 @@ const SamlCallback = () => {
...
+          if (refreshToken) {
+            await setRefreshToken(refreshToken);
+            // Remove refresh token from cookie storage, don't want to keep it in the browser
+            cookieStorage.removeItem(REFRESH_TOKEN_KEY);
+          }
+
+          await handleSuccessfulLogin(oidcUser);
+        } catch {
+          // Error handling is already done in handleSuccessfulLogin
+        }
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/pages/SamlCallback/index.tsx]: We can pull out this code outside of useEffect if required, please clean this up to improve readability

File: openmetadata-ui/src/main/resources/ui/src/index.tsx (hunk 2 above)
Comment (maulikkotak98) [reply openmetadata-ui/src/main/resources/ui/src/index.tsx:35]: LocalStorage will be used as a fallback if the browser doesn't have support for service worker or indexedDB.
Code that handles the fallback - https://github.com/open-metadata/OpenMetadata/pull/22539/files/c472b5e683aa98ff1cf40df548b27a27b9538f30#diff-1567f463bceac456f5e558c1ae113f293240871938982f833ff9c8d3502f3627R61

File: openmetadata-ui/src/main/resources/ui/src/pages/SamlCallback/index.tsx (hunk 3 above)
Comment (maulikkotak98) [reply openmetadata-ui/src/main/resources/ui/src/pages/SamlCallback/index.tsx]: Ack, taking a look.

File: openmetadata-ui/src/main/resources/ui/src/components/Auth/AppAuthenticators/OidcAuthenticator.tsx (hunk 1 above)
Comment (maulikkotak98) [reply openmetadata-ui/src/main/resources/ui/src/components/Auth/AppAuthenticators/OidcAuthenticator.tsx:211]: The Callback component seems to expect a synchronous function for onSuccess, so kept it as is.

File: openmetadata-ui/src/main/resources/ui/src/pages/SamlCallback/index.tsx (hunk 3 above)
Comment (maulikkotak98) [reply openmetadata-ui/src/main/resources/ui/src/pages/SamlCallback/index.tsx]: Done

**Review by ShaileshParmar11 — APPROVED** [review]
