### PR TITLE
Fixes #2068 Tag duplication

### LINKED ISSUE #2068: Tag duplication
Steps to reproduce:
1. Add `#PersonalData.Personal` to a table column.
2. Then add `#User.FacePhoto`
3. There will be two `#PersonalData.Personal` tags 
4. After this, tags can't be added or deleted.

https://user-images.githubusercontent.com/83201188/148355737-449604fa-0502-4684-87f6-57b654c4426a.mov

The same is happening with the tag `User.politics`

https://user-images.githubusercontent.com/83201188/148355758-e7e10210-fccf-46a3-87e8-276b7c8635d4.mov

### PR DESCRIPTION
**Pull request by sureshms**
### Describe your changes :

See #2068 for more details

#
### Type of change :

- [x] Bug fix
- [] Improvement
- [] New feature
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

@harshach

### CODE REVIEW

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/util/EntityUtil.java [hunk 1]
```diff
@@ -347,14 +349,17 @@ public static void removeTagsByPrefix(TagDAO tagDAO, String fullyQualifiedName)
...
-  public static List<TagLabel> mergeTags(List<TagLabel> list1, List<TagLabel> list2) {
-    List<TagLabel> mergedTags =
-        Stream.concat(
-                Optional.ofNullable(list1).orElse(Collections.emptyList()).stream(),
-                Optional.ofNullable(list2).orElse(Collections.emptyList()).stream())
-            .distinct()
-            .collect(Collectors.toList());
-    return mergedTags.isEmpty() ? null : mergedTags;
+  /** Merge derivedTags into tags, if it already does not exist in tags */
+  public static void mergeTags(List<TagLabel> tags, List<TagLabel> derivedTags) {
```
Comment (mithmatt) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/util/EntityUtil.java:353]: private instead of public?

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/util/EntityUtil.java [hunk 2]
```diff
@@ -347,14 +349,17 @@ public static void removeTagsByPrefix(TagDAO tagDAO, String fullyQualifiedName)
     tagDAO.deleteTagsByPrefix(fullyQualifiedName);
   }
 
-  public static List<TagLabel> mergeTags(List<TagLabel> list1, List<TagLabel> list2) {
-    List<TagLabel> mergedTags =
-        Stream.concat(
-                Optional.ofNullable(list1).orElse(Collections.emptyList()).stream(),
-                Optional.ofNullable(list2).orElse(Collections.emptyList()).stream())
-            .distinct()
-            .collect(Collectors.toList());
```
Comment (mithmatt) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/util/EntityUtil.java:356]: I'm probably missing something obvious here
The stream concat + distinct seems correct to me

**Review by mithmatt — APPROVED** [review]

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/util/EntityUtil.java (hunk 1 above)
Comment (sureshms) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/util/EntityUtil.java:353]: It is used from outside also

**Review by harshach — APPROVED** [review]
