### PR TITLE
Fix #25457 - Nested columns not updating in real time

### LINKED ISSUE #25457: Nested column description does not refresh after edit until page reload
**Affected module**
Does it impact the UI, backend or Ingestion Framework? -UI

**Describe the bug**
- When editing the description of a nested column, the updated description is saved successfully but does not reflect immediately in the UI.
The user must manually refresh the page to see the updated description.

This behavior is inconsistent with top-level columns, which update instantly after saving.

**To Reproduce**

Screenshots or steps to reproduce

https://github.com/user-attachments/assets/9346b455-03fe-49ef-84f3-33da4b7544d9

**Expected behavior**
- The updated description for the nested column should refresh immediately in the UI after saving, without requiring a page reload.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by aniketkatkar97**
Fixes #25457 

This pull request introduces comprehensive improvements for supporting and testing updates to deeply nested columns in tables, particularly focusing on immediate UI updates (without page refresh) for descriptions, tags, and display names. The changes include new Playwright end-to-end tests, enhancements to the `SchemaTable` component logic, and expanded unit test coverage for nested column structures.

**Key changes:**

### End-to-end Testing for Nested Columns

* Added a new Playwright test suite, `NestedColumnUpdates.spec.ts`, which verifies that updating descriptions, tags, and display names for both level 1 and deeply nested columns takes effect immediately in the UI without requiring a page refresh.

### SchemaTable Component Enhancements

* Refactored the `updateColumnDetails` function in `SchemaTable.component.tsx` to use the new `updateColumnInNestedStructure` utility for updating columns, ensuring correct updates for nested column structures. The function signature was simplified, and all update call sites were updated accordingly. [[1]](diffhunk://#diff-1a8b63f049d4b128fe07203a4cfe1a1a29a0587366ec81fe0a714fea69cbd50dL432-R440) [[2]](diffhunk://#diff-1a8b63f049d4b128fe07203a4cfe1a1a29a0587366ec81fe0a714fea69cbd50dL455-R451) [[3]](diffhunk://#diff-1a8b63f049d4b128fe07203a4cfe1a1a29a0587366ec81fe0a714fea69cbd50dL478-R470) [[4]](diffhunk://#diff-1a8b63f049d4b128fe07203a4cfe1a1a29a0587366ec81fe0a714fea69cbd50dL571-R564)

### Nested Columns Unit Testing

* Extended `SchemaTable.test.tsx` with new mock data containing nested columns and new tests to verify rendering, structure, and update logic for nested columns. Also ensured that `updateColumnInNestedStructure` is available and tested. [[1]](diffhunk://#diff-acc5ca5bb26ec223d660b4c5a9b2fec6cd95fecdd5d7365d5a82b9109dcfe90eR67-R124) [[2]](diffhunk://#diff-acc5ca5bb26ec223d660b4c5a9b2fec6cd95fecdd5d7365d5a82b9109dcfe90eR206) [[3]](diffhunk://#diff-acc5ca5bb26ec223d660b4c5a9b2fec6cd95fecdd5d7365d5a82b9109dcfe90eR554-R614)

### Utilities and Test Improvements

* Updated the Playwright utility `updateDisplayNameForEntityChildren` to filter out analytics requests when waiting for column update responses, making tests more robust.

### Cleanup

* Removed the obsolete `TableUtils.test.ts` file, as nested column logic and tests have been moved or are now covered elsewhere.

### CODE REVIEW

**Comment by shah-harshit** [comment]
LGTM!

**Review by sonika-shah — APPROVED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/DriveService/File/FileColumnsTable/FileColumnsTable.tsx [hunk 1]
```diff
@@ -86,7 +86,7 @@ function FileColumnsTable() {
     };
   }, [permissions, fileDetails]);
 
-  const schema = pruneEmptyChildren(fileDetails?.columns ?? []);
+  const schema = fileDetails?.columns;
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/DriveService/File/FileColumnsTable/FileColumnsTable.tsx:91]: Why are we removing `pruneEmptyChildren`

File: openmetadata-ui/src/main/resources/ui/src/components/DriveService/File/FileColumnsTable/FileColumnsTable.tsx [hunk 2]
```diff
@@ -281,7 +281,7 @@ function FileColumnsTable() {
         className="align-table-filter-left"
         columns={columns}
         data-testid="file-columns-table"
-        dataSource={schema}
+        dataSource={pruneEmptyChildren(schema ?? [])}
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/DriveService/File/FileColumnsTable/FileColumnsTable.tsx]: Can we avoid it on render? it will run multiple times

**Comment by aniketkatkar97** [comment]
Known failure in Playwright, unrelated to the PR changes. Will be fixed in another PR.

**Review by harshsoni2024 — APPROVED** [review]
