### PR TITLE
UI : Remove whitespace in the name

### LINKED ISSUE #9045: UI - trim name if it's used and identifier in the URL
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**

- If a user creates a entity / team / user name with trailing space, It will be difficult to reach out to it via URL
- We should trim such name before sending it to Backend

**To Reproduce**

Screenshots or steps to reproduce

If we do refresh after reaching to this team it fail with an error 
Screenshot 2022-11-29 at 12 58 10 PM

Screenshot 2022-11-29 at 12 58 48 PM

**Expected behaviour**

It should work without any additional efforts

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes :

- Issue : Closes #9045
- remove whitespace in the name while team creation, Adding webhook, rules, policies and tags 

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :

https://user-images.githubusercontent.com/66266464/204560640-bad4c8cd-a1ab-4571-beee-db1195cd1d23.mov

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/pages/tags/index.tsx [hunk 1]
```diff
@@ -215,7 +215,7 @@ const TagsPage = () => {
   const createCategory = (data: CreateTagCategory) => {
     const errData = onNewCategoryChange(data, true);
     if (!Object.values(errData).length) {
-      createTagCategory(data)
+      createTagCategory({ ...data, name: trimStart(trimEnd(data.name)) })
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/tags/index.tsx:218]: @Ashish8689 , Can we use the `trim` method here?

**Review by chirag-madlani — APPROVED** [review]

File: openmetadata-ui/src/main/resources/ui/src/pages/tags/index.tsx (hunk 1 above)
Comment (Ashish8689) [reply openmetadata-ui/src/main/resources/ui/src/pages/tags/index.tsx]: @Sachin-chaurasiya  updated!

**Review by Sachin-chaurasiya — APPROVED** [review]
