### PR TITLE
#13876: change placement of comment and close button in task approval workflow

### LINKED ISSUE #13876: Placement of Accept Suggestion is creating a confusion between Conversation message and Accept Suggestion
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**

Issue from https://github.com/open-metadata/OpenMetadata/issues/13316#issuecomment-1790470928

The placement of accepting suggestions creates confusion between adding a conversation message and accepting a suggestion action to be same.

**To Reproduce**

Screenshots or steps to reproduce

image

**Expected behavior**

- Need a better UI to differentiate both accordingly.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes:

Fixes #13876

- I worked on changing placement of comment and close button in task approval workflow

Note : 
- We have an issue with the closing task on which the creator himself tries to close it. Issue PR https://github.com/open-metadata/OpenMetadata/issues/17059
- Will unblock the playwright code once the above issue get resolved.

image
image

image
image
image
image
image

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedEditor/ActivityFeedEditor.tsx [hunk 1]
```diff
@@ -33,60 +41,83 @@ export type EditorContentRef = {
...
+      if (!ref) {
+        return;
+      }
+
+      if (isFunction(ref)) {
+        ref(editorRef.current);
+      } else {
+        ref.current = editorRef.current;
+      }
+    }, [ref]);
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedEditor/ActivityFeedEditor.tsx:92]: useImperativeHandle? 
https://github.com/open-metadata/OpenMetadata/blob/d52db7735bc9c00d3d2cfacc8e96cd2cfc8ac492/openmetadata-ui/src/main/resources/ui/src/components/Auth/AppAuthenticators/OidcAuthenticator.tsx#L104

File: openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedEditor/ActivityFeedEditor.tsx [hunk 2]
```diff
@@ -33,60 +41,83 @@ export type EditorContentRef = {
...
+          editAction
+        ) : (
+          <>
+            <SendButton
+              editorValue={editorValue}
+              onSaveHandler={onSaveHandler}
+            />
+            <KeyHelp editorValue={editorValue} />
+          </>
+        )}
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedEditor/ActivityFeedEditor.tsx:117]:
```suggestion
        {editAction ??(
          <>
            <SendButton
              editorValue={editorValue}
              onSaveHandler={onSaveHandler}
            />
            <KeyHelp editorValue={editorValue} />
          </>
        )}
```

**Comment by Ashish8689** [comment]
@chirag-madlani changes made as per comments!

**Review by chirag-madlani — APPROVED** [review]
