### PR TITLE
Fix #6346  UI - convert all cron editor jsx file to tsx file

### LINKED ISSUE #6346: UI - convert all jsx files to tsx file
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
Remove all jsx files and create respective tsx files

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
### Describe your changes :

I worked on converting the cron editor JSX file to a TSX file and added types for the same.

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/common/CronEditor/CronEditor.tsx [hunk 1]
```diff
@@ -33,8 +31,19 @@ import {
...
+  CronOption,
+  CronValue,
+  SelectedDayOption,
+  SelectedHourOption,
+  SelectedYearOption,
+  StateValue,
+  ToDisplay,
+} from './CronEditor.interface';
+
+const getCron = (state: StateValue) => {
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/common/CronEditor/CronEditor.tsx:46]: Let's move this to a util file

File: openmetadata-ui/src/main/resources/ui/src/components/common/CronEditor/CronEditor.tsx [hunk 2]
```diff
@@ -58,23 +66,24 @@ const getCron = (state) => {
       return getMonthCron(selectedMonthOption);
     case 'year':
       return getYearCron(selectedYearOption);
+    case 'hour':
     default:
-      return null;
+      return getHourCron(selectedHourOption);
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/common/CronEditor/CronEditor.tsx:71]: Why we are changing return value for default case

Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/components/common/CronEditor/CronEditor.tsx:71]: @chirag-madlani , we don't need this will revert the change.

Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/components/common/CronEditor/CronEditor.tsx]: Done.

File: openmetadata-ui/src/main/resources/ui/src/components/common/CronEditor/CronEditor.tsx [hunk 3]
```diff
@@ -564,10 +599,10 @@ const CronEditor = (props) => {
             <label htmlFor="ingestionType">Every:</label>
             <select
               className="tw-form-inputs tw-px-3 tw-py-1"
+              data-testid="ingestion-type"
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/common/CronEditor/CronEditor.tsx:602]: `id` should be something related to cron and not ingestion
It's minor but something to keep in mind while assigning it

**Review by chirag-madlani — COMMENTED** [review]
@Sachin-chaurasiya Since it's bigger change let's guard this PR with some unit tests.
Basic and positive will work

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya Since it's bigger change let's guard this PR with some unit tests. Basic and positive will work

Yes, we already have unit tests.

File: openmetadata-ui/src/main/resources/ui/src/components/common/CronEditor/CronEditor.tsx (hunk 3 above)
Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/components/common/CronEditor/CronEditor.tsx:602]: Thanks, @chirag-madlani, I will change that.
