### PR TITLE
UI : Fix ML_Model issues and added version feature in it

### LINKED ISSUE #9284: UI - ML Model feedback
- [ ] Feature descriptions
From sandbox beta:
image

We can edit it, but not suggest as in the general description

- [ ] The models shows no version

image

- [ ] Weird bug on expanding feature sources. They get closed and become unclickable until I refresh the page. Happens in Safari, not on Chrome 

https://user-images.githubusercontent.com/35870520/207520649-3a1086db-0430-49ec-a124-b50e4eb9bbd1.mov

Thanks

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes :

- Issue : Closes #9284
- fix dropdown issue
- fix title issue on edit button
- added version feature in ML_Model

#
### Type of change :

- [x] Bug fix
- [x] Improvement
- [x] New feature

#
### Frontend Preview (Screenshots) :
image
image
image
image

https://user-images.githubusercontent.com/66266464/211567785-72bbd97a-7e04-4507-8575-d93bb53cf283.mov

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/pages/EntityVersionPage/EntityVersionPage.component.tsx [hunk 1]
```diff
@@ -356,6 +370,56 @@ const EntityVersionPage: FunctionComponent = () => {
...
+              .catch((err: AxiosError) => {
+                showErrorToast(
+                  err,
+                  `Error while fetching ${entityFQN} versions`
+                );
+              });
+          })
+
+          .catch((err: AxiosError) => {
+            showErrorToast(err, `Error while fetching ${entityFQN} versions`);
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/pages/EntityVersionPage/EntityVersionPage.component.tsx:417]: Localisation

File: openmetadata-ui/src/main/resources/ui/src/pages/EntityVersionPage/EntityVersionPage.component.tsx [hunk 2]
```diff
@@ -592,6 +656,59 @@ const EntityVersionPage: FunctionComponent = () => {
...
+                    url: '',
+                    activeTitle: true,
+                  },
+                ]);
+                setIsVersionLoading(false);
+              })
+              .catch((err: AxiosError) => {
+                showErrorToast(
+                  err,
+                  `Error while fetching ${entityFQN} version ${version}`
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/pages/EntityVersionPage/EntityVersionPage.component.tsx:698]: Localisation

File: openmetadata-ui/src/main/resources/ui/src/components/MlModelVersion/MlModelVersion.component.tsx [hunk 3]
```diff
@@ -0,0 +1,418 @@
...
+  const [changeDescription, setChangeDescription] = useState<ChangeDescription>(
+    currentVersionData.changeDescription as ChangeDescription
+  );
+  const tabs = [
+    {
+      name: 'Features',
+      icon: {
+        alt: 'features',
+        name: 'icon-schema',
+        title: 'Features',
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/MlModelVersion/MlModelVersion.component.tsx:68]: Localisation

**Review by chirag-madlani — CHANGES_REQUESTED** [review]

**Review by chirag-madlani — APPROVED** [review]
