### PR TITLE
Fixes #15483 : Change Generic to Webhook

### LINKED ISSUE #15483: UI: Alert form destination selection improvements
**Affected module**

UI

**Describe the bug**

- [x] Change the `Generic` option to `Webhook`

Screenshot 2024-03-07 at 3 00 15 PM

- [ ] The selected option labels are not showing properly for the external destination options

Screenshot 2024-03-07 at 3 03 01 PM

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by mohityadav766**
### Describe your changes:

- Rename Generic to Webhook
- Migrated Generic to Webhook

Fixes #15483

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v140/MigrationUtil.java [hunk 1]
```diff
@@ -35,6 +38,32 @@ private MigrationUtil() {
     /* Cannot create object  util class*/
   }
 
+  public static void migrateGenericToWebhook(CollectionDAO collectionDAO) {
+    try {
+      List<String> jsonEventSubscription =
+          collectionDAO.eventSubscriptionDAO().listAllEventsSubscriptions();
+      for (String eventSubscription : jsonEventSubscription) {
```
Comment (TeddyCr) [inline openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v140/MigrationUtil.java:45]: from what I remember postgres returns a `PGObject` and not a `String`.

Comment (mohityadav766) [reply openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v140/MigrationUtil.java:45]: @TeddyCr that is needed only when working with handle and writing custom queries , when you do row.get()
