### PR TITLE
fix(#15924): 'Learn More' links on my-data page have 2 URLS combined as one

### LINKED ISSUE #15924: 'Learn More' links on my-data page have 2 URLS combined as one
**Affected module**
UI Module - http://127.0.0.1:8585/my-data landing page.

**Describe the bug**
The 'Learn More' links in the Following and Recent Views widgets have two URL's combined into one URL.  It's a combination of the FQDN of the server and the correct how-to URL at open-metadata.org.

I stood up a production instance for us today and this issue was noticed. I was able to reproduce it locally using the same Azure SSO authentication. I then tested it with simple Basic Authentication to verify that the URL wasn't added by a value in the .env and even with a simplified .env and basic authentication the problem still exists.  Whatever the server name is, it gets appended in front of the expected URL.  In my local test, the server 'http://127.0.0.1:8585' is appended.

Following points to:
'http://127.0.0.1:8585/https://docs.open-metadata.org/how-to-guides/guide-for-data-users/follow-data-asset'

Recent Views points to:
'http://127.0.0.1:8585/https://docs.open-metadata.org/how-to-guides/data-discovery/discover'

image

image

**To Reproduce**

Install Docker Compose Postgres version: https://github.com/open-metadata/OpenMetadata/releases/download/1.3.2-release/docker-compose-postgres.yml

Start with docker-compose command, create an account, and login.

The following fields are defined in my .env:
POSTGRES_USER
POSTGRES_PASSWORD
AUTHORIZER_CLASS_NAME
AUTHORIZER_REQUEST_FILTER
RSA_PUBLIC_KEY_FILE_PATH
RSA_PRIVATE_KEY_FILE_PATH
JWT_ISSUIE

**Expected behavior**
These links shouldn't append the server FQDN to the How-To Links

**Version:**
 - OS: Debian 12 & Docker 26.0.1 and MacOS 14.4.1 & Docker Desktop 4.28.0
 - OpenMetadata version: 1.3.2

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
### Describe your changes:

Fixes #15924 

I worked on issue #15924 

https://github.com/open-metadata/OpenMetadata/assets/59080942/beb1c1b0-2a9c-428b-b3ce-c8b9954efe29

#
### Type of change:

- [x] Bug fix

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Review by Ashish8689 — DISMISSED** [review]

**Review by ShaileshParmar11 — APPROVED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/MyData/RightSidebar/FollowingWidget.tsx [hunk 1]
```diff
@@ -105,7 +105,7 @@ function FollowingWidget({
                 className="link-title"
                 rel="noreferrer"
                 target="_blank"
-                to={FOLLOW_DATA_ASSET}>
+                to={{ pathname: FOLLOW_DATA_ASSET }}>
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/MyData/RightSidebar/FollowingWidget.tsx:108]: We shouldn't be using Router Link for external links

File: openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/RecentlyViewed/RecentlyViewed.tsx [hunk 2]
```diff
@@ -119,7 +119,7 @@ const RecentlyViewed = ({
                   className="link-title"
                   rel="noreferrer"
                   target="_blank"
-                  to={RECENTLY_VIEWED}>
+                  to={{ pathname: RECENTLY_VIEWED }}>
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/RecentlyViewed/RecentlyViewed.tsx:122]: same

**Review by chirag-madlani — CHANGES_REQUESTED** [review]

**Review by chirag-madlani — APPROVED** [review]
