### PR TITLE
fix(#15364): autogenerate ingestion pipeline name and show displayName

### LINKED ISSUE #15364: autogenerate ingestion pipeline name and show displayName
we are having issues with some users where their Ingestion Pipeline names (currently generated as `serviceName-<random ingestion name>` are too long or contain weird characters.

We should:
- autogenerate Ingestion pipeline name as a random UUID
- we can keep using the `serviceName-<random ingestion name>` as a displayName of the pipeline

This will help us maintain easy rules when mapping this information with Airflow/Argo

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
### Describe your changes:

Fixes #15364 

I worked on the issue #15364 

https://github.com/open-metadata/OpenMetadata/assets/59080942/2edad3fc-c8db-4f86-809d-6647bf2edf72

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/utils/StringsUtils.ts [hunk 1]
```diff
@@ -254,3 +254,21 @@ export const formatJsonString = (jsonString: string, indent = '') => {
...
 };
+export const getUUID = () => {
+  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(
+    /[xy]/g,
+    function (character) {
+      // Generate a random number between 0 and 15
+      const randomNumber = (Math.random() * 16) | 0;
+
+      // If the character in the UUID template is 'x', use the random number.
+      // Otherwise, use the random number ANDed with 0x3 (which gives a number between 0 and 3) ORed with 0x8
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/utils/StringsUtils.ts:265]: Can we pull out callback function to outside and pass it's reference

```
return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(
    /[xy]/g, callbackFunc)
```

Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/utils/StringsUtils.ts:265]: Hello @chirag-madlani, thanks for the feedback, however, can you elaborate on what difference it will make?
