### PR TITLE
Fix issue-3406 wrong toast on UI for editing tests, issue-3452 config value is not getting display in edit mode

### LINKED ISSUE #3406: Getting test added message on UI for editing tests
**Affected module**
UI

**Describe the bug**
Getting test added message on UI for editing tests

**To Reproduce**
- Add a column/table test from data quality tab.
- Edit the added test and click save.
- UI gives`Test columnValuesToBeUnique for last_order_date has been added.` message

https://user-images.githubusercontent.com/83201188/158174233-671b2e08-0e59-42cd-8da3-08c26d64b4c6.mov

**Expected behavior**
Should show proper message as per the actions

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
NA

### LINKED ISSUE #3452: Data quality:- Config value is not getting display in edit mode for columnCount
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI:- Data quality tab

**Describe the bug**
Config value is not getting display in edit mode for columnCount

**To Reproduce**
1. add `tableColumnCountToEqual ` test for table.
2. click on edit button

Screenshots or steps to reproduce
image
image

**Expected behavior**
on click of edit exciting config should be visible

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes :

Closes #3406 
Changed toast message for adding and editing test, also added toast notification for deleting test successfully. to keep consistent ui as we are showing toast notification for edit and add

Closes #3452 
Config value is not getting display in edit mode for `columnCoun`

#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :

#3406

https://user-images.githubusercontent.com/71748675/158559188-541ccea3-7b8e-4e91-ac23-966836d01df4.mov

#3452 

https://user-images.githubusercontent.com/71748675/158558397-b04b5798-33ce-4bd1-8543-7b27443217ab.mov

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

@harshach @vivekratnavel @Sachin-chaurasiya @shahsank3t @darth-coder00

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx [hunk 1]
```diff
@@ -714,6 +723,10 @@ const DatasetDetailsPage: FunctionComponent = () => {
           (d) => d.testCase.tableTestType !== testType
         );
         setTableTestCase(updatedTest);
+        showToast({
+          variant: 'success',
+          body: `Test successfully deleted.`,
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx:728]:
```suggestion
          body: `Test deleted successfully`,
```
Also, move this out to constant and use it from there.

File: openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx [hunk 2]
```diff
@@ -745,6 +758,10 @@ const DatasetDetailsPage: FunctionComponent = () => {
           return d;
         });
         setColumns(updatedColumns);
+        showToast({
+          variant: 'success',
+          body: `Test successfully deleted.`,
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx:763]:
```suggestion
          body: `Test deleted successfully`,
```

**Review by Sachin-chaurasiya — CHANGES_REQUESTED** [review]
Minor changes required

**Review by Sachin-chaurasiya — APPROVED** [review]
