### PR TITLE
fix: use aggregation search instead of suggest query

### LINKED ISSUE #13804: In Advanced Search, Unable to choose [Database == ] String that is not in the truncated dropdown list.
**Affected module**
Advanced Search

**Describe the bug**
I can't search on a selected DB if it isn't in the incomplete Advance Search list.
 
image

**To Reproduce**

After I hit enter, it reverts to:
 
image (1)

**Expected behavior**

The dropdown list for `==` conditions should be complete, not truncated.

(The filtering works fine with the `Contains` condition, but I had to know the exact case sensitive string)

image (2)

**Version:**
 - OS: Windows
 - Python version: Chrome
 - OpenMetadata version: **1.1.6**
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by karanh37**
### Describe your changes:

Fixes #13804 

I worked on ... because ...

https://github.com/open-metadata/OpenMetadata/assets/33024356/65681a96-31ed-41bb-9768-d50545cb2bc8

#
### Type of change:

- [x] Bug fix

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/constants/AdvancedSearch.constants.ts [hunk 1]
```diff
@@ -220,64 +218,28 @@ export const emptyJsonTree: JsonTree = {
...
+
+      return {
+        values: buckets.map((bucket) => ({
+          value: bucket.key,
+          title: bucket.label ?? bucket.key,
+        })),
+        hasMore: false,
+      };
+    });
+    // }
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/constants/AdvancedSearch.constants.ts:242]: nit

**Review by chirag-madlani — APPROVED** [review]
