### PR TITLE
Fix: integrate API for notifications and bots update bot details redirection

### LINKED ISSUE #23225: Data not found / data not available” behavior in UI
I created a bot (see attached screenshots) and noticed inconsistent behavior in the UI:

In the activity field, it displays data not found.

When I click on it, it changes to data not available.

However, when I return to the UI, the table instance does show up correctly.

I also tested with a notification, and the same issue occurs:

The UI shows data not available.

But when I click on it, the notification is displayed correctly.

Steps to Reproduce

Create a bot (or notification).

Check the activity feed.

Notice the inconsistency between the feed message and the actual entity view.

Expected Behavior
The activity feed should display consistent and accurate messages. If the entity exists, it should not show data not found or data not available.

Screenshots
Attached for reference.

Image

Image

Image

https://github.com/user-attachments/assets/9deb5cc3-579f-4b7e-a516-2b76378cbaaf

OMD 1.9.5

### PR DESCRIPTION
**Pull request by anuj-kumary**
Integrated API calls for fetching notifications and bots instead of showing "No data found" on hover in the activity feed. Fixed the redirection issue when clicking on a bot name in the activity feed.

Fixes #23225 

https://github.com/user-attachments/assets/e1fa2b1f-84d1-42b8-8c43-23fa2dee0401

https://github.com/user-attachments/assets/2b2561cb-0a55-4ca1-8cff-5786d80cc0e5

Screenshot 2025-09-12 at 2 36 18 PM
Screenshot 2025-09-12 at 2 28 34 PM
Screenshot 2025-09-12 at 2 20 01 PM
Screenshot 2025-09-12 at 2 19 54 PM
Screenshot 2025-09-12 at 2 19 31 PM

### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/rest/contractAPI.ts [hunk 1]
```diff
@@ -49,7 +49,7 @@ export const listContracts = async (params: ListContractsParams) => {
 
 export const getContract = async (fqn: string) => {
   const response = await APIClient.get<CreateDataContract>(
-    `/data-contracts/${fqn}`
+    `/dataContracts/name/${fqn}`
```
Comment (karanh37) [inline openmetadata-ui/src/main/resources/ui/src/rest/contractAPI.ts:52]: @Ashish8689 can you confirm if this is correct ??

Comment (Ashish8689) [reply openmetadata-ui/src/main/resources/ui/src/rest/contractAPI.ts:52]: yes, this is correct. We aren't using this API for at any place yet.

**Review by chirag-madlani — APPROVED** [review]
