### PR TITLE
Fixes #15686 : Updated Data Insights Report Schema

### LINKED ISSUE #15686: [DataInsights] Update the Data Insights Report Mail Schema
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by mohityadav766**
### Describe your changes:

Fixes <issue-number>

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/DataInsightsReportApp.java [hunk 1]
```diff
@@ -294,6 +294,7 @@ private DataInsightDescriptionAndOwnerTemplate createDescriptionTemplate(
           PERCENTAGE_OF_ENTITIES_WITH_DESCRIPTION_BY_TYPE,
           currentPercentCompleted,
           currentPercentCompleted - previousPercentCompleted,
+          (int) currentCompletedDescription,
```
Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/DataInsightsReportApp.java:297]: should this be a long?

Comment (mohityadav766) [reply openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/DataInsightsReportApp.java:297]: nope it is count of entities with description

**Comment by harshach** [comment]
@mohityadav766 lets merge this into 1.3.2
