### PR TITLE
Fix #3348: UI: Tags dropdown does not render glossary terms consistently

### LINKED ISSUE #3348: UI: Tags dropdown does not render glossary terms consistently
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI
**Describe the bug**
The tags dropdown does not list all the glossary terms correctly. They appear and disappear immediately.

**To Reproduce**
Try to add a tag anywhere and search for glossary term.

**Expected behavior**
It renders all the tags and glossary terms.

### PR DESCRIPTION
**Pull request by vivekratnavel**
### Describe your changes :

See #3348 

#
### Type of change :

- [x] Bug fix

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [ ] I have tagged my reviewers below.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/utils/GlossaryUtils.ts [hunk 1]
```diff
@@ -11,18 +11,46 @@
...
 
 export interface GlossaryTermTreeNode {
   children?: GlossaryTermTreeNode[];
   fullyQualifiedName: string;
   name: string;
 }
 
+export const fetchGlossaryTerms = (): Promise<FormattedGlossaryTermData[]> => {
+  return new Promise<FormattedGlossaryTermData[]>((resolve, reject) => {
+    searchData(WILD_CARD_CHAR, 1, 1000, '', '', '', SearchIndex.GLOSSARY)
```
Comment (darth-coder00) [inline openmetadata-ui/src/main/resources/ui/src/utils/GlossaryUtils.ts:37]: Should be `''` instead of `WILD_CARD_CHAR` as this will hit api with `***` instead of just `*`

File: openmetadata-ui/src/main/resources/ui/src/components/tags/tags.tsx [hunk 2]
```diff
@@ -31,7 +31,6 @@ const Tags: FunctionComponent<TagProps> = ({
   const baseStyle = tagStyles.base;
   const layoutStyles = tagStyles[type];
   const textBaseStyle = tagStyles.text.base;
-  const textLayoutStyles = tagStyles.text[type] || tagStyles.text.default;
```
Comment (darth-coder00) [inline openmetadata-ui/src/main/resources/ui/src/components/tags/tags.tsx:34]: Why did we remove this? This will affect spacing everywhere

**Review by darth-coder00 — APPROVED** [review]
Few comments to be taken care of
Nothing blocker, can fix this in next patch

**Comment by darth-coder00** [comment]
@vivekratnavel We can merge the PR once Maven CI check passes
