### PR TITLE
fix(ui): column name overlapping in entity table

### LINKED ISSUE #14003: OM-1.2.0 - Long column names are breaking the UI
When i have a long column name like 
"bkg_original_selling_amount", it is overlapping with the datatype of the column.

Shared the screenshot

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes:

Fixes #14003

- I worked on fixing the column name overlapping issue  in entity tables

image
image
image
image
image

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.component.tsx [hunk 1]
```diff
@@ -421,19 +421,25 @@ const DashboardDetails = ({
...
 
           return record.sourceUrl ? (
-            <Typography.Link href={record.sourceUrl} target="_blank">
-              <Space>
-                {chartName}
-                <ExternalLinkIcon height={14} width={14} />
-              </Space>
-            </Typography.Link>
+            <div className="d-flex items-center">
+              <Typography.Link href={record.sourceUrl} target="_blank">
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.component.tsx:431]: Is it external links?

**Review by chirag-madlani — APPROVED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.component.tsx (hunk 1 above)
Comment (Ashish8689) [reply openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.component.tsx:431]: yes, it is external!
