### PR TITLE
Fix: #21276 Only 3 Comments Shown by Default in Incident View

### LINKED ISSUE #21276: Only 3 Comments Shown by Default in Incident View
**Affected module**
UI

**Describe the bug**
In OpenMetadata version 1.7.0, when viewing an incident, only the first three comments are initially visible. Although more comments exist, they are not displayed until a user interacts with the page—for example, by clicking a reaction (like 👍 :) on a comment. This appears to trigger a UI refresh that then loads the full list of comments. This behavior is misleading and may cause users to think comments are missing.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
All comments should be visible immediately when opening an incident, without needing to interact with reactions or trigger a UI refresh manually.

**Version:**
 - OS: Linux
 - Python version: 3.10
 - OpenMetadata version: 1.7.0
 - OpenMetadata Ingestion package version:  1.7.0

https://github.com/user-attachments/assets/f7359a08-de15-43e0-b71e-ec1f874d01b1

**Additional context**

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes:

Fixes #21276

- Add functionality to load comments of the post via lazy loading
- Fix flickering while switching tasks.
- Fix re-rending issue, if the user clicks on an active task/feed/conversation
- Added playwright test

https://github.com/user-attachments/assets/4f4b71fa-bf7e-4c5f-9076-5e2c0c06adf2

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Review by karanh37 — DISMISSED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCardNew/ActivityFeedcardNew.component.tsx [hunk 1]
```diff
@@ -183,6 +183,38 @@ const ActivityFeedCardNew = ({
     setShowFeedEditor(false);
   };
 
+  const renderPosts = useMemo(() => {
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCardNew/ActivityFeedcardNew.component.tsx]: It's already rendered so we can call it `posts`

File: openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedProvider/ActivityFeedProvider.tsx [hunk 2]
```diff
@@ -90,22 +96,41 @@ const ActivityFeedProvider = ({ children, user }: Props) => {
...
+  }, []);
+
+  const fetchPostsFeed = useCallback(async (active: Thread) => {
+    // If the posts count is greater than the page count, fetch the posts
+    if (
+      active?.id &&
+      active?.postsCount &&
+      active?.postsCount > POST_FEED_PAGE_COUNT &&
+      active?.posts?.length !== active?.postsCount
+    ) {
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedProvider/ActivityFeedProvider.tsx]: We can convert it to optional chaining

**Review by chirag-madlani — APPROVED** [review]
