### PR TITLE
Fixes #13987 database schema search pagination

### LINKED ISSUE #13987: Pagination buttons are disabled when database schema serach is used
**Affected module**
UI

**Describe the bug**
Database schema pagination is disabled when search is used  

**To Reproduce**

https://github.com/open-metadata/OpenMetadata/assets/29060284/051594f4-a4d6-4c99-89b2-26340da490d2

Type something in the schema search box, the pagination button will be grayed out.

**Expected behavior**
In databases schemas page pagination is possible when a search is used 

**Version:**
 - Python version:
 - OpenMetadata version: [1.2.0 / 1.2.1]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by dechoma**
### Describe your changes:

Fixes #13987

I worked on ... because ...

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/Database/DatabaseSchema/DatabaseSchemaTable/DatabaseSchemaTable.tsx [hunk 1]
```diff
@@ -128,12 +128,14 @@ export const DatabaseSchemaTable = () => {
...
-      if (cursorType) {
+      if (searchValue) {
+        searchSchema(searchValue, currentPage);
+      } else if (cursorType) {
         fetchDatabaseSchema({ [cursorType]: paging[cursorType] });
       }
       handlePageChange(currentPage);
     },
-    [paging, fetchDatabaseSchema]
+    [paging, fetchDatabaseSchema, searchSchema]
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Database/DatabaseSchema/DatabaseSchemaTable/DatabaseSchemaTable.tsx:138]:
```suggestion
    [paging, fetchDatabaseSchema, searchSchema, searchValue]
```

**Review by chirag-madlani — CHANGES_REQUESTED** [review]

**Review by chirag-madlani — APPROVED** [review]

**Comment by chirag-madlani** [comment]
Thanks @dechoma 🚀
