### PR TITLE
UI : Dbt Workflow Improvement

### LINKED ISSUE #9382: DBT Workflow UI Improvements
**Affected module**
UI

**Describe the bug**

- [ ]  now since DBT ingestion has a separate workflow, having option of no config source does not make sense here

image

- [ ] catalog file is now not a required field as per json schema, so we should remove it as required from local & http source ([dbt local](https://github.com/open-metadata/OpenMetadata/blob/2abe40f08c7afcb52acbf62d074307056d9f07e7/openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dbtconfig/dbtLocalConfig.json#L31), [dbt http](https://github.com/open-metadata/OpenMetadata/blob/2abe40f08c7afcb52acbf62d074307056d9f07e7/openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dbtconfig/dbtHttpConfig.json#L31))

image

image

- [ ] `Http` in the title should be in caps 

image

- [ ] `Dbt` in add dbt workflow should be in caps 

image

- [ ] required filed in DBT GCS  source is not as per the json schema, all the fields in gcs credential values should not be required as user might want to use ADC for authentication (ref [gsc json schema](https://github.com/open-metadata/OpenMetadata/blob/2abe40f08c7afcb52acbf62d074307056d9f07e7/openmetadata-spec/src/main/resources/json/schema/security/credentials/gcsCredentials.json#L21))

image

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes :

- Issue : Closes #9382 
- Remove the required type from DBT catalog file / http path field
- Capitalize the DBT name
- Remove the required type from the DBT GCS config section
- added redirect to  it's service type once deleting any Service

#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :
image

image
image

image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui 
 @open-metadata/ingestion

### CODE REVIEW

**Review by ulixius9 — APPROVED** [review]
UI changes, LGTM!

File: openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx [hunk 1]
```diff
@@ -276,6 +276,30 @@ const Ingestion: React.FC<IngestionProps> = ({
     );
   };
 
+  const getAddIngestionName = (type: PipelineType): string => {
+    let name;
+    switch (type) {
+      case PipelineType.ElasticSearchReindex:
+        name = `${t('label.add')} ${startCase(type)}`;
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx:283]: We shouldn't use `startCase(type)`
If we choose different lang it will still show English or you can say default, Use localisation here too

File: openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx [hunk 2]
```diff
@@ -276,6 +276,30 @@ const Ingestion: React.FC<IngestionProps> = ({
...
+
+        break;
+
+      case PipelineType.Dbt:
+        name = t('label.add-workflow-ingestion', {
+          workflow: upperCase(type),
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx:289]: same

File: openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx [hunk 3]
```diff
@@ -276,6 +276,30 @@ const Ingestion: React.FC<IngestionProps> = ({
...
+        });
+
+        break;
+
+      default:
+        name = t('label.add-workflow-ingestion', {
+          workflow: startCase(type),
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx:296]: same

File: openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTGCSConfig.tsx [hunk 4]
```diff
@@ -358,7 +337,7 @@ export const DBTGCSConfig: FunctionComponent<Props> = ({
         <label
           className="tw-block tw-form-label tw-mb-1"
           htmlFor="gcs-cred-path">
-          {requiredField('GCS Credentials Path')}
+          GCS Credentials Path
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTGCSConfig.tsx:340]: We make all these field as non-required?

File: openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json [hunk 5]
```diff
@@ -309,6 +309,7 @@
     "detail-plural": "Details",
     "ingestion": "Ingestion",
     "add-workflow-ingestion": "Add {{workflow}} Ingestion",
+    "ingestion-workflow-action": "{{action}} {{workflow}} Ingestion",
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json:312]:
```suggestion
    "edit-workflow-action": "edit {{workflow}} Ingestion",
```
as Add one is just present above we can have it as Edit one

**Review by chirag-madlani — CHANGES_REQUESTED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTGCSConfig.tsx (hunk 4 above)
Comment (Ashish8689) [reply openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTGCSConfig.tsx:340]: @chirag-madlani yes, we do as per new schema!

**Comment by Ashish8689** [comment]
@chirag-madlani changes made as per comments!

**Review by chirag-madlani — DISMISSED** [review]

**Review by chirag-madlani — APPROVED** [review]
