### PR TITLE
Fix #17929 : Fix team export issue

### LINKED ISSUE #17929: Issue While Exporting Teams with Dot Characters in Name
**Affected module**
Backend

**Describe the bug**
when a Team is created with a dot (for example: my.team), it creates the team correctly but when we want to export all the teams, it appears an error saying that the team with dot in the name does not exist.

**To Reproduce**

Screenshots or steps to reproduce
image

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by sonika-shah**
### Describe your changes:

Fixes #17929

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java [hunk 1]
```diff
@@ -3255,7 +3255,7 @@ default List<String> listAfter(ListFilter filter, int limit, String afterName, S
       String condition = filter.getCondition();
       if (parentTeam != null) {
         // validate parent team
-        Team team = findEntityByName(parentTeam, filter.getInclude());
+        Team team = findEntityByName(FullyQualifiedName.quoteName(parentTeam), filter.getInclude());
```
Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java:3258]: We need to pass FQN of team not name

**Review by harshach — CHANGES_REQUESTED** [review]

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java (hunk 1 above)
Comment (harshach) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java:3258]: shouldn't we passing fqn instead of name there?

**Review by ShaileshParmar11 — DISMISSED** [review]

**Review by Ashish8689 — APPROVED** [review]

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java (hunk 1 above)
Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java]: updated with use of fqn

**Review by chirag-madlani — APPROVED** [review]

**Review by mohityadav766 — APPROVED** [review]
