### PR TITLE
Fix #3080: Activity Feed: Blank feed on my-data page for updating user's role or team

### LINKED ISSUE #3080: Activity Feed: Blank feed on my-data page for updating user's role or team
**Affected module**
UI

**Describe the bug**
Blank feed on my-data page for updating users. Also getting versions.

**To Reproduce**

Screenshot 2022-03-02 at 6 18 57 PM

**Expected behavior**
Not sure if an empty feed is intentional.
Not sure where to check the versioning for users.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
NA

### PR DESCRIPTION
**Pull request by vivekratnavel**
### Describe your changes :

See #3080 

#
### Type of change :

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [ ] I have tagged my reviewers below.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/events/ChangeEventHandler.java [hunk 1]
```diff
@@ -72,10 +72,16 @@ public Void process(ContainerRequestContext requestContext, ContainerResponseCon
 
         // Add a new thread to the entity for every change event
         // for the event to appear in activity feeds
-        List<Thread> threads = getThreads(responseContext, changeEvent);
-        if (threads != null) {
-          for (var thread : threads) {
-            feedDao.create(thread);
+        // Skip creating threads for user or team related changes for now
+        if (!Entity.USER.equals(changeEvent.getEntityType()) && !Entity.TEAM.equals(changeEvent.getEntityType())) {
```
Comment (mithmatt) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/events/ChangeEventHandler.java:76]: Can we maintain a list of entities in Entity.java that we can grab with `shouldDisplayEntityChangeOnFeed` or something similar?

We need to avoid user, team, role, bot, policy

Comment (vivekratnavel) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/events/ChangeEventHandler.java:76]: Sounds good. I will work on updating the patch.

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java [hunk 2]
```diff
@@ -106,6 +106,11 @@
   public static final String AIRFLOW_PIPELINE = "airflowPipeline";
   public static final String WEBHOOK = "webhook";
 
+  //
+  // List of entities whose changes should not be published to the Activity Feed
+  //
+  public static final List<String> ACTIVITY_FEED_EXCLUDED_ENTITIES = List.of(USER, TEAM, ROLE, POLICY, BOTS);
```
Comment (mithmatt) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java:112]: Minor: this could be a Set/HashSet

**Review by mithmatt — APPROVED** [review]

**Comment by vivekratnavel** [comment]
Test failure is not related

```
2022-03-04T03:01:20.4128731Z [ERROR] Failures: 
2022-03-04T03:01:20.4158135Z [ERROR]   WebhookResourceTest.put_updateEndpointURL:180->EntityResourceTest.deleteEntity:1414->EntityResourceTest.deleteEntity:1424 Expected org.apache.http.client.HttpResponseException to be thrown, but nothing was thrown.
```
