### PR TITLE
Fixed Add Partition Setting in UI for Profiler #8624

### LINKED ISSUE #8624: Add Partition Setting in UI for Profiler
## Context
#8623 introduce the possibility to profile/test tables based on partition configuration. We need to allow user to set up this config from the frontend.

## Proposed solution
We'll need to send the below payload to configure partitioning to the following endpoint `http://localhost:8585/api/v1/tables/{id}/tableProfilerConfig`
```
{
    "partitioning": {
        "enablePartitioning": true,
        "partitionColumnName": "order_date",
        "partitionIntervalType": "TIME-UNIT",
        "partitionInterval": 5,
        "partitionIntervalUnit": "YEAR"
    }
}
```
All fields are required. Below is the JSON Schema definition and their accepted values for each key. Disregard `partitionValues ` for now, this is for support in future releases.

```
    "partitionProfilerConfig": {
       "description": "This schema defines the partition configuration used by profiler.",
       "type": "object",
       "javaType": "org.openmetadata.schema.type.PartitionProfilerConfig",
       "properties": {
         "enablePartitioning": {
           "description": "whether to use partition",
           "type": "boolean",
           "default": false
         },
         "partitionColumnName": {
           "description": "name of the column to use for the partition",
           "type": "string"
         },
         "partitionIntervalType": {
           "description": "type of partition interval",
           "type": "string",
           "enum": ["TIME-UNIT", "INGESTION-TIME"]
         },
         "partitionInterval": {
           "description": "The interval to use for the partitioning",
           "type": "integer"
         },
         "partitionIntervalUnit": {
           "description": "unit used for the partition interval",
           "type": "string",
           "enum": ["YEAR", "MONTH", "DAY", "HOUR"]
         },
         "partitionValues": {
           "description": "unit used for the partition interval",
           "type": "array"
         }
       }
     }
```

A few elements to note:
1. This setting should be placed under the "Enable Column Profile", we should have "Enable Partitioning" section with the keys of the config ("enablePartitioning", "partitionColumnName", "partitionIntervalType", "partitionInterval", "partitionIntervalUnit")
2. "partitionColumnName" should be a list of column with one of the following data type "DATE", "DATETIME", "TIMESTAMP", "TIMESTAMPZ". The user should be able to only choose ONE. If no column with this type is present partitioning config should be disabled.
Screenshot 2022-11-09 at 5 43 15 PM

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes :

Add Partition Setting in UI for Profiler
Closes #8624

#
### Type of change :

- [x] Improvement
- [x] New feature

#
### Frontend Preview (Screenshots) :
image

https://user-images.githubusercontent.com/71748675/201340806-95748cb3-6130-4fad-9c5f-df1fa9b9a87c.mov

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/ProfilerSettingsModal.tsx [hunk 1]
```diff
@@ -82,8 +98,43 @@ const ProfilerSettingsModal: React.FC<ProfilerSettingsModalProps> = ({
...
+      value,
+      label: value,
+    }));
+  }, []);
+  const intervalUnitOptions = useMemo(() => {
+    return Object.values(PartitionIntervalUnit).map((value) => ({
+      value,
+      label: value,
+    }));
+  }, []);
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/ProfilerSettingsModal.tsx:134]: we can have them in utils or constant files

Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/ProfilerSettingsModal.tsx]: updated!

**Review by chirag-madlani — APPROVED** [review]
