### PR TITLE
fixed issue-5779 Add manage tab to soft deleted entity

### LINKED ISSUE #5779: Added manage tab to soft deleted entity
- add the manage tab to a soft-deleted entity, so the user can permanently delete any entity
- change the terms of the delete section
   - soft delete => delete
   - hard delete => Permanent delete

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes :

I worked on the adding manage tab to the soft-deleted entity so the admin can delete it permanently 
Closes #5779 
#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :

https://user-images.githubusercontent.com/71748675/176633621-ff98817e-9362-4110-8657-5c77e30e508d.mov

image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/common/DeleteWidget/DeleteWidget.tsx [hunk 1]
```diff
@@ -42,7 +42,7 @@ const DeleteWidget = ({
     useState<typeof ENTITY_DELETE_STATE>(ENTITY_DELETE_STATE);
 
   const prepareDeleteMessage = (softDelete = false) => {
-    const softDeleteText = `Soft deleting will deactivate the ${entityName}. This will disable any discovery, read or write operations on ${entityName}`;
+    const softDeleteText = `Delete will deactivate the ${entityName}. This will disable any discovery, read or write operations on ${entityName}`;
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/components/common/DeleteWidget/DeleteWidget.tsx:45]:
```suggestion
    const softDeleteText = `Delete will deactivate the ${entityType} ${entityName}. This will disable any discovery, read or write operations on ${entityName}`;
```

File: openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx [hunk 2]
```diff
@@ -612,11 +612,11 @@ export const getEntityName = (entity?: EntityReference) => {
 
 export const getEntityDeleteMessage = (entity: string, dependents: string) => {
   if (dependents) {
-    return `Deleting this ${getTitleCase(
+    return `Permanently deleting this ${getTitleCase(
       entity
     )} will permanently remove its metadata, as well as the metadata of ${dependents} from OpenMetadata.`;
   } else {
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx:618]:
```suggestion
    return `Permanently deleting this ${getTitleCase(
      entity
    )} will remove its metadata, as well as the metadata of ${dependents} from OpenMetadata permanently.`;
  } else {
```

File: openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx [hunk 3]
```diff
@@ -612,11 +612,11 @@ export const getEntityName = (entity?: EntityReference) => {
...
-    return `Deleting this ${getTitleCase(
+    return `Permanently deleting this ${getTitleCase(
       entity
     )} will permanently remove its metadata from OpenMetadata.`;
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx:621]:
```suggestion
    return `Permanently deleting this ${getTitleCase(
      entity
    )} will remove its metadata from OpenMetadata permanently.`;
```
