### PR TITLE
fix #12815: user not able to create ingestion pipeline with isOwner() or matchTeam() conditions

### LINKED ISSUE #12815: Policy rule bug when adding services (isOwner(), matchTeam())
## Affected module

Permission granting: backend and ingestion framework, but probably not the UI.

## Describe the bug

Conditions on policies do not seem to be working properly when setting up a new service. Our goal was to allow people to:
✅ Add services freely
✅ Change ownership on services they own
🚫 Test connections (unsuccessful with conditions applied)
🚫 See ingestion tab (unsuccessful when team owns service)
🚫 Edit/add ingestion (unsuccessful: only works when user owns service and has all operations on `Ingestion pipeline` resource)

Right now, non-admin users are blocked from onboarding their services to OpenMetadata as they cannot create ingestions for these unless we grant them admin rights – which is a security concern and beats the purpose of having policies. Conditions in rules do not seem to be working properly especially the `isOwner()` and `matchTeam()` ones.

## To Reproduce

You need two types of users: one admin (who can set up policies etc.) and one Data Consumer (who can test said policies). The steps to reproduce are below:

1. Set up new rule for adding services and add it to Data Consumer policy
image

2. Non-admin should add a database service (`tmp_database`)

3. Set up new rule within Data Consumer policy for changing service (it can contain the `EditOwner` operation only):

image

4. Set up `tmp_team`

5. Add non-admin user to `tmp_team`

6. Non-admin should change owner of `tmp_database` from themselves to `tmp_team`

7. ⚠️ At this point – once the `tmp_team` owns the database service – no matter what rule is assigned to the Data Consumer policy, the non-admin user won't be able to see the _Ingestions_ tab on the UI, and they won't have permissions to create ingestions.

### Scenarios

**Scenario 1**
image
- Non-admin user can test connection
- Non-admin user cannot see Ingestions tab (and ingestions)
- Non-admin user cannot set up an ingestion

**Scenario 2**

image
image
- Either of the `matchTeam()` or `isOwner()` conditions seem to prevent many actions for non-admin user (actions that were previously working
- Non-admin user cannot test connection
- Non-admin user cannot see Ingestions tab (and ingestions)
- Non-admin user cannot set up an ingestion

**Scenario 3**

Non-admin user is set as owner for the database service
- Non-admin user can see ingestion tab
- Non-admin user can add ingestion given a rule allows Data Consumers to work with _Ingestion Pipeline_ resources
- However, if we add the isOwner() condition to the same rule for _Ingestion Pipeline_ resource, user cannot set up ingestions anymore

### Overall

So in summary, non-admin users cannot set up ingestions for resources their teams own at all, and conditions on the rules seem not to be working properly. This is a serious blocker in adoption for us as we are encouraging teams to onboard their datasets to OpenMetadata but they are blocked from doing so unless we make them admins.

## Expected behavior

Conditions should be working
- `isOwner()` should allow users permissions for resources they own (support [conversation](https://openmetadata.slack.com/archives/C02B6955S4S/p1680178940144119?thread_ts=1680177375.549479&cid=C02B6955S4S))
- `matchTeam()` should allow users permissions for resources their teams own ([documentation](https://docs.open-metadata.org/v1.0.0/main-concepts/metadata-standard/schemas/entity/policies/accesscontrol/rule): "_Returns true if the user and the resource belongs to the team hierarchy where this policy is attached. This allows restricting permissions to a resource to the members of the team hierarchy._")

## Version:
Using 1.1.0 for OM and ingestion.

## Additional context
The issue has been raised for a previous version 2 weeks ago in the OM Slack [#support](https://openmetadata.slack.com/archives/C02B6955S4S/p1690265676431209) channel.

### PR DESCRIPTION
**Pull request by aniketkatkar97**
### Describe your changes:

Fixes #12815 

I worked on 
- [x] UI changes to show the ingestion tab on the service details page for users who are part of the service owner team

https://github.com/open-metadata/OpenMetadata/assets/51777795/3b1a23ef-b2bd-469c-a16e-0ea434329b70

#
### Type of change:

- [x] Bug fix

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx [hunk 1]
```diff
@@ -915,7 +915,12 @@ const ServiceDetailsPage: FunctionComponent = () => {
   const tabs: TabsProps['items'] = useMemo(() => {
     const tabs = [];
     const isOwner = AppState.userDetails.id === serviceDetails?.owner?.id;
-    const showIngestionTab = Boolean(isOwner || isAdminUser);
+    const isUserInOwnerTeam = AppState.userDetails.teams?.find(
+      (team) => team.id === serviceDetails?.owner?.id
+    );
+    const showIngestionTab = Boolean(
+      isUserInOwnerTeam || isOwner || isAdminUser
+    );
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx:923]:
```suggestion
    const userOwnsService = AppState.userDetails.id === serviceDetails?.owner?.id;
const userInOwnerTeam = AppState.userDetails.teams?.some(
  (team) => team.id === serviceDetails?.owner?.id
);
const showIngestionTab = userInOwnerTeam || userOwnsService || isAdminUser;

```

**Review by karanh37 — DISMISSED** [review]

File: openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx [hunk 2]
```diff
@@ -914,8 +914,15 @@ const ServiceDetailsPage: FunctionComponent = () => {
...
     const tabs = [];
-    const isOwner = AppState.userDetails.id === serviceDetails?.owner?.id;
-    const showIngestionTab = Boolean(isOwner || isAdminUser);
+    const userOwnsService =
+      AppState.userDetails.id === serviceDetails?.owner?.id;
+
+    const userInOwnerTeam =
+      AppState.userDetails.teams?.some(
+        (team) => team.id === serviceDetails?.owner?.id
+      ) ?? false;
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx:923]:
```suggestion
      Boolean(AppState.userDetails.teams?.some(
        (team) => team.id === serviceDetails?.owner?.id
      ) );
```

**Review by Sachin-chaurasiya — APPROVED** [review]

**Review by karanh37 — APPROVED** [review]
