### PR TITLE
Fix(UI)#7173: Fixed issue where soft deleted tables were showing on schema details page

### LINKED ISSUE #7173: Do not show soft deleted tables on the UI
Tables that are soft deleted should not appear on the schema:

image

Request URL: http://localhost:8585/api/v1/databaseSchemas/name/snow.OMTESTDB.INFORMATION_SCHEMA?fields=owner,tables,usageSummary

```
{"id":"9996c60f-9be2-45ed-a0da-0eae19a1dd77","name":"INFORMATION_SCHEMA","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA","version":0.1,"updatedAt":1662132120650,"updatedBy":"pere-om-sa","href":"http://localhost:8585/api/v1/databaseSchemas/9996c60f-9be2-45ed-a0da-0eae19a1dd77","service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://localhost:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","database":{"id":"20feab24-61b7-4807-8c66-c16a573e59a1","type":"database","name":"OMTESTDB","fullyQualifiedName":"snow.OMTESTDB","deleted":false,"href":"http://localhost:8585/api/v1/databases/20feab24-61b7-4807-8c66-c16a573e59a1"},"tables":[{"id":"6d89291b-4c44-423c-8a13-d8c770c84e2d","type":"table","name":"APPLICABLE_ROLES","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.APPLICABLE_ROLES","description":"The roles that can be applied to the current user.","deleted":true,"href":"http://localhost:8585/api/v1/tables/6d89291b-4c44-423c-8a13-d8c770c84e2d"},{"id":"e6daff0a-d8fa-4a0e-aac8-95c3c03d1c9f","type":"table","name":"COLUMNS","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.COLUMNS","description":"The columns of tables defined in this database that are accessible to the current user's role.","deleted":true,"href":"http://localhost:8585/api/v1/tables/e6daff0a-d8fa-4a0e-aac8-95c3c03d1c9f"},{"id":"28e660f7-36ef-4257-aa26-f944a585d9b3","type":"table","name":"DATABASES","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.DATABASES","description":"The databases that are accessible to the current user's role.","deleted":true,"href":"http://localhost:8585/api/v1/tables/28e660f7-36ef-4257-aa26-f944a585d9b3"},{"id":"e9338296-1403-4f14-965b-91a0906cdd0c","type":"table","name":"ENABLED_ROLES","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.ENABLED_ROLES","description":"The roles that are enabled to the current user.","deleted":true,"href":"http://localhost:8585/api/v1/tables/e9338296-1403-4f14-965b-91a0906cdd0c"},{"id":"d18bce9f-1af5-4c7c-ab5d-f64e0bbdb4c9","type":"table","name":"EXTERNAL_TABLES","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.EXTERNAL_TABLES","description":"The external tables defined in this database that are accessible to the current user's role.","deleted":true,"href":"http://localhost:8585/api/v1/tables/d18bce9f-1af5-4c7c-ab5d-f64e0bbdb4c9"},{"id":"0d2eb7b1-d777-4b0c-a99a-80f4402bba85","type":"table","name":"FILE_FORMATS","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.FILE_FORMATS","description":"The file formats defined in this database that are accessible to the current user's role.","deleted":true,"href":"http://localhost:8585/api/v1/tables/0d2eb7b1-d777-4b0c-a99a-80f4402bba85"},{"id":"abb77b63-aec0-41e5-91c0-b3f3f5c1a28d","type":"table","name":"FUNCTIONS","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.FUNCTIONS","description":"The user-defined functions defined in this database that are accessible to the current user's role.","deleted":true,"href":"http://localhost:8585/api/v1/tables/abb77b63-aec0-41e5-91c0-b3f3f5c1a28d"},{"id":"39eb623d-ac7c-4a7e-9f13-0d312db56031","type":"table","name":"INFORMATION_SCHEMA_CATALOG_NAME","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.INFORMATION_SCHEMA_CATALOG_NAME","description":"Identifies the database (or catalog, in SQL terminology) that contains the information_schema","deleted":true,"href":"http://localhost:8585/api/v1/tables/39eb623d-ac7c-4a7e-9f13-0d312db56031"},{"id":"2fd323c0-cd4e-4de8-bc92-4b97d2341280","type":"table","name":"LOAD_HISTORY","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.LOAD_HISTORY","description":"The loading information of the copy command","deleted":true,"href":"http://localhost:8585/api/v1/tables/2fd323c0-cd4e-4de8-bc92-4b97d2341280"},{"id":"7f793542-1085-4e6a-b1b5-93e3e9a35409","type":"table","name":"OBJECT_PRIVILEGES","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.OBJECT_PRIVILEGES","description":"The privileges on all objects defined in this database that are accessible to the current user's role.","deleted":true,"href":"http://localhost:8585/api/v1/tables/7f793542-1085-4e6a-b1b5-93e3e9a35409"},{"id":"54413064-2fba-4c22-baf5-f242a76ace55","type":"table","name":"PACKAGES","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.PACKAGES","description":"Available packages in current account","deleted":true,"href":"http://localhost:8585/api/v1/tables/54413064-2fba-4c22-baf5-f242a76ace55"},{"id":"e691cf35-5701-4ec4-bd98-99f9bd5eb18a","type":"table","name":"PIPES","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.PIPES","description":"The pipes defined in this database that are accessible to the current user's role.","deleted":true,"href":"http://localhost:8585/api/v1/tables/e691cf35-5701-4ec4-bd98-99f9bd5eb18a"},{"id":"5ebed3b2-c82b-452e-ab6d-963b305fdfb7","type":"table","name":"PROCEDURES","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.PROCEDURES","description":"The stored procedures defined in this database that are accessible to the current user's role.","deleted":true,"href":"http://localhost:8585/api/v1/tables/5ebed3b2-c82b-452e-ab6d-963b305fdfb7"},{"id":"62613af8-5b77-4181-b9e5-1ef1abfa5a58","type":"table","name":"REFERENTIAL_CONSTRAINTS","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS","description":"Referential Constraints in this database that are accessible to the current user","deleted":true,"href":"http://localhost:8585/api/v1/tables/62613af8-5b77-4181-b9e5-1ef1abfa5a58"},{"id":"3b968d91-da61-4aa9-a1ef-ade663c2218e","type":"table","name":"REPLICATION_DATABASES","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.REPLICATION_DATABASES","description":"The databases for replication that are accessible to the current user's role.","deleted":true,"href":"http://localhost:8585/api/v1/tables/3b968d91-da61-4aa9-a1ef-ade663c2218e"},{"id":"eec7db93-7fb8-45da-b5dc-cb6063253d93","type":"table","name":"REPLICATION_GROUPS","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.REPLICATION_GROUPS","description":"The replication groups that are accessible to the current user's role.","deleted":true,"href":"http://localhost:8585/api/v1/tables/eec7db93-7fb8-45da-b5dc-cb6063253d93"},{"id":"3f7b0973-222e-4138-8668-e3d98b89e512","type":"table","name":"SCHEMATA","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.SCHEMATA","description":"The schemas defined in this database that are accessible to the current user's role.","deleted":true,"href":"http://localhost:8585/api/v1/tables/3f7b0973-222e-4138-8668-e3d98b89e512"},{"id":"c1841e14-2d68-429a-a847-02fc54eeb314","type":"table","name":"SEQUENCES","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.SEQUENCES","description":"The sequences defined in this database that are accessible to the current user's role.","deleted":true,"href":"http://localhost:8585/api/v1/tables/c1841e14-2d68-429a-a847-02fc54eeb314"},{"id":"8ab27d73-e84b-477d-94fb-9592f7d26a07","type":"table","name":"STAGES","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.STAGES","description":"Stages in this database that are accessible by the current user's role","deleted":true,"href":"http://localhost:8585/api/v1/tables/8ab27d73-e84b-477d-94fb-9592f7d26a07"},{"id":"a0438900-6e8f-47bc-93f9-43a4c6783158","type":"table","name":"TABLES","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.TABLES","description":"The tables defined in this database that are accessible to the current user's role.","deleted":true,"href":"http://localhost:8585/api/v1/tables/a0438900-6e8f-47bc-93f9-43a4c6783158"},{"id":"19767859-c4fb-4579-9633-c69dc04290b0","type":"table","name":"TABLE_CONSTRAINTS","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.TABLE_CONSTRAINTS","description":"Constraints defined on the tables in this database that are accessible to the current user","deleted":true,"href":"http://localhost:8585/api/v1/tables/19767859-c4fb-4579-9633-c69dc04290b0"},{"id":"2ea7c6cb-7011-44d3-b379-0c79a573a19a","type":"table","name":"TABLE_PRIVILEGES","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.TABLE_PRIVILEGES","description":"The privileges on tables defined in this database that are accessible to the current user's role.","deleted":true,"href":"http://localhost:8585/api/v1/tables/2ea7c6cb-7011-44d3-b379-0c79a573a19a"},{"id":"00c09910-7dad-415a-888b-3f0841e645cd","type":"table","name":"TABLE_STORAGE_METRICS","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.TABLE_STORAGE_METRICS","description":"All tables within an account, including expired tables.","deleted":true,"href":"http://localhost:8585/api/v1/tables/00c09910-7dad-415a-888b-3f0841e645cd"},{"id":"f7f5979c-d378-4958-8859-71f8747a8e5f","type":"table","name":"USAGE_PRIVILEGES","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.USAGE_PRIVILEGES","description":"The usage privileges on sequences defined in this database that are accessible to the current user's role.","deleted":true,"href":"http://localhost:8585/api/v1/tables/f7f5979c-d378-4958-8859-71f8747a8e5f"},{"id":"561640b3-aacd-41d7-aaf1-4fa0d9abd1fd","type":"table","name":"VIEWS","fullyQualifiedName":"snow.OMTESTDB.INFORMATION_SCHEMA.VIEWS","description":"The views defined in this database that are accessible to the current user's role.","deleted":true,"href":"http://localhost:8585/api/v1/tables/561640b3-aacd-41d7-aaf1-4fa0d9abd1fd"}],"usageSummary":{"dailyStats":{"count":0,"percentileRank":0.0},"weeklyStats":{"count":0,"percentileRank":0.0},"monthlyStats":{"count":0,"percentileRank":0.0},"date":"2022-09-03"},"deleted":false}
```

Also, tables that are soft-deleted are counting towards the left panel view

Request URL: http://localhost:8585/api/v1/util/entities/count
response `{"tableCount":178,"topicCount":0,"dashboardCount":0,"pipelineCount":0,"mlmodelCount":0,"servicesCount":7,"userCount":1,"teamCount":1,"testSuiteCount":0}`

image

But not once you click to the explore page

image

Request URL: http://localhost:8585/api/v1/search/query?q=*&from=0&size=0&sort_field=updatedAt&sort_order=desc&index=table_search_index
```
{"took":4,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":153,"relation":"eq"},"max_score":null,"hits":[{"_index":"table_search_index","_type":"_doc","_id":"e77d7562-242c-40e4-a398-6d9f26e638b6","_score":null,"_source":{"id":"e77d7562-242c-40e4-a398-6d9f26e638b6","name":"VARIA","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.VARIA","version":0.1,"updatedAt":1662136623788,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/e77d7562-242c-40e4-a398-6d9f26e638b6","tableType":"Regular","columns":[{"name":"FLOAT1","dataType":"FLOAT","dataLength":1,"dataTypeDisplay":"float","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.VARIA.FLOAT1","constraint":"NULL"},{"name":"V","dataType":"JSON","dataLength":1,"dataTypeDisplay":"json","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.VARIA.V","constraint":"NULL"},{"name":"FLOAT2","dataType":"FLOAT","dataLength":1,"dataTypeDisplay":"float","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.VARIA.FLOAT2","constraint":"NULL"}],"databaseSchema":{"id":"cc39dde1-ec79-41cb-a8c2-139b102dfba6","type":"databaseSchema","name":"PUBLIC","fullyQualifiedName":"snow.OMTESTDB.PUBLIC","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/cc39dde1-ec79-41cb-a8c2-139b102dfba6"},"database":{"id":"20feab24-61b7-4807-8c66-c16a573e59a1","type":"database","name":"OMTESTDB","fullyQualifiedName":"snow.OMTESTDB","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/20feab24-61b7-4807-8c66-c16a573e59a1"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.OMTESTDB.PUBLIC.VARIA","weight":5},{"input":"VARIA","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"FLOAT1","weight":5},{"input":"V","weight":5},{"input":"FLOAT2","weight":5}],"schema_suggest":[{"input":"PUBLIC","weight":5}],"database_suggest":[{"input":"OMTESTDB","weight":5}],"entityType":"table"},"sort":[1662136623788000]},{"_index":"table_search_index","_type":"_doc","_id":"d776a085-8692-4ed0-9d2d-c24c076e2e36","_score":null,"_source":{"id":"d776a085-8692-4ed0-9d2d-c24c076e2e36","name":"CLEAN_USERS","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.CLEAN_USERS","version":0.1,"updatedAt":1662135980561,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/d776a085-8692-4ed0-9d2d-c24c076e2e36","tableType":"Regular","columns":[{"name":"NAME","dataType":"VARCHAR","dataLength":50,"dataTypeDisplay":"varchar(50)","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.CLEAN_USERS.NAME","constraint":"NULL"},{"name":"AGE","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.CLEAN_USERS.AGE","constraint":"NULL"},{"name":"HASH","dataType":"VARCHAR","dataLength":16777216,"dataTypeDisplay":"varchar(16777216)","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.CLEAN_USERS.HASH","constraint":"NULL"}],"databaseSchema":{"id":"cc39dde1-ec79-41cb-a8c2-139b102dfba6","type":"databaseSchema","name":"PUBLIC","fullyQualifiedName":"snow.OMTESTDB.PUBLIC","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/cc39dde1-ec79-41cb-a8c2-139b102dfba6"},"database":{"id":"20feab24-61b7-4807-8c66-c16a573e59a1","type":"database","name":"OMTESTDB","fullyQualifiedName":"snow.OMTESTDB","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/20feab24-61b7-4807-8c66-c16a573e59a1"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.OMTESTDB.PUBLIC.CLEAN_USERS","weight":5},{"input":"CLEAN_USERS","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"NAME","weight":5},{"input":"AGE","weight":5},{"input":"HASH","weight":5}],"schema_suggest":[{"input":"PUBLIC","weight":5}],"database_suggest":[{"input":"OMTESTDB","weight":5}],"entityType":"table"},"sort":[1662135980561000]},{"_index":"table_search_index","_type":"_doc","_id":"7e037e00-79ef-4521-9d73-6d9ad02bb578","_score":null,"_source":{"id":"7e037e00-79ef-4521-9d73-6d9ad02bb578","name":"USERS_VIEW","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.USERS_VIEW","version":0.1,"updatedAt":1662134416005,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/7e037e00-79ef-4521-9d73-6d9ad02bb578","tableType":"View","columns":[{"name":"ID","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.USERS_VIEW.ID","constraint":"NULL"},{"name":"NAME","dataType":"VARCHAR","dataLength":50,"dataTypeDisplay":"varchar(50)","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.USERS_VIEW.NAME","constraint":"NULL"},{"name":"FULLNAME","dataType":"VARCHAR","dataLength":50,"dataTypeDisplay":"varchar(50)","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.USERS_VIEW.FULLNAME","constraint":"NULL"},{"name":"NICKNAME","dataType":"VARCHAR","dataLength":50,"dataTypeDisplay":"varchar(50)","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.USERS_VIEW.NICKNAME","constraint":"NULL"},{"name":"COMMENTS","dataType":"VARCHAR","dataLength":100,"dataTypeDisplay":"varchar(100)","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.USERS_VIEW.COMMENTS","constraint":"NULL"},{"name":"AGE","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.USERS_VIEW.AGE","constraint":"NULL"}],"databaseSchema":{"id":"cc39dde1-ec79-41cb-a8c2-139b102dfba6","type":"databaseSchema","name":"PUBLIC","fullyQualifiedName":"snow.OMTESTDB.PUBLIC","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/cc39dde1-ec79-41cb-a8c2-139b102dfba6"},"database":{"id":"20feab24-61b7-4807-8c66-c16a573e59a1","type":"database","name":"OMTESTDB","fullyQualifiedName":"snow.OMTESTDB","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/20feab24-61b7-4807-8c66-c16a573e59a1"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","viewDefinition":"CREATE VIEW PUBLIC.users_view AS SELECT * FROM PUBLIC.users","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.OMTESTDB.PUBLIC.USERS_VIEW","weight":5},{"input":"USERS_VIEW","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"ID","weight":5},{"input":"NAME","weight":5},{"input":"FULLNAME","weight":5},{"input":"NICKNAME","weight":5},{"input":"COMMENTS","weight":5},{"input":"AGE","weight":5}],"schema_suggest":[{"input":"PUBLIC","weight":5}],"database_suggest":[{"input":"OMTESTDB","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-02","weeklyStats":{"percentileRank":0.0,"count":23},"monthlyStats":{"percentileRank":0.0,"count":23},"dailyStats":{"percentileRank":0.0,"count":4}}},"sort":[1662134416005000]},{"_index":"table_search_index","_type":"_doc","_id":"bc9df4ae-d2a6-48ff-8d87-34bf4ec8c653","_score":null,"_source":{"id":"bc9df4ae-d2a6-48ff-8d87-34bf4ec8c653","name":"USERS","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.USERS","version":0.1,"updatedAt":1662134415882,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/bc9df4ae-d2a6-48ff-8d87-34bf4ec8c653","tableType":"Regular","columns":[{"name":"ID","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.USERS.ID","constraint":"NULL"},{"name":"NAME","dataType":"VARCHAR","dataLength":50,"dataTypeDisplay":"varchar(50)","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.USERS.NAME","constraint":"NULL"},{"name":"FULLNAME","dataType":"VARCHAR","dataLength":50,"dataTypeDisplay":"varchar(50)","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.USERS.FULLNAME","constraint":"NULL"},{"name":"NICKNAME","dataType":"VARCHAR","dataLength":50,"dataTypeDisplay":"varchar(50)","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.USERS.NICKNAME","constraint":"NULL"},{"name":"COMMENTS","dataType":"VARCHAR","dataLength":100,"dataTypeDisplay":"varchar(100)","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.USERS.COMMENTS","constraint":"NULL"},{"name":"AGE","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.OMTESTDB.PUBLIC.USERS.AGE","constraint":"NULL"}],"databaseSchema":{"id":"cc39dde1-ec79-41cb-a8c2-139b102dfba6","type":"databaseSchema","name":"PUBLIC","fullyQualifiedName":"snow.OMTESTDB.PUBLIC","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/cc39dde1-ec79-41cb-a8c2-139b102dfba6"},"database":{"id":"20feab24-61b7-4807-8c66-c16a573e59a1","type":"database","name":"OMTESTDB","fullyQualifiedName":"snow.OMTESTDB","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/20feab24-61b7-4807-8c66-c16a573e59a1"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.OMTESTDB.PUBLIC.USERS","weight":5},{"input":"USERS","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"ID","weight":5},{"input":"NAME","weight":5},{"input":"FULLNAME","weight":5},{"input":"NICKNAME","weight":5},{"input":"COMMENTS","weight":5},{"input":"AGE","weight":5}],"schema_suggest":[{"input":"PUBLIC","weight":5}],"database_suggest":[{"input":"OMTESTDB","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-02","weeklyStats":{"percentileRank":0.0,"count":4},"monthlyStats":{"percentileRank":0.0,"count":4},"dailyStats":{"percentileRank":0.0,"count":4}}},"sort":[1662134415882000]},{"_index":"table_search_index","_type":"_doc","_id":"6174a656-8110-421b-b19f-cc2ff949fe55","_score":null,"_source":{"id":"6174a656-8110-421b-b19f-cc2ff949fe55","name":"MYTABLE_AUG","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE_AUG","version":0.1,"updatedAt":1662134415760,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/6174a656-8110-421b-b19f-cc2ff949fe55","tableType":"Regular","columns":[{"name":"ID","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE_AUG.ID","constraint":"NULL"},{"name":"NAME","dataType":"VARCHAR","dataLength":20,"dataTypeDisplay":"varchar(20)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE_AUG.NAME","constraint":"NULL"},{"name":"CITY","dataType":"VARCHAR","dataLength":20,"dataTypeDisplay":"varchar(20)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE_AUG.CITY","constraint":"NULL"}],"databaseSchema":{"id":"e4b51f6f-f7ba-48d7-ba2f-d6b73ea75158","type":"databaseSchema","name":"MYSCHEMA","fullyQualifiedName":"snow.MYDB.MYSCHEMA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/e4b51f6f-f7ba-48d7-ba2f-d6b73ea75158"},"database":{"id":"5d7e7568-f533-4def-9e68-2156298ab6c8","type":"database","name":"MYDB","fullyQualifiedName":"snow.MYDB","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/5d7e7568-f533-4def-9e68-2156298ab6c8"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.MYDB.MYSCHEMA.MYTABLE_AUG","weight":5},{"input":"MYTABLE_AUG","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"ID","weight":5},{"input":"NAME","weight":5},{"input":"CITY","weight":5}],"schema_suggest":[{"input":"MYSCHEMA","weight":5}],"database_suggest":[{"input":"MYDB","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-02","weeklyStats":{"percentileRank":0.0,"count":25},"monthlyStats":{"percentileRank":0.0,"count":25},"dailyStats":{"percentileRank":0.0,"count":9}}},"sort":[1662134415760000]},{"_index":"table_search_index","_type":"_doc","_id":"e0abb36f-ae55-493f-8b54-d12bf2029605","_score":null,"_source":{"id":"e0abb36f-ae55-493f-8b54-d12bf2029605","name":"MYTABLE3","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE3","version":0.1,"updatedAt":1662134415669,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/e0abb36f-ae55-493f-8b54-d12bf2029605","tableType":"Regular","columns":[{"name":"ID","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE3.ID","constraint":"NULL"},{"name":"NAME","dataType":"VARCHAR","dataLength":20,"dataTypeDisplay":"varchar(20)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE3.NAME","constraint":"NULL"}],"databaseSchema":{"id":"e4b51f6f-f7ba-48d7-ba2f-d6b73ea75158","type":"databaseSchema","name":"MYSCHEMA","fullyQualifiedName":"snow.MYDB.MYSCHEMA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/e4b51f6f-f7ba-48d7-ba2f-d6b73ea75158"},"database":{"id":"5d7e7568-f533-4def-9e68-2156298ab6c8","type":"database","name":"MYDB","fullyQualifiedName":"snow.MYDB","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/5d7e7568-f533-4def-9e68-2156298ab6c8"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.MYDB.MYSCHEMA.MYTABLE3","weight":5},{"input":"MYTABLE3","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"ID","weight":5},{"input":"NAME","weight":5}],"schema_suggest":[{"input":"MYSCHEMA","weight":5}],"database_suggest":[{"input":"MYDB","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-02","weeklyStats":{"percentileRank":0.0,"count":25},"monthlyStats":{"percentileRank":0.0,"count":25},"dailyStats":{"percentileRank":0.0,"count":9}}},"sort":[1662134415669000]},{"_index":"table_search_index","_type":"_doc","_id":"557987bc-1c7d-4daf-95d5-80ae6b298795","_score":null,"_source":{"id":"557987bc-1c7d-4daf-95d5-80ae6b298795","name":"MYTABLE5","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE5","version":0.1,"updatedAt":1662134415580,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/557987bc-1c7d-4daf-95d5-80ae6b298795","tableType":"Regular","columns":[{"name":"ID","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE5.ID","constraint":"NULL"},{"name":"NAME","dataType":"VARCHAR","dataLength":20,"dataTypeDisplay":"varchar(20)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE5.NAME","constraint":"NULL"},{"name":"CITY","dataType":"VARCHAR","dataLength":20,"dataTypeDisplay":"varchar(20)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE5.CITY","constraint":"NULL"}],"databaseSchema":{"id":"e4b51f6f-f7ba-48d7-ba2f-d6b73ea75158","type":"databaseSchema","name":"MYSCHEMA","fullyQualifiedName":"snow.MYDB.MYSCHEMA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/e4b51f6f-f7ba-48d7-ba2f-d6b73ea75158"},"database":{"id":"5d7e7568-f533-4def-9e68-2156298ab6c8","type":"database","name":"MYDB","fullyQualifiedName":"snow.MYDB","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/5d7e7568-f533-4def-9e68-2156298ab6c8"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.MYDB.MYSCHEMA.MYTABLE5","weight":5},{"input":"MYTABLE5","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"ID","weight":5},{"input":"NAME","weight":5},{"input":"CITY","weight":5}],"schema_suggest":[{"input":"MYSCHEMA","weight":5}],"database_suggest":[{"input":"MYDB","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-02","weeklyStats":{"percentileRank":0.0,"count":19},"monthlyStats":{"percentileRank":0.0,"count":19},"dailyStats":{"percentileRank":0.0,"count":8}}},"sort":[1662134415580000]},{"_index":"table_search_index","_type":"_doc","_id":"ac0116c3-4120-4dea-b228-39f9f71591cd","_score":null,"_source":{"id":"ac0116c3-4120-4dea-b228-39f9f71591cd","name":"MYTABLE4","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE4","version":0.1,"updatedAt":1662134415479,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/ac0116c3-4120-4dea-b228-39f9f71591cd","tableType":"Regular","columns":[{"name":"ID","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE4.ID","constraint":"NULL"},{"name":"NAME","dataType":"VARCHAR","dataLength":20,"dataTypeDisplay":"varchar(20)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE4.NAME","constraint":"NULL"},{"name":"CITY","dataType":"VARCHAR","dataLength":20,"dataTypeDisplay":"varchar(20)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE4.CITY","constraint":"NULL"}],"databaseSchema":{"id":"e4b51f6f-f7ba-48d7-ba2f-d6b73ea75158","type":"databaseSchema","name":"MYSCHEMA","fullyQualifiedName":"snow.MYDB.MYSCHEMA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/e4b51f6f-f7ba-48d7-ba2f-d6b73ea75158"},"database":{"id":"5d7e7568-f533-4def-9e68-2156298ab6c8","type":"database","name":"MYDB","fullyQualifiedName":"snow.MYDB","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/5d7e7568-f533-4def-9e68-2156298ab6c8"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.MYDB.MYSCHEMA.MYTABLE4","weight":5},{"input":"MYTABLE4","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"ID","weight":5},{"input":"NAME","weight":5},{"input":"CITY","weight":5}],"schema_suggest":[{"input":"MYSCHEMA","weight":5}],"database_suggest":[{"input":"MYDB","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-02","weeklyStats":{"percentileRank":0.0,"count":27},"monthlyStats":{"percentileRank":0.0,"count":27},"dailyStats":{"percentileRank":0.0,"count":8}}},"sort":[1662134415479000]},{"_index":"table_search_index","_type":"_doc","_id":"f2bca404-35fa-4d13-9079-f00240661f9d","_score":null,"_source":{"id":"f2bca404-35fa-4d13-9079-f00240661f9d","name":"MYTABLE1","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE1","version":0.1,"updatedAt":1662134415400,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/f2bca404-35fa-4d13-9079-f00240661f9d","tableType":"Regular","columns":[{"name":"ID","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE1.ID","constraint":"NULL"},{"name":"NAME","dataType":"VARCHAR","dataLength":20,"dataTypeDisplay":"varchar(20)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE1.NAME","constraint":"NULL"},{"name":"CITY","dataType":"VARCHAR","dataLength":20,"dataTypeDisplay":"varchar(20)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE1.CITY","constraint":"NULL"}],"databaseSchema":{"id":"e4b51f6f-f7ba-48d7-ba2f-d6b73ea75158","type":"databaseSchema","name":"MYSCHEMA","fullyQualifiedName":"snow.MYDB.MYSCHEMA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/e4b51f6f-f7ba-48d7-ba2f-d6b73ea75158"},"database":{"id":"5d7e7568-f533-4def-9e68-2156298ab6c8","type":"database","name":"MYDB","fullyQualifiedName":"snow.MYDB","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/5d7e7568-f533-4def-9e68-2156298ab6c8"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.MYDB.MYSCHEMA.MYTABLE1","weight":5},{"input":"MYTABLE1","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"ID","weight":5},{"input":"NAME","weight":5},{"input":"CITY","weight":5}],"schema_suggest":[{"input":"MYSCHEMA","weight":5}],"database_suggest":[{"input":"MYDB","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-02","weeklyStats":{"percentileRank":0.0,"count":29},"monthlyStats":{"percentileRank":0.0,"count":29},"dailyStats":{"percentileRank":0.0,"count":9}}},"sort":[1662134415400000]},{"_index":"table_search_index","_type":"_doc","_id":"dcb828f4-e217-4c37-b074-f9f6d85a27da","_score":null,"_source":{"id":"dcb828f4-e217-4c37-b074-f9f6d85a27da","name":"MYTABLE2","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE2","version":0.1,"updatedAt":1662134415303,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/dcb828f4-e217-4c37-b074-f9f6d85a27da","tableType":"Regular","columns":[{"name":"ID","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE2.ID","constraint":"NULL"},{"name":"NAME","dataType":"VARCHAR","dataLength":20,"dataTypeDisplay":"varchar(20)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE2.NAME","constraint":"NULL"},{"name":"CITY","dataType":"VARCHAR","dataLength":20,"dataTypeDisplay":"varchar(20)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE2.CITY","constraint":"NULL"}],"databaseSchema":{"id":"e4b51f6f-f7ba-48d7-ba2f-d6b73ea75158","type":"databaseSchema","name":"MYSCHEMA","fullyQualifiedName":"snow.MYDB.MYSCHEMA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/e4b51f6f-f7ba-48d7-ba2f-d6b73ea75158"},"database":{"id":"5d7e7568-f533-4def-9e68-2156298ab6c8","type":"database","name":"MYDB","fullyQualifiedName":"snow.MYDB","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/5d7e7568-f533-4def-9e68-2156298ab6c8"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.MYDB.MYSCHEMA.MYTABLE2","weight":5},{"input":"MYTABLE2","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"ID","weight":5},{"input":"NAME","weight":5},{"input":"CITY","weight":5}],"schema_suggest":[{"input":"MYSCHEMA","weight":5}],"database_suggest":[{"input":"MYDB","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-02","weeklyStats":{"percentileRank":0.0,"count":28},"monthlyStats":{"percentileRank":0.0,"count":28},"dailyStats":{"percentileRank":0.0,"count":10}}},"sort":[1662134415303000]},{"_index":"table_search_index","_type":"_doc","_id":"88967f3a-b2d7-439b-8ef2-54604bf79179","_score":null,"_source":{"id":"88967f3a-b2d7-439b-8ef2-54604bf79179","name":"MYTABLE6","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE6","version":0.1,"updatedAt":1662134414988,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/88967f3a-b2d7-439b-8ef2-54604bf79179","tableType":"Regular","columns":[{"name":"CUSTOM_ID","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE6.CUSTOM_ID","constraint":"NULL"},{"name":"CUSTOM_NAME","dataType":"VARCHAR","dataLength":20,"dataTypeDisplay":"varchar(20)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE6.CUSTOM_NAME","constraint":"NULL"},{"name":"CUSTOM_CITY","dataType":"VARCHAR","dataLength":20,"dataTypeDisplay":"varchar(20)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE6.CUSTOM_CITY","constraint":"NULL"}],"databaseSchema":{"id":"e4b51f6f-f7ba-48d7-ba2f-d6b73ea75158","type":"databaseSchema","name":"MYSCHEMA","fullyQualifiedName":"snow.MYDB.MYSCHEMA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/e4b51f6f-f7ba-48d7-ba2f-d6b73ea75158"},"database":{"id":"5d7e7568-f533-4def-9e68-2156298ab6c8","type":"database","name":"MYDB","fullyQualifiedName":"snow.MYDB","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/5d7e7568-f533-4def-9e68-2156298ab6c8"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.MYDB.MYSCHEMA.MYTABLE6","weight":5},{"input":"MYTABLE6","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"CUSTOM_ID","weight":5},{"input":"CUSTOM_NAME","weight":5},{"input":"CUSTOM_CITY","weight":5}],"schema_suggest":[{"input":"MYSCHEMA","weight":5}],"database_suggest":[{"input":"MYDB","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-02","weeklyStats":{"percentileRank":0.0,"count":25},"monthlyStats":{"percentileRank":0.0,"count":25},"dailyStats":{"percentileRank":0.0,"count":12}}},"sort":[1662134414988000]},{"_index":"table_search_index","_type":"_doc","_id":"3fdca4f9-45e3-4580-8da0-e934a1c79c88","_score":null,"_source":{"id":"3fdca4f9-45e3-4580-8da0-e934a1c79c88","name":"T4","fullyQualifiedName":"snow.MYDB.TEST_CLUSTER.T4","version":0.1,"updatedAt":1662134414818,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/3fdca4f9-45e3-4580-8da0-e934a1c79c88","tableType":"Regular","columns":[{"name":"UID","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.MYDB.TEST_CLUSTER.T4.UID","constraint":"NULL"},{"name":"NAME","dataType":"VARCHAR","dataLength":16777216,"dataTypeDisplay":"varchar(16777216)","fullyQualifiedName":"snow.MYDB.TEST_CLUSTER.T4.NAME","constraint":"NULL"}],"databaseSchema":{"id":"cb5c6948-04fb-4cdd-b7d9-a8164a9b01fd","type":"databaseSchema","name":"TEST_CLUSTER","fullyQualifiedName":"snow.MYDB.TEST_CLUSTER","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/cb5c6948-04fb-4cdd-b7d9-a8164a9b01fd"},"database":{"id":"5d7e7568-f533-4def-9e68-2156298ab6c8","type":"database","name":"MYDB","fullyQualifiedName":"snow.MYDB","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/5d7e7568-f533-4def-9e68-2156298ab6c8"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.MYDB.TEST_CLUSTER.T4","weight":5},{"input":"T4","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"UID","weight":5},{"input":"NAME","weight":5}],"schema_suggest":[{"input":"TEST_CLUSTER","weight":5}],"database_suggest":[{"input":"MYDB","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-02","weeklyStats":{"percentileRank":0.0,"count":40},"monthlyStats":{"percentileRank":0.0,"count":40},"dailyStats":{"percentileRank":0.0,"count":12}}},"sort":[1662134414818000]},{"_index":"table_search_index","_type":"_doc","_id":"b50110ab-374f-4100-a1de-6cd051c70f7f","_score":null,"_source":{"id":"b50110ab-374f-4100-a1de-6cd051c70f7f","name":"T1","fullyQualifiedName":"snow.MYDB.TEST_CLUSTER.T1","version":0.1,"updatedAt":1662134414596,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/b50110ab-374f-4100-a1de-6cd051c70f7f","tableType":"Partitioned","columns":[{"name":"C1","dataType":"DATE","dataLength":1,"dataTypeDisplay":"date","fullyQualifiedName":"snow.MYDB.TEST_CLUSTER.T1.C1","constraint":"NULL"},{"name":"C2","dataType":"VARCHAR","dataLength":16777216,"dataTypeDisplay":"varchar(16777216)","fullyQualifiedName":"snow.MYDB.TEST_CLUSTER.T1.C2","constraint":"NULL"},{"name":"C3","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.MYDB.TEST_CLUSTER.T1.C3","constraint":"NULL"}],"tablePartition":{"columns":["C1","C2"],"intervalType":"COLUMN-VALUE"},"databaseSchema":{"id":"cb5c6948-04fb-4cdd-b7d9-a8164a9b01fd","type":"databaseSchema","name":"TEST_CLUSTER","fullyQualifiedName":"snow.MYDB.TEST_CLUSTER","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/cb5c6948-04fb-4cdd-b7d9-a8164a9b01fd"},"database":{"id":"5d7e7568-f533-4def-9e68-2156298ab6c8","type":"database","name":"MYDB","fullyQualifiedName":"snow.MYDB","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/5d7e7568-f533-4def-9e68-2156298ab6c8"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.MYDB.TEST_CLUSTER.T1","weight":5},{"input":"T1","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"C1","weight":5},{"input":"C2","weight":5},{"input":"C3","weight":5}],"schema_suggest":[{"input":"TEST_CLUSTER","weight":5}],"database_suggest":[{"input":"MYDB","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-02","weeklyStats":{"percentileRank":0.0,"count":38},"monthlyStats":{"percentileRank":0.0,"count":38},"dailyStats":{"percentileRank":0.0,"count":14}}},"sort":[1662134414596000]},{"_index":"table_search_index","_type":"_doc","_id":"cde40490-c9dc-4c4f-ae76-f04766a423ad","_score":null,"_source":{"id":"cde40490-c9dc-4c4f-ae76-f04766a423ad","name":"T2","fullyQualifiedName":"snow.MYDB.TEST_CLUSTER.T2","version":0.1,"updatedAt":1662134414384,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/cde40490-c9dc-4c4f-ae76-f04766a423ad","tableType":"Partitioned","columns":[{"name":"C1","dataType":"TIMESTAMP","dataLength":1,"dataTypeDisplay":"timestamp","fullyQualifiedName":"snow.MYDB.TEST_CLUSTER.T2.C1","constraint":"NULL"},{"name":"C2","dataType":"VARCHAR","dataLength":16777216,"dataTypeDisplay":"varchar(16777216)","fullyQualifiedName":"snow.MYDB.TEST_CLUSTER.T2.C2","constraint":"NULL"},{"name":"C3","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.MYDB.TEST_CLUSTER.T2.C3","constraint":"NULL"}],"tablePartition":{"columns":["C1","C2"],"intervalType":"COLUMN-VALUE"},"databaseSchema":{"id":"cb5c6948-04fb-4cdd-b7d9-a8164a9b01fd","type":"databaseSchema","name":"TEST_CLUSTER","fullyQualifiedName":"snow.MYDB.TEST_CLUSTER","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/cb5c6948-04fb-4cdd-b7d9-a8164a9b01fd"},"database":{"id":"5d7e7568-f533-4def-9e68-2156298ab6c8","type":"database","name":"MYDB","fullyQualifiedName":"snow.MYDB","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/5d7e7568-f533-4def-9e68-2156298ab6c8"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.MYDB.TEST_CLUSTER.T2","weight":5},{"input":"T2","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"C1","weight":5},{"input":"C2","weight":5},{"input":"C3","weight":5}],"schema_suggest":[{"input":"TEST_CLUSTER","weight":5}],"database_suggest":[{"input":"MYDB","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-02","weeklyStats":{"percentileRank":0.0,"count":35},"monthlyStats":{"percentileRank":0.0,"count":35},"dailyStats":{"percentileRank":0.0,"count":12}}},"sort":[1662134414384000]},{"_index":"table_search_index","_type":"_doc","_id":"d432f493-4a33-4bf6-947b-3de528b68ec3","_score":null,"_source":{"id":"d432f493-4a33-4bf6-947b-3de528b68ec3","name":"T3","fullyQualifiedName":"snow.MYDB.TEST_CLUSTER.T3","version":0.1,"updatedAt":1662134414161,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/d432f493-4a33-4bf6-947b-3de528b68ec3","tableType":"Partitioned","columns":[{"name":"T","dataType":"TIMESTAMP","dataLength":1,"dataTypeDisplay":"timestamp","fullyQualifiedName":"snow.MYDB.TEST_CLUSTER.T3.T","constraint":"NULL"},{"name":"V","dataType":"JSON","dataLength":1,"dataTypeDisplay":"json","fullyQualifiedName":"snow.MYDB.TEST_CLUSTER.T3.V","constraint":"NULL"}],"tablePartition":{"columns":["V"],"intervalType":"COLUMN-VALUE"},"databaseSchema":{"id":"cb5c6948-04fb-4cdd-b7d9-a8164a9b01fd","type":"databaseSchema","name":"TEST_CLUSTER","fullyQualifiedName":"snow.MYDB.TEST_CLUSTER","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/cb5c6948-04fb-4cdd-b7d9-a8164a9b01fd"},"database":{"id":"5d7e7568-f533-4def-9e68-2156298ab6c8","type":"database","name":"MYDB","fullyQualifiedName":"snow.MYDB","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/5d7e7568-f533-4def-9e68-2156298ab6c8"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.MYDB.TEST_CLUSTER.T3","weight":5},{"input":"T3","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"T","weight":5},{"input":"V","weight":5}],"schema_suggest":[{"input":"TEST_CLUSTER","weight":5}],"database_suggest":[{"input":"MYDB","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-02","weeklyStats":{"percentileRank":0.0,"count":33},"monthlyStats":{"percentileRank":0.0,"count":33},"dailyStats":{"percentileRank":0.0,"count":13}}},"sort":[1662134414161000]},{"_index":"table_search_index","_type":"_doc","_id":"e4c7cf35-26b9-44fd-b193-f60eca488396","_score":null,"_source":{"id":"e4c7cf35-26b9-44fd-b193-f60eca488396","name":"MYTABLE_AUG_2","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE_AUG_2","version":0.1,"updatedAt":1662134414067,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/e4c7cf35-26b9-44fd-b193-f60eca488396","tableType":"Regular","columns":[{"name":"ID","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE_AUG_2.ID","constraint":"NULL"},{"name":"NAME","dataType":"VARCHAR","dataLength":20,"dataTypeDisplay":"varchar(20)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE_AUG_2.NAME","constraint":"NULL"},{"name":"CITY","dataType":"VARCHAR","dataLength":20,"dataTypeDisplay":"varchar(20)","fullyQualifiedName":"snow.MYDB.MYSCHEMA.MYTABLE_AUG_2.CITY","constraint":"NULL"}],"databaseSchema":{"id":"e4b51f6f-f7ba-48d7-ba2f-d6b73ea75158","type":"databaseSchema","name":"MYSCHEMA","fullyQualifiedName":"snow.MYDB.MYSCHEMA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/e4b51f6f-f7ba-48d7-ba2f-d6b73ea75158"},"database":{"id":"5d7e7568-f533-4def-9e68-2156298ab6c8","type":"database","name":"MYDB","fullyQualifiedName":"snow.MYDB","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/5d7e7568-f533-4def-9e68-2156298ab6c8"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.MYDB.MYSCHEMA.MYTABLE_AUG_2","weight":5},{"input":"MYTABLE_AUG_2","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"ID","weight":5},{"input":"NAME","weight":5},{"input":"CITY","weight":5}],"schema_suggest":[{"input":"MYSCHEMA","weight":5}],"database_suggest":[{"input":"MYDB","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-02","weeklyStats":{"percentileRank":0.0,"count":20},"monthlyStats":{"percentileRank":0.0,"count":20},"dailyStats":{"percentileRank":0.0,"count":8}}},"sort":[1662134414067000]},{"_index":"table_search_index","_type":"_doc","_id":"656c1c48-ac15-4217-8933-8eaf8775b33e","_score":null,"_source":{"id":"656c1c48-ac15-4217-8933-8eaf8775b33e","name":"PARTSUPP","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PARTSUPP","description":"Partsupp data as defined by TPC-H","version":0.1,"updatedAt":1662134413692,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/656c1c48-ac15-4217-8933-8eaf8775b33e","tableType":"Regular","columns":[{"name":"PS_PARTKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PARTSUPP.PS_PARTKEY","constraint":"NOT_NULL"},{"name":"PS_SUPPKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PARTSUPP.PS_SUPPKEY","constraint":"NOT_NULL"},{"name":"PS_AVAILQTY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PARTSUPP.PS_AVAILQTY","constraint":"NOT_NULL"},{"name":"PS_SUPPLYCOST","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PARTSUPP.PS_SUPPLYCOST","constraint":"NOT_NULL"},{"name":"PS_COMMENT","dataType":"VARCHAR","dataLength":199,"dataTypeDisplay":"varchar(199)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PARTSUPP.PS_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"8e5eddb1-a4e9-41b3-a020-62ea25af6c75","type":"databaseSchema","name":"TPCH_SF100","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/8e5eddb1-a4e9-41b3-a020-62ea25af6c75"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PARTSUPP","weight":5},{"input":"PARTSUPP","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"PS_PARTKEY","weight":5},{"input":"PS_SUPPKEY","weight":5},{"input":"PS_AVAILQTY","weight":5},{"input":"PS_SUPPLYCOST","weight":5},{"input":"PS_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF100","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":9},"monthlyStats":{"percentileRank":0.0,"count":9},"dailyStats":{"percentileRank":0.0,"count":9}}},"sort":[1662134413692000]},{"_index":"table_search_index","_type":"_doc","_id":"ed64d813-f1d8-4320-8c92-d690489e7920","_score":null,"_source":{"id":"ed64d813-f1d8-4320-8c92-d690489e7920","name":"PARTSUPP","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PARTSUPP","description":"Partsupp data as defined by TPC-H","version":0.1,"updatedAt":1662134413334,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/ed64d813-f1d8-4320-8c92-d690489e7920","tableType":"Partitioned","columns":[{"name":"PS_PARTKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PARTSUPP.PS_PARTKEY","constraint":"NOT_NULL"},{"name":"PS_SUPPKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PARTSUPP.PS_SUPPKEY","constraint":"NOT_NULL"},{"name":"PS_AVAILQTY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PARTSUPP.PS_AVAILQTY","constraint":"NOT_NULL"},{"name":"PS_SUPPLYCOST","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PARTSUPP.PS_SUPPLYCOST","constraint":"NOT_NULL"},{"name":"PS_COMMENT","dataType":"VARCHAR","dataLength":199,"dataTypeDisplay":"varchar(199)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PARTSUPP.PS_COMMENT","constraint":"NULL"}],"tablePartition":{"columns":["PS_SUPPKEY"],"intervalType":"COLUMN-VALUE"},"databaseSchema":{"id":"fd066fb9-ff76-4cd6-9d5c-c29765f3e38c","type":"databaseSchema","name":"TPCH_SF1000","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/fd066fb9-ff76-4cd6-9d5c-c29765f3e38c"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PARTSUPP","weight":5},{"input":"PARTSUPP","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"PS_PARTKEY","weight":5},{"input":"PS_SUPPKEY","weight":5},{"input":"PS_AVAILQTY","weight":5},{"input":"PS_SUPPLYCOST","weight":5},{"input":"PS_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF1000","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":9},"monthlyStats":{"percentileRank":0.0,"count":9},"dailyStats":{"percentileRank":0.0,"count":9}}},"sort":[1662134413334000]},{"_index":"table_search_index","_type":"_doc","_id":"d987bac1-eb6c-41ee-a5df-266bafc6a0b5","_score":null,"_source":{"id":"d987bac1-eb6c-41ee-a5df-266bafc6a0b5","name":"PARTSUPP","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PARTSUPP","description":"Partsupp data as defined by TPC-H","version":0.1,"updatedAt":1662134412979,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/d987bac1-eb6c-41ee-a5df-266bafc6a0b5","tableType":"Regular","columns":[{"name":"PS_PARTKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PARTSUPP.PS_PARTKEY","constraint":"NOT_NULL"},{"name":"PS_SUPPKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PARTSUPP.PS_SUPPKEY","constraint":"NOT_NULL"},{"name":"PS_AVAILQTY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PARTSUPP.PS_AVAILQTY","constraint":"NOT_NULL"},{"name":"PS_SUPPLYCOST","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PARTSUPP.PS_SUPPLYCOST","constraint":"NOT_NULL"},{"name":"PS_COMMENT","dataType":"VARCHAR","dataLength":199,"dataTypeDisplay":"varchar(199)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PARTSUPP.PS_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"dcc4d82e-9bb7-471a-97fd-6364937a2790","type":"databaseSchema","name":"TPCH_SF10","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/dcc4d82e-9bb7-471a-97fd-6364937a2790"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PARTSUPP","weight":5},{"input":"PARTSUPP","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"PS_PARTKEY","weight":5},{"input":"PS_SUPPKEY","weight":5},{"input":"PS_AVAILQTY","weight":5},{"input":"PS_SUPPLYCOST","weight":5},{"input":"PS_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF10","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":9},"monthlyStats":{"percentileRank":0.0,"count":9},"dailyStats":{"percentileRank":0.0,"count":9}}},"sort":[1662134412979000]},{"_index":"table_search_index","_type":"_doc","_id":"4188b81d-a403-4d62-9892-22c083580c00","_score":null,"_source":{"id":"4188b81d-a403-4d62-9892-22c083580c00","name":"PARTSUPP","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP","description":"Partsupp data as defined by TPC-H","version":0.1,"updatedAt":1662134412639,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/4188b81d-a403-4d62-9892-22c083580c00","tableType":"Regular","columns":[{"name":"PS_PARTKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP.PS_PARTKEY","constraint":"NOT_NULL"},{"name":"PS_SUPPKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP.PS_SUPPKEY","constraint":"NOT_NULL"},{"name":"PS_AVAILQTY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP.PS_AVAILQTY","constraint":"NOT_NULL"},{"name":"PS_SUPPLYCOST","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP.PS_SUPPLYCOST","constraint":"NOT_NULL"},{"name":"PS_COMMENT","dataType":"VARCHAR","dataLength":199,"dataTypeDisplay":"varchar(199)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP.PS_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"3de73d4c-904f-4e9a-b084-821e34da26f3","type":"databaseSchema","name":"TPCH_SF1","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/3de73d4c-904f-4e9a-b084-821e34da26f3"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP","weight":5},{"input":"PARTSUPP","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"PS_PARTKEY","weight":5},{"input":"PS_SUPPKEY","weight":5},{"input":"PS_AVAILQTY","weight":5},{"input":"PS_SUPPLYCOST","weight":5},{"input":"PS_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF1","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":9},"monthlyStats":{"percentileRank":0.0,"count":9},"dailyStats":{"percentileRank":0.0,"count":9}}},"sort":[1662134412639000]},{"_index":"table_search_index","_type":"_doc","_id":"75038d17-4d33-4b19-a668-7a875b911548","_score":null,"_source":{"id":"75038d17-4d33-4b19-a668-7a875b911548","name":"CLEAN_USERS","fullyQualifiedName":"snow.NEWDB.PUBLIC.CLEAN_USERS","version":0.1,"updatedAt":1662134412233,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/75038d17-4d33-4b19-a668-7a875b911548","tableType":"Regular","columns":[{"name":"ID","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.NEWDB.PUBLIC.CLEAN_USERS.ID","constraint":"NULL"},{"name":"NAME","dataType":"VARCHAR","dataLength":50,"dataTypeDisplay":"varchar(50)","fullyQualifiedName":"snow.NEWDB.PUBLIC.CLEAN_USERS.NAME","constraint":"NULL"},{"name":"FULLNAME","dataType":"VARCHAR","dataLength":50,"dataTypeDisplay":"varchar(50)","fullyQualifiedName":"snow.NEWDB.PUBLIC.CLEAN_USERS.FULLNAME","constraint":"NULL"}],"databaseSchema":{"id":"1da7e3b4-762a-4aa8-87e8-e88fe9f8652d","type":"databaseSchema","name":"PUBLIC","fullyQualifiedName":"snow.NEWDB.PUBLIC","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/1da7e3b4-762a-4aa8-87e8-e88fe9f8652d"},"database":{"id":"f53cbd09-d2b1-41c1-aecb-b4f110136e5a","type":"database","name":"NEWDB","fullyQualifiedName":"snow.NEWDB","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/f53cbd09-d2b1-41c1-aecb-b4f110136e5a"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.NEWDB.PUBLIC.CLEAN_USERS","weight":5},{"input":"CLEAN_USERS","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"ID","weight":5},{"input":"NAME","weight":5},{"input":"FULLNAME","weight":5}],"schema_suggest":[{"input":"PUBLIC","weight":5}],"database_suggest":[{"input":"NEWDB","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":9},"monthlyStats":{"percentileRank":0.0,"count":9},"dailyStats":{"percentileRank":0.0,"count":9}}},"sort":[1662134412233000]},{"_index":"table_search_index","_type":"_doc","_id":"42fed572-5c76-4539-b6d7-bca590bdb08f","_score":null,"_source":{"id":"42fed572-5c76-4539-b6d7-bca590bdb08f","name":"PART","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PART","description":"Part data as defined by TPC-H","version":0.1,"updatedAt":1662134411443,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/42fed572-5c76-4539-b6d7-bca590bdb08f","tableType":"Regular","columns":[{"name":"P_PARTKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PART.P_PARTKEY","constraint":"NOT_NULL"},{"name":"P_NAME","dataType":"VARCHAR","dataLength":55,"dataTypeDisplay":"varchar(55)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PART.P_NAME","constraint":"NOT_NULL"},{"name":"P_MFGR","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PART.P_MFGR","constraint":"NOT_NULL"},{"name":"P_BRAND","dataType":"VARCHAR","dataLength":10,"dataTypeDisplay":"varchar(10)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PART.P_BRAND","constraint":"NOT_NULL"},{"name":"P_TYPE","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PART.P_TYPE","constraint":"NOT_NULL"},{"name":"P_SIZE","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PART.P_SIZE","constraint":"NOT_NULL"},{"name":"P_CONTAINER","dataType":"VARCHAR","dataLength":10,"dataTypeDisplay":"varchar(10)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PART.P_CONTAINER","constraint":"NOT_NULL"},{"name":"P_RETAILPRICE","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PART.P_RETAILPRICE","constraint":"NOT_NULL"},{"name":"P_COMMENT","dataType":"VARCHAR","dataLength":23,"dataTypeDisplay":"varchar(23)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PART.P_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"8e5eddb1-a4e9-41b3-a020-62ea25af6c75","type":"databaseSchema","name":"TPCH_SF100","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/8e5eddb1-a4e9-41b3-a020-62ea25af6c75"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PART","weight":5},{"input":"PART","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"P_PARTKEY","weight":5},{"input":"P_NAME","weight":5},{"input":"P_MFGR","weight":5},{"input":"P_BRAND","weight":5},{"input":"P_TYPE","weight":5},{"input":"P_SIZE","weight":5},{"input":"P_CONTAINER","weight":5},{"input":"P_RETAILPRICE","weight":5},{"input":"P_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF100","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":28},"monthlyStats":{"percentileRank":0.0,"count":28},"dailyStats":{"percentileRank":0.0,"count":28}}},"sort":[1662134411443000]},{"_index":"table_search_index","_type":"_doc","_id":"1a6454c5-a956-443a-bb54-4c4c94853589","_score":null,"_source":{"id":"1a6454c5-a956-443a-bb54-4c4c94853589","name":"PART","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PART","description":"Part data as defined by TPC-H","version":0.1,"updatedAt":1662134410943,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/1a6454c5-a956-443a-bb54-4c4c94853589","tableType":"Regular","columns":[{"name":"P_PARTKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PART.P_PARTKEY","constraint":"NOT_NULL"},{"name":"P_NAME","dataType":"VARCHAR","dataLength":55,"dataTypeDisplay":"varchar(55)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PART.P_NAME","constraint":"NOT_NULL"},{"name":"P_MFGR","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PART.P_MFGR","constraint":"NOT_NULL"},{"name":"P_BRAND","dataType":"VARCHAR","dataLength":10,"dataTypeDisplay":"varchar(10)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PART.P_BRAND","constraint":"NOT_NULL"},{"name":"P_TYPE","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PART.P_TYPE","constraint":"NOT_NULL"},{"name":"P_SIZE","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PART.P_SIZE","constraint":"NOT_NULL"},{"name":"P_CONTAINER","dataType":"VARCHAR","dataLength":10,"dataTypeDisplay":"varchar(10)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PART.P_CONTAINER","constraint":"NOT_NULL"},{"name":"P_RETAILPRICE","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PART.P_RETAILPRICE","constraint":"NOT_NULL"},{"name":"P_COMMENT","dataType":"VARCHAR","dataLength":23,"dataTypeDisplay":"varchar(23)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PART.P_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"fd066fb9-ff76-4cd6-9d5c-c29765f3e38c","type":"databaseSchema","name":"TPCH_SF1000","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/fd066fb9-ff76-4cd6-9d5c-c29765f3e38c"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PART","weight":5},{"input":"PART","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"P_PARTKEY","weight":5},{"input":"P_NAME","weight":5},{"input":"P_MFGR","weight":5},{"input":"P_BRAND","weight":5},{"input":"P_TYPE","weight":5},{"input":"P_SIZE","weight":5},{"input":"P_CONTAINER","weight":5},{"input":"P_RETAILPRICE","weight":5},{"input":"P_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF1000","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":28},"monthlyStats":{"percentileRank":0.0,"count":28},"dailyStats":{"percentileRank":0.0,"count":28}}},"sort":[1662134410943000]},{"_index":"table_search_index","_type":"_doc","_id":"2df5fc58-cc2a-4e5c-99db-8ad46137bf98","_score":null,"_source":{"id":"2df5fc58-cc2a-4e5c-99db-8ad46137bf98","name":"PART","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART","description":"Part data as defined by TPC-H","version":0.1,"updatedAt":1662134410489,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/2df5fc58-cc2a-4e5c-99db-8ad46137bf98","tableType":"Regular","columns":[{"name":"P_PARTKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART.P_PARTKEY","constraint":"NOT_NULL"},{"name":"P_NAME","dataType":"VARCHAR","dataLength":55,"dataTypeDisplay":"varchar(55)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART.P_NAME","constraint":"NOT_NULL"},{"name":"P_MFGR","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART.P_MFGR","constraint":"NOT_NULL"},{"name":"P_BRAND","dataType":"VARCHAR","dataLength":10,"dataTypeDisplay":"varchar(10)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART.P_BRAND","constraint":"NOT_NULL"},{"name":"P_TYPE","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART.P_TYPE","constraint":"NOT_NULL"},{"name":"P_SIZE","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART.P_SIZE","constraint":"NOT_NULL"},{"name":"P_CONTAINER","dataType":"VARCHAR","dataLength":10,"dataTypeDisplay":"varchar(10)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART.P_CONTAINER","constraint":"NOT_NULL"},{"name":"P_RETAILPRICE","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART.P_RETAILPRICE","constraint":"NOT_NULL"},{"name":"P_COMMENT","dataType":"VARCHAR","dataLength":23,"dataTypeDisplay":"varchar(23)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART.P_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"dcc4d82e-9bb7-471a-97fd-6364937a2790","type":"databaseSchema","name":"TPCH_SF10","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/dcc4d82e-9bb7-471a-97fd-6364937a2790"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART","weight":5},{"input":"PART","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"P_PARTKEY","weight":5},{"input":"P_NAME","weight":5},{"input":"P_MFGR","weight":5},{"input":"P_BRAND","weight":5},{"input":"P_TYPE","weight":5},{"input":"P_SIZE","weight":5},{"input":"P_CONTAINER","weight":5},{"input":"P_RETAILPRICE","weight":5},{"input":"P_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF10","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":28},"monthlyStats":{"percentileRank":0.0,"count":28},"dailyStats":{"percentileRank":0.0,"count":28}}},"sort":[1662134410489000]},{"_index":"table_search_index","_type":"_doc","_id":"467d823f-4629-4bbf-9f4d-f610c44437ea","_score":null,"_source":{"id":"467d823f-4629-4bbf-9f4d-f610c44437ea","name":"PART","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART","description":"Part data as defined by TPC-H","version":0.1,"updatedAt":1662134409995,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/467d823f-4629-4bbf-9f4d-f610c44437ea","tableType":"Regular","columns":[{"name":"P_PARTKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART.P_PARTKEY","constraint":"NOT_NULL"},{"name":"P_NAME","dataType":"VARCHAR","dataLength":55,"dataTypeDisplay":"varchar(55)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART.P_NAME","constraint":"NOT_NULL"},{"name":"P_MFGR","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART.P_MFGR","constraint":"NOT_NULL"},{"name":"P_BRAND","dataType":"VARCHAR","dataLength":10,"dataTypeDisplay":"varchar(10)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART.P_BRAND","constraint":"NOT_NULL"},{"name":"P_TYPE","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART.P_TYPE","constraint":"NOT_NULL"},{"name":"P_SIZE","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART.P_SIZE","constraint":"NOT_NULL"},{"name":"P_CONTAINER","dataType":"VARCHAR","dataLength":10,"dataTypeDisplay":"varchar(10)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART.P_CONTAINER","constraint":"NOT_NULL"},{"name":"P_RETAILPRICE","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART.P_RETAILPRICE","constraint":"NOT_NULL"},{"name":"P_COMMENT","dataType":"VARCHAR","dataLength":23,"dataTypeDisplay":"varchar(23)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART.P_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"3de73d4c-904f-4e9a-b084-821e34da26f3","type":"databaseSchema","name":"TPCH_SF1","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/3de73d4c-904f-4e9a-b084-821e34da26f3"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART","weight":5},{"input":"PART","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"P_PARTKEY","weight":5},{"input":"P_NAME","weight":5},{"input":"P_MFGR","weight":5},{"input":"P_BRAND","weight":5},{"input":"P_TYPE","weight":5},{"input":"P_SIZE","weight":5},{"input":"P_CONTAINER","weight":5},{"input":"P_RETAILPRICE","weight":5},{"input":"P_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF1","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":28},"monthlyStats":{"percentileRank":0.0,"count":28},"dailyStats":{"percentileRank":0.0,"count":28}}},"sort":[1662134409995000]},{"_index":"table_search_index","_type":"_doc","_id":"b1bb6ccf-85ad-4d1d-b05a-73d0c9ef7e8a","_score":null,"_source":{"id":"b1bb6ccf-85ad-4d1d-b05a-73d0c9ef7e8a","name":"CUSTOMER","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER","description":"Customer data as defined by TPC-H","version":0.1,"updatedAt":1662134409239,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/b1bb6ccf-85ad-4d1d-b05a-73d0c9ef7e8a","tableType":"Regular","columns":[{"name":"C_CUSTKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER.C_CUSTKEY","constraint":"NOT_NULL"},{"name":"C_NAME","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER.C_NAME","constraint":"NOT_NULL"},{"name":"C_ADDRESS","dataType":"VARCHAR","dataLength":40,"dataTypeDisplay":"varchar(40)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER.C_ADDRESS","constraint":"NOT_NULL"},{"name":"C_NATIONKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER.C_NATIONKEY","constraint":"NOT_NULL"},{"name":"C_PHONE","dataType":"VARCHAR","dataLength":15,"dataTypeDisplay":"varchar(15)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER.C_PHONE","constraint":"NOT_NULL"},{"name":"C_ACCTBAL","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER.C_ACCTBAL","constraint":"NOT_NULL"},{"name":"C_MKTSEGMENT","dataType":"VARCHAR","dataLength":10,"dataTypeDisplay":"varchar(10)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER.C_MKTSEGMENT","constraint":"NULL"},{"name":"C_COMMENT","dataType":"VARCHAR","dataLength":117,"dataTypeDisplay":"varchar(117)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER.C_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"fd066fb9-ff76-4cd6-9d5c-c29765f3e38c","type":"databaseSchema","name":"TPCH_SF1000","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/fd066fb9-ff76-4cd6-9d5c-c29765f3e38c"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER","weight":5},{"input":"CUSTOMER","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"C_CUSTKEY","weight":5},{"input":"C_NAME","weight":5},{"input":"C_ADDRESS","weight":5},{"input":"C_NATIONKEY","weight":5},{"input":"C_PHONE","weight":5},{"input":"C_ACCTBAL","weight":5},{"input":"C_MKTSEGMENT","weight":5},{"input":"C_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF1000","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":28},"monthlyStats":{"percentileRank":0.0,"count":28},"dailyStats":{"percentileRank":0.0,"count":28}}},"sort":[1662134409239000]},{"_index":"table_search_index","_type":"_doc","_id":"cfe9d26d-560e-4809-8f38-5bb4f75c1661","_score":null,"_source":{"id":"cfe9d26d-560e-4809-8f38-5bb4f75c1661","name":"CUSTOMER","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER","description":"Customer data as defined by TPC-H","version":0.1,"updatedAt":1662134408633,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/cfe9d26d-560e-4809-8f38-5bb4f75c1661","tableType":"Regular","columns":[{"name":"C_CUSTKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER.C_CUSTKEY","constraint":"NOT_NULL"},{"name":"C_NAME","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER.C_NAME","constraint":"NOT_NULL"},{"name":"C_ADDRESS","dataType":"VARCHAR","dataLength":40,"dataTypeDisplay":"varchar(40)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER.C_ADDRESS","constraint":"NOT_NULL"},{"name":"C_NATIONKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER.C_NATIONKEY","constraint":"NOT_NULL"},{"name":"C_PHONE","dataType":"VARCHAR","dataLength":15,"dataTypeDisplay":"varchar(15)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER.C_PHONE","constraint":"NOT_NULL"},{"name":"C_ACCTBAL","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER.C_ACCTBAL","constraint":"NOT_NULL"},{"name":"C_MKTSEGMENT","dataType":"VARCHAR","dataLength":10,"dataTypeDisplay":"varchar(10)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER.C_MKTSEGMENT","constraint":"NULL"},{"name":"C_COMMENT","dataType":"VARCHAR","dataLength":117,"dataTypeDisplay":"varchar(117)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER.C_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"8e5eddb1-a4e9-41b3-a020-62ea25af6c75","type":"databaseSchema","name":"TPCH_SF100","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/8e5eddb1-a4e9-41b3-a020-62ea25af6c75"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER","weight":5},{"input":"CUSTOMER","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"C_CUSTKEY","weight":5},{"input":"C_NAME","weight":5},{"input":"C_ADDRESS","weight":5},{"input":"C_NATIONKEY","weight":5},{"input":"C_PHONE","weight":5},{"input":"C_ACCTBAL","weight":5},{"input":"C_MKTSEGMENT","weight":5},{"input":"C_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF100","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":28},"monthlyStats":{"percentileRank":0.0,"count":28},"dailyStats":{"percentileRank":0.0,"count":28}}},"sort":[1662134408633000]},{"_index":"table_search_index","_type":"_doc","_id":"6aba424d-c63d-454f-9058-b42cd3f6e7e6","_score":null,"_source":{"id":"6aba424d-c63d-454f-9058-b42cd3f6e7e6","name":"CUSTOMER","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER","description":"Customer data as defined by TPC-H","version":0.1,"updatedAt":1662134407965,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/6aba424d-c63d-454f-9058-b42cd3f6e7e6","tableType":"Regular","columns":[{"name":"C_CUSTKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER.C_CUSTKEY","constraint":"NOT_NULL"},{"name":"C_NAME","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","description":"Customer Name","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER.C_NAME","constraint":"NOT_NULL"},{"name":"C_ADDRESS","dataType":"VARCHAR","dataLength":40,"dataTypeDisplay":"varchar(40)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER.C_ADDRESS","constraint":"NOT_NULL"},{"name":"C_NATIONKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER.C_NATIONKEY","constraint":"NOT_NULL"},{"name":"C_PHONE","dataType":"VARCHAR","dataLength":15,"dataTypeDisplay":"varchar(15)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER.C_PHONE","constraint":"NOT_NULL"},{"name":"C_ACCTBAL","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER.C_ACCTBAL","constraint":"NOT_NULL"},{"name":"C_MKTSEGMENT","dataType":"VARCHAR","dataLength":10,"dataTypeDisplay":"varchar(10)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER.C_MKTSEGMENT","constraint":"NULL"},{"name":"C_COMMENT","dataType":"VARCHAR","dataLength":117,"dataTypeDisplay":"varchar(117)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER.C_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"dcc4d82e-9bb7-471a-97fd-6364937a2790","type":"databaseSchema","name":"TPCH_SF10","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/dcc4d82e-9bb7-471a-97fd-6364937a2790"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER","weight":5},{"input":"CUSTOMER","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"C_CUSTKEY","weight":5},{"input":"C_NAME","weight":5},{"input":"C_ADDRESS","weight":5},{"input":"C_NATIONKEY","weight":5},{"input":"C_PHONE","weight":5},{"input":"C_ACCTBAL","weight":5},{"input":"C_MKTSEGMENT","weight":5},{"input":"C_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF10","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":28},"monthlyStats":{"percentileRank":0.0,"count":28},"dailyStats":{"percentileRank":0.0,"count":28}}},"sort":[1662134407965000]},{"_index":"table_search_index","_type":"_doc","_id":"1d6e8f51-8a0b-4e93-9f86-fca0e5e7fc1e","_score":null,"_source":{"id":"1d6e8f51-8a0b-4e93-9f86-fca0e5e7fc1e","name":"CUSTOMER","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER","description":"Customer data as defined by TPC-H","version":0.1,"updatedAt":1662134407345,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/1d6e8f51-8a0b-4e93-9f86-fca0e5e7fc1e","tableType":"Regular","columns":[{"name":"C_CUSTKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER.C_CUSTKEY","constraint":"NOT_NULL"},{"name":"C_NAME","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER.C_NAME","constraint":"NOT_NULL"},{"name":"C_ADDRESS","dataType":"VARCHAR","dataLength":40,"dataTypeDisplay":"varchar(40)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER.C_ADDRESS","constraint":"NOT_NULL"},{"name":"C_NATIONKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER.C_NATIONKEY","constraint":"NOT_NULL"},{"name":"C_PHONE","dataType":"VARCHAR","dataLength":15,"dataTypeDisplay":"varchar(15)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER.C_PHONE","constraint":"NOT_NULL"},{"name":"C_ACCTBAL","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER.C_ACCTBAL","constraint":"NOT_NULL"},{"name":"C_MKTSEGMENT","dataType":"VARCHAR","dataLength":10,"dataTypeDisplay":"varchar(10)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER.C_MKTSEGMENT","constraint":"NULL"},{"name":"C_COMMENT","dataType":"VARCHAR","dataLength":117,"dataTypeDisplay":"varchar(117)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER.C_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"3de73d4c-904f-4e9a-b084-821e34da26f3","type":"databaseSchema","name":"TPCH_SF1","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/3de73d4c-904f-4e9a-b084-821e34da26f3"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER","weight":5},{"input":"CUSTOMER","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"C_CUSTKEY","weight":5},{"input":"C_NAME","weight":5},{"input":"C_ADDRESS","weight":5},{"input":"C_NATIONKEY","weight":5},{"input":"C_PHONE","weight":5},{"input":"C_ACCTBAL","weight":5},{"input":"C_MKTSEGMENT","weight":5},{"input":"C_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF1","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":28},"monthlyStats":{"percentileRank":0.0,"count":28},"dailyStats":{"percentileRank":0.0,"count":28}}},"sort":[1662134407345000]},{"_index":"table_search_index","_type":"_doc","_id":"603f9465-c6af-44f2-a0bb-171b9af9c7b3","_score":null,"_source":{"id":"603f9465-c6af-44f2-a0bb-171b9af9c7b3","name":"CUSTOMER","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER","version":0.1,"updatedAt":1662134406711,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/603f9465-c6af-44f2-a0bb-171b9af9c7b3","tableType":"Partitioned","columns":[{"name":"C_CUSTOMER_SK","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER.C_CUSTOMER_SK","constraint":"NOT_NULL"},{"name":"C_CUSTOMER_ID","dataType":"VARCHAR","dataLength":16,"dataTypeDisplay":"varchar(16)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER.C_CUSTOMER_ID","constraint":"NOT_NULL"},{"name":"C_CURRENT_CDEMO_SK","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER.C_CURRENT_CDEMO_SK","constraint":"NULL"},{"name":"C_CURRENT_HDEMO_SK","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER.C_CURRENT_HDEMO_SK","constraint":"NULL"},{"name":"C_CURRENT_ADDR_SK","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER.C_CURRENT_ADDR_SK","constraint":"NULL"},{"name":"C_FIRST_SHIPTO_DATE_SK","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER.C_FIRST_SHIPTO_DATE_SK","constraint":"NULL"},{"name":"C_FIRST_SALES_DATE_SK","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER.C_FIRST_SALES_DATE_SK","constraint":"NULL"},{"name":"C_SALUTATION","dataType":"VARCHAR","dataLength":10,"dataTypeDisplay":"varchar(10)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER.C_SALUTATION","constraint":"NULL"},{"name":"C_FIRST_NAME","dataType":"VARCHAR","dataLength":20,"dataTypeDisplay":"varchar(20)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER.C_FIRST_NAME","constraint":"NULL"},{"name":"C_LAST_NAME","dataType":"VARCHAR","dataLength":30,"dataTypeDisplay":"varchar(30)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER.C_LAST_NAME","constraint":"NULL"},{"name":"C_PREFERRED_CUST_FLAG","dataType":"VARCHAR","dataLength":1,"dataTypeDisplay":"varchar(1)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER.C_PREFERRED_CUST_FLAG","constraint":"NULL"},{"name":"C_BIRTH_DAY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER.C_BIRTH_DAY","constraint":"NULL"},{"name":"C_BIRTH_MONTH","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER.C_BIRTH_MONTH","constraint":"NULL"},{"name":"C_BIRTH_YEAR","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER.C_BIRTH_YEAR","constraint":"NULL"},{"name":"C_BIRTH_COUNTRY","dataType":"VARCHAR","dataLength":20,"dataTypeDisplay":"varchar(20)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER.C_BIRTH_COUNTRY","constraint":"NULL"},{"name":"C_LOGIN","dataType":"VARCHAR","dataLength":13,"dataTypeDisplay":"varchar(13)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER.C_LOGIN","constraint":"NULL"},{"name":"C_EMAIL_ADDRESS","dataType":"VARCHAR","dataLength":50,"dataTypeDisplay":"varchar(50)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER.C_EMAIL_ADDRESS","constraint":"NULL"},{"name":"C_LAST_REVIEW_DATE","dataType":"VARCHAR","dataLength":10,"dataTypeDisplay":"varchar(10)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER.C_LAST_REVIEW_DATE","constraint":"NULL"}],"tablePartition":{"columns":["C_CUSTOMER_SK"],"intervalType":"COLUMN-VALUE"},"databaseSchema":{"id":"dbaefcbb-9a18-48bd-ae9c-bfa5dd8096f8","type":"databaseSchema","name":"TPCDS_SF10TCL","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/dbaefcbb-9a18-48bd-ae9c-bfa5dd8096f8"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER","weight":5},{"input":"CUSTOMER","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"C_CUSTOMER_SK","weight":5},{"input":"C_CUSTOMER_ID","weight":5},{"input":"C_CURRENT_CDEMO_SK","weight":5},{"input":"C_CURRENT_HDEMO_SK","weight":5},{"input":"C_CURRENT_ADDR_SK","weight":5},{"input":"C_FIRST_SHIPTO_DATE_SK","weight":5},{"input":"C_FIRST_SALES_DATE_SK","weight":5},{"input":"C_SALUTATION","weight":5},{"input":"C_FIRST_NAME","weight":5},{"input":"C_LAST_NAME","weight":5},{"input":"C_PREFERRED_CUST_FLAG","weight":5},{"input":"C_BIRTH_DAY","weight":5},{"input":"C_BIRTH_MONTH","weight":5},{"input":"C_BIRTH_YEAR","weight":5},{"input":"C_BIRTH_COUNTRY","weight":5},{"input":"C_LOGIN","weight":5},{"input":"C_EMAIL_ADDRESS","weight":5},{"input":"C_LAST_REVIEW_DATE","weight":5}],"schema_suggest":[{"input":"TPCDS_SF10TCL","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":28},"monthlyStats":{"percentileRank":0.0,"count":28},"dailyStats":{"percentileRank":0.0,"count":28}}},"sort":[1662134406711000]},{"_index":"table_search_index","_type":"_doc","_id":"357858a2-6b27-48b5-b485-3375e40f84d8","_score":null,"_source":{"id":"357858a2-6b27-48b5-b485-3375e40f84d8","name":"CUSTOMER","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER","version":0.1,"updatedAt":1662134406085,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/357858a2-6b27-48b5-b485-3375e40f84d8","tableType":"Partitioned","columns":[{"name":"C_CUSTOMER_SK","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER.C_CUSTOMER_SK","constraint":"PRIMARY_KEY"},{"name":"C_CUSTOMER_ID","dataType":"VARCHAR","dataLength":16,"dataTypeDisplay":"varchar(16)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER.C_CUSTOMER_ID","constraint":"NOT_NULL"},{"name":"C_CURRENT_CDEMO_SK","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER.C_CURRENT_CDEMO_SK","constraint":"NULL"},{"name":"C_CURRENT_HDEMO_SK","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER.C_CURRENT_HDEMO_SK","constraint":"NULL"},{"name":"C_CURRENT_ADDR_SK","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER.C_CURRENT_ADDR_SK","constraint":"NULL"},{"name":"C_FIRST_SHIPTO_DATE_SK","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER.C_FIRST_SHIPTO_DATE_SK","constraint":"NULL"},{"name":"C_FIRST_SALES_DATE_SK","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER.C_FIRST_SALES_DATE_SK","constraint":"NULL"},{"name":"C_SALUTATION","dataType":"VARCHAR","dataLength":10,"dataTypeDisplay":"varchar(10)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER.C_SALUTATION","constraint":"NULL"},{"name":"C_FIRST_NAME","dataType":"VARCHAR","dataLength":20,"dataTypeDisplay":"varchar(20)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER.C_FIRST_NAME","constraint":"NULL"},{"name":"C_LAST_NAME","dataType":"VARCHAR","dataLength":30,"dataTypeDisplay":"varchar(30)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER.C_LAST_NAME","constraint":"NULL"},{"name":"C_PREFERRED_CUST_FLAG","dataType":"VARCHAR","dataLength":1,"dataTypeDisplay":"varchar(1)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER.C_PREFERRED_CUST_FLAG","constraint":"NULL"},{"name":"C_BIRTH_DAY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER.C_BIRTH_DAY","constraint":"NULL"},{"name":"C_BIRTH_MONTH","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER.C_BIRTH_MONTH","constraint":"NULL"},{"name":"C_BIRTH_YEAR","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER.C_BIRTH_YEAR","constraint":"NULL"},{"name":"C_BIRTH_COUNTRY","dataType":"VARCHAR","dataLength":20,"dataTypeDisplay":"varchar(20)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER.C_BIRTH_COUNTRY","constraint":"NULL"},{"name":"C_LOGIN","dataType":"VARCHAR","dataLength":13,"dataTypeDisplay":"varchar(13)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER.C_LOGIN","constraint":"NULL"},{"name":"C_EMAIL_ADDRESS","dataType":"VARCHAR","dataLength":50,"dataTypeDisplay":"varchar(50)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER.C_EMAIL_ADDRESS","constraint":"NULL"},{"name":"C_LAST_REVIEW_DATE","dataType":"VARCHAR","dataLength":10,"dataTypeDisplay":"varchar(10)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER.C_LAST_REVIEW_DATE","constraint":"NULL"}],"tableConstraints":[{"constraintType":"FOREIGN_KEY","columns":["C_CURRENT_ADDR_SK","C_CURRENT_CDEMO_SK","C_FIRST_SALES_DATE_SK","C_FIRST_SHIPTO_DATE_SK","C_CURRENT_HDEMO_SK"]}],"tablePartition":{"columns":["C_CUSTOMER_SK"],"intervalType":"COLUMN-VALUE"},"databaseSchema":{"id":"17d613a6-7fcf-40c6-832f-dd470f95f5ca","type":"databaseSchema","name":"TPCDS_SF100TCL","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/17d613a6-7fcf-40c6-832f-dd470f95f5ca"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER","weight":5},{"input":"CUSTOMER","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"C_CUSTOMER_SK","weight":5},{"input":"C_CUSTOMER_ID","weight":5},{"input":"C_CURRENT_CDEMO_SK","weight":5},{"input":"C_CURRENT_HDEMO_SK","weight":5},{"input":"C_CURRENT_ADDR_SK","weight":5},{"input":"C_FIRST_SHIPTO_DATE_SK","weight":5},{"input":"C_FIRST_SALES_DATE_SK","weight":5},{"input":"C_SALUTATION","weight":5},{"input":"C_FIRST_NAME","weight":5},{"input":"C_LAST_NAME","weight":5},{"input":"C_PREFERRED_CUST_FLAG","weight":5},{"input":"C_BIRTH_DAY","weight":5},{"input":"C_BIRTH_MONTH","weight":5},{"input":"C_BIRTH_YEAR","weight":5},{"input":"C_BIRTH_COUNTRY","weight":5},{"input":"C_LOGIN","weight":5},{"input":"C_EMAIL_ADDRESS","weight":5},{"input":"C_LAST_REVIEW_DATE","weight":5}],"schema_suggest":[{"input":"TPCDS_SF100TCL","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":28},"monthlyStats":{"percentileRank":0.0,"count":28},"dailyStats":{"percentileRank":0.0,"count":28}}},"sort":[1662134406085000]},{"_index":"table_search_index","_type":"_doc","_id":"ac64f0f7-ed4c-481a-a5fc-e6bbf6d8b906","_score":null,"_source":{"id":"ac64f0f7-ed4c-481a-a5fc-e6bbf6d8b906","name":"NATION","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.NATION","description":"Nation data as defined by TPC-H","version":0.1,"updatedAt":1662134405384,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/ac64f0f7-ed4c-481a-a5fc-e6bbf6d8b906","tableType":"Regular","columns":[{"name":"N_NATIONKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.NATION.N_NATIONKEY","constraint":"NOT_NULL"},{"name":"N_NAME","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.NATION.N_NAME","constraint":"NOT_NULL"},{"name":"N_REGIONKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.NATION.N_REGIONKEY","constraint":"NOT_NULL"},{"name":"N_COMMENT","dataType":"VARCHAR","dataLength":152,"dataTypeDisplay":"varchar(152)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.NATION.N_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"fd066fb9-ff76-4cd6-9d5c-c29765f3e38c","type":"databaseSchema","name":"TPCH_SF1000","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/fd066fb9-ff76-4cd6-9d5c-c29765f3e38c"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.NATION","weight":5},{"input":"NATION","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"N_NATIONKEY","weight":5},{"input":"N_NAME","weight":5},{"input":"N_REGIONKEY","weight":5},{"input":"N_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF1000","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":16},"monthlyStats":{"percentileRank":0.0,"count":16},"dailyStats":{"percentileRank":0.0,"count":16}}},"sort":[1662134405384000]},{"_index":"table_search_index","_type":"_doc","_id":"681c367d-61d1-4d49-8009-e884df5a5b37","_score":null,"_source":{"id":"681c367d-61d1-4d49-8009-e884df5a5b37","name":"NATION","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION","description":"Nation data as defined by TPC-H","version":0.1,"updatedAt":1662134405064,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/681c367d-61d1-4d49-8009-e884df5a5b37","tableType":"Regular","columns":[{"name":"N_NATIONKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION.N_NATIONKEY","constraint":"NOT_NULL"},{"name":"N_NAME","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION.N_NAME","constraint":"NOT_NULL"},{"name":"N_REGIONKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION.N_REGIONKEY","constraint":"NOT_NULL"},{"name":"N_COMMENT","dataType":"VARCHAR","dataLength":152,"dataTypeDisplay":"varchar(152)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION.N_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"dcc4d82e-9bb7-471a-97fd-6364937a2790","type":"databaseSchema","name":"TPCH_SF10","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/dcc4d82e-9bb7-471a-97fd-6364937a2790"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION","weight":5},{"input":"NATION","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"N_NATIONKEY","weight":5},{"input":"N_NAME","weight":5},{"input":"N_REGIONKEY","weight":5},{"input":"N_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF10","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":16},"monthlyStats":{"percentileRank":0.0,"count":16},"dailyStats":{"percentileRank":0.0,"count":16}}},"sort":[1662134405064000]},{"_index":"table_search_index","_type":"_doc","_id":"07b955d4-1acd-4c5a-88f5-6349e17c718c","_score":null,"_source":{"id":"07b955d4-1acd-4c5a-88f5-6349e17c718c","name":"NATION","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION","description":"Nation data as defined by TPC-H","version":0.1,"updatedAt":1662134404747,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/07b955d4-1acd-4c5a-88f5-6349e17c718c","tableType":"Regular","columns":[{"name":"N_NATIONKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION.N_NATIONKEY","constraint":"NOT_NULL"},{"name":"N_NAME","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION.N_NAME","constraint":"NOT_NULL"},{"name":"N_REGIONKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION.N_REGIONKEY","constraint":"NOT_NULL"},{"name":"N_COMMENT","dataType":"VARCHAR","dataLength":152,"dataTypeDisplay":"varchar(152)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION.N_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"8e5eddb1-a4e9-41b3-a020-62ea25af6c75","type":"databaseSchema","name":"TPCH_SF100","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/8e5eddb1-a4e9-41b3-a020-62ea25af6c75"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION","weight":5},{"input":"NATION","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"N_NATIONKEY","weight":5},{"input":"N_NAME","weight":5},{"input":"N_REGIONKEY","weight":5},{"input":"N_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF100","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":16},"monthlyStats":{"percentileRank":0.0,"count":16},"dailyStats":{"percentileRank":0.0,"count":16}}},"sort":[1662134404747000]},{"_index":"table_search_index","_type":"_doc","_id":"c088399b-5bd1-4ece-bab3-f7b2af2c0eda","_score":null,"_source":{"id":"c088399b-5bd1-4ece-bab3-f7b2af2c0eda","name":"NATION","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION","description":"Nation data as defined by TPC-H","version":0.1,"updatedAt":1662134404374,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/c088399b-5bd1-4ece-bab3-f7b2af2c0eda","tableType":"Regular","columns":[{"name":"N_NATIONKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION.N_NATIONKEY","constraint":"NOT_NULL"},{"name":"N_NAME","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION.N_NAME","constraint":"NOT_NULL"},{"name":"N_REGIONKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION.N_REGIONKEY","constraint":"NOT_NULL"},{"name":"N_COMMENT","dataType":"VARCHAR","dataLength":152,"dataTypeDisplay":"varchar(152)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION.N_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"3de73d4c-904f-4e9a-b084-821e34da26f3","type":"databaseSchema","name":"TPCH_SF1","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/3de73d4c-904f-4e9a-b084-821e34da26f3"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION","weight":5},{"input":"NATION","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"N_NATIONKEY","weight":5},{"input":"N_NAME","weight":5},{"input":"N_REGIONKEY","weight":5},{"input":"N_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF1","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":16},"monthlyStats":{"percentileRank":0.0,"count":16},"dailyStats":{"percentileRank":0.0,"count":16}}},"sort":[1662134404374000]},{"_index":"table_search_index","_type":"_doc","_id":"23359b61-3152-4cbb-8049-2240d5c846c4","_score":null,"_source":{"id":"23359b61-3152-4cbb-8049-2240d5c846c4","name":"NEW_USERS","fullyQualifiedName":"snow.NEWDB.PUBLIC.NEW_USERS","version":0.1,"updatedAt":1662134403919,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/23359b61-3152-4cbb-8049-2240d5c846c4","tableType":"Regular","columns":[{"name":"ID","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.NEWDB.PUBLIC.NEW_USERS.ID","constraint":"NULL"},{"name":"NAME","dataType":"VARCHAR","dataLength":50,"dataTypeDisplay":"varchar(50)","fullyQualifiedName":"snow.NEWDB.PUBLIC.NEW_USERS.NAME","constraint":"NULL"},{"name":"FULLNAME","dataType":"VARCHAR","dataLength":50,"dataTypeDisplay":"varchar(50)","fullyQualifiedName":"snow.NEWDB.PUBLIC.NEW_USERS.FULLNAME","constraint":"NULL"},{"name":"NICKNAME","dataType":"VARCHAR","dataLength":50,"dataTypeDisplay":"varchar(50)","fullyQualifiedName":"snow.NEWDB.PUBLIC.NEW_USERS.NICKNAME","constraint":"NULL"},{"name":"COMMENTS","dataType":"VARCHAR","dataLength":100,"dataTypeDisplay":"varchar(100)","fullyQualifiedName":"snow.NEWDB.PUBLIC.NEW_USERS.COMMENTS","constraint":"NULL"},{"name":"AGE","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.NEWDB.PUBLIC.NEW_USERS.AGE","constraint":"NULL"}],"databaseSchema":{"id":"1da7e3b4-762a-4aa8-87e8-e88fe9f8652d","type":"databaseSchema","name":"PUBLIC","fullyQualifiedName":"snow.NEWDB.PUBLIC","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/1da7e3b4-762a-4aa8-87e8-e88fe9f8652d"},"database":{"id":"f53cbd09-d2b1-41c1-aecb-b4f110136e5a","type":"database","name":"NEWDB","fullyQualifiedName":"snow.NEWDB","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/f53cbd09-d2b1-41c1-aecb-b4f110136e5a"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.NEWDB.PUBLIC.NEW_USERS","weight":5},{"input":"NEW_USERS","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"ID","weight":5},{"input":"NAME","weight":5},{"input":"FULLNAME","weight":5},{"input":"NICKNAME","weight":5},{"input":"COMMENTS","weight":5},{"input":"AGE","weight":5}],"schema_suggest":[{"input":"PUBLIC","weight":5}],"database_suggest":[{"input":"NEWDB","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":20},"monthlyStats":{"percentileRank":0.0,"count":20},"dailyStats":{"percentileRank":0.0,"count":20}}},"sort":[1662134403919000]},{"_index":"table_search_index","_type":"_doc","_id":"39bff745-9011-4374-af8e-0e54d679f03e","_score":null,"_source":{"id":"39bff745-9011-4374-af8e-0e54d679f03e","name":"REGION","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.REGION","description":"Region data as defined by TPC-H","version":0.1,"updatedAt":1662134403560,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/39bff745-9011-4374-af8e-0e54d679f03e","tableType":"Regular","columns":[{"name":"R_REGIONKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.REGION.R_REGIONKEY","constraint":"NOT_NULL"},{"name":"R_NAME","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.REGION.R_NAME","constraint":"NOT_NULL"},{"name":"R_COMMENT","dataType":"VARCHAR","dataLength":152,"dataTypeDisplay":"varchar(152)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.REGION.R_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"8e5eddb1-a4e9-41b3-a020-62ea25af6c75","type":"databaseSchema","name":"TPCH_SF100","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/8e5eddb1-a4e9-41b3-a020-62ea25af6c75"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.REGION","weight":5},{"input":"REGION","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"R_REGIONKEY","weight":5},{"input":"R_NAME","weight":5},{"input":"R_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF100","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":14},"monthlyStats":{"percentileRank":0.0,"count":14},"dailyStats":{"percentileRank":0.0,"count":14}}},"sort":[1662134403560000]},{"_index":"table_search_index","_type":"_doc","_id":"4493b51f-c67a-42fb-af31-6ecc976abe4c","_score":null,"_source":{"id":"4493b51f-c67a-42fb-af31-6ecc976abe4c","name":"REGION","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.REGION","description":"Region data as defined by TPC-H","version":0.1,"updatedAt":1662134403314,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/4493b51f-c67a-42fb-af31-6ecc976abe4c","tableType":"Regular","columns":[{"name":"R_REGIONKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.REGION.R_REGIONKEY","constraint":"NOT_NULL"},{"name":"R_NAME","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.REGION.R_NAME","constraint":"NOT_NULL"},{"name":"R_COMMENT","dataType":"VARCHAR","dataLength":152,"dataTypeDisplay":"varchar(152)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.REGION.R_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"fd066fb9-ff76-4cd6-9d5c-c29765f3e38c","type":"databaseSchema","name":"TPCH_SF1000","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/fd066fb9-ff76-4cd6-9d5c-c29765f3e38c"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.REGION","weight":5},{"input":"REGION","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"R_REGIONKEY","weight":5},{"input":"R_NAME","weight":5},{"input":"R_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF1000","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":14},"monthlyStats":{"percentileRank":0.0,"count":14},"dailyStats":{"percentileRank":0.0,"count":14}}},"sort":[1662134403314000]},{"_index":"table_search_index","_type":"_doc","_id":"13516892-bf62-455d-ba9c-f235d693a031","_score":null,"_source":{"id":"13516892-bf62-455d-ba9c-f235d693a031","name":"REGION","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.REGION","description":"Region data as defined by TPC-H","version":0.1,"updatedAt":1662134403055,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/13516892-bf62-455d-ba9c-f235d693a031","tableType":"Regular","columns":[{"name":"R_REGIONKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.REGION.R_REGIONKEY","constraint":"NOT_NULL"},{"name":"R_NAME","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.REGION.R_NAME","constraint":"NOT_NULL"},{"name":"R_COMMENT","dataType":"VARCHAR","dataLength":152,"dataTypeDisplay":"varchar(152)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.REGION.R_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"dcc4d82e-9bb7-471a-97fd-6364937a2790","type":"databaseSchema","name":"TPCH_SF10","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/dcc4d82e-9bb7-471a-97fd-6364937a2790"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.REGION","weight":5},{"input":"REGION","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"R_REGIONKEY","weight":5},{"input":"R_NAME","weight":5},{"input":"R_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF10","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":14},"monthlyStats":{"percentileRank":0.0,"count":14},"dailyStats":{"percentileRank":0.0,"count":14}}},"sort":[1662134403055000]},{"_index":"table_search_index","_type":"_doc","_id":"77408c54-f48b-474e-a347-8c01708da59f","_score":null,"_source":{"id":"77408c54-f48b-474e-a347-8c01708da59f","name":"REGION","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION","description":"Region data as defined by TPC-H","version":0.1,"updatedAt":1662134402773,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/77408c54-f48b-474e-a347-8c01708da59f","tableType":"Regular","columns":[{"name":"R_REGIONKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION.R_REGIONKEY","constraint":"NOT_NULL"},{"name":"R_NAME","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION.R_NAME","constraint":"NOT_NULL"},{"name":"R_COMMENT","dataType":"VARCHAR","dataLength":152,"dataTypeDisplay":"varchar(152)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION.R_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"3de73d4c-904f-4e9a-b084-821e34da26f3","type":"databaseSchema","name":"TPCH_SF1","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/3de73d4c-904f-4e9a-b084-821e34da26f3"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION","weight":5},{"input":"REGION","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"R_REGIONKEY","weight":5},{"input":"R_NAME","weight":5},{"input":"R_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF1","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":14},"monthlyStats":{"percentileRank":0.0,"count":14},"dailyStats":{"percentileRank":0.0,"count":14}}},"sort":[1662134402773000]},{"_index":"table_search_index","_type":"_doc","_id":"210adf74-f310-4292-bee0-50ab7d794b28","_score":null,"_source":{"id":"210adf74-f310-4292-bee0-50ab7d794b28","name":"SUPPLIER","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.SUPPLIER","description":"Supplier data as defined by TPC-H","version":0.1,"updatedAt":1662134401637,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/210adf74-f310-4292-bee0-50ab7d794b28","tableType":"Regular","columns":[{"name":"S_SUPPKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.SUPPLIER.S_SUPPKEY","constraint":"NOT_NULL"},{"name":"S_NAME","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.SUPPLIER.S_NAME","constraint":"NOT_NULL"},{"name":"S_ADDRESS","dataType":"VARCHAR","dataLength":40,"dataTypeDisplay":"varchar(40)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.SUPPLIER.S_ADDRESS","constraint":"NOT_NULL"},{"name":"S_NATIONKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.SUPPLIER.S_NATIONKEY","constraint":"NOT_NULL"},{"name":"S_PHONE","dataType":"VARCHAR","dataLength":15,"dataTypeDisplay":"varchar(15)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.SUPPLIER.S_PHONE","constraint":"NOT_NULL"},{"name":"S_ACCTBAL","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.SUPPLIER.S_ACCTBAL","constraint":"NOT_NULL"},{"name":"S_COMMENT","dataType":"VARCHAR","dataLength":101,"dataTypeDisplay":"varchar(101)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.SUPPLIER.S_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"fd066fb9-ff76-4cd6-9d5c-c29765f3e38c","type":"databaseSchema","name":"TPCH_SF1000","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/fd066fb9-ff76-4cd6-9d5c-c29765f3e38c"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.SUPPLIER","weight":5},{"input":"SUPPLIER","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"S_SUPPKEY","weight":5},{"input":"S_NAME","weight":5},{"input":"S_ADDRESS","weight":5},{"input":"S_NATIONKEY","weight":5},{"input":"S_PHONE","weight":5},{"input":"S_ACCTBAL","weight":5},{"input":"S_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF1000","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":21},"monthlyStats":{"percentileRank":0.0,"count":21},"dailyStats":{"percentileRank":0.0,"count":21}}},"sort":[1662134401637000]},{"_index":"table_search_index","_type":"_doc","_id":"982c7e0e-c4ef-4658-ad56-f9987f0fcfeb","_score":null,"_source":{"id":"982c7e0e-c4ef-4658-ad56-f9987f0fcfeb","name":"SUPPLIER","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.SUPPLIER","description":"Supplier data as defined by TPC-H","version":0.1,"updatedAt":1662134401225,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/982c7e0e-c4ef-4658-ad56-f9987f0fcfeb","tableType":"Regular","columns":[{"name":"S_SUPPKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.SUPPLIER.S_SUPPKEY","constraint":"NOT_NULL"},{"name":"S_NAME","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.SUPPLIER.S_NAME","constraint":"NOT_NULL"},{"name":"S_ADDRESS","dataType":"VARCHAR","dataLength":40,"dataTypeDisplay":"varchar(40)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.SUPPLIER.S_ADDRESS","constraint":"NOT_NULL"},{"name":"S_NATIONKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.SUPPLIER.S_NATIONKEY","constraint":"NOT_NULL"},{"name":"S_PHONE","dataType":"VARCHAR","dataLength":15,"dataTypeDisplay":"varchar(15)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.SUPPLIER.S_PHONE","constraint":"NOT_NULL"},{"name":"S_ACCTBAL","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.SUPPLIER.S_ACCTBAL","constraint":"NOT_NULL"},{"name":"S_COMMENT","dataType":"VARCHAR","dataLength":101,"dataTypeDisplay":"varchar(101)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.SUPPLIER.S_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"8e5eddb1-a4e9-41b3-a020-62ea25af6c75","type":"databaseSchema","name":"TPCH_SF100","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/8e5eddb1-a4e9-41b3-a020-62ea25af6c75"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.SUPPLIER","weight":5},{"input":"SUPPLIER","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"S_SUPPKEY","weight":5},{"input":"S_NAME","weight":5},{"input":"S_ADDRESS","weight":5},{"input":"S_NATIONKEY","weight":5},{"input":"S_PHONE","weight":5},{"input":"S_ACCTBAL","weight":5},{"input":"S_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF100","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":21},"monthlyStats":{"percentileRank":0.0,"count":21},"dailyStats":{"percentileRank":0.0,"count":21}}},"sort":[1662134401225000]},{"_index":"table_search_index","_type":"_doc","_id":"d1936390-1e0c-4cff-be13-2c475e36706d","_score":null,"_source":{"id":"d1936390-1e0c-4cff-be13-2c475e36706d","name":"SUPPLIER","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER","description":"Supplier data as defined by TPC-H","version":0.1,"updatedAt":1662134400750,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/d1936390-1e0c-4cff-be13-2c475e36706d","tableType":"Regular","columns":[{"name":"S_SUPPKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER.S_SUPPKEY","constraint":"NOT_NULL"},{"name":"S_NAME","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER.S_NAME","constraint":"NOT_NULL"},{"name":"S_ADDRESS","dataType":"VARCHAR","dataLength":40,"dataTypeDisplay":"varchar(40)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER.S_ADDRESS","constraint":"NOT_NULL"},{"name":"S_NATIONKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER.S_NATIONKEY","constraint":"NOT_NULL"},{"name":"S_PHONE","dataType":"VARCHAR","dataLength":15,"dataTypeDisplay":"varchar(15)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER.S_PHONE","constraint":"NOT_NULL"},{"name":"S_ACCTBAL","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER.S_ACCTBAL","constraint":"NOT_NULL"},{"name":"S_COMMENT","dataType":"VARCHAR","dataLength":101,"dataTypeDisplay":"varchar(101)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER.S_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"dcc4d82e-9bb7-471a-97fd-6364937a2790","type":"databaseSchema","name":"TPCH_SF10","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/dcc4d82e-9bb7-471a-97fd-6364937a2790"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER","weight":5},{"input":"SUPPLIER","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"S_SUPPKEY","weight":5},{"input":"S_NAME","weight":5},{"input":"S_ADDRESS","weight":5},{"input":"S_NATIONKEY","weight":5},{"input":"S_PHONE","weight":5},{"input":"S_ACCTBAL","weight":5},{"input":"S_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF10","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":21},"monthlyStats":{"percentileRank":0.0,"count":21},"dailyStats":{"percentileRank":0.0,"count":21}}},"sort":[1662134400750000]},{"_index":"table_search_index","_type":"_doc","_id":"de3754b2-b0a0-4c21-9b6e-d65a9bfc8e69","_score":null,"_source":{"id":"de3754b2-b0a0-4c21-9b6e-d65a9bfc8e69","name":"SUPPLIER","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER","description":"Supplier data as defined by TPC-H","version":0.1,"updatedAt":1662134400323,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/de3754b2-b0a0-4c21-9b6e-d65a9bfc8e69","tableType":"Regular","columns":[{"name":"S_SUPPKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER.S_SUPPKEY","constraint":"NOT_NULL"},{"name":"S_NAME","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER.S_NAME","constraint":"NOT_NULL"},{"name":"S_ADDRESS","dataType":"VARCHAR","dataLength":40,"dataTypeDisplay":"varchar(40)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER.S_ADDRESS","constraint":"NOT_NULL"},{"name":"S_NATIONKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER.S_NATIONKEY","constraint":"NOT_NULL"},{"name":"S_PHONE","dataType":"VARCHAR","dataLength":15,"dataTypeDisplay":"varchar(15)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER.S_PHONE","constraint":"NOT_NULL"},{"name":"S_ACCTBAL","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER.S_ACCTBAL","constraint":"NOT_NULL"},{"name":"S_COMMENT","dataType":"VARCHAR","dataLength":101,"dataTypeDisplay":"varchar(101)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER.S_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"3de73d4c-904f-4e9a-b084-821e34da26f3","type":"databaseSchema","name":"TPCH_SF1","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/3de73d4c-904f-4e9a-b084-821e34da26f3"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER","weight":5},{"input":"SUPPLIER","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"S_SUPPKEY","weight":5},{"input":"S_NAME","weight":5},{"input":"S_ADDRESS","weight":5},{"input":"S_NATIONKEY","weight":5},{"input":"S_PHONE","weight":5},{"input":"S_ACCTBAL","weight":5},{"input":"S_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF1","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":21},"monthlyStats":{"percentileRank":0.0,"count":21},"dailyStats":{"percentileRank":0.0,"count":21}}},"sort":[1662134400323000]},{"_index":"table_search_index","_type":"_doc","_id":"36dd6c62-8311-4274-833c-9dfafad84baa","_score":null,"_source":{"id":"36dd6c62-8311-4274-833c-9dfafad84baa","name":"NEW_CUSTOMER","fullyQualifiedName":"snow.NEWDB.PUBLIC.NEW_CUSTOMER","version":0.1,"updatedAt":1662134399891,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/36dd6c62-8311-4274-833c-9dfafad84baa","tableType":"Regular","columns":[{"name":"C_CUSTKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.NEWDB.PUBLIC.NEW_CUSTOMER.C_CUSTKEY","constraint":"NULL"},{"name":"C_NAME","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.NEWDB.PUBLIC.NEW_CUSTOMER.C_NAME","constraint":"NULL"},{"name":"C_ADDRESS","dataType":"VARCHAR","dataLength":40,"dataTypeDisplay":"varchar(40)","fullyQualifiedName":"snow.NEWDB.PUBLIC.NEW_CUSTOMER.C_ADDRESS","constraint":"NULL"},{"name":"C_NATIONKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.NEWDB.PUBLIC.NEW_CUSTOMER.C_NATIONKEY","constraint":"NULL"},{"name":"C_PHONE","dataType":"VARCHAR","dataLength":15,"dataTypeDisplay":"varchar(15)","fullyQualifiedName":"snow.NEWDB.PUBLIC.NEW_CUSTOMER.C_PHONE","constraint":"NULL"},{"name":"C_ACCTBAL","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.NEWDB.PUBLIC.NEW_CUSTOMER.C_ACCTBAL","constraint":"NULL"},{"name":"C_MKTSEGMENT","dataType":"VARCHAR","dataLength":10,"dataTypeDisplay":"varchar(10)","fullyQualifiedName":"snow.NEWDB.PUBLIC.NEW_CUSTOMER.C_MKTSEGMENT","constraint":"NULL"},{"name":"C_COMMENT","dataType":"VARCHAR","dataLength":117,"dataTypeDisplay":"varchar(117)","fullyQualifiedName":"snow.NEWDB.PUBLIC.NEW_CUSTOMER.C_COMMENT","constraint":"NULL"}],"databaseSchema":{"id":"1da7e3b4-762a-4aa8-87e8-e88fe9f8652d","type":"databaseSchema","name":"PUBLIC","fullyQualifiedName":"snow.NEWDB.PUBLIC","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/1da7e3b4-762a-4aa8-87e8-e88fe9f8652d"},"database":{"id":"f53cbd09-d2b1-41c1-aecb-b4f110136e5a","type":"database","name":"NEWDB","fullyQualifiedName":"snow.NEWDB","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/f53cbd09-d2b1-41c1-aecb-b4f110136e5a"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.NEWDB.PUBLIC.NEW_CUSTOMER","weight":5},{"input":"NEW_CUSTOMER","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"C_CUSTKEY","weight":5},{"input":"C_NAME","weight":5},{"input":"C_ADDRESS","weight":5},{"input":"C_NATIONKEY","weight":5},{"input":"C_PHONE","weight":5},{"input":"C_ACCTBAL","weight":5},{"input":"C_MKTSEGMENT","weight":5},{"input":"C_COMMENT","weight":5}],"schema_suggest":[{"input":"PUBLIC","weight":5}],"database_suggest":[{"input":"NEWDB","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":22},"monthlyStats":{"percentileRank":0.0,"count":22},"dailyStats":{"percentileRank":0.0,"count":22}}},"sort":[1662134399891000]},{"_index":"table_search_index","_type":"_doc","_id":"f3eb45ec-859a-4107-8f21-1675ed18fbbe","_score":null,"_source":{"id":"f3eb45ec-859a-4107-8f21-1675ed18fbbe","name":"LINEITEM","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM","description":"Lineitem data as defined by TPC-H","version":0.1,"updatedAt":1662134399396,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/f3eb45ec-859a-4107-8f21-1675ed18fbbe","tableType":"Partitioned","columns":[{"name":"L_ORDERKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM.L_ORDERKEY","constraint":"NOT_NULL"},{"name":"L_PARTKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM.L_PARTKEY","constraint":"NOT_NULL"},{"name":"L_SUPPKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM.L_SUPPKEY","constraint":"NOT_NULL"},{"name":"L_LINENUMBER","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM.L_LINENUMBER","constraint":"NOT_NULL"},{"name":"L_QUANTITY","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM.L_QUANTITY","constraint":"NOT_NULL"},{"name":"L_EXTENDEDPRICE","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM.L_EXTENDEDPRICE","constraint":"NOT_NULL"},{"name":"L_DISCOUNT","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM.L_DISCOUNT","constraint":"NOT_NULL"},{"name":"L_TAX","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM.L_TAX","constraint":"NOT_NULL"},{"name":"L_RETURNFLAG","dataType":"VARCHAR","dataLength":1,"dataTypeDisplay":"varchar(1)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM.L_RETURNFLAG","constraint":"NOT_NULL"},{"name":"L_LINESTATUS","dataType":"VARCHAR","dataLength":1,"dataTypeDisplay":"varchar(1)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM.L_LINESTATUS","constraint":"NOT_NULL"},{"name":"L_SHIPDATE","dataType":"DATE","dataLength":1,"dataTypeDisplay":"date","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM.L_SHIPDATE","constraint":"NOT_NULL"},{"name":"L_COMMITDATE","dataType":"DATE","dataLength":1,"dataTypeDisplay":"date","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM.L_COMMITDATE","constraint":"NOT_NULL"},{"name":"L_RECEIPTDATE","dataType":"DATE","dataLength":1,"dataTypeDisplay":"date","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM.L_RECEIPTDATE","constraint":"NOT_NULL"},{"name":"L_SHIPINSTRUCT","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM.L_SHIPINSTRUCT","constraint":"NOT_NULL"},{"name":"L_SHIPMODE","dataType":"VARCHAR","dataLength":10,"dataTypeDisplay":"varchar(10)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM.L_SHIPMODE","constraint":"NOT_NULL"},{"name":"L_COMMENT","dataType":"VARCHAR","dataLength":44,"dataTypeDisplay":"varchar(44)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM.L_COMMENT","constraint":"NOT_NULL"}],"tablePartition":{"columns":["L_SHIPDATE"],"intervalType":"COLUMN-VALUE"},"databaseSchema":{"id":"fd066fb9-ff76-4cd6-9d5c-c29765f3e38c","type":"databaseSchema","name":"TPCH_SF1000","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/fd066fb9-ff76-4cd6-9d5c-c29765f3e38c"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM","weight":5},{"input":"LINEITEM","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"L_ORDERKEY","weight":5},{"input":"L_PARTKEY","weight":5},{"input":"L_SUPPKEY","weight":5},{"input":"L_LINENUMBER","weight":5},{"input":"L_QUANTITY","weight":5},{"input":"L_EXTENDEDPRICE","weight":5},{"input":"L_DISCOUNT","weight":5},{"input":"L_TAX","weight":5},{"input":"L_RETURNFLAG","weight":5},{"input":"L_LINESTATUS","weight":5},{"input":"L_SHIPDATE","weight":5},{"input":"L_COMMITDATE","weight":5},{"input":"L_RECEIPTDATE","weight":5},{"input":"L_SHIPINSTRUCT","weight":5},{"input":"L_SHIPMODE","weight":5},{"input":"L_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF1000","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":53},"monthlyStats":{"percentileRank":0.0,"count":53},"dailyStats":{"percentileRank":0.0,"count":53}}},"sort":[1662134399396000]},{"_index":"table_search_index","_type":"_doc","_id":"f6629c93-e9fa-4693-902a-e19b8dee8f38","_score":null,"_source":{"id":"f6629c93-e9fa-4693-902a-e19b8dee8f38","name":"LINEITEM","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM","description":"Lineitem data as defined by TPC-H","version":0.1,"updatedAt":1662134398278,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/f6629c93-e9fa-4693-902a-e19b8dee8f38","tableType":"Regular","columns":[{"name":"L_ORDERKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM.L_ORDERKEY","constraint":"NOT_NULL"},{"name":"L_PARTKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM.L_PARTKEY","constraint":"NOT_NULL"},{"name":"L_SUPPKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM.L_SUPPKEY","constraint":"NOT_NULL"},{"name":"L_LINENUMBER","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM.L_LINENUMBER","constraint":"NOT_NULL"},{"name":"L_QUANTITY","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM.L_QUANTITY","constraint":"NOT_NULL"},{"name":"L_EXTENDEDPRICE","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM.L_EXTENDEDPRICE","constraint":"NOT_NULL"},{"name":"L_DISCOUNT","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM.L_DISCOUNT","constraint":"NOT_NULL"},{"name":"L_TAX","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM.L_TAX","constraint":"NOT_NULL"},{"name":"L_RETURNFLAG","dataType":"VARCHAR","dataLength":1,"dataTypeDisplay":"varchar(1)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM.L_RETURNFLAG","constraint":"NOT_NULL"},{"name":"L_LINESTATUS","dataType":"VARCHAR","dataLength":1,"dataTypeDisplay":"varchar(1)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM.L_LINESTATUS","constraint":"NOT_NULL"},{"name":"L_SHIPDATE","dataType":"DATE","dataLength":1,"dataTypeDisplay":"date","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM.L_SHIPDATE","constraint":"NOT_NULL"},{"name":"L_COMMITDATE","dataType":"DATE","dataLength":1,"dataTypeDisplay":"date","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM.L_COMMITDATE","constraint":"NOT_NULL"},{"name":"L_RECEIPTDATE","dataType":"DATE","dataLength":1,"dataTypeDisplay":"date","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM.L_RECEIPTDATE","constraint":"NOT_NULL"},{"name":"L_SHIPINSTRUCT","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM.L_SHIPINSTRUCT","constraint":"NOT_NULL"},{"name":"L_SHIPMODE","dataType":"VARCHAR","dataLength":10,"dataTypeDisplay":"varchar(10)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM.L_SHIPMODE","constraint":"NOT_NULL"},{"name":"L_COMMENT","dataType":"VARCHAR","dataLength":44,"dataTypeDisplay":"varchar(44)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM.L_COMMENT","constraint":"NOT_NULL"}],"databaseSchema":{"id":"8e5eddb1-a4e9-41b3-a020-62ea25af6c75","type":"databaseSchema","name":"TPCH_SF100","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/8e5eddb1-a4e9-41b3-a020-62ea25af6c75"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM","weight":5},{"input":"LINEITEM","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"L_ORDERKEY","weight":5},{"input":"L_PARTKEY","weight":5},{"input":"L_SUPPKEY","weight":5},{"input":"L_LINENUMBER","weight":5},{"input":"L_QUANTITY","weight":5},{"input":"L_EXTENDEDPRICE","weight":5},{"input":"L_DISCOUNT","weight":5},{"input":"L_TAX","weight":5},{"input":"L_RETURNFLAG","weight":5},{"input":"L_LINESTATUS","weight":5},{"input":"L_SHIPDATE","weight":5},{"input":"L_COMMITDATE","weight":5},{"input":"L_RECEIPTDATE","weight":5},{"input":"L_SHIPINSTRUCT","weight":5},{"input":"L_SHIPMODE","weight":5},{"input":"L_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF100","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":53},"monthlyStats":{"percentileRank":0.0,"count":53},"dailyStats":{"percentileRank":0.0,"count":53}}},"sort":[1662134398278000]},{"_index":"table_search_index","_type":"_doc","_id":"cbd1629d-774a-4de0-9a18-ba40d9863d13","_score":null,"_source":{"id":"cbd1629d-774a-4de0-9a18-ba40d9863d13","name":"LINEITEM","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM","description":"Lineitem data as defined by TPC-H","version":0.1,"updatedAt":1662134397073,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/cbd1629d-774a-4de0-9a18-ba40d9863d13","tableType":"Regular","columns":[{"name":"L_ORDERKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_ORDERKEY","constraint":"NOT_NULL"},{"name":"L_PARTKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_PARTKEY","constraint":"NOT_NULL"},{"name":"L_SUPPKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_SUPPKEY","constraint":"NOT_NULL"},{"name":"L_LINENUMBER","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_LINENUMBER","constraint":"NOT_NULL"},{"name":"L_QUANTITY","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_QUANTITY","constraint":"NOT_NULL"},{"name":"L_EXTENDEDPRICE","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_EXTENDEDPRICE","constraint":"NOT_NULL"},{"name":"L_DISCOUNT","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_DISCOUNT","constraint":"NOT_NULL"},{"name":"L_TAX","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_TAX","constraint":"NOT_NULL"},{"name":"L_RETURNFLAG","dataType":"VARCHAR","dataLength":1,"dataTypeDisplay":"varchar(1)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_RETURNFLAG","constraint":"NOT_NULL"},{"name":"L_LINESTATUS","dataType":"VARCHAR","dataLength":1,"dataTypeDisplay":"varchar(1)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_LINESTATUS","constraint":"NOT_NULL"},{"name":"L_SHIPDATE","dataType":"DATE","dataLength":1,"dataTypeDisplay":"date","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_SHIPDATE","constraint":"NOT_NULL"},{"name":"L_COMMITDATE","dataType":"DATE","dataLength":1,"dataTypeDisplay":"date","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_COMMITDATE","constraint":"NOT_NULL"},{"name":"L_RECEIPTDATE","dataType":"DATE","dataLength":1,"dataTypeDisplay":"date","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_RECEIPTDATE","constraint":"NOT_NULL"},{"name":"L_SHIPINSTRUCT","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_SHIPINSTRUCT","constraint":"NOT_NULL"},{"name":"L_SHIPMODE","dataType":"VARCHAR","dataLength":10,"dataTypeDisplay":"varchar(10)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_SHIPMODE","constraint":"NOT_NULL"},{"name":"L_COMMENT","dataType":"VARCHAR","dataLength":44,"dataTypeDisplay":"varchar(44)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM.L_COMMENT","constraint":"NOT_NULL"}],"databaseSchema":{"id":"dcc4d82e-9bb7-471a-97fd-6364937a2790","type":"databaseSchema","name":"TPCH_SF10","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/dcc4d82e-9bb7-471a-97fd-6364937a2790"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM","weight":5},{"input":"LINEITEM","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"L_ORDERKEY","weight":5},{"input":"L_PARTKEY","weight":5},{"input":"L_SUPPKEY","weight":5},{"input":"L_LINENUMBER","weight":5},{"input":"L_QUANTITY","weight":5},{"input":"L_EXTENDEDPRICE","weight":5},{"input":"L_DISCOUNT","weight":5},{"input":"L_TAX","weight":5},{"input":"L_RETURNFLAG","weight":5},{"input":"L_LINESTATUS","weight":5},{"input":"L_SHIPDATE","weight":5},{"input":"L_COMMITDATE","weight":5},{"input":"L_RECEIPTDATE","weight":5},{"input":"L_SHIPINSTRUCT","weight":5},{"input":"L_SHIPMODE","weight":5},{"input":"L_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF10","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":53},"monthlyStats":{"percentileRank":0.0,"count":53},"dailyStats":{"percentileRank":0.0,"count":53}}},"sort":[1662134397073000]},{"_index":"table_search_index","_type":"_doc","_id":"6644441f-0f4c-455b-b8e1-83912f5404bc","_score":null,"_source":{"id":"6644441f-0f4c-455b-b8e1-83912f5404bc","name":"LINEITEM","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM","description":"Lineitem data as defined by TPC-H","version":0.1,"updatedAt":1662134395917,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/6644441f-0f4c-455b-b8e1-83912f5404bc","tableType":"Regular","columns":[{"name":"L_ORDERKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM.L_ORDERKEY","constraint":"NOT_NULL"},{"name":"L_PARTKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM.L_PARTKEY","constraint":"NOT_NULL"},{"name":"L_SUPPKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM.L_SUPPKEY","constraint":"NOT_NULL"},{"name":"L_LINENUMBER","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM.L_LINENUMBER","constraint":"NOT_NULL"},{"name":"L_QUANTITY","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM.L_QUANTITY","constraint":"NOT_NULL"},{"name":"L_EXTENDEDPRICE","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM.L_EXTENDEDPRICE","constraint":"NOT_NULL"},{"name":"L_DISCOUNT","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM.L_DISCOUNT","constraint":"NOT_NULL"},{"name":"L_TAX","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM.L_TAX","constraint":"NOT_NULL"},{"name":"L_RETURNFLAG","dataType":"VARCHAR","dataLength":1,"dataTypeDisplay":"varchar(1)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM.L_RETURNFLAG","constraint":"NOT_NULL"},{"name":"L_LINESTATUS","dataType":"VARCHAR","dataLength":1,"dataTypeDisplay":"varchar(1)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM.L_LINESTATUS","constraint":"NOT_NULL"},{"name":"L_SHIPDATE","dataType":"DATE","dataLength":1,"dataTypeDisplay":"date","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM.L_SHIPDATE","constraint":"NOT_NULL"},{"name":"L_COMMITDATE","dataType":"DATE","dataLength":1,"dataTypeDisplay":"date","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM.L_COMMITDATE","constraint":"NOT_NULL"},{"name":"L_RECEIPTDATE","dataType":"DATE","dataLength":1,"dataTypeDisplay":"date","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM.L_RECEIPTDATE","constraint":"NOT_NULL"},{"name":"L_SHIPINSTRUCT","dataType":"VARCHAR","dataLength":25,"dataTypeDisplay":"varchar(25)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM.L_SHIPINSTRUCT","constraint":"NOT_NULL"},{"name":"L_SHIPMODE","dataType":"VARCHAR","dataLength":10,"dataTypeDisplay":"varchar(10)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM.L_SHIPMODE","constraint":"NOT_NULL"},{"name":"L_COMMENT","dataType":"VARCHAR","dataLength":44,"dataTypeDisplay":"varchar(44)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM.L_COMMENT","constraint":"NOT_NULL"}],"databaseSchema":{"id":"3de73d4c-904f-4e9a-b084-821e34da26f3","type":"databaseSchema","name":"TPCH_SF1","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/3de73d4c-904f-4e9a-b084-821e34da26f3"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM","weight":5},{"input":"LINEITEM","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"L_ORDERKEY","weight":5},{"input":"L_PARTKEY","weight":5},{"input":"L_SUPPKEY","weight":5},{"input":"L_LINENUMBER","weight":5},{"input":"L_QUANTITY","weight":5},{"input":"L_EXTENDEDPRICE","weight":5},{"input":"L_DISCOUNT","weight":5},{"input":"L_TAX","weight":5},{"input":"L_RETURNFLAG","weight":5},{"input":"L_LINESTATUS","weight":5},{"input":"L_SHIPDATE","weight":5},{"input":"L_COMMITDATE","weight":5},{"input":"L_RECEIPTDATE","weight":5},{"input":"L_SHIPINSTRUCT","weight":5},{"input":"L_SHIPMODE","weight":5},{"input":"L_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF1","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":53},"monthlyStats":{"percentileRank":0.0,"count":53},"dailyStats":{"percentileRank":0.0,"count":53}}},"sort":[1662134395917000]},{"_index":"table_search_index","_type":"_doc","_id":"d6437e6b-e871-48a9-b42c-5b16a2af38ef","_score":null,"_source":{"id":"d6437e6b-e871-48a9-b42c-5b16a2af38ef","name":"ORDERS","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS","description":"Orders data as defined by TPC-H","version":0.1,"updatedAt":1662134394449,"updatedBy":"pere-om-sa","href":"http://openmetadata-server:8585/api/v1/tables/d6437e6b-e871-48a9-b42c-5b16a2af38ef","tableType":"Partitioned","columns":[{"name":"O_ORDERKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS.O_ORDERKEY","constraint":"NOT_NULL"},{"name":"O_CUSTKEY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS.O_CUSTKEY","constraint":"NOT_NULL"},{"name":"O_ORDERSTATUS","dataType":"VARCHAR","dataLength":1,"dataTypeDisplay":"varchar(1)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS.O_ORDERSTATUS","constraint":"NOT_NULL"},{"name":"O_TOTALPRICE","dataType":"DECIMAL","dataLength":1,"precision":12,"scale":2,"dataTypeDisplay":"decimal(12,2)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS.O_TOTALPRICE","constraint":"NOT_NULL"},{"name":"O_ORDERDATE","dataType":"DATE","dataLength":1,"dataTypeDisplay":"date","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS.O_ORDERDATE","constraint":"NOT_NULL"},{"name":"O_ORDERPRIORITY","dataType":"VARCHAR","dataLength":15,"dataTypeDisplay":"varchar(15)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS.O_ORDERPRIORITY","constraint":"NOT_NULL"},{"name":"O_CLERK","dataType":"VARCHAR","dataLength":15,"dataTypeDisplay":"varchar(15)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS.O_CLERK","constraint":"NOT_NULL"},{"name":"O_SHIPPRIORITY","dataType":"DECIMAL","dataLength":1,"precision":38,"scale":0,"dataTypeDisplay":"decimal(38,0)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS.O_SHIPPRIORITY","constraint":"NOT_NULL"},{"name":"O_COMMENT","dataType":"VARCHAR","dataLength":79,"dataTypeDisplay":"varchar(79)","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS.O_COMMENT","constraint":"NOT_NULL"}],"tablePartition":{"columns":["O_ORDERDATE"],"intervalType":"COLUMN-VALUE"},"databaseSchema":{"id":"fd066fb9-ff76-4cd6-9d5c-c29765f3e38c","type":"databaseSchema","name":"TPCH_SF1000","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databaseSchemas/fd066fb9-ff76-4cd6-9d5c-c29765f3e38c"},"database":{"id":"1162c12e-47ff-4547-b7e0-50f5fd3d193d","type":"database","name":"SNOWFLAKE_SAMPLE_DATA","fullyQualifiedName":"snow.SNOWFLAKE_SAMPLE_DATA","deleted":false,"href":"http://openmetadata-server:8585/api/v1/databases/1162c12e-47ff-4547-b7e0-50f5fd3d193d"},"service":{"id":"7800a7b5-5d98-4494-ae8f-f5e598a6d495","type":"databaseService","name":"snow","fullyQualifiedName":"snow","description":"","deleted":false,"href":"http://openmetadata-server:8585/api/v1/services/databaseServices/7800a7b5-5d98-4494-ae8f-f5e598a6d495"},"serviceType":"Snowflake","deleted":false,"tags":[],"tier":null,"followers":[],"suggest":[{"input":"snow.SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS","weight":5},{"input":"ORDERS","weight":10}],"service_suggest":[{"input":"snow","weight":5}],"column_suggest":[{"input":"O_ORDERKEY","weight":5},{"input":"O_CUSTKEY","weight":5},{"input":"O_ORDERSTATUS","weight":5},{"input":"O_TOTALPRICE","weight":5},{"input":"O_ORDERDATE","weight":5},{"input":"O_ORDERPRIORITY","weight":5},{"input":"O_CLERK","weight":5},{"input":"O_SHIPPRIORITY","weight":5},{"input":"O_COMMENT","weight":5}],"schema_suggest":[{"input":"TPCH_SF1000","weight":5}],"database_suggest":[{"input":"SNOWFLAKE_SAMPLE_DATA","weight":5}],"entityType":"table","usageSummary":{"date":"2022-09-01","weeklyStats":{"percentileRank":0.0,"count":29},"monthlyStats":{"percentileRank":0.0,"count":29},"dailyStats":{"percentileRank":0.0,"count":29}}},"sort":[1662134394449000]}]},"aggregations":{"sterms#EntityType":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"table","doc_count":153}]},"sterms#ServiceCategory":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"databaseService","doc_count":153}]},"sterms#Tier":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[]},"sterms#ServiceName":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"snow","doc_count":153}]},"sterms#Database":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"SNOWFLAKE_SAMPLE_DATA","doc_count":86},{"key":"COVID19_BY_STARSCHEMA_DM","doc_count":43},{"key":"MYDB","doc_count":12},{"key":"NEWDB","doc_count":6},{"key":"OMTESTDB","doc_count":4},{"key":"TESTDB","doc_count":2}]},"sterms#Service":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"Snowflake","doc_count":153}]},"sterms#Tags":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[]},"sterms#DatabaseSchema":{"doc_count_error_upper_bound":0,"sum_other_doc_count":2,"buckets":[{"key":"PUBLIC","doc_count":53},{"key":"TPCDS_SF10TCL","doc_count":25},{"key":"TPCDS_SF100TCL","doc_count":24},{"key":"MYSCHEMA","doc_count":8},{"key":"TPCH_SF1","doc_count":8},{"key":"TPCH_SF10","doc_count":8},{"key":"TPCH_SF100","doc_count":8},{"key":"TPCH_SF1000","doc_count":8},{"key":"WEATHER","doc_count":5},{"key":"TEST_CLUSTER","doc_count":4}]}}}
```

### PR DESCRIPTION
**Pull request by aniketkatkar97**
### Describe your changes :

I worked on fixing the issue with soft deleted tables showing on the schema details page.
I also added pagination support for the tables list.
closes #7173 

#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :
<p align="center">

https://user-images.githubusercontent.com/51777795/205881365-6c43b862-80a2-494e-a978-d220851faf98.mov

</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

Frontend: @open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx [hunk 1]
```diff
@@ -323,6 +323,23 @@ const DatabaseSchemaPage: FunctionComponent = () => {
       });
   };
 
+  const getSchemaTables = async (pageNumber: string | number) => {
+    try {
+      setCurrentTablesPage(pageNumber as number);
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx:328]:
```suggestion
      setCurrentTablesPage(toNumber(pageNumber));
```

File: openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx [hunk 2]
```diff
@@ -323,6 +323,23 @@ const DatabaseSchemaPage: FunctionComponent = () => {
...
+      const res = await searchQuery({
+        pageNumber: pageNumber as number,
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx:330]:
```suggestion
        pageNumber: toNumber(pageNumber),
```

File: openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx [hunk 3]
```diff
@@ -323,6 +323,23 @@ const DatabaseSchemaPage: FunctionComponent = () => {
...
+        pageSize: PAGE_SIZE,
+        queryFilter: { 'databaseSchema.name': databaseSchema?.name },
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx:332]:
```suggestion
        queryFilter: { 'databaseSchema.name': databaseSchema?.name??"" },
```

File: openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx [hunk 4]
```diff
@@ -616,6 +643,7 @@ const DatabaseSchemaPage: FunctionComponent = () => {
         activeTabHandler(1);
       }
       getDetailsByFQN();
+      getSchemaTables(INITIAL_PAGING_VALUE);
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx:646]: I would recommend only making this api call if databaseSchema data is available.

File: openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx (hunk 1 above)
Comment (aniketkatkar97) [reply openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx]: Done

File: openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx (hunk 3 above)
Comment (aniketkatkar97) [reply openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx]: Done

File: openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx (hunk 4 above)
Comment (aniketkatkar97) [reply openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx]: Made the suggested changes. Can you please review?

**Review by Sachin-chaurasiya — APPROVED** [review]

**Review by ShaileshParmar11 — APPROVED** [review]
