### PR TITLE
fix: add application enable disable state

### LINKED ISSUE #13829: ui: enable application workflow
- [ ] currently we dont have any workflow to enable the disabled application from ui also once the application is disabled we dont show it anywhere in OM.
- [ ] Once application is disabled, i am getting option to install the application in market place and if i try to install the application, its throwing entity already exist error.

### PR DESCRIPTION
**Pull request by karanh37**
### Describe your changes:

Fixes #13829 

I worked on ... because ...

https://github.com/open-metadata/OpenMetadata/assets/33024356/e1a1edd5-61ea-4885-9350-f75b4ed3a0d3

#
### Type of change:

- [x] Improvement

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/Applications/AppDetails/AppDetails.component.tsx [hunk 1]
```diff
@@ -446,6 +502,31 @@ const AppDetails = () => {
...
+        })}
+        onCancel={() => {
+          setShowReactiveModal(false);
+        }}
+        onOk={handleRestore}>
+        <Typography.Text data-testid="restore-modal-body">
+          {t('message.are-you-sure-want-to-enable', {
+            entity: appData ? getEntityName(appData) : '',
+          })}
+        </Typography.Text>
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Applications/AppDetails/AppDetails.component.tsx:528]: Can you see if we can use this component here? `ConfirmationModal`

File: openmetadata-ui/src/main/resources/ui/src/components/Applications/AppDetails/AppDetails.component.tsx [hunk 2]
```diff
@@ -327,6 +386,18 @@ const AppDetails = () => {
...
   }, [appData, jsonSchema]);
 
+  const actionText = useMemo(() => {
+    if (action === AppAction.ENABLE) {
+      return t('label.enable-lowercase');
+    } else if (action === AppAction.DISABLE) {
+      return t('label.disable-lowercase');
+    } else if (action === AppAction.UNINSTALL) {
+      return t('label.uninstall-lowercase');
+    }
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Applications/AppDetails/AppDetails.component.tsx:396]: switch case will fit better here

**Review by chirag-madlani — APPROVED** [review]
