### PR TITLE
Fixes #14252 : Check tasks cannot be created by,assigned to,reassigned to bot users

### LINKED ISSUE #14252: Add Tests for Feed When Creating Task the user should not be bot
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by sonika-shah**
### Describe your changes:

Fixes <#14252>

- Added validation checks for assigning and reassigning tasks to ensure that the assignee is not a bot user.
- Implemented validation to prevent task creation by bot users.
- Created test cases covering each scenario to verify the correctness of the implemented changes.

#
### Type of change:

- [x] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.
- [x] I have added a test that covers the exact scenario we are fixing. For complex issues, comment the issue number in the test for future reference.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java [hunk 1]
```diff
@@ -836,6 +838,16 @@ private void validateAnnouncement(Thread thread) {
     }
   }
 
+  private void validateTaskByNonBotUser(Thread thread) {
```
Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java:841]: @sonika-shah lets make this check in populateAssignees method

Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java:841]: sure @harshach but we can also place it in validateAssignees method, because it contains with the validation logic and throwing exception

Comment (harshach) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java:841]: @sonika-shah sounds good. Ad it in validateAssignees itself

Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java]: changes done - added logic in validateAssignees method

**Review by mohityadav766 — APPROVED** [review]
