### PR TITLE
Fixes Incorrect Classification of Tier Tags for tags containing word …

### LINKED ISSUE #9693: unrelated tags containting tier show up under Tier search refinement category
**Affected module**
UI

**Describe the bug**
Tags that contain the string "Tier" (e.g. Business Tier) show up under "Tier" search refinement category, even thought they are part of different tag category.

**To Reproduce**

image

**Expected behavior**
Only Tier1-5 show up under "Tier" tag category.

**Version:**
 - OS: Chrome
 - OpenMetadata version: 0.13.1

### PR DESCRIPTION
**Pull request by mohityadav766**
…"Tier"

### Describe your changes :

Fixes #9693

#
### Type of change :

- [x] Bug fix

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/ElasticSearchIndexDefinition.java [hunk 1]
```diff
@@ -272,9 +272,12 @@ class ParseTags {
     if (!tags.isEmpty()) {
       List<TagLabel> tagsList = new ArrayList<>(tags);
       for (TagLabel tag : tagsList) {
-        if (tag.getTagFQN().toLowerCase().matches("(.*)tier(.*)")) {
-          tierTag = tag;
-          break;
+        if (tag.getTagFQN().contains(".")) {
```
Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/ElasticSearchIndexDefinition.java:275]: Cant we just containsIgnoreCase

Comment (mohityadav766) [reply openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/ElasticSearchIndexDefinition.java]: yeah that should also do it

**Review by harshach — APPROVED** [review]

File: openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/ElasticSearchIndexDefinition.java [hunk 2]
```diff
@@ -272,7 +272,8 @@ class ParseTags {
     if (!tags.isEmpty()) {
       List<TagLabel> tagsList = new ArrayList<>(tags);
       for (TagLabel tag : tagsList) {
-        if (tag.getTagFQN().toLowerCase().matches("(.*)tier(.*)")) {
+        String tier = tag.getTagFQN().split("\\.")[0];
+        if (tier.equalsIgnoreCase("tier")) {
```
Comment (sureshms) [inline openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/ElasticSearchIndexDefinition.java:276]: @mohityadav766 let's use `FullyQualifiedName.getRoot()` method for this. That way we are using a method that is tested to get the root of the FQN instead of doing split in different parts of the code. All FQN processing should happen with that util class.
