### PR TITLE
fix(ui): Format row count and decimal values across the profiler and DQ

### LINKED ISSUE #24572: Profiler 0 values are shown as null.
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by shah-harshit**
### Describe your changes:

It fixes #24572 and #24619 

Comma separated values for row count
Screenshot 2025-12-02 at 12 07 23 PM

Percentage values should have maximum two decimal points
Screenshot 2025-12-02 at 12 07 49 PM

Show empty data instead of 0 in table

Issue
Screenshot 2025-12-02 at 7 35 14 PM

Fix
Screenshot 2025-12-02 at 7 36 52 PM

I worked on ... because ...

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/DataQuality/SummaryPannel/SummaryPieChartCard/SummaryPieChartCard.component.tsx [hunk 1]
```diff
@@ -106,7 +106,7 @@ const SummaryPieChartCard = ({
               textAnchor="middle"
               x="50%"
               y="50%">
-              {`${percentage}%`}
+              {percentage}
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/src/components/DataQuality/SummaryPannel/SummaryPieChartCard/SummaryPieChartCard.component.tsx:109]: we have't wrap this in calculate percentage method also removed the % indicator. can you please double check if its expected?

Comment (shah-harshit) [reply openmetadata-ui/src/main/resources/ui/src/components/DataQuality/SummaryPannel/SummaryPieChartCard/SummaryPieChartCard.component.tsx:109]: Yes, we are getting percentage from props and we have wrapped it in calculate percentage along with the format param so we will receive the formatted percentage string here.

File: openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/ColumnProfileTable/ColumnProfileTable.tsx
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/ColumnProfileTable/ColumnProfileTable.tsx:1]: We need undefined check in this table.

Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/ColumnProfileTable/ColumnProfileTable.tsx:1]: Image

**Review by ShaileshParmar11 — APPROVED** [review]
