### PR TITLE
Fix #16493 :User Deletion Error in Search - Adding Conditional Check

### LINKED ISSUE #16493: Issue with Removing Document from Search Index When Deleting User
**Affected module**
backend

**Describe the bug**
When attempting to delete a user, we encounter an error where the corresponding document fails to be removed from the search index.

```
ERROR [2024-05-30 07:02:30,186] [dw-204 - DELETE /api/v1/users/1bedc6cd-4ce9-4eae-bf4e-e034dfda7f1b?hardDelete=true&recursive=false] 
o.o.s.s.SearchRepository - Issue in Deleting the search document for entityID [1bedc6cd-4ce9-4eae-bf4e-e034dfda7f1b] and entityType [user]. 
Reason[Validation Failed: 1: use _all if you really want to delete from all existing indexes;], Cause[null], Stack [os.org.opensearch.action.ActionRequestValidationException: Validation Failed: 1: use _all if you really want to delete from all existing indexes;
	at os.org.opensearch.action.ValidateActions.addValidationError(ValidateActions.java:44)
	at os.org.opensearch.index.reindex.DeleteByQueryRequest.validate(DeleteByQueryRequest.java:156)
	at os.org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1873)
	at os.org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1845)
	at os.org.opensearch.client.RestHighLevelClient.deleteByQuery(RestHighLevelClient.java:505)
	at org.openmetadata.service.search.opensearch.OpenSearchClient.deleteEntityFromOpenSearchByQuery(OpenSearchClient.java:1608)

```
**To Reproduce**

When deleting user permanently.
image

**Expected behavior**
The error in the log should not be present

**Version:**
 - Python version:
 - OpenMetadata version: 1.4.0
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by sonika-shah**
### Describe your changes:

Fixes #16493
Added additional check before user deletion from search

#
### Type of change:

- [x] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Review by harshach — DISMISSED** [review]

File: openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java [hunk 1]
```diff
@@ -586,9 +586,12 @@ public void deleteOrUpdateChildren(EntityInterface entity, IndexMapping indexMap
             List.of(new ImmutablePair<>("service.id", docId)));
       }
       default -> {
-        searchClient.deleteEntityByFields(
-            indexMapping.getChildAliases(clusterAlias),
-            List.of(new ImmutablePair<>(entityType + ".id", docId)));
+        List<String> indexNames = indexMapping.getChildAliases(clusterAlias);
+        if (!indexNames.isEmpty()) {
+          searchClient.deleteEntityByFields(
+              indexMapping.getChildAliases(clusterAlias),
```
Comment (TeddyCr) [inline openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java:592]: can't we just pass the `indexNames` here (vs calling `indexMapping.getChildAliases(clusterAlias)` again?)

Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java]: yes @TeddyCr , did the change.  thanks!

**Review by TeddyCr — APPROVED** [review]
