### PR TITLE
Fix #25342: Unapproved Terms should not be linked during bulk import

### LINKED ISSUE #25342: Unapproved Glossary Terms Can Be Linked via Import/Export
**Affected module**
Does it impact the UI, backend or Ingestion Framework? - Backend

**Describe the bug**
- We have identified an issue where unapproved glossary terms can be linked to:
 - the Related Terms field, or
 -Data Assets
 when using the Import/Export process.

This behavior is incorrect. Only approved glossary terms should be allowed to be linked or associated.

**To Reproduce**
- Add an unapproved term in the CSV & Perform Import at the Glossary or data asset level

Screenshots or steps to reproduce

**Expected behavior**
- Only approved glossary terms should be linked using Import/Export:
 - Related Terms
 - Data Assets

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by yan-3005**
### Describe your changes:

Fixes [#25342](https://github.com/open-metadata/OpenMetadata/issues/25342)

Importing in Database Schema
image

Importing at Glossary
image

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

---
## Summary by Gitar

- **Fixed validation bug:** Prevents unapproved glossary terms (status `IN_REVIEW`) from being linked during CSV bulk import operations to data assets and as related terms
- **New validation method:** `getEntityReferencesForGlossaryTerms()` in `EntityCsv.java` validates `EntityStatus.APPROVED` before allowing glossary term references during CSV processing
- **Updated import flow:** `GlossaryRepository.java` now uses the new validation method for related terms field during glossary CSV import
- **Comprehensive test coverage:** Added 4 integration tests across `DatabaseSchemaResourceIT` and `GlossaryResourceIT` verifying both approved terms succeed and unapproved terms fail with appropriate error messages

<sub>This summary will update automatically on new commits.</sub>

---

### CODE REVIEW

File: openmetadata-integration-tests/src/test/java/org/openmetadata/it/tests/DatabaseSchemaResourceIT.java [hunk 1]
```diff
@@ -1291,4 +1293,199 @@ void testBulk_AdminCanOverrideDescription(TestNamespace ns) {
...
+
+    // Create CSV with the unapproved glossary term
+    String csv =
+        "name*,displayName,description,owner,tags,glossaryTerms,tiers,certification,retentionPeriod,sourceUrl,domains,extension\n"
+            + ns.prefix("testTable")
+            + ",Test Table,Updated description,,,\""
+            + inReviewTerm.getFullyQualifiedName()
+            + "\",,,,,,";
+
+    log.info("TEST: CSV to import:\n{}", csv);
```
Comment (sonika-shah) [inline openmetadata-integration-tests/src/test/java/org/openmetadata/it/tests/DatabaseSchemaResourceIT.java:1375]: @yan-3005 can we remove these logs please

**Comment by yan-3005** [comment]
@gitar-bot Fixed your review comments, review again

File: openmetadata-integration-tests/src/test/java/org/openmetadata/it/tests/DatabaseSchemaResourceIT.java (hunk 1 above)
Comment (yan-3005) [reply openmetadata-integration-tests/src/test/java/org/openmetadata/it/tests/DatabaseSchemaResourceIT.java:1375]: @sonika-shah Yes removed them

**Review by sonika-shah — APPROVED** [review]

**Comment by yan-3005** [comment]
Cherry Picked to 1.11.7
