### PR TITLE
#14067: Recursive true while soft deletion and deleted entity version page bug fixes

### LINKED ISSUE #14067: DatabaseSchema Restore operation throws error EntityNotFound, if a table that belongs to schema is already restored
**Affected module**
It is impacting Ingestion Framework of public schema

**Describe the bug**
Cant restated the deleted schema of 'public' & also it is showing table instance for 004aa994-6a2b-414d-b093-e84ee6d20022 not found when restore.

**Screenshots**

[
image
image (1)
image (2)
](url)

**Version:**

 - OpenMetadata version: [1.2.2]

### PR DESCRIPTION
**Pull request by aniketkatkar97**
### Describe your changes:

Fixes #14067 

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/ListView/ListView.component.tsx [hunk 1]
```diff
@@ -59,20 +61,33 @@ export const ListView = <T extends object = any>({
...
+          <span>
+            <Switch
+              checked={deleted}
+              data-testid="show-deleted-switch"
+              onChange={handleDeletedSwitchChange}
+            />
+            <Typography.Text className="m-l-xs">
+              {t('label.deleted')}
+            </Typography.Text>
+          </span>
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/ListView/ListView.component.tsx:74]: This should be a conditional render, It's common component so we can't keep adding things. We can make it based on props only

**Review by chirag-madlani — DISMISSED** [review]
