### PR TITLE
Fix: #16742 - allow all the tier tags to be assign on entity 

### LINKED ISSUE #16742: new Tier Option is updating the tag but NOT the tier
**Affected module**
1.4.5 and below

**Describe the bug**
I have created a new Tier TAG:
https://sandbox-beta.open-metadata.org/tags/Tier

**To Reproduce**

This Tag if added, adds on the TAGs, but Tier says No Tier:
image

**Expected behavior**
**Tier Tags are added as Tier**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by chirag-madlani**
### Describe your changes:

Fixes #16742 

https://github.com/open-metadata/OpenMetadata/assets/12962843/bff05cb7-0b3e-43fe-9650-c7726a8939f4

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/playwright/support/tag/TagClass.ts [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+  //         headers: {
+  //           'Content-Type': 'application/json-patch+json',
+  //         },
+  //       }
+  //     );
+
+  //     this.responseData = await response.json();
+
+  //     return await response.json();
+  //   }
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/playwright/support/tag/TagClass.ts:87]: lets remove if not needed!

File: openmetadata-ui/src/main/resources/ui/playwright/support/tag/TagClass.ts [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+type ResponseDataType = {
+  name: string;
+  displayName: string;
+  description: string;
+  reviewers: unknown[];
+  relatedTerms: unknown[];
+  synonyms: unknown[];
+  mutuallyExclusive: boolean;
+  tags: unknown[];
+  glossary: Record<string, string>;
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/playwright/support/tag/TagClass.ts:26]: I think it should be classification

File: openmetadata-ui/src/main/resources/ui/playwright/support/tag/TagClass.ts [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+
+  responseData: ResponseDataType;
+
+  constructor(tag: Partial<TagData>) {
+    this.data.classification = tag.classification ?? this.data.classification;
+  }
+
+  async visitPage(page: Page) {
+    await visitClassificationPage(page, this.responseData.glossary.displayName);
+  }
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/playwright/support/tag/TagClass.ts:61]: here as well

File: openmetadata-ui/src/main/resources/ui/playwright/utils/tag.ts [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+import { sidebarClick } from './sidebar';
+
+export const visitClassificationPage = async (
+  page: Page,
+  classificationName: string
+) => {
+  await redirectToHomePage(page);
+  const glossaryResponse = page.waitForResponse('/api/v1/glossaries?fields=*');
+  await sidebarClick(page, SidebarItem.GLOSSARY);
+  await glossaryResponse;
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/playwright/utils/tag.ts:25]: It should be related to classification.

**Review by ShaileshParmar11 — COMMENTED** [review]
few comments

**Review by ShaileshParmar11 — APPROVED** [review]
