### PR TITLE
fix#10859: permission issue in test suite details page

### LINKED ISSUE #10859: User with Create, Delete , edit all permissions cannot edit or delete data quality test rules.
**Affected module**
UI- verson 13.2.5

**Describe the bug**
We have a Data Steward Policy, with create, delete, edit all access. But, users are not able to edit the test(after creation) and deleting the tests. Please guide.

**To Reproduce**

Screenshots 
image

image
image

policy evaluation results :

{
    "resource": "table",
    "permissions": [
        {
            "operation": "Create",
            "access": "allow",
            "rule": {
                "name": "DataStewardPolicy-EditRule",
                "effect": "allow",
                "operations": [
                    "Create",
                    "Delete",
                    "EditAll",
                    "ViewAll"
                ],
                "resources": [
                    "all"
                ]
            },
            "policy": "DataStewardPolicy",
            "role": "DataSteward"
        },
        {
            "operation": "Delete",
            "access": "allow",
            "rule": {
                "name": "DataStewardPolicy-EditRule",
                "effect": "allow",
                "operations": [
                    "Create",
                    "Delete",
                    "EditAll",
                    "ViewAll"
                ],
                "resources": [
                    "all"
                ]
            },
            "policy": "DataStewardPolicy",
            "role": "DataSteward"
        },
        {
            "operation": "ViewAll",
            "access": "allow",
            "rule": {
                "name": "DataStewardPolicy-EditRule",
                "effect": "allow",
                "operations": [
                    "Create",
                    "Delete",
                    "EditAll",
                    "ViewAll"
                ],
                "resources": [
                    "all"
                ]
            },
            "policy": "DataStewardPolicy",
            "role": "DataSteward"
        },
        {
            "operation": "ViewBasic",
            "access": "allow",
            "rule": {
                "name": "DataStewardPolicy-EditRule",
                "effect": "allow",
                "operations": [
                    "Create",
                    "Delete",
                    "EditAll",
                    "ViewAll"
                ],
                "resources": [
                    "all"
                ]
            },
            "policy": "DataStewardPolicy",
            "role": "DataSteward"
        },
        {
            "operation": "ViewUsage",
            "access": "allow",
            "rule": {
                "name": "DataStewardPolicy-EditRule",
                "effect": "allow",
                "operations": [
                    "Create",
                    "Delete",
                    "EditAll",
                    "ViewAll"
                ],
                "resources": [
                    "all"
                ]
            },
            "policy": "DataStewardPolicy",
            "role": "DataSteward"
        },
        {
            "operation": "ViewTests",
            "access": "allow",
            "rule": {
                "name": "DataStewardPolicy-EditRule",
                "effect": "allow",
                "operations": [
                    "Create",
                    "Delete",
                    "EditAll",
                    "ViewAll"
                ],
                "resources": [
                    "all"
                ]
            },
            "policy": "DataStewardPolicy",
            "role": "DataSteward"
        },
        {
            "operation": "ViewQueries",
            "access": "allow",
            "rule": {
                "name": "DataStewardPolicy-EditRule",
                "effect": "allow",
                "operations": [
                    "Create",
                    "Delete",
                    "EditAll",
                    "ViewAll"
                ],
                "resources": [
                    "all"
                ]
            },
            "policy": "DataStewardPolicy",
            "role": "DataSteward"
        },
        {
            "operation": "ViewDataProfile",
            "access": "allow",
            "rule": {
                "name": "DataStewardPolicy-EditRule",
                "effect": "allow",
                "operations": [
                    "Create",
                    "Delete",
                    "EditAll",
                    "ViewAll"
                ],
                "resources": [
                    "all"
                ]
            },
            "policy": "DataStewardPolicy",
            "role": "DataSteward"
        },
        {
            "operation": "ViewSampleData",
            "access": "allow",
            "rule": {
                "name": "DataStewardPolicy-EditRule",
                "effect": "allow",
                "operations": [
                    "Create",
                    "Delete",
                    "EditAll",
                    "ViewAll"
                ],
                "resources": [
                    "all"
                ]
            },
            "policy": "DataStewardPolicy",
            "role": "DataSteward"
        },
        {
            "operation": "EditAll",
            "access": "allow",
            "rule": {
                "name": "DataStewardPolicy-EditRule",
                "effect": "allow",
                "operations": [
                    "Create",
                    "Delete",
                    "EditAll",
                    "ViewAll"
                ],
                "resources": [
                    "all"
                ]
            },
            "policy": "DataStewardPolicy",
            "role": "DataSteward"
        },
        {
            "operation": "EditDescription",
            "access": "allow",
            "rule": {
                "name": "DataStewardPolicy-EditRule",
                "effect": "allow",
                "operations": [
                    "Create",
                    "Delete",
                    "EditAll",
                    "ViewAll"
                ],
                "resources": [
                    "all"
                ]
            },
            "policy": "DataStewardPolicy",
            "role": "DataSteward"
        },
        {
            "operation": "EditDisplayName",
            "access": "allow",
            "rule": {
                "name": "DataStewardPolicy-EditRule",
                "effect": "allow",
                "operations": [
                    "Create",
                    "Delete",
                    "EditAll",
                    "ViewAll"
                ],
                "resources": [
                    "all"
                ]
            },
            "policy": "DataStewardPolicy",
            "role": "DataSteward"
        },
        {
            "operation": "EditTags",
            "access": "allow",
            "rule": {
                "name": "DataStewardPolicy-EditRule",
                "effect": "allow",
                "operations": [
                    "Create",
                    "Delete",
                    "EditAll",
                    "ViewAll"
                ],
                "resources": [
                    "all"
                ]
            },
            "policy": "DataStewardPolicy",
            "role": "DataSteward"
        },
        {
            "operation": "EditOwner",
            "access": "allow",
            "rule": {
                "name": "DataStewardPolicy-EditRule",
                "effect": "allow",
                "operations": [
                    "Create",
                    "Delete",
                    "EditAll",
                    "ViewAll"
                ],
                "resources": [
                    "all"
                ]
            },
            "policy": "DataStewardPolicy",
            "role": "DataSteward"
        },
        {
            "operation": "EditTier",
            "access": "allow",
            "rule": {
                "name": "DataStewardPolicy-EditRule",
                "effect": "allow",
                "operations": [
                    "Create",
                    "Delete",
                    "EditAll",
                    "ViewAll"
                ],
                "resources": [
                    "all"
                ]
            },
            "policy": "DataStewardPolicy",
            "role": "DataSteward"
        },
        {
            "operation": "EditCustomFields",
            "access": "allow",
            "rule": {
                "name": "DataStewardPolicy-EditRule",
                "effect": "allow",
                "operations": [
                    "Create",
                    "Delete",
                    "EditAll",
                    "ViewAll"
                ],
                "resources": [
                    "all"
                ]
            },
            "policy": "DataStewardPolicy",
            "role": "DataSteward"
        },
        {
            "operation": "EditTests",
            "access": "allow",
            "rule": {
                "name": "DataStewardPolicy-EditRule",
                "effect": "allow",
                "operations": [
                    "Create",
                    "Delete",
                    "EditAll",
                    "ViewAll"
                ],
                "resources": [
                    "all"
                ]
            },
            "policy": "DataStewardPolicy",
            "role": "DataSteward"
        },
        {
            "operation": "EditQueries",
            "access": "allow",
            "rule": {
                "name": "DataStewardPolicy-EditRule",
                "effect": "allow",
                "operations": [
                    "Create",
                    "Delete",
                    "EditAll",
                    "ViewAll"
                ],
                "resources": [
                    "all"
                ]
            },
            "policy": "DataStewardPolicy",
            "role": "DataSteward"
        },
        {
            "operation": "EditDataProfile",
            "access": "allow",
            "rule": {
                "name": "DataStewardPolicy-EditRule",
                "effect": "allow",
                "operations": [
                    "Create",
                    "Delete",
                    "EditAll",
                    "ViewAll"
                ],
                "resources": [
                    "all"
                ]
            },
            "policy": "DataStewardPolicy",
            "role": "DataSteward"
        },
        {
            "operation": "EditSampleData",
            "access": "allow",
            "rule": {
                "name": "DataStewardPolicy-EditRule",
                "effect": "allow",
                "operations": [
                    "Create",
                    "Delete",
                    "EditAll",
                    "ViewAll"
                ],
                "resources": [
                    "all"
                ]
            },
            "policy": "DataStewardPolicy",
            "role": "DataSteward"
        },
        {
            "operation": "EditLineage",
            "access": "allow",
            "rule": {
                "name": "DataStewardPolicy-EditRule",
                "effect": "allow",
                "operations": [
                    "Create",
                    "Delete",
                    "EditAll",
                    "ViewAll"
                ],
                "resources": [
                    "all"
                ]
            },
            "policy": "DataStewardPolicy",
            "role": "DataSteward"
        }
    ]
}

### PR DESCRIPTION
**Pull request by aniketkatkar97**
### Describe your changes:

Fixes #10859 

I worked on fixing the bug where users with proper permissions were not able to edit test cases

https://user-images.githubusercontent.com/51777795/231107136-380186b0-c35d-4df1-a24e-519784b24ec0.mov

#
### Type of change:

- [x] Bug fix

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/DataQualityTab.tsx [hunk 1]
```diff
@@ -173,12 +188,14 @@ const DataQualityTab: React.FC<DataQualityTabProps> = ({
                 <Tooltip
                   placement="bottomRight"
                   title={
-                    hasAccess ? t('label.edit') : NO_PERMISSION_FOR_ACTION
+                    testCaseEditPermission
+                      ? t('label.edit')
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/DataQualityTab.tsx:192]: We don't need button tooltip if it's not disabled since button also mentioning it's action

File: openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/DataQualityTab.tsx [hunk 2]
```diff
@@ -192,12 +209,14 @@ const DataQualityTab: React.FC<DataQualityTabProps> = ({
               <Tooltip
                 placement="bottomLeft"
                 title={
-                  hasAccess ? t('label.delete') : NO_PERMISSION_FOR_ACTION
+                  testCaseDeletePermission
+                    ? t('label.delete')
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/DataQualityTab.tsx:213]: same

Comment (aniketkatkar97) [reply openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/DataQualityTab.tsx:213]: Here also no action is mentioned in the button so tooltip would be helpful.

**Review by chirag-madlani — APPROVED** [review]

**Comment by lailapatel** [comment]
Hi @chirag-madlani

**Comment by chirag-madlani** [comment]
Hi @lailapatel,
Yes, it's resolved in 1.0 let us know if you are facing any issue here

**Comment by lailapatel** [comment]
yes, like in the below case, the user got Data Steward role with the below permissions i.e. Edit All and View All.

1. He is able to edit the tests successfully.
2. However, he is also able to create the tests, though the assigned role is for Editing only.

image

image

image

image

image

**Comment by chirag-madlani** [comment]
Yes @lailapatel, To allow create `testSuites` you need to modify the Rule to Allow create shown in the below screenshot.
We are considering each operation differently so If someone doesn't have create permission, we won't allow it

Screenshot 2023-05-02 at 12 58 11 PM

**Comment by chirag-madlani** [comment]
Hi @lailapatel,
Seems working on [Sandbox](https://sandbox.open-metadata.org/). Can you reach out to support for a more efficient resolution here?
