### PR TITLE
Fix #14590: Improve airflow plugin error message

### LINKED ISSUE #14590: Ingestion - missing docs information for airflow
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ingestion

**Describe the bug**

In case airflow is not available we should put more information about what can be done as the next step to fix it.
Either doc links or a support link will be much helpful here

**To Reproduce**

Screenshots or steps to reproduce

image

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by ulixius9**
### Describe your changes:

Fix #14590: Improve airflow plugin error message

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Review by Sachin-chaurasiya — APPROVED** [review]

File: openmetadata-service/src/main/java/org/openmetadata/service/clients/pipeline/airflow/AirflowRESTClient.java [hunk 1]
```diff
@@ -292,7 +292,7 @@ public PipelineServiceClientResponse getServiceStatusInternal() {
       // APIs URL not found
       if (response.statusCode() == 404) {
         return buildUnhealthyStatus(
-            "Airflow APIs not found. Please follow the installation guide.");
+            "Airflow APIs not found. Please validate if the OpenMetadata Airflow plugin is installed correctly. Follow [this guide](https://docs.open-metadata.org/v1.2.x/deployment/ingestion/openmetadata) for further details.");
```
Comment (ayush-shah) [inline openmetadata-service/src/main/java/org/openmetadata/service/clients/pipeline/airflow/AirflowRESTClient.java:295]:
```suggestion
            "Airflow APIs not found. Please validate if the OpenMetadata Airflow plugin is installed correctly. Follow [this guide](https://docs.open-metadata.org/deployment/ingestion/openmetadata) for further details.");
```

to pick the latest version

**Review by pmbrull — APPROVED** [review]
