### PR TITLE
fix(services): use class-based search index and wildcard search on name+displayName in service listing

### LINKED ISSUE #26459: ui: Service search does not find services by display name
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**
Searching for services on the Settings > Services page has two issues.

### Problem
1. Search ignores display name
When searching for a service, only the internal name is matched. If a service has a different display name (the name users actually see in the UI), searching by that display name returns no results.
Steps to reproduce:
- Go to Settings > Services (e.g., Database Services).
- Find a service whose display name differs from its internal name.
- Type the display name in the search bar.
- No results are returned.
 
### Expected behaviour: 
- Services should be found by both their internal name and display name.

2. Search index lookup is not extensible
The search index used for service lookup is resolved directly instead of going through the overridable base class. This prevents Collate from adding support for additional service types (e.g., security services) without modifying upstream code.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by harsh-vador**
### Describe your changes:
Fixes #26459 

## Summary

https://github.com/user-attachments/assets/d94e11db-5a56-401c-aac7-0933040a0470

### Problem
Service listing search had two issues:
1. Search only matched `name` — searching by `displayName` returned no results.
2. `getSearchIndexFromService` was called directly in `Services.tsx` instead of going through the overridable `serviceUtilClassBase`, making the search index non-extensible for Collate (which needed `security_service_search_index` support).

### Changes

**`ServiceUtilClassBase.ts`**
- Added `getServiceTypeFromEntityType()` method that delegates to `getSearchIndexFromService`, allowing Collate to override search index resolution via `ServiceUtilClassCollate`.

**`Services.tsx`**
- Replaced `getSearchIndexFromService` direct call with `serviceUtilClassBase.getServiceTypeFromEntityType()`.
- Replaced `serviceTypeQueryFilter` (type-only filter) with `serviceQueryFilter` that builds a structured ES `bool.must` query combining:
  - Wildcard clauses on both `name.keyword` and `displayName.keyword` when a search term is present.
  - `term` clauses on `serviceType` when type filters are active.
- Removed the `search` (plain `q=`) parameter from `searchService` calls — all search is now handled via structured `query_filter`.

### Tests

**`Services.test.tsx`** (unit)
- Added `search and filter behavior` describe block with 3 new tests:
  - No search term → `getServices` REST API is used, `searchService` is not called.
  - Search term → `searchService` called with wildcard `query_filter` on `name.keyword` AND `displayName.keyword`.
  - Search term + type filter → combined `must` clauses (wildcard + term).

**`ServiceListing.spec.ts`** (E2E)
- Added test asserting the wildcard `query_filter` structure is sent on search.
- Added test verifying a service is found when searching by `displayName` (covers database and messaging service pages).

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Services.tsx [hunk 1]
```diff
@@ -107,28 +106,54 @@ const Services = ({ serviceName }: ServicesProps) => {
...
+
+    if (searchTerm) {
+      const escapedTerm = searchTerm.replace(/[*?\\]/g, '\\$&');
+      mustClauses.push({
+        bool: {
+          should: [
+            { wildcard: { 'name.keyword': `*${escapedTerm}*` } },
+            { wildcard: { 'displayName.keyword': `*${escapedTerm}*` } },
+          ],
+          minimum_should_match: 1,
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Services.tsx:120]: please verify these queries with @sonika-shah.

File: openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Services.tsx [hunk 2]
```diff
@@ -107,28 +106,54 @@ const Services = ({ serviceName }: ServicesProps) => {
...
+        },
+      });
+    }
+
+    if (serviceTypeFilter?.length) {
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Services.tsx]:
```suggestion
    if (!isEmpty(serviceTypeFilter)) {
```

File: openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Services.tsx (hunk 1 above)
Comment (harsh-vador) [reply openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Services.tsx:120]: Yes verified and these are correct
