### PR TITLE
fix(ui): table data issue in entity table lineage sidebar

### LINKED ISSUE #13880: Bug on Entity information in lineage page
**Affected module**
UI

**Describe the bug**
Hi team, there is something strange in the lineage visual. when I click on Table information in the right panel is not shown correctly. in the pictures below the same table and the same lineage, the one on v1.2 (test env) compared to v1.1.5 (currently used), database service, or schema not shown.

**To Reproduce**
cc @chirag-madlani 
https://openmetadata.slack.com/archives/C02B6955S4S/p1699347802454999

**Expected behavior**

**Version:**
 - OS: v1.2
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes:

Fixes #13880

- I worked on fixing table data issue in entity table lineage sidebar

https://github.com/open-metadata/OpenMetadata/assets/66266464/8163b4a4-534e-48ed-85e9-90efc5e1800b

#
### Type of change:

- [x] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/TableSummary/TableSummary.component.tsx [hunk 1]
```diff
@@ -200,7 +200,18 @@ function TableSummary({
...
+    isTourPage,
+    isTableDeleted,
+    fetchProfilerData,
+    fetchAllTests,
+    getEntityPermission,
+  ]);
+
+  useEffect(() => {
+    setTableDetails(entityDetails);
+  }, [entityDetails]);
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/TableSummary/TableSummary.component.tsx:214]: I do not recommend this @Ashish8689

**Comment by Ashish8689** [comment]
@Chirag Madlani changes made as per comments!

**Review by chirag-madlani — APPROVED** [review]
Just test tour page since we have changes around that part
