### PR TITLE
Fix (ui) :-  Tag dropdown overflow issue and added localisation

### LINKED ISSUE #8167: UI: Tag dropdown box getting overflow
image (13)

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes :

-  Issue : Closes #8167
- fix dropdown overflow issue while adding tags
- added localisation 

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :
image

image
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

**Review by chirag-madlani — DISMISSED** [review]

**Review by ShaileshParmar11 — DISMISSED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx [hunk 1]
```diff
@@ -543,7 +553,7 @@ const EntityTable = ({
         {checkIfJoinsAvailable(record?.name) && (
           <div className="tw-mt-3" data-testid="frequently-joined-columns">
             <span className="tw-text-grey-muted tw-mr-1">
-              Frequently joined columns:
+              {t('label.frequently-joined-columns')}
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx:556]:
```suggestion
              {t('label.frequently-joined-columns')}:
```

Comment (Ashish8689) [reply openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx]: @Sachin-chaurasiya  Updated!

**Review by Sachin-chaurasiya — APPROVED** [review]
