### PR TITLE
Fix #8416: Restore Entities after soft delete with all it's old data

### LINKED ISSUE #8416: Restore Entities after soft delete with all it's old data
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
backend

**Describe the bug**
Restoring Entities after soft delete using `PUT` request manages to restore it but with only minimal old data which should not be done. 

**Expected behavior**
After Restoring all the data before soft deleted should come as it is

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by harshach**
### Describe your changes :

I worked on the ..... because ...

#
### Type of change :

- [x] Improvement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

**Review by pmbrull — APPROVED** [review]

File: openmetadata-service/src/main/java/org/openmetadata/service/resources/analytics/WebAnalyticEventResource.java [hunk 1]
```diff
@@ -278,6 +279,26 @@ public Response delete(
     return delete(uriInfo, securityContext, id, false, hardDelete);
   }
 
+  @PUT
+  @Path("/restore")
+  @Operation(
+      operationId = "restore",
+      summary = "Restore a soft deleted WebAnalyticEvent.",
+      tags = "tables",
+      description = "Restore a soft deleted WebAnalyticEvent.",
```
Comment (sureshms) [inline openmetadata-service/src/main/java/org/openmetadata/service/resources/analytics/WebAnalyticEventResource.java:288]: This will be under tables section in the API. Needs to be updated.

File: openmetadata-service/src/main/java/org/openmetadata/service/resources/services/messaging/MessagingServiceResource.java [hunk 2]
```diff
@@ -345,6 +346,26 @@ public Response delete(
     return delete(uriInfo, securityContext, id, recursive, hardDelete);
   }
 
+  @PUT
+  @Path("/restore")
```
Comment (sureshms) [inline openmetadata-service/src/main/java/org/openmetadata/service/resources/services/messaging/MessagingServiceResource.java:350]: Can we have path /restore/{id}?

Comment (harshach) [reply openmetadata-service/src/main/java/org/openmetadata/service/resources/services/messaging/MessagingServiceResource.java:350]: discussed offline:
PUT/POST requires a body and Jersey client throws an exception when there is no body

**Comment by harshach** [comment]
@sureshms when you get a chance, please check again fixed the tags

**Review by sureshms — APPROVED** [review]
