### PR TITLE
fix(ui): dashboard data model name column should not be link

### LINKED ISSUE #21459: Dashboard Datamodel columns should not be links
**Affected module**
UI

**Describe the bug**
Dashboard Datamodel columns should not be links and clickable

Image

example: https://sandbox.open-metadata.org/dashboardDataModel/sample_looker.model.orders_view

### PR DESCRIPTION
**Pull request by pranita09**
### Describe your changes:

Fixes #21459

Worked on Dashboard Data Model name column should not be links and clickable. 
Removed `link` prop from `DisplayName` component inside `ModelTab`, making the `link` optional inside `DisplayName` component.

Issue:

https://github.com/user-attachments/assets/16ae1a94-7c0f-4569-a18f-19b6c3dc9cd3

Fix:

https://github.com/user-attachments/assets/a065799d-03bd-4df8-977b-c9a7622e7588

Name and displayName color fix:
Earlier name and displayName both had same regular color making it difficult to identify them if link is not present.
Added `text-grey-600` class to name if displayName is present changing color of the name to grey.

Screenshot 2025-05-30 at 9 40 33 PM

Screenshot 2025-05-30 at 9 41 08 PM

Screenshot 2025-05-30 at 9 41 29 PM

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/common/DisplayName/DisplayName.tsx [hunk 1]
```diff
@@ -46,27 +46,43 @@ const DisplayName: React.FC<DisplayNameProps> = ({
...
+          {renderTextWithOptionalLink(displayName, name)}
+        </Typography.Text>
+      </>
+    );
+  }, [displayName, name, renderTextWithOptionalLink]);
+
   return (
     <div className="flex-column hover-icon-group w-max-full">
       <Typography.Text
-        className="m-b-0 d-block text-grey-muted break-word"
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/common/DisplayName/DisplayName.tsx:52]: Is this change intended? Removal of `text-grey-muted`

**Review by chirag-madlani — APPROVED** [review]

**Comment by chirag-madlani** [comment]
@pranita09 is screenshots are updated with latest changes?

**Comment by pranita09** [comment]
@chirag-madlani Yes, screenshots are updated with latest changes

**Review by chirag-madlani — APPROVED** [review]
