### PR TITLE
Nested columns search fix

### LINKED ISSUE #6810: Tables with columns with children are not indexed properly
**Affected module**
UI and backend
**Describe the bug**
When tables have columns with children, the child columns (especially their descriptions) are not indexed.

**To Reproduce**
See sample json. 
1. Searching for the keywords in the child columns do not yield results
2. Advanced column search will suggest "parent.child" only sometimes and never "parent.child1.child2"
3. Advanced column search will not actually return any table hits when the "parent.child" suggestion is selected. 

**Expected behavior**
All descriptions and column names must be searchable.
Advanced column search must suggest even when the entered query is a child column (e.g., child2 should suggest parent.child1.child2)
**Version:**
 - OS: [e.g. iOS]:n/a
 - Python version: 3.9
 - OpenMetadata version: 0.11.4
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by 07Himank**
Fixes #6810 , #12399

I worked on ... because ...Nested columns search fix

#
### Type of change:

- [ x] Bug fix
- [ x] Improvement

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java [hunk 1]
```diff
@@ -526,7 +526,9 @@ private static SearchSourceBuilder buildTopicSearchBuilder(String query, int fro
     hb.field(new HighlightBuilder.Field("messageSchema.schemaFields.description").highlighterType(UNIFIED));
     hb.field(new HighlightBuilder.Field("messageSchema.schemaFields.children.name").highlighterType(UNIFIED));
     SearchSourceBuilder searchSourceBuilder = searchBuilder(queryBuilder, hb, from, size);
-    searchSourceBuilder.aggregation(AggregationBuilders.terms(ES_MESSAGE_SCHEMA_FIELD).field(ES_MESSAGE_SCHEMA_FIELD));
+    searchSourceBuilder
+        .aggregation(AggregationBuilders.terms(ES_MESSAGE_SCHEMA_FIELD).field(ES_MESSAGE_SCHEMA_FIELD))
```
Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java:530]: lets call the names as 
1. fieldNames
2. columnNames

File: openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TableIndex.java [hunk 2]
```diff
@@ -46,22 +49,32 @@ public Map<String, Object> buildESDoc() {
     List<SearchSuggest> schemaSuggest = new ArrayList<>();
     List<SearchSuggest> databaseSuggest = new ArrayList<>();
     List<SearchSuggest> serviceSuggest = new ArrayList<>();
+    Set<List<TagLabel>> tagsWithChildren = new HashSet<>();
```
Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TableIndex.java:52]: it should be a single set not set of Lists

Comment (07Himank) [reply openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TableIndex.java:52]: @harshach, we are getting List<TagLable> from functions so its done that way other wise will need loops to add it.. we are flattening it before adding to doc.

File: openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java (hunk 1 above)
Comment (07Himank) [reply openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java:530]: @harshach ,Done pushed in latest commit

File: openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TableIndex.java [hunk 3]
```diff
@@ -46,22 +49,32 @@ public Map<String, Object> buildESDoc() {
...
       }
+      doc.put("columnNames", columnsWithChildrenName);
     }
     parseTableSuggest(suggest);
     serviceSuggest.add(SearchSuggest.builder().input(table.getService().getName()).weight(5).build());
     databaseSuggest.add(SearchSuggest.builder().input(table.getDatabase().getName()).weight(5).build());
     schemaSuggest.add(SearchSuggest.builder().input(table.getDatabaseSchema().getName()).weight(5).build());
     ParseTags parseTags = new ParseTags(Entity.getEntityTags(Entity.TABLE, table));
+    tagsWithChildren.add(parseTags.getTags());
+    List<TagLabel> flattenedTagList =
```
Comment (harshach) [inline openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TableIndex.java:74]: this should be a set. Otherwise we will get duplicates

Comment (07Himank) [reply openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TableIndex.java:74]: above we are having it as a set of List<TagLabel> so it will be unique only right .. i have tested it adding duplicate values it works fine..

**Review by harshach — APPROVED** [review]
