### PR TITLE
Fix #12083 - Backoff retry when polling for pipeline service client status

### LINKED ISSUE #12083: Add exponential backoff in PipelineServiceStatusJob
if we get an exception when running `registerStatusMetric` to avoid false negatives

### PR DESCRIPTION
**Pull request by pmbrull**
### Describe your changes:

Fixes #12083

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/PipelineServiceStatusJob.java [hunk 1]
```diff
@@ -39,11 +46,35 @@ public void execute(JobExecutionContext jobExecutionContext) {
     }
   }
 
+  private String getServiceStatus(PipelineServiceClient pipelineServiceClient) {
+    RetryConfig retryConfig =
+        RetryConfig.<String>custom()
+            .maxAttempts(MAX_ATTEMPTS)
+            .waitDuration(Duration.ofMillis(BACKOFF_TIME_SECONDS * 1_000L))
+            .retryOnResult(response -> !HEALTHY_STATUS.equals(response))
+            .failAfterMaxAttempts(false)
```
Comment (pmbrull) [inline openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/PipelineServiceStatusJob.java:55]: We check 3 times if the status is not unhealthy. If it still is, we return it to be registered in prometheus

**Review by harshach — APPROVED** [review]
