### PR TITLE
Fixes #15358: add bots to the options of the filters.

### LINKED ISSUE #15358: Bug can not add bot to ActivityFeedAlert
**Affected module**
 it impact the UI

**Describe the bug**
I am using version 1.3.0 I I've noticed that filter seems to support excluding users (default exclude is ingestion-bot). When I edit or update something to ActivityFeedAlert . I can not add any new bot I created to that filter. Even if I removed ingestion-bot, I can't add it back again/ Because this drop down list only show end user,  does not include any bot to select.

**To Reproduce**

Screenshots or steps to reproduce
image

**Expected behavior**
End user can add bot to list of Updater name

**Version:**
 - Open Metadata Kubernetes v1.3.0

**Additional context**

### PR DESCRIPTION
**Pull request by nakaken-churadata**
### Describe your changes:

Fixes 15358

I worked on adding bots to the options of the filters.

#
### Type of change:

- [X] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [X] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

- [ ] I have added a test that covers the exact scenario we are fixing. For complex issues, comment the issue number in the test for future reference.
I couldn't find any tests that I had to modify.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/utils/Alerts/AlertsUtil.tsx [hunk 1]
```diff
@@ -543,7 +550,7 @@ export const getFieldByArgumentType = (
               },
             ]}>
             <AsyncSelect
-              api={getUserOptions}
+              api={getUserBotOptions}
               className="w-full"
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/src/utils/Alerts/AlertsUtil.tsx:554]: Can we use the function based on the argument type here? since we only need bots to show in case the `argument` value is `updateByUserList`.

**Review by aniketkatkar97 — COMMENTED** [review]
Hey @nakaken-churadata, thanks for your contribution. Left a minor comment can you please check that?

**Review by aniketkatkar97 — APPROVED** [review]
