### PR TITLE
Fixed: UI inconsistency as per feedback #4192

### LINKED ISSUE #4192: UI Consistency and Updates
- [x] Background/Table styling is different in Table/Topics from Services (@ShaileshParmar11 )
Table Styling

- [x] #4219 (@Sachin-chaurasiya)
- [x] Remove user page all together, Team to be renamed as “Teams & Users” (@ShaileshParmar11 ) #4299 
- [x] On top right question mark icon menu, add GitHub link on “version” click (@Sachin-chaurasiya )
- [x] #4223 (@Sachin-chaurasiya )
- [x] On user card instead of mentioning all the teams, mention “(Team Name) number+) (@ShaileshParmar11 )
- [x] Rename “Connection Config” as “Connection” on service detail page (@Sachin-chaurasiya)
- [x] Change Request Description icon (@Sachin-chaurasiya )
Request Description

- [x] Navigation in service detail page needs improvement (@darth-coder00)

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes :

 UI inconsistency as per feedback #4192
Closes #4192 

#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :
feedback point 1
image
image
image
image

Feedback point 6
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/UserDataCard/UserDataCard.tsx [hunk 1]
```diff
@@ -25,7 +25,7 @@ type Item = {
   email: string;
   isActiveUser?: boolean;
   profilePhoto?: string;
-  teamCount?: string;
+  teamCount?: string | JSX.Element;
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/UserDataCard/UserDataCard.tsx:28]:
```suggestion
  teamCount?: string | ReactNode;
```

**Review by vivekratnavel — APPROVED** [review]
