### PR TITLE
Fix #7868 UI: Auth0 SSO is redirecting to logout page on Signin

### LINKED ISSUE #7868: UI: Auth0 SSO is redirecting to logout page on Signin
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI 

**Describe the bug**
Unable to login with Auth0 SSO. It keeps redirecting to logout URL of Auth0.

### PR DESCRIPTION
**Pull request by vivekratnavel**
### Describe your changes :
See #7868 

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/authentication/authenticators/Auth0Authenticator.tsx [hunk 1]
```diff
@@ -31,19 +31,17 @@ interface Props {
 const Auth0Authenticator = forwardRef<AuthenticatorRef, Props>(
   ({ children, onLogoutSuccess }: Props, ref) => {
     const { setIsAuthenticated, authConfig } = useAuthContext();
-    const {
-      loginWithRedirect,
-      logout,
-      getAccessTokenSilently,
-      getIdTokenClaims,
-    } = useAuth0();
+    const { loginWithRedirect, getAccessTokenSilently, getIdTokenClaims } =
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/authentication/authenticators/Auth0Authenticator.tsx:34]:
```suggestion
    const { loginWithRedirect, getAccessTokenSilently, getIdTokenClaims, isAuthenticated } =
```

File: openmetadata-ui/src/main/resources/ui/src/authentication/authenticators/Auth0Authenticator.tsx [hunk 2]
```diff
@@ -31,19 +31,17 @@ interface Props {
...
       invokeLogin() {
-        loginWithRedirect();
+        loginWithRedirect().catch((error) => {
+          // eslint-disable-next-line no-console
+          console.error(error);
+        });
       },
       invokeLogout() {
-        logout();
         setIsAuthenticated(false);
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/authentication/authenticators/Auth0Authenticator.tsx:45]:
```suggestion
        if(isAuthenticated){
logout();
        setIsAuthenticated(false);
        onLogoutSuccess();
}
```

Comment (chirag-madlani) [reply openmetadata-ui/src/main/resources/ui/src/authentication/authenticators/Auth0Authenticator.tsx:45]: We don't need above as we didn't intend to logout from SSO

**Review by chirag-madlani — APPROVED** [review]
