### PR TITLE
UI: Fixed Data is getting round off at the time of formatting in en-US

### LINKED ISSUE #8574: UI: RowCount and ValueCount is getting round-off for profiler
image

### LINKED ISSUE #8575: Row count is updated correctly as 37289322 in the Profiler column page , but shown as 37300000 in the Profiler main page
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
I am trying to ingest profiling data for a table using the API "Add table profile data" .
Row count is updated correctly as 37289322 in the Profiler column page , but shown as 37300000 in the Profiler main page

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
Counts should be same in both pages
**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes :

Fixed Data is getting round-off at the time of formatting in en-US
Closes #8575 
Closes #8574 

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx [hunk 1]
```diff
@@ -786,9 +786,7 @@ export const showPagination = (paging: Paging) => {
 };
 
 export const formatNumberWithComma = (number: number) => {
-  return new Intl.NumberFormat('en-US', { maximumSignificantDigits: 3 }).format(
-    number
-  );
+  return new Intl.NumberFormat('en-US').format(number);
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx:789]: I feel this will break at other places. Can you verify that?
Does it format numbers with commas properly?

Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx:789]: Yes its format's properly
image

**Review by chirag-madlani — APPROVED** [review]
