### PR TITLE
Fix: show full fqn for reference tables

### LINKED ISSUE #18700: Add Query from UI not show full FQN of reference tables
**Affected module**
UI

**Describe the bug**
When add new Query in Queries Tab, droplist in "Query used by other tables" not show FQN so if we have many tables with the same name but store in difference database, we can not pick the right one for these queries.

**To Reproduce**
image

**Expected behavior**
Droplist should be shown FQN instead of only Table Name

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by pranita09**
### Describe your changes:

Fixes #18700

The dropdown list for 'Add New Query' displays both the table name and its FQN instead of just the table name.

Screenshot 2024-11-29 at 6 05 05 PM

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/pages/AddQueryPage/AddQueryPage.component.tsx [hunk 1]
```diff
@@ -102,7 +115,11 @@ const AddQueryPage = () => {
         SearchIndex.TABLE
       );
       const options = data.hits.hits.map((value) => ({
-        label: getEntityName(value._source),
+        label: getLabelValue(
+          value._source.displayName || '',
+          value._source.name,
+          value._source.fullyQualifiedName || ''
+        ),
```
Comment (Ashish8689) [inline openmetadata-ui/src/main/resources/ui/src/pages/AddQueryPage/AddQueryPage.component.tsx:122]: since we are extracting the values from the same object we can pass the whole object and extracting the values which we needed ?

File: openmetadata-ui/src/main/resources/ui/src/pages/AddQueryPage/AddQueryPage.component.tsx [hunk 2]
```diff
@@ -88,6 +88,19 @@ const AddQueryPage = () => {
...
+    name: string,
+    fullyQualifiedName: string
+  ): JSX.Element => (
+    <Space direction="vertical" size={0}>
+      <Typography.Text>{getEntityName({ displayName, name })}</Typography.Text>
+      <Typography.Text className="text-gray-400 text-xs break-word">
+        {fullyQualifiedName}
+      </Typography.Text>
+    </Space>
+  );
```
Comment (Ashish8689) [inline openmetadata-ui/src/main/resources/ui/src/pages/AddQueryPage/AddQueryPage.component.tsx:102]: we can move this to utils files, and use with import!

**Review by Ashish8689 — CHANGES_REQUESTED** [review]

File: openmetadata-ui/src/main/resources/ui/src/pages/AddQueryPage/AddQueryPage.component.tsx (hunk 1 above)
Comment (pranita09) [reply openmetadata-ui/src/main/resources/ui/src/pages/AddQueryPage/AddQueryPage.component.tsx:122]: Passed the whole object and extracted values from it.

File: openmetadata-ui/src/main/resources/ui/src/pages/AddQueryPage/AddQueryPage.component.tsx (hunk 2 above)
Comment (pranita09) [reply openmetadata-ui/src/main/resources/ui/src/pages/AddQueryPage/AddQueryPage.component.tsx:102]: Moved this function to `EntityUtils.tsx`

**Review by ShaileshParmar11 — APPROVED** [review]
