### PR TITLE
fixes: Improve search functionality for teams page #10653

### LINKED ISSUE #10653: Improve search functionality for glossary term and teams page
Glossary term and teams page has the tree structure view, and the search is limited to only terms/teams available on UI side (which are already fetched and stored in the state), but the problem with this approach is, I will not get terms/team which does not yet fetch.

Solution:
The solution would be to fetch team/term from ES at the time of searching

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes:

Fixes #10653 

https://user-images.githubusercontent.com/71748675/229782466-50c78f18-511f-4aed-8515-7e41b2e892db.mov

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.tsx [hunk 1]
```diff
@@ -347,6 +350,19 @@ const TeamDetailsV1 = ({
         ]),
   ];
 
+  const searchTeams = async (text: string) => {
+    try {
+      const res = await getSuggestions(text, SearchIndex.TEAM);
+      const data = (res.data as RawSuggestResponse<SearchIndex.TEAM>).suggest[
+        'metadata-suggest'
+      ][0].options.map((value) => value._source);
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.tsx:358]:
```
const getSuggestResults = async (value: string) => {
    try {
      const data = await getSuggestions<ExploreSearchIndex>(
        value,
        SearchIndex[
          entityType as keyof typeof SearchIndex
        ] as ExploreSearchIndex
      );
      setData(
        formatDataResponse(data.data.suggest['metadata-suggest'][0].options)
      );
    } catch (error) {
      showErrorToast(
        error as AxiosError,
        t('server.entity-fetch-error', {
          entity: t('label.suggestion-lowercase-plural'),
        })
      );
    }
  };

```

For better typing @ShaileshParmar11

File: openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.utils.tsx [hunk 2]
```diff
@@ -69,21 +68,3 @@ export const getTabs = (
...
-    if (matched) {
-      results = [...results, { ...team, children: undefined }];
-    }
-    if (hasChildren) {
-      results = [...results, ...searchTeam(team.children as Team[], value)];
-    }
-  }
-
-  return results;
-};
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.utils.tsx:89]: Let's have this method around we need it in future

**Review by chirag-madlani — APPROVED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.utils.tsx (hunk 2 above)
Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.utils.tsx:89]: sure!
