### PR TITLE
Fix MCP tools entity status

### LINKED ISSUE #26549: GlossaryTerms Created via MCP Marked as Unprocessed (No Change Events Generated)
**Affected module**
Does it impact the UI, backend or Ingestion Framework? - AI

**Describe the bug**
- GlossaryTerms created via MCP are being set with an Unprocessed status. Upon validation, it appears that MCP is not generating any change events for GlossaryTerm or Table assets, which is likely causing this issue.

**To Reproduce**

Screenshots or steps to reproduce
1. Create a GlossaryTerm using MCP
2. Observe the status of the created GlossaryTerm

**Expected behavior**
- Glossary Terms should go through the Approval Workflow correctly after creation
- Corresponding change events should be generated for GlossaryTerm, Tables, and related assets

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by Vishnuujain**
Fixes #26549
Screenshot 2026-03-18 at 9 19 24 AM

----
## Summary by Gitar

- **Refactored entity preparation:**
  - Replaced `prepare()` and `setFullyQualifiedName()` calls with `prepareInternal()` in `CreateMetricTool`, `CreateTestCaseTool`, `GlossaryTool`, and `GlossaryTermTool`
- **Added reviewers support:**
  - Added `reviewers` parameter handling in `GlossaryTermTool` for approval workflows
  - Added `reviewers` field schema in `tools.json` with description for workflow-based approval
- **Code cleanup:**
  - Removed unused imports and glossary lookup logic from `GlossaryTermTool`

<sub>This will update automatically on new commits.</sub>

### CODE REVIEW

File: openmetadata-mcp/src/main/java/org/openmetadata/mcp/tools/CreateMetricTool.java [hunk 1]
```diff
@@ -180,8 +180,7 @@ public Map<String, Object> execute(
     authorizer.authorize(securityContext, operationContext, createResourceContext);
 
     MetricRepository repo = (MetricRepository) Entity.getEntityRepository(Entity.METRIC);
-    repo.prepare(metric, true);
-    repo.setFullyQualifiedName(metric);
+    repo.prepareInternal(metric, false);
```
Comment (pmbrull) [inline openmetadata-mcp/src/main/java/org/openmetadata/mcp/tools/CreateMetricTool.java:183]: should this be applied on PATCH tool too? Or did that generate ChangeEvents already

Comment (Vishnuujain) [reply openmetadata-mcp/src/main/java/org/openmetadata/mcp/tools/CreateMetricTool.java:183]: No, the PATCH tool doesn't need this change and has ChangeEvents already
