### PR TITLE
Fix: Misc issues for adding Tags, Teams and Service

### LINKED ISSUE #2104: Adding tag category with space results in disappearing of other tag categories
Steps to reproduce:
1. Add a tag category name with space e.g. `Personal Data`
2. Refresh the page

https://user-images.githubusercontent.com/83201188/148530340-a89dc2f8-4cab-4103-ac8c-23f3156b6fa2.mov

The same happens when you add tag name with space in tag category, that particular tag disappears from the list.

### LINKED ISSUE #2105: Can add just 'space' as name for entities like teams and service
https://user-images.githubusercontent.com/83201188/148533290-34b5c1e3-2359-4a79-941b-f027e0cce4f3.mov

Screenshot 2022-01-07 at 3 58 58 PM

### LINKED ISSUE #2124: No message on UI when added tag of same name.
https://user-images.githubusercontent.com/83201188/148724167-5abb482d-a53f-4ac4-b330-ee16f6c05ac7.mov

### PR DESCRIPTION
**Pull request by darth-coder00**
### Describe your changes :
Closes #2104, closes #2105, closes #2124 

I worked on the misc issues while adding teams, tags and services

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :
<p align="center">
Screenshot 2022-01-11 at 1 14 21 PM
Screenshot 2022-01-11 at 1 14 42 PM
Screenshot 2022-01-11 at 1 15 37 PM
Screenshot 2022-01-11 at 1 16 59 PM
Screenshot 2022-01-11 at 1 17 34 PM

</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@shahsank3t @Sachin-chaurasiya

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/pages/tags/Form.tsx [hunk 1]
```diff
@@ -124,6 +136,9 @@ Form.propTypes = {
     description: PropTypes.string.isRequired,
     categoryType: PropTypes.string.isRequired,
   }).isRequired,
+  errorData: PropTypes.shape({
+    name: PropTypes.string.isRequired,
+  }).isRequired,
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/tags/Form.tsx:141]: why we are making it as required?
In form prop it is marked as optional 
```  errorData?: { [key: string]: string | undefined };```

File: openmetadata-ui/src/main/resources/ui/src/pages/tags/index.tsx [hunk 2]
```diff
@@ -64,6 +65,10 @@ const TagsPage = () => {
   const [editTag, setEditTag] = useState<TagClass>();
   const [error, setError] = useState<string>('');
   const [isLoading, setIsLoading] = useState<boolean>(false);
+  const [errorDataCategory, setErrorDataCategory] =
+    useState<{ [key: string]: string | undefined }>();
+  const [errorDataTag, setErrorDataTag] =
+    useState<{ [key: string]: string | undefined }>();
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/pages/tags/index.tsx:71]: instead of repeating `{ [key: string]: string | undefined }` we can make a separate type and use it here.
```type keyValue = { [key: string]: string | undefined };```

**Review by Sachin-chaurasiya — CHANGES_REQUESTED** [review]
Requested a few changes.

File: openmetadata-ui/src/main/resources/ui/src/pages/tags/Form.tsx (hunk 1 above)
Comment (darth-coder00) [reply openmetadata-ui/src/main/resources/ui/src/pages/tags/Form.tsx:141]: Nice observation, Thanks :)

**Review by Sachin-chaurasiya — APPROVED** [review]
