### PR TITLE
Fix #7184 add description lags

### LINKED ISSUE #7184: add description lags
https://user-images.githubusercontent.com/12093397/188253919-d068551a-4bb6-4794-bc1a-0dc9ce878be0.mp4

**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**
when i add any description，from click the save button to  display finally，it lasts more than 10 seconds，is it normally？ step1 click save ----wait nearly 10 seconds-------> step2 display finally

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
Fixes #7184 
### Describe your changes :

I worked on issue #7184 

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :

https://user-images.githubusercontent.com/59080942/188445923-0a9e188d-a2ce-4467-8b3b-3726454e3d8d.mov

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/pages/BotDetailsPage/BotDetailsPage.tsx [hunk 1]
```diff
@@ -55,20 +55,19 @@ const BotDetailsPage = () => {
...
-      .catch((err: AxiosError) => {
-        showErrorToast(err);
-      });
+
+    try {
+      const response = await updateUserDetail(botsData.id, jsonPatch);
+      setBotsData((prevData) => ({
+        ...prevData,
+        ...response,
+      }));
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/pages/BotDetailsPage/BotDetailsPage.tsx:67]: Please add check for response is value or not and add error just like we had

**Review by chirag-madlani — APPROVED** [review]
