### PR TITLE
Fixed issue Create test suite ingestion pipelines with underscores instead of spaces #7279

### LINKED ISSUE #7279: Create test suite ingestion pipelines with underscores instead of spaces
**Affected module**
UI

**Describe the bug**
When an ingestion pipeline for a test suite with spaces on the name is created, the UI tries to get the status for a DAG name that does not exist.

**To Reproduce**
- Create a Test Suite for any table with a space, e.g., `Test Suite`:
image
- In the `pipeline` tab of the test suite, we see this:
image
but in Airflow, we have:
image

This cause running it to be impossible.

**Expected behavior**
The UI should get the status for the same DAG name created in Airflow and also allow the user to run the DAG.

**Version:**
 - OpenMetadata version: 0.12
 
 ** Additional issue **
 The link to the ingestion points to the wrong URL.

cc: @TeddyCr

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes :

I worked on the issue #7279
Closes #7279

#
### Type of change :
- [x] Improvement

#
### Frontend Preview (Screenshots) :
image
image
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/TestSuiteIngestion.tsx [hunk 1]
```diff
@@ -103,13 +103,15 @@ const TestSuiteIngestion: React.FC<TestSuiteIngestionProps> = ({
   };
 
   const createIngestionPipeline = async (repeatFrequency: string) => {
+    const updatedName = testSuite.name.replace(/ /g, '_');
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/TestSuiteIngestion.tsx:106]: Can we use the `replaceSpaceWith_` common util here?

Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/TestSuiteIngestion.tsx:106]: Thanks I'll check!
