### PR TITLE
Fixes 23223: Mentions from incidents/entities not showing in Notifications

### LINKED ISSUE #23223: Mentions not shown when tagging somoeoe in incidents, conversations..
**Affected module**
UI
**Describe the bug**
When tagging a user in an Incident or Conversation, This makes it difficult for users to track when they have been tagged in discussions, since the Mentions tab should centralize all mentions across the platform

**To Reproduce**

Create an Incident or Conversation.

Tag a user 

Go to Notifications → Mentions.

Observe that the mention is missing from the list.
Screenshots or steps to reproduce

Image

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: 1.9.5
 - OpenMetadata Ingestion package version: [1.9.5.0

**Additional context**

### PR DESCRIPTION
**Pull request by Rohit0301**
### Describe your changes:

Problem:
Mentions made inside Incidents or Entities were not appearing in the Notifications → Mentions tab.

Root causes:
- The mentions API in Notifications was using a hard filter: type = conversation, which excluded Incident mentions.
- Incidents use type = task, and the Mentions tab logic was not handling that type.

Changes made:
1. Removed the type = conversation filter from the Mentions API call.
   - This allows mentions from Incidents, Conversations, and Entities to appear.

2. Mapped type `task` to `conversation` for rendering
   - Only for the Mentions tab UI, task-based mentions are treated as conversation types.
   - This prevents them from showing as “task assigned” notifications.

Fixes #23223

Screenshot 2025-10-13 at 7 58 12 PM

https://github.com/user-attachments/assets/49cf4e4e-cf36-42f9-866d-298b4bc9a681

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/playwright/utils/activityFeed.ts [hunk 1]
```diff
@@ -128,14 +128,6 @@ export const addMentionCommentInFeed = async (
...
   await page.waitForSelector('[data-testid="loader"]', { state: 'detached' });
 
-  const firstMessage = getNthFeedMessage(page, 0);
-
-  await expect(firstMessage).toBeVisible();
-
-  await firstMessage.locator('[data-testid="reply-count"]').click();
-  await page.waitForSelector('.ant-drawer-content', {
-    state: 'visible',
-  });
```
Comment (Ashish8689) [inline openmetadata-ui/src/main/resources/ui/playwright/utils/activityFeed.ts:138]: why we remove this pieces ?

File: openmetadata-ui/src/main/resources/ui/src/components/NotificationBox/NotificationBox.component.tsx [hunk 2]
```diff
@@ -106,7 +109,7 @@ const NotificationBox = ({
   }, [notifications]);
 
   const getNotificationData = (
-    threadType: ThreadType,
+    threadType: ThreadType | undefined,
     feedFilter: FeedFilter
```
Comment (Ashish8689) [inline openmetadata-ui/src/main/resources/ui/src/components/NotificationBox/NotificationBox.component.tsx]: can we shift the non-required argument to end after the required arguments!

Comment (Rohit0301) [reply openmetadata-ui/src/main/resources/ui/src/components/NotificationBox/NotificationBox.component.tsx]: Done

**Review by Ashish8689 — DISMISSED** [review]

**Review by Ashish8689 — APPROVED** [review]
