### PR TITLE
Fix #4414 User Profile Roles are missing Admin option in dropdown

### LINKED ISSUE #4414: User Profile Roles are missing Admin option in dropdown
**Affected module**
Does it impact the UI, backend or Ingestion Framework?- UI

**Describe the bug**
User Profile Roles are missing Admin option in dropdown

**To Reproduce**

Screenshot 2022-04-23 at 10 37 25 PM

**Expected behavior**
Roles dropdown should have the option to make user an Admin

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
Admin users can see `Admin` in the assigned role

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
Fixes #4414 
### Describe your changes :

I worked on issue #4414 

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.tsx [hunk 1]
```diff
@@ -390,6 +390,17 @@ const Users = ({
...
 
   const getRolesComponent = () => {
+    const userRolesOption = roles?.map((role) => ({
+      label: getEntityName(role as unknown as EntityReference),
+      value: role.id,
+    }));
+    if (!userData.isAdmin) {
+      userRolesOption.push({
+        label: TERM_ADMIN,
+        value: 'admin',
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.tsx:400]: can we use `TERM_ADMIN.toLowerCase()` here?

File: openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.tsx [hunk 2]
```diff
@@ -624,7 +632,7 @@ const Users = ({
     ];
     if (userData.isAdmin) {
       defaultRoles.push({
-        label: 'Admin',
+        label: TERM_ADMIN,
         value: 'admin',
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.tsx:636]: same here

**Review by ShaileshParmar11 — COMMENTED** [review]
miner change

**Review by vivekratnavel — APPROVED** [review]

**Review by darth-coder00 — APPROVED** [review]

**Review by ShaileshParmar11 — APPROVED** [review]
