### PR TITLE
Fix(ui):Test connection timeout message improvement

### LINKED ISSUE #20205: Test connection timeout message improvements
If the test connection times out, show a banner specifying 

```
Please make sure you configured {service_type} to allow connections from {ip}
```

This should help users double-check if whitelist of IPs has been done properly.

### PR DESCRIPTION
**Pull request by dhruvjsx**
Fixed #20205 
Earlier the message was `The test connection is taking too long. Please try again.`

When Ip is present
Screenshot 2025-06-25 at 8 01 14 PM

When IP is absent
Screenshot 2025-06-25 at 8 04 11 PM

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/TestConnection.tsx [hunk 1]
```diff
@@ -328,7 +328,12 @@ const TestConnection: FC<TestConnectionProps> = ({
         );
 
         if (!isWorkflowCompleted) {
-          setMessage(TEST_CONNECTION_INFO_MESSAGE);
+          setMessage(
+            t('message.test-connection-taking-too-long', {
+              service_type: serviceType,
+              ip: hostIp,
+            })
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/TestConnection.tsx]: Can we ensure this message renders well with hostIP absent?

File: openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx [hunk 2]
```diff
@@ -176,6 +179,27 @@ const ServiceDetailsPage: FunctionComponent = () => {
   const [workflowStatesData, setWorkflowStatesData] =
     useState<WorkflowStatesData>();
   const [isWorkflowStatusLoading, setIsWorkflowStatusLoading] = useState(true);
+  const [hostIp, setHostIp] = useState<string>();
+
+  const fetchHostIp = async () => {
+    try {
+      const { status, data } = await getPipelineServiceHostIp();
+      if (status === 200) {
+        setHostIp(data?.ip || '[unknown]');
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx]: If we are setting it unknown then it will be appear on screen as well no?

**Comment by pmbrull** [comment]
the sentence reads a bit wonky. "make sure you configured Database..." feels strange. Let's clean it up a bit

**Review by chirag-madlani — APPROVED** [review]
