### PR TITLE
fix #7729 Number of passed/failed rows should be captured

### LINKED ISSUE #7729: Number of passed/failed rows should be captured
- [x] Add ingestion logic to capture the number of failed rows
- [ ] Display number of failed rows on the UI

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes:

Fixes #7729

- Provided switch to enable and disable the computation of row count failure
- Shown the computed value of the test result on hover of graph
- added unit test for test case form.

image

image
image

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/EditTestCaseModal.tsx [hunk 1]
```diff
@@ -62,6 +69,25 @@ const EditTestCaseModal: React.FC<EditTestCaseModalProps> = ({
     [testCase]
   );
 
+  const isComputeRowCountFieldVisible = useMemo(() => {
+    return selectedDefinition?.supportsRowLevelPassedFailed ?? false;
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/EditTestCaseModal.tsx:73]:
```suggestion
    return Boolean(selectedDefinition?.supportsRowLevelPassedFailed);
```

File: openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/EditTestCaseModal.tsx [hunk 2]
```diff
@@ -103,10 +129,11 @@ const EditTestCaseModal: React.FC<EditTestCaseModalProps> = ({
             : value,
       })
     );
+    const description = markdownRef.current?.getEditorContent();
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/EditTestCaseModal.tsx:132]: @ShaileshParmar11, I would recommend not to use the ref for getting the description, instead get the value from the form directly.

File: openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/components/TestCaseForm.tsx [hunk 3]
```diff
@@ -113,7 +133,7 @@ const TestCaseForm: React.FC<TestCaseFormProps> = ({
 
       setTestCases(data);
     } catch (error) {
-      showErrorToast(error as AxiosError);
+      setTestCases([]);
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/components/TestCaseForm.tsx:136]: Don't we want to show the toast error message here?

File: openmetadata-ui/src/main/resources/ui/src/components/Persona/AddEditPersona/AddEditPersona.component.tsx [hunk 4]
```diff
@@ -131,7 +131,7 @@ export const AddEditPersonaForm = ({
         trigger: 'onUpdate',
         initialValue: [],
       },
-      formItemLayout: FormItemLayout.HORIZONATAL,
+      formItemLayout: FormItemLayout.HORIZONTAL,
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/Persona/AddEditPersona/AddEditPersona.component.tsx:134]: Thanks for tacking care of this.

File: openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/TestSummary.tsx [hunk 5]
```diff
@@ -65,10 +65,11 @@ import Loader from '../../Loader/Loader';
 import SchemaEditor from '../../SchemaEditor/SchemaEditor';
 import { TestSummaryProps } from '../profilerDashboard.interface';
 import './test-summary.less';
+import TestSummaryCustomTooltip from './TestSummaryCustomTooltip.component';
 
 type ChartDataType = {
   information: { label: string; color: string }[];
-  data: { [key: string]: string }[];
+  data: { [key: string]: string | number | undefined }[];
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/TestSummary.tsx:72]: Let's create one union type and use it everywhere.

```ts
type ChartDataValueUnion = string | number | undefined;
```

File: openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/TestSummaryCustomTooltip.component.tsx [hunk 6]
```diff
@@ -0,0 +1,47 @@
...
+import React from 'react';
+import { TooltipProps } from 'recharts';
+
+const TestSummaryCustomTooltip = (
+  props: TooltipProps<string | number, string>
+) => {
+  const { active, payload = [] } = props;
+  const data = payload.length ? entries(omit(payload[0].payload, 'name')) : [];
+
+  return active && payload.length ? (
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/TestSummaryCustomTooltip.component.tsx:24]: Here we can do early return like below

```js
if(conditionNotMet) return null;

return jsx
```

**Review by Sachin-chaurasiya — COMMENTED** [review]
Left a few comments, thanks

File: openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/components/TestCaseForm.tsx (hunk 3 above)
Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/components/TestCaseForm.tsx:136]: Yes, we don't need toast here as we are fetching this data to validate duplicate name, even if this API fails, the user should not get error warning

File: openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/EditTestCaseModal.tsx (hunk 1 above)
Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/EditTestCaseModal.tsx:73]: `selectedDefinition?.supportsRowLevelPassedFailed` itself is a boolean value, i am just giving fallback of default value.

File: openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/TestSummaryCustomTooltip.component.tsx (hunk 6 above)
Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/TestSummaryCustomTooltip.component.tsx:24]: good thought, will try it

File: openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/EditTestCaseModal.tsx (hunk 1 above)
Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/EditTestCaseModal.tsx:64]: @ShaileshParmar11, to return a boolean value, we can use Boolean. If `selectedDefinition?.supportsRowLevelPassedFailed` is nullish, it will return false.

**Review by Sachin-chaurasiya — APPROVED** [review]

**Review by karanh37 — APPROVED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/TestSummaryCustomTooltip.component.tsx [hunk 7]
```diff
@@ -0,0 +1,51 @@
...
+            key={`item-${key}`}>
+            <span className="flex items-center text-grey-muted">
+              {startCase(key)}
+            </span>
+            <span className="font-medium" data-testid={key}>
+              {value}
+            </span>
+          </li>
+        ))}
+      </ul>
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/TestSummaryCustomTooltip.component.tsx:46]: Can we use AntD list here?

Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/TestSummaryCustomTooltip.component.tsx:46]: Will check for that
