### PR TITLE
Fix: Advanced search bugs for the custom properties

### LINKED ISSUE #17001: Custom property search unable to handle space characters
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

UI (and backend?)

**Describe the bug**

Custom property search is unable to handle queries containing space characters.

**To Reproduce**

1. Create a custom property of string type to any entity.
2. Add any sentence containing a space (' ') to the custom property.
3. Use the advanced search in Explore, and search for the added sentence using the created custom property.
4. The search returns nothing.
image
image
image

**Expected behavior**

The search returns all entities containing the matching custom property, even if it contains space characters.

**Version:**
 - OS: Windows 10/11
 - Python version: 3.10 (Docker quickstart package is used) 
 - OpenMetadata version: 1.4.4
 - OpenMetadata Ingestion package version: 1.4.4?

**Additional context**
If the keyword is only a single word, the search correctly works. If the space is replaced with encodings (e.g. `%20`), the query correctly escapes the `%` and the search becomes literal.

### LINKED ISSUE #21600: Search within drop-down field in custom property does not work
We have a custom property field (enum type) with many possible entries where we have to choose one of them. The entries are not sorted by alphabet or numeric, nor the search within the drop down is working. So it is impossible to get easy and fast to the right value.
We need the search within the drop-down working to use this field properly.

### LINKED ISSUE #22939: Advanced Searched Filter generates faulty Elasticsearch query for custom property of type table-cp
**Affected module**
The advanced Search filter of the UI

**Describe the bug**
Its impossible to find values of custom properties which are of type `table-cp`.

**To Reproduce**
1. Create a custom property of type `table-cp`
2. Add a value for the custom property to a container (did not test it for other entities)
3. Use the advanced search filter to search for the value

Screenshots or steps to reproduce

**Expected behavior**
The container should be findable by the value of the custom property

**Version:**
 - OS: Windows
 - Python version: n/a
 - OpenMetadata version: 1.8.10
 - OpenMetadata Ingestion package version: n/a
 - Docker image: openmetadata/server:1.8.10
 - Browser: Microsoft Edge v139

**Additional context**
The generated query filter for Elasticsearch if the following:
```json
{
  ...
        "must": [
            {
                "wildcard": {
                    "extension.processAttributes": {
                        "value": "*MAT-789*"
                    }
                }
            },
            {
                "term": {
                    "entityType": "container"
                }
            }
        ]
 ...
}
```
which would work if the `table-cp` property was a string but it is a table like so
```json
{
...
    "extension": {
        "processAttributes": {
            "rows": [
                {
                    "key": "sample-id",
                    "value": "MAT-789"
                },
                {
                    "key": "magnification-range",
                    "value": "1000x-50000x"
                },
                {
                    "key": "acceleration-voltage",
                    "value": "15kV"
                }
            ],
            "columns": [
                "key",
                "value"
            ]
        }
    }
}
```
An Elasticsearch query which would work would be the following for searching a value in the table.
```json
{
  ...
      "must": [
        {
          "wildcard": {
            "extension.processAttributes.rows.<COLUMN_NAME>.keyword": "MAT-789"
          }
        },
  ...
}
```
For this to work, it should either be possible to select the column to search through in the UI or the `table-cp` types must be stored as nested in Elasticsearch.

### PR DESCRIPTION
**Pull request by aniketkatkar97**
Fixes #17001 
Fixes #21600 
Fixes #22939 
Fixes https://github.com/open-metadata/openmetadata-collate/issues/2539

This pull request introduces several improvements and refactors to the advanced search functionality, operator constants, and internationalization files. The main highlights are the refactoring of custom property handling in advanced search, the addition of new search operators, and the expansion of translation keys in multiple languages.

### Advanced Search Refactoring and Improvements

* Refactored the logic for handling custom properties in advanced search by replacing inline logic with a reusable `processEntityTypeFields` utility function, simplifying the code and improving maintainability in `AdvanceSearchProvider.component.tsx`. [[1]](diffhunk://#diff-ea40040c0c388b500e6f56c60d8b04faf6658888ca7984cd6089e1211510ad76L20-R21) [[2]](diffhunk://#diff-ea40040c0c388b500e6f56c60d8b04faf6658888ca7984cd6089e1211510ad76L33-R39) [[3]](diffhunk://#diff-ea40040c0c388b500e6f56c60d8b04faf6658888ca7984cd6089e1211510ad76L232-R230)
* Updated the SQL query formatting logic to clarify value assignment and improve readability in `AdvanceSearchProvider.component.tsx`.

### Operator Constants Enhancements

* Added new operators (`is_null`, `is_not_null`) to `MULTISELECT_FIELD_OPERATORS` and `NUMBER_FIELD_OPERATORS`, and defined `NUMBER_FIELD_OPERATORS` to better support null checks and range queries in `AdvancedSearch.constants.ts`.

### Type and Interface Updates

* Cleaned up and clarified type definitions related to aggregation buckets by removing the `AggregationEntry` and `Bucket` interface from `search.interface.ts`, and importing `Bucket` from the `Models` module instead. [[1]](diffhunk://#diff-471e6338c5f717ee9ad14fe6fdf9f1a0b8cc7c291f3df499ac006aca4d8f6754R14) [[2]](diffhunk://#diff-471e6338c5f717ee9ad14fe6fdf9f1a0b8cc7c291f3df499ac006aca4d8f6754L410-L422)

### Internationalization (i18n) Updates

* Added new translation keys for "start" and "end" (and their usage in date/time contexts) in English, Arabic, German, Spanish, French, and Galician language files. [[1]](diffhunk://#diff-f7fe84f16a48645e0b93ac986efc3fddbba73a7a82b96969a197a00b660cbedaR605) [[2]](diffhunk://#diff-f7fe84f16a48645e0b93ac986efc3fddbba73a7a82b96969a197a00b660cbedaR1660) [[3]](diffhunk://#diff-f7fe84f16a48645e0b93ac986efc3fddbba73a7a82b96969a197a00b660cbedaL2170-R2173) [[4]](diffhunk://#diff-13b7b0df62de02305392e0bbcc883493386601f0115b7676b8f8ec8e35e85467R605) [[5]](diffhunk://#diff-13b7b0df62de02305392e0bbcc883493386601f0115b7676b8f8ec8e35e85467R1660) [[6]](diffhunk://#diff-13b7b0df62de02305392e0bbcc883493386601f0115b7676b8f8ec8e35e85467L2170-R2173) [[7]](diffhunk://#diff-1e3bf29b7b168236549a9ecd31eed78c37a4560dd2d375025aadcb905613de0aR605) [[8]](diffhunk://#diff-1e3bf29b7b168236549a9ecd31eed78c37a4560dd2d375025aadcb905613de0aR1660) [[9]](diffhunk://#diff-1e3bf29b7b168236549a9ecd31eed78c37a4560dd2d375025aadcb905613de0aL2170-R2173) [[10]](diffhunk://#diff-556a3fbd92263f52b98d180d2106fe61cd61c8b97fcf50e5e3943d1690be24b2R605) [[11]](diffhunk://#diff-556a3fbd92263f52b98d180d2106fe61cd61c8b97fcf50e5e3943d1690be24b2R1660) [[12]](diffhunk://#diff-556a3fbd92263f52b98d180d2106fe61cd61c8b97fcf50e5e3943d1690be24b2L2170-R2173) [[13]](diffhunk://#diff-61c987ecb4dfbc9ee6cc22478ec7afd80c5051cc63763bb52e9035bb51afc433R605) [[14]](diffhunk://#diff-61c987ecb4dfbc9ee6cc22478ec7afd80c5051cc63763bb52e9035bb51afc433R1660) [[15]](diffhunk://#diff-61c987ecb4dfbc9ee6cc22478ec7afd80c5051cc63763bb52e9035bb51afc433L2170-R2173)
* Fixed untranslated warning messages by ensuring the domain asset migration warning is now localized in all supported languages. [[1]](diffhunk://#diff-f7fe84f16a48645e0b93ac986efc3fddbba73a7a82b96969a197a00b660cbedaL2170-R2173) [[2]](diffhunk://#diff-13b7b0df62de02305392e0bbcc883493386601f0115b7676b8f8ec8e35e85467L2170-R2173) [[3]](diffhunk://#diff-1e3bf29b7b168236549a9ecd31eed78c37a4560dd2d375025aadcb905613de0aL2170-R2173) [[4]](diffhunk://#diff-556a3fbd92263f52b98d180d2106fe61cd61c8b97fcf50e5e3943d1690be24b2L2170-R2173) [[5]](diffhunk://#diff-61c987ecb4dfbc9ee6cc22478ec7afd80c5051cc63763bb52e9035bb51afc433L2170-R2173)

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/utils/SearchUtils.tsx [hunk 1]
```diff
@@ -443,7 +478,13 @@ export const getTermQuery = (
     });
   }
 
-  const boolQuery: any = {
+  // Define type for Elasticsearch bool query structure
+  type ESBoolQuery = Record<string, ESQueryClause[] | number> & {
+    must_not?: ESQueryClause[];
+    minimum_should_match?: number;
+  };
```
Comment (karanh37) [inline openmetadata-ui/src/main/resources/ui/src/utils/SearchUtils.tsx]: We already have these interfaces, check ElasticsearchQuery in QueryBuilderUtils.tsx
