### PR TITLE
#17021: fix the widget placement when adding new

### LINKED ISSUE #17021: Placement of widget after adding is incorrect
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**

- After adding any widget the placement of it is in between some existing widgets making the layout disturbed.
**To Reproduce**

Screenshots or steps to reproduce

https://github.com/user-attachments/assets/26c24620-9d8b-4a0e-a98f-39888123ddac

**Expected behavior**

- Every new widget should be added at the bottom of the layout so, the existing layout placement should not be disturbed.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes:

Fixes #17021

- I worked on fixing the newly added widget to the bottom.
- Fix the check display on the widget even if it has been removed.

https://github.com/user-attachments/assets/eb79cd58-a182-4cee-b83f-ce7930f1bdc9

https://github.com/user-attachments/assets/8b534b09-8d75-463b-a34d-dfd53394f946

https://github.com/user-attachments/assets/135fe0b3-0dc7-4f21-8c49-54f0b488f3a0

### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Review by ShaileshParmar11 — COMMENTED** [review]
Please add test

File: openmetadata-ui/src/main/resources/ui/src/utils/CustomizableLandingPageUtils.tsx [hunk 1]
```diff
@@ -55,13 +55,24 @@ export const getAddWidgetHandler =
     if (
       placeholderWidgetKey === LandingPageWidgetKeys.EMPTY_WIDGET_PLACEHOLDER
     ) {
+      const lowestWidgetLayout = currentLayout.reduce(
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/utils/CustomizableLandingPageUtils.tsx:58]: I feel we need to capture the position on emptyWidget and pass it here. This logic will again add widget at bottom no?

File: openmetadata-ui/src/main/resources/ui/src/utils/CustomizableLandingPageUtils.tsx [hunk 2]
```diff
@@ -55,13 +55,17 @@ export const getAddWidgetHandler =
     if (
       placeholderWidgetKey === LandingPageWidgetKeys.EMPTY_WIDGET_PLACEHOLDER
     ) {
+      const emptyWidgetPlaceholder = currentLayout.find(
+        (item) => item.i === LandingPageWidgetKeys.EMPTY_WIDGET_PLACEHOLDER
+      ) ?? { x: 0, y: 99 };
+
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/utils/CustomizableLandingPageUtils.tsx:61]: will it still work as expected if I have multiple EmptyWidgets? 
Or are we not marking the removed widget as EmptyWidget

File: openmetadata-ui/src/main/resources/ui/src/utils/CustomizableLandingPageUtils.tsx [hunk 3]
```diff
@@ -55,13 +55,17 @@ export const getAddWidgetHandler =
...
       return [
         ...moveEmptyWidgetToTheEnd(currentLayout),
         {
           w: widgetWidth,
           h: widgetHeight,
-          x: 0,
-          y: 0,
+          x: emptyWidgetPlaceholder.x,
+          y: emptyWidgetPlaceholder.y,
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/src/utils/CustomizableLandingPageUtils.tsx:68]: We are giving the x and y the same as the empty placeholder, shouldn't the 'y' be y-1?

File: openmetadata-ui/src/main/resources/ui/src/utils/CustomizableLandingPageUtils.tsx (hunk 2 above)
Comment (Ashish8689) [reply openmetadata-ui/src/main/resources/ui/src/utils/CustomizableLandingPageUtils.tsx:61]: yes, it will work as the empty widgets are still set with the previous widget which was removed. so even we have multiple empty widget It will work fine. You can refer to the video as well.
image

File: openmetadata-ui/src/main/resources/ui/src/utils/CustomizableLandingPageUtils.tsx (hunk 3 above)
Comment (Ashish8689) [reply openmetadata-ui/src/main/resources/ui/src/utils/CustomizableLandingPageUtils.tsx:68]: It will be fine as the new widget will override the empty placeholder one!

**Review by chirag-madlani — APPROVED** [review]
