### PR TITLE
Issue-19066: ViewAll() not working with matchAnyTag() and isOwner() conditions

### LINKED ISSUE #19066: ViewAll() not working with matchAnyTag() and isOwner() conditions
ViewAll() not working with matchAnyTag() and isOwner() conditions

@chirag-madlani need someone from UI to handle the tests from playwright

### PR DESCRIPTION
**Pull request by harshach**
### Describe your changes:

Fixes #19066 

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/Entity.java [hunk 1]
```diff
@@ -260,6 +262,24 @@ public final class Entity {
...
+    ENTITY_SERVICE_TYPE_MAP.put(DASHBOARD_DATA_MODEL, DASHBOARD_SERVICE);
+    ENTITY_SERVICE_TYPE_MAP.put(CHART, DASHBOARD_SERVICE);
+    ENTITY_SERVICE_TYPE_MAP.put(PIPELINE, PIPELINE_SERVICE);
+    ENTITY_SERVICE_TYPE_MAP.put(MLMODEL, MLMODEL_SERVICE);
+    ENTITY_SERVICE_TYPE_MAP.put(TOPIC, MESSAGING_SERVICE);
+    ENTITY_SERVICE_TYPE_MAP.put(API, API_SERVICE);
+    ENTITY_SERVICE_TYPE_MAP.put(API_COLLCECTION, API_SERVICE);
+    ENTITY_SERVICE_TYPE_MAP.put(API_ENDPOINT, API_SERVICE);
+    ENTITY_SERVICE_TYPE_MAP.put(CONTAINER, STORAGE_SERVICE);
+    ENTITY_SERVICE_TYPE_MAP.put(SEARCH_INDEX, SEARCH_SERVICE);
```
Comment (sonika-shah) [inline openmetadata-service/src/main/java/org/openmetadata/service/Entity.java:281]: map value missing for  ` public static final String METADATA_SERVICE = "metadataService";`

Comment (harshach) [reply openmetadata-service/src/main/java/org/openmetadata/service/Entity.java:281]: @sonika-shah why do we need METADATA_SERVICE here? the goal is to have for a given data asset which is table, topic, etc. what is the respective service its associated with so that in ListFilter when someone passes service which is generic parameter to map to based on the entity its being queried on

**Review by sonika-shah — APPROVED** [review]
