### PR TITLE
[Fixes #1983 ] Fixed the use of string concatenation causing sonar warning instead o…

### LINKED ISSUE #1983: Format specifiers should be used instead of string concatenation.
Errors flagged by sonarcloud:
https://sonarcloud.io/project/issues?id=open-metadata_OpenMetadata&resolved=false&rules=java%3AS3457&severities=MAJOR

### PR DESCRIPTION
**Pull request by MustaphaGHA**
…f String Format method
Closes #1983
### Describe your changes :

Changed the use of concatenation that causes sonar warning and introduced String.format method 

#
### Type of change :

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [ ] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/CatalogApplication.java [hunk 1]
```diff
@@ -181,7 +181,7 @@ public void start() {
               @Override
               public void stop() {
                 long startTime = System.currentTimeMillis();
-                LOG.info("Took " + (System.currentTimeMillis() - startTime) + " ms to close all the services");
+                LOG.info(String.format("Took %s ms to close all the services", (System.currentTimeMillis() - startTime)));
               }
```
Comment (sureshms) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/CatalogApplication.java:185]: @MustaphaGHA, you can avoid String.format altogether by using parameterized logging as follows:
LOG.info("Took {} ms to close all the services", (System.currentTimeMillis() - startTime)));

See https://stackoverflow.com/questions/30975026/log4j-implicit-string-formatting

This can be done in other places as well.

**Comment by sureshms** [comment]
@MustaphaGHA, left a comment on the code to use parameterized log4j logging.

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/CatalogApplication.java (hunk 1 above)
Comment (MustaphaGHA) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/CatalogApplication.java:185]: Alright , applying changes now

**Review by sureshms — APPROVED** [review]

**Comment by sureshms** [comment]
@MustaphaGHA, congrats on your first-time contribution 🥳. Hopefully, many more to come!

**Comment by MustaphaGHA** [comment]
> @MustaphaGHA, congrats on your first-time contribution 🥳. Hopefully, many more to come!

Thank you 🥳🥳
