### PR TITLE
Fix #4452 UI: Redirection issue for glossary term from activity feeds

### LINKED ISSUE #4452: UI: Redirection issue for glossary term from activity feeds
**Affected module**
Does it impact the UI, backend or Ingestion Framework? - UI

**Describe the bug**
Clicking on glossary-term from activity-feed redirects to `glossary/activity_feed` instead of `glossary/<FQN>`

**To Reproduce**

https://user-images.githubusercontent.com/86726556/165016840-eac16267-8075-4d22-8c14-f564a0901899.mov

**Expected behavior**
Clicking on glossary-term from activity-feed should redirect to `glossary/<FQN>`

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
None

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
Fixes #4452 
### Describe your changes :

I worked on issue #4452 

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/FeedCardHeader/FeedCardHeader.tsx [hunk 1]
```diff
@@ -169,13 +183,61 @@ const FeedCardHeader: FC<FeedHeaderProp> = ({
       ].includes(entityType as EntityType)
     ) {
       displayName = getPartialNameFromFQN(entityFQN, ['service']);
+    } else if (
+      [EntityType.GLOSSARY, EntityType.GLOSSARY_TERM].includes(
+        entityType as EntityType
+      )
+    ) {
+      displayName = entityFQN.split(FQN_SEPARATOR_CHAR).pop();
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/FeedCardHeader/FeedCardHeader.tsx:191]: Do we need to join again by fqn separator character?

Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/FeedCardHeader/FeedCardHeader.tsx:191]: No, here we will just need the glossary or glossaryTerm name.

**Review by vivekratnavel — APPROVED** [review]
