### PR TITLE
fix: Some Column Attributes aren't being displayed, even if populated

### LINKED ISSUE #10451: Some Column Attributes aren't being displayed, even if populated
**Affected module**
UI. Highlighted in yellow are attributes that are not visible anywhere on UI. 

**Describe the bug**
I have populated precision, scale, ordinal position, display name, dataLegth column attributes. they have been consumed successfully (I can retrieve them via API), but they are not shown anywhere on the UI.

**To Reproduce**
Populate a few columns for a table (char and decimal) with all attributes populated.
image
image
Screenshots or steps to reproduce

**Expected behavior**
I would expect this information is being collected to display to OMD data catalog users. 

**Version:**
 - OS: [e.g. iOS]. Docker Deployment
 - Python version:
 - OpenMetadata version: [e.g. 13.2]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes :

fixed Some Column Attributes aren't being displayed, even if populated 
Closes #10451 
- Added `Scale`, `Precision` and `Ordinal Position` fields in entity details page
- Move `getEntityName` and `getEntityId` from commonUtils to EntityUtils file

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/TestSuitePipelineTab/TestSuitePipelineTab.component.tsx [hunk 1]
```diff
@@ -310,11 +311,13 @@ const TestSuitePipelineTab = () => {
         title: t('label.name'),
         dataIndex: 'name',
         key: 'name',
-        render: (name: string) => {
+        render: (_, record) => {
+          const FieldName = getEntityName(record);
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/TestSuitePipelineTab/TestSuitePipelineTab.component.tsx:315]:
```suggestion
          const name = getEntityName(record);
```

File: openmetadata-ui/src/main/resources/ui/src/components/TestSuitePipelineTab/TestSuitePipelineTab.component.tsx [hunk 2]
```diff
@@ -310,11 +311,13 @@ const TestSuitePipelineTab = () => {
...
+
           return (
             <Tooltip
               title={
-                viewPermission ? name : t('message.no-permission-to-view')
+                viewPermission ? FieldName : t('message.no-permission-to-view')
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/TestSuitePipelineTab/TestSuitePipelineTab.component.tsx:320]:
```suggestion
                viewPermission ? name : t('message.no-permission-to-view')
```

File: openmetadata-ui/src/main/resources/ui/src/components/TestSuitePipelineTab/TestSuitePipelineTab.component.tsx [hunk 3]
```diff
@@ -323,7 +326,7 @@ const TestSuitePipelineTab = () => {
                   href={`${airFlowEndPoint}`}
                   rel="noopener noreferrer"
                   target="_blank">
-                  {name}
+                  {FieldName}
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/TestSuitePipelineTab/TestSuitePipelineTab.component.tsx:329]:
```suggestion
                  {name}
```

**Review by chirag-madlani — APPROVED** [review]
