### PR TITLE
Fix : Fixing long team name issues #2280 #2279 #2277

### LINKED ISSUE #2277: Long team name changes the 'Add new user' button alignment
https://user-images.githubusercontent.com/83201188/150078816-2904ea0d-35cd-48bb-84e8-402397f58c7b.mov

Screenshot 2022-01-19 at 12 17 01 PM

### LINKED ISSUE #2279: Long team names while selecting teams during sign-in are not properly displayed.
https://user-images.githubusercontent.com/83201188/150080763-1c9c88c9-8e1e-476b-884e-1316df5906e9.mov

Screenshot 2022-01-19 at 12 35 48 PM

### LINKED ISSUE #2280: Team name goes out of the card
Screenshot 2022-01-19 at 12 38 39 PM

Screenshot 2022-01-19 at 12 39 42 PM

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
Fixes #2280 
Fixes #2279 
Fixes #2277 
### Describe your changes :

I worked on fixing long team name issues.

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
 @shahsank3t, @darth-coder00

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/ManageTab/ManageTab.component.tsx [hunk 1]
```diff
@@ -225,7 +226,17 @@ const ManageTab: FunctionComponent<Props> = ({
             theme="primary"
             variant="link"
             onClick={() => setListVisible((visible) => !visible)}>
-            {getOwnerById() || 'Select Owner'}
+            {getOwnerById() ? (
```
Comment (shahsank3t) [inline openmetadata-ui/src/main/resources/ui/src/components/ManageTab/ManageTab.component.tsx:229]: We are calling `getOwnerById` thrice. Instead, we should call it once and store it in a variable and use that variable everywhere.

**Review by shahsank3t — COMMENTED** [review]
One minor comment. Rest looks good to me.

**Review by shahsank3t — APPROVED** [review]
