### PR TITLE
#18008: global search should persist quick filter in explore

### LINKED ISSUE #18008: Search Clears Left Panel Tree Filters
**Affected module**
UI

**Describe the bug**
When using the data asset tree structure on the left panel to filter by a specific data source (e.g., BigQuery), later using the search bar at the top clears the applied filter and performs a global free text search instead of searching within the selected data source.

**To Reproduce**
1. Open OpenMetadata version 1.5.4
2. Navigate to the data asset tree structure on the left panel
3. Select a specific data source (e.g., BigQuery)
4. Use the search bar at the top to search for an asset
5. Observe that the search clears the BigQuery filter and performs a global search

**Expected behaviour**
When a data source is selected in the left panel, using the search bar should maintain the applied filter and search only within the selected data source. The user should have the option to perform a global search without clearing the applied filters.

**Version:**
 - OS: [User to specify]
 - Python version: [User to specify]
 - OpenMetadata version: 1.5.4

**Additional context**
This behaviour may cause confusion for users who expect the search to be limited to their selected data source. Consider implementing a way to make it clear when the search is limited to the components selected on the left side, or provide an option to toggle between filtered and global search.

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes:

Fixes #18008

- I worked on persisting quick filter when global search is applied on it

https://github.com/user-attachments/assets/7b0c860b-dd37-4c6c-b84c-8fb82f424fc2

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/AppBar/Suggestions.tsx [hunk 1]
```diff
@@ -171,6 +178,18 @@ const Suggestions = ({
...
+  const quickFilter = useMemo(() => {
+    const parsedSearch = Qs.parse(
+      location.search.startsWith('?')
+        ? location.search.substring(1)
+        : location.search
+    );
+
+    return !isString(parsedSearch.quickFilter)
+      ? {}
+      : JSON.parse(parsedSearch.quickFilter);
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/src/components/AppBar/Suggestions.tsx:190]: i feel its unnecessary negative condition!

**Review by ShaileshParmar11 — APPROVED** [review]
