### PR TITLE
✨ feat UI : kill endpoint for IngestionPipeline

### LINKED ISSUE #6273: UI kill endpoint for IngestionPipeline
Add a new action button `Kill` on the Ingestion Pipelines for `/kill/{id}`. It should kill and mark as failed any running execution for that pipeline

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
Closes #6273
### Describe your changes :

I worked on adding support for the kill endpoint for the ingestion pipelines.

#
### Type of change :

- [x] New feature

#
### Frontend Preview (Screenshots) :

https://user-images.githubusercontent.com/59080942/180766919-8a9285a1-fc0b-4d16-beec-97e2cc9e1287.mov

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/Modals/KillIngestionPipelineModal/KillIngestionPipelineModal.tsx [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+    try {
+      const response = await killIngestionPipelineById(pipelineId);
+      const status = response.status;
+      if (status === 200) {
+        onClose();
+        showSuccessToast(
+          `Successfully killed running workflows for ${pipelinName}.`
+        );
+        // reload the page after successful api response
+        history.go(0);
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/components/Modals/KillIngestionPipelineModal/KillIngestionPipelineModal.tsx:48]: Instead of reloading the page, can we fetch the API response again and re-render the component with the updated pipeline status? That should be much faster than a reload right?

Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/components/Modals/KillIngestionPipelineModal/KillIngestionPipelineModal.tsx]: Thanks, @vivekratnavel, I have removed the reload logic and added logic to fetch updated pipeline status.

**Review by pmbrull — APPROVED** [review]

File: openmetadata-ui/src/main/resources/ui/src/axiosAPIs/ingestionPipelineAPI.ts [hunk 2]
```diff
@@ -88,3 +88,9 @@ export const getIngestionPipelineLogById = (
 ): Promise<AxiosResponse> => {
   return APIClient.get(`/services/ingestionPipelines/logs/${id}/last`);
 };
+
+export const killIngestionPipelineById = (
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/axiosAPIs/ingestionPipelineAPI.ts:92]: Let's start adding: `get`, `post`, `put`, `delete` for Rest API functions, so that it will differ from normal function

File: openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx [hunk 3]
```diff
@@ -535,6 +542,17 @@ const Ingestion: React.FC<IngestionProps> = ({
                             )}
                           </button>
                           {separator}
+                          <button
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx:545]: Can we start using antD button now?

File: openmetadata-ui/src/main/resources/ui/src/components/Modals/KillIngestionPipelineModal/KillIngestionPipelineModal.tsx [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+      destroyOnClose
+      closable={false}
+      confirmLoading={isLoading}
+      data-testid="kill-modal"
+      okText="Confirm"
+      title={`Kill ${pipelinName} ?`}
+      visible={isModalOpen}
+      onCancel={onClose}
+      onOk={handleConfirm}>
+      <span data-testid="kill-modal-body">
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Modals/KillIngestionPipelineModal/KillIngestionPipelineModal.tsx:69]: <Typography.Text>?

**Review by chirag-madlani — COMMENTED** [review]
Thanks @Sachin-chaurasiya for having unit tests in code 🙌

**Review by chirag-madlani — APPROVED** [review]
Thanks @Sachin-chaurasiya
