### PR TITLE
Fix #2220: 2nd follow-up PR: Support for getting deleted entities in GET and LIST operations

### LINKED ISSUE #2220: 2nd follow-up PR: Support for getting deleted entities in GET and LIST operations
Follow-up of #2126 and #2206.

- [x] remove `addAllRelationships`
- [x] rename `addAllRelationshipsAfterCreation` to `beforeDeletion`
- [ ] review all `Include.NON_DELETED` if they are legit
- [x] consolidate all the getService (4) in EntityUtil
- [ ] remove getEntity without Include
- [ ] (do not work on this) design the lineage behaviour with deleted entities
- [ ] test with container deleted and/or the entity deleted
- [x] tests `owns` in User and Team
- [x] test `location` in Table
- [ ] Distinguish between 404 and 500 (database inconsistency)
#
image

### PR DESCRIPTION
**Pull request by amiorin**
### Describe your changes :

See #2220 

#
### Type of change :

- [x] Improvement

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

### CODE REVIEW

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java [hunk 1]
```diff
@@ -203,6 +218,20 @@ public static void deleteEntity(String entity, UUID entityId, boolean recursive)
...
+  public static <T> EntityRepository<T> getEntityRepositoryForClass(@NonNull Class<T> clazz) {
+    EntityRepository<T> entityRepository = (EntityRepository<T>) CLASS_ENTITY_REPOSITORY_MAP.get(clazz);
+    if (entityRepository == null) {
+      throw EntityNotFoundException.byMessage(
+          CatalogExceptionMessage.entityTypeNotFound(getEntityNameFromClass(clazz)));
+    }
+    return entityRepository;
+  }
+
+  public static <T> EntityRepository<T>.EntityHandler h(@NonNull T entity) {
```
Comment (mithmatt) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java:230]: h as in handler?

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/exception/CatalogExceptionMessage.java [hunk 2]
```diff
@@ -41,6 +41,10 @@ public static String entityTypeNotFound(String entity) {
     return String.format("Entity type %s not found", entity);
   }
 
+  public static String fieldIsNull(String entity) {
```
Comment (mithmatt) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/exception/CatalogExceptionMessage.java:44]: field instead of entity for variable name?

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/EntityRepository.java [hunk 3]
```diff
@@ -588,6 +585,198 @@ private void recoverDeletedRelationships(T original) {
...
+    public EntityReference getOwnerOrNull() {
+      List<EntityReference> refs =
+          daoCollection
+              .relationshipDAO()
+              .findFrom(
+                  entityInterface.getId().toString(), entityName, Relationship.OWNS.ordinal(), toBoolean(isDeleted));
+      if (refs.isEmpty()) {
+        return null;
+      } else if (refs.size() > 1) {
+        LOG.warn("Possible database issues - multiple relationships found for entity {}", entityInterface.getId());
```
Comment (mithmatt) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/EntityRepository.java:656]: Can we also add entity type in the log, so that it helps with debugging if needed?

Reasoning:
- With the type explicitly mentioned in the log line, it is easy for us to go directly to the corresponding table in the database

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/TableRepository.java [hunk 4]
```diff
@@ -13,8 +13,8 @@
 
 package org.openmetadata.catalog.jdbi3;
 
+import static org.openmetadata.catalog.Entity.*;
```
Comment (mithmatt) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/TableRepository.java:16]: Should we avoid having wildcard imports in the codebase?

File: catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/EntityResourceTest.java [hunk 5]
```diff
@@ -323,9 +330,9 @@ public void afterAllTests() throws Exception {
   public abstract Object createRequest(String name, String description, String displayName, EntityReference owner)
       throws URISyntaxException;
 
-  // Add all possible relationship to check if the entity is missing any of them after deletion
-  public Object addAllRelationships(TestInfo test, Object create) throws HttpResponseException {
-    return create;
+  // Add all possible relationships to check if the entity is missing any of them after deletion
+  public T beforeDeletion(TestInfo test, T entity) throws HttpResponseException {
```
Comment (mithmatt) [inline catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/EntityResourceTest.java:334]: `addAllRelationships` seems to have been more informative (based on comment above) more than `beforeDeletion`

May be I'm losing track of the sequence of API calls for tests.

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java (hunk 1 above)
Comment (amiorin) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java:230]: Yes, but any letter works. It's like the $ of jQuery. Given that you need to use it everywhere, better to make it short.

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/TableRepository.java (hunk 4 above)
Comment (amiorin) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/TableRepository.java:16]: We should, I don't how it was created.

File: catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/EntityResourceTest.java (hunk 5 above)
Comment (amiorin) [reply catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/EntityResourceTest.java:334]: `beforeDeletion` tells you when your code will be invoked and not what your code should do that could change in the future.

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/TableRepository.java (hunk 4 above)
Comment (mithmatt) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/TableRepository.java:16]: Check IntelliJ settings -- it does something automatically, if number of imports from the class exceeds a count.

I made it a large number (200) as shown below for "Class count to use import with * "

image

Comment (amiorin) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/TableRepository.java]: Mine is 999. No idea what happened.

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/exception/CatalogExceptionMessage.java (hunk 2 above)
Comment (amiorin) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/exception/CatalogExceptionMessage.java:44]: Yep

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/EntityRepository.java (hunk 3 above)
Comment (amiorin) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/EntityRepository.java]: Done.

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java [hunk 6]
```diff
@@ -203,6 +209,46 @@ public static void deleteEntity(String entity, UUID entityId, boolean recursive)
...
+
+  /**
+   * Utility method to create the decorator from an Entity class instance. By Entity class we don't mean Entity.java but
+   * the entity classes generated from JSONSchema files like DatabaseService, Database, Table, and so on.
+   *
+   * @param entity must be an Entity class instance with a companion EntityRepository
+   * @param <T> must be the Entity class of this entity or object if multiple results are possible.
+   * @return the decorator
+   */
+  public static <T> EntityRepository<T>.EntityHandler h(@NonNull T entity) {
```
Comment (harshach) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java:231]: @amiorin  can we have meaningful name here. "h" is really confusing what it does.

**Review by harshach — CHANGES_REQUESTED** [review]

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java (hunk 6 above)
Comment (amiorin) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java:231]: Sure, do you have anything in mind? The reason for being just one letter, it's that we need to type it often and it's inspired by jQuery `$`.

We need two names for `h` (Entity->Decorator) and `r` (EntityReference->Decorator).

Comment (amiorin) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java:231]: To be able to use overloading we need to implement the suggestion in #2267 because of [this](https://stackoverflow.com/a/17669851).

Comment (amiorin) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java]: done

**Review by harshach — APPROVED** [review]
