### PR TITLE
Fix #4090: Backend: Capture Activity Feed for Hard Delete Operation

### LINKED ISSUE #4090: Backend: Capture Activity Feed for Hard Delete Operation
We will be supporting hard delete from UI, It would be great if we capture the activity feed for the same. this will help the user to track what entities have been deleted.

### LINKED ISSUE #4312: team instance for <TEAM_ID> not found
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
backend

**Describe the bug**
once we soft-delete any team and refresh the tab and call users API with the team it throws an error.

**To Reproduce**
- delete any team
- refresh the page
- check the network tab in the developer tab.

Delete API:- 
`http://localhost:3000/api/v1/teams/cd7f642b-29c0-464a-9d3a-465ff4f92504`

after refreshing the page:-
user API:-
`http://localhost:3000/api/v1/users?fields=profile,teams,roles&limit=100000`

resposne-
```
{"code":404,"message":"team instance for 3100f560-cf78-4cd8-9fdf-57d17ab5638c not found"}
```

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### LINKED ISSUE #4341: UI: My Data and Following data is not updated in the homepage
https://user-images.githubusercontent.com/1051198/164537313-793451ba-2d93-4a68-bac0-182cbce6fc9c.mov

cc @harshach

### PR DESCRIPTION
**Pull request by vivekratnavel**
Closes #4341 
Closes #4312 

### Describe your changes :
See #4090 

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :
Screen Shot 2022-04-21 at 12 40 12 PM

https://user-images.githubusercontent.com/1051198/164585443-83150fc2-75db-42dc-8725-5e338191fb5f.mov

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

### CODE REVIEW

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/events/ChangeEventHandler.java [hunk 1]
```diff
@@ -79,7 +79,17 @@ public Void process(ContainerRequestContext requestContext, ContainerResponseCon
         for (var thread : CommonUtil.listOrEmpty(getThreads(responseContext))) {
```
Comment (harshach) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/events/ChangeEventHandler.java:79]: can we make this as part of import it self import CommonUtil.listOrEmpty

**Review by harshach — APPROVED** [review]

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/events/ChangeEventHandler.java (hunk 1 above)
Comment (vivekratnavel) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/events/ChangeEventHandler.java:79]: Sure, let me fix that

**Review by harshach — APPROVED** [review]
