### PR TITLE
Fix  UI :- Special character issue in column while creating  Quality test

### LINKED ISSUE #7623: Quality tests can not be created if the column names have spaces or special characters
**Affected module**
UI issue: Profiler and Quality test tab

**Describe the bug**
issue 1: Quality test cannot be created for the column names with spaces 
issue 2 : For columns with special characters in name, upon clicking the add test button the web page for adding test does not load.

payload for issue 1:

{name: "gross bookings_columnValueMaxToBeBetween", description: "",…}
description
:
""
entityLink
:
"<#E::table::[rs-dwh.dev](http://rs-dwh.dev/).public.vw_wbr_metrics_by_city_lw_wow::columns::gross bookings>"
name
:
"gross bookings_columnValueMaxToBeBetween"
owner
:
{id: "9ff2f38c-fa2e-4384-8f4b-92012fad6881", type: "user"}
parameterValues
:
[{name: "minValueForMaxInCol", value: 0}, {name: "maxValueForMaxInCol", value: 100}]
testDefinition
:
{id: "7d954464-ae39-4636-98e5-98c36b7822f5", type: "testDefinition"}
testSuite
:
{id: "b3679cae-5650-4db7-99cd-e531275e49c8", type: "testSuite"}

issue 2 

image (1)

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes :

-  Issue #7623
- Column having space or special character run into 404 page while creating DataQuality 

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :
Before :- 

https://user-images.githubusercontent.com/66266464/191728569-bf31af76-c027-42f5-8865-215f2c14955c.mov

After :- 

https://user-images.githubusercontent.com/66266464/191729050-e47f70b8-25b5-4d81-82c9-f871d2b235d7.mov

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/constants/constants.ts [hunk 1]
```diff
@@ -280,7 +280,7 @@ export const getVersionPath = (
 export const getTableTabPath = (tableFQN: string, tab = 'schema') => {
   let path = ROUTES.TABLE_DETAILS_WITH_TAB;
   path = path
-    .replace(PLACEHOLDER_ROUTE_TABLE_FQN, tableFQN)
+    .replace(PLACEHOLDER_ROUTE_TABLE_FQN, encodeURIComponent(tableFQN))
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/constants/constants.ts:283]: Can we use [`getEncodedFqn`](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-ui/src/main/resources/ui/src/utils/StringsUtils.ts#L131) util here?

**Review by ShaileshParmar11 — APPROVED** [review]
