### PR TITLE
Fixes 21540: Fixed the description highlight issue in the explore page

### LINKED ISSUE #21540: UI - Description is not Highlighted is any term is description is searched
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
- When searching for anything keyword that is present in the entity description and hitting enter, the matched text is not getting highlighted in the entity card.

**To Reproduce**

Screenshots or steps to reproduce

https://github.com/user-attachments/assets/6d84f90f-139c-4a99-9498-7b982b277352

**Expected behavior**

- The search text if present should be highlighted in description

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by Rohit0301**
### Describe your changes:
Fixed the description highlight issue in the explore page

Fixes #21540 

https://github.com/user-attachments/assets/2872ad4a-8dc5-4f08-bbc0-6cc224ce18cc

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/SearchedData/SearchedData.tsx [hunk 1]
```diff
@@ -72,6 +72,7 @@ const SearchedData: React.FC<SearchedDataProps> = ({
             handleSummaryPanelDisplay={handleSummaryPanelDisplay}
             id={`tabledatacard${index}`}
             matches={matches}
+            searchValue={filter?.search as string}
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/src/components/SearchedData/SearchedData.tsx:75]: Please avoid type casting.
