### PR TITLE
FIXES #14294: return null if no aggregation value is present

### LINKED ISSUE #14294: Api sent data with 0 for all the timestamps in cost analysis
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
ingestion/backend

**Describe the bug**
on the fresh instance, API sent data with 0 all the timestamps

**To Reproduce**

Screenshots or steps to reproduce

https://github.com/open-metadata/OpenMetadata/assets/71748675/96e1c6e6-0e6c-4eac-a6f7-49c5ff883dae

**Expected behavior**
if there is no data available send an empty array so UI can show no data placeholder

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by TeddyCr**
### Describe your changes:

Fixes #14294 
- return null if no aggregation value is present

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [x] I have commented on my code, particularly in hard-to-understand areas. 
- [x] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

Bug fix
- [x] I have added a test that covers the exact scenario we are fixing. For complex issues, comment the issue number in the test for future reference.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchAggregatedUnusedAssetsCountAggregator.java [hunk 1]
```diff
@@ -35,6 +35,6 @@ protected Sum getAggregations(Bucket bucket, String key) {
 
   @Override
   protected Double getValue(Sum aggregations) {
-    return aggregations != null ? aggregations.getValue() : 0.0;
+    return aggregations != null ? aggregations.getValue() : null;
```
Comment (mohityadav766) [inline openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchAggregatedUnusedAssetsCountAggregator.java:38]: you can also wrap these using Optional

**Review by mohityadav766 — APPROVED** [review]
