### PR TITLE
UI: Fixed Clicking "profiler & data quality" and "data quality" tab making the main tabs disappear #7351

### LINKED ISSUE #7351: Clicking "profiler & data quality" and "data quality" tab making the main tabs disappear
**Affected module**
UI

**Describe the bug**
image
Clicking the "profiler & data quality" and "data quality" tab makes the main tabs disappear

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes :

Fixed Clicking "profiler & data quality" and "data quality" tab making the main tabs disappear #7351
Closes #7351
#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :

https://user-images.githubusercontent.com/71748675/189868316-804fdcd2-d9ef-419d-9c25-e9379d2956c2.mov

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/TableProfilerV1.tsx [hunk 1]
```diff
@@ -60,16 +62,50 @@ const TableProfilerV1: FC<TableProfilerProps> = ({
...
+    testCaseStatus.unshift({
+      label: 'All',
+      value: '',
+    });
+
+    return testCaseStatus;
+  }, []);
+
+  const testCaseTypeOption = useMemo(() => {
+    const testCaseStatus: Record<string, string>[] = Object.entries(
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/TableProfilerV1.tsx:96]:
```suggestion
    const testCaseStatus: Option[] = Object.entries(
```

File: openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/TableProfilerV1.tsx [hunk 2]
```diff
@@ -169,6 +197,35 @@ const TableProfilerV1: FC<TableProfilerProps> = ({
...
+  };
+
+  const handleTestCaseTypeChange = (value: string) => {
+    if (value !== selectedTestType) {
+      setSelectedTestType(value);
+    }
+  };
+
+  const getFilterTestCase = () => {
+    let test: TestCase[] = [];
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/TableProfilerV1.tsx:213]:
```suggestion
    let tests: TestCase[] = [];
```

File: openmetadata-ui/src/main/resources/ui/src/styles/app.less [hunk 3]
```diff
@@ -35,6 +35,10 @@
   width: 100%;
 }
 
+.w-40 {
+  width: 10rem /* 160px */;
+}
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/styles/app.less:40]: move this to size.less

File: openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/TableProfilerV1.tsx [hunk 4]
```diff
@@ -60,16 +62,50 @@ const TableProfilerV1: FC<TableProfilerProps> = ({
...
     ProfilerDashboardTab.SUMMARY
   );
+  const [selectedTestCaseStatus, setSelectedTestCaseStatus] =
+    useState<string>('');
+  const [selectedTestType, setSelectedTestType] = useState('');
+  const isSummary = activeTab === ProfilerDashboardTab.SUMMARY;
+  const isDataQuality = activeTab === ProfilerDashboardTab.DATA_QUALITY;
+
+  const testCaseStatusOption = useMemo(() => {
+    const testCaseStatus: Record<string, string>[] = Object.values(
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/TableProfilerV1.tsx:81]: Can we use strict type here instead of `Record<string, string>`?

**Review by Sachin-chaurasiya — APPROVED** [review]
