### PR TITLE
Issue-19197: Deleting Data Product should delete the data asset relationships

### LINKED ISSUE #19197: Older Assignment are not deleted for Data Product
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
-- Backend

**Describe the bug**
-- Creating a new data product called Car, it gets 70 assets assigned seemingly at random. No other data product that I have created has had any assets automatically attached.

**To Reproduce**

Screenshots or steps to reproduce
-- Delete the existing Data Product, then recreate it with the same name. Once done, you should be able to see the assets already assigned to it.

**Expected behavior**
-- Older Assignment should be deleted for Data Product

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by harshach**
### Describe your changes:

Fixes #19197 

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java [hunk 1]
```diff
@@ -1151,6 +1151,7 @@ public final DeleteResponse<T> delete(
       String updatedBy, UUID id, boolean recursive, boolean hardDelete) {
     DeleteResponse<T> response = deleteInternal(updatedBy, id, recursive, hardDelete);
     postDelete(response.entity());
+    deleteFromSearch(response.entity(), hardDelete);
```
Comment (sonika-shah) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java:1154]: As we have removed the` repository.deleteFromSearch(response.entity(), response.changeType());` from deleteByName endpoint also, we need to add the  same `deleteFromSearch(response.entity(), hardDelete);`  in EntityRepository.deleteByName method

Comment (harshach) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java:1154]: @sonika-shah good catch! fixed it.

**Review by sonika-shah — APPROVED** [review]

**Review by ShaileshParmar11 — APPROVED** [review]

**Review by sonika-shah — APPROVED** [review]
