### PR TITLE
Fix #5229: Entity Type Custom field changes are recorded as Charts in activity feed

### LINKED ISSUE #5229: [Backend] : Entity Type Custom field changes are recorded as `Charts` in activity feed.
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Backend

**Describe the bug**
image

### PR DESCRIPTION
**Pull request by vivekratnavel**
### Describe your changes :
See #5229 

- Refactored "custom fields" -> "custom properties" in all the places

#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :

https://user-images.githubusercontent.com/1051198/171810828-55ad34c8-062e-40f0-919e-f80f731ff970.mov

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/CustomEntityDetail/CustomEntityDetail.tsx [hunk 1]
```diff
@@ -149,20 +149,20 @@ const CustomEntityDetail: FC<Props> = ({ entityTypes, entityTypeFQN }) => {
...
               <div data-testid="entity-custom-fields">
                 <div className="tw-flex tw-justify-end">
                   <Button
                     className="tw-mb-4 tw-py-1 tw-px-2 tw-rounded"
                     data-testid="add-field-button"
                     size="custom"
                     theme="primary"
-                    onClick={() => handleAddField()}>
-                    Add Field
+                    onClick={() => handleAddProperty()}>
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/components/CustomEntityDetail/CustomEntityDetail.tsx:160]:
```suggestion
                    onClick={handleAddProperty}>
```

**Review by Sachin-chaurasiya — APPROVED** [review]
