### PR TITLE
MINNOR: fix owner not showing after refresh in teams page

### LINKED ISSUE #16525: Owner not showing after refresh on Teams Page
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**

- After adding owner in a Team, if we refresh the page selected owner is disapper.

**To Reproduce**

Screenshots or steps to reproduce

https://github.com/open-metadata/OpenMetadata/assets/66266464/4d64c98a-1c1a-42a7-95e6-f7a1e6cb4d6b

**Expected behavior**

- Owner should be there after refresh or visiting the page

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes:

Fixes #16525

- I worked on fixing owner not showing after refresh in teams page

https://github.com/open-metadata/OpenMetadata/assets/66266464/f59dea63-f861-48fe-a790-fdb5a0f840d8

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Review by Sachin-chaurasiya — APPROVED** [review]

File: openmetadata-ui/src/main/resources/ui/src/pages/TeamsPage/TeamsPage.tsx [hunk 1]
```diff
@@ -217,7 +217,7 @@ const TeamsPage = () => {
     setIsPageLoading(loadPage);
     try {
       const data = await getTeamByName(name, {
-        fields: 'users,parents,profile',
+        fields: 'users,parents,profile,owner',
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/pages/TeamsPage/TeamsPage.tsx:220]: Do we need to change cypress for the same?

Comment (Ashish8689) [reply openmetadata-ui/src/main/resources/ui/src/pages/TeamsPage/TeamsPage.tsx:220]: No, we have unit test for the same, no need to update cypress for it.
