### PR TITLE
Fix KPI and Total Data Assets widgets

### LINKED ISSUE #21592: Create 12 widgets with all 2 size available small & medium
Refer widget design here: https://www.figma.com/design/iWBOROgihrvHr5Ah0ElDa0/Collate-Saas---1.7-Release?node-id=16515-19236&t=jyd9vwBe7dP0Ffl1-1

### PR DESCRIPTION
**Pull request by pranita09**
### Describe your changes:

Fixes #21592

Worked on KPI and Total Data Assets widget, also fixed minor style issues.

Screenshot 2025-07-17 at 12 43 22 PM

Screenshot 2025-07-17 at 12 11 57 AM

Screenshot 2025-07-17 at 1 00 13 AM

https://github.com/user-attachments/assets/f12d4e31-5628-43d0-a035-094622c9be0b

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Comment by chirag-madlani** [comment]
@pranita09 it's not aligned with Designs please ensure we are following designs here

File: openmetadata-ui/src/main/resources/ui/src/components/MyData/CustomizableComponents/CustomizablePageHeader/CustomizablePageHeader.tsx [hunk 1]
```diff
@@ -103,7 +103,7 @@ export const CustomizablePageHeader = ({
 
   return (
     <Card
-      className="customize-page-header"
+      className="customize-page-header m-b-lg"
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/MyData/CustomizableComponents/CustomizablePageHeader/CustomizablePageHeader.tsx:106]: Why card has a classname called page-header?

File: openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/CuratedAssetsWidget/curated-assets-widget.less [hunk 2]
```diff
@@ -82,31 +82,31 @@
...
-.ant-dropdown-menu-item-active {
-  color: @blue-34 !important;
-  background-color: @blue-33 !important;
-  font-weight: @font-medium !important;
+.widget-title-half-size {
+  max-width: 155px !important;
+}
+
+.widget-title-full-size {
+  max-width: 525px !important;
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/CuratedAssetsWidget/curated-assets-widget.less]: Why we need this fixed width?

File: openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/KPIWidget/KPILegend/kpi-legend.less [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+  .legend-dot {
+    border-radius: 50%;
+    display: inline-block;
+    flex-shrink: 0;
+  }
+
+  .kpi-full-legend {
+    text-align: center;
+    min-width: 280px;
+    background-color: #efedfe80;
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/KPIWidget/KPILegend/kpi-legend.less]: variable please, we are writing very regid CSS can we avoid doing so?

File: openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/MyTaskWidget/my-task-widget.less [hunk 4]
```diff
@@ -89,6 +89,23 @@
...
+      background-color: @blue-33 !important;
+      font-weight: 500 !important;
+    }
+  }
+
+  .ant-dropdown-menu-item-active {
+    color: @blue-34 !important;
+    background-color: @blue-33 !important;
+    font-weight: 500 !important;
+  }
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/MyTaskWidget/my-task-widget.less]: Why using too many !importatnt

File: openmetadata-ui/src/main/resources/ui/src/constants/Widgets.constant.ts [hunk 5]
```diff
@@ -72,3 +72,28 @@ export const WIDGETS_MORE_MENU_OPTIONS = [
...
+  '#1570EF',
+  '#2E90FA',
+];
+
+export const KPI_WIDGET_GRAPH_COLORS = [
+  '#7262F6',
+  '#6AD2FF',
+  '#E7B85D',
+  '#416BB3',
+];
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/constants/Widgets.constant.ts]: Why are not using theme colors?

File: openmetadata-ui/src/main/resources/ui/src/styles/variables.less [hunk 6]
```diff
@@ -151,6 +152,7 @@
 @grey-28: #00000040;
 @grey-29: #f9faff;
 @grey-30: #f4f6fb;
+@grey-31: #f1f3fc;
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/styles/variables.less:158]: We can't keep adding colors like this

File: openmetadata-ui/src/main/resources/ui/src/constants/Widgets.constant.ts (hunk 5 above)
Comment (pranita09) [reply openmetadata-ui/src/main/resources/ui/src/constants/Widgets.constant.ts]: Used theme colors for Total Data Assets Widget Chart. For KPI chart, if colors applied of the same shade using theme, the chart lines are not distinguishable, that's why keeping these colors from figma design.

File: openmetadata-ui/src/main/resources/ui/src/components/MyData/CustomizableComponents/CustomizablePageHeader/CustomizablePageHeader.tsx (hunk 1 above)
Comment (pranita09) [reply openmetadata-ui/src/main/resources/ui/src/components/MyData/CustomizableComponents/CustomizablePageHeader/CustomizablePageHeader.tsx:106]: This card represents customise page header that's why developer must have added it. The change from my end was m-b-lg only.

File: openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/KPIWidget/KPILegend/kpi-legend.less (hunk 3 above)
Comment (pranita09) [reply openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/KPIWidget/KPILegend/kpi-legend.less]: Used variables.

File: openmetadata-ui/src/main/resources/ui/src/styles/variables.less (hunk 6 above)
Comment (pranita09) [reply openmetadata-ui/src/main/resources/ui/src/styles/variables.less:158]: We didn't have similar shade in the existing colors, that's why added this one. Will keep this on mid to not add any more colors.

File: openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/CuratedAssetsWidget/curated-assets-widget.less (hunk 2 above)
Comment (pranita09) [reply openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/CuratedAssetsWidget/curated-assets-widget.less]: @shah-harshit for more context here.

File: openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/MyTaskWidget/my-task-widget.less (hunk 4 above)
Comment (pranita09) [reply openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/MyTaskWidget/my-task-widget.less]: Refactored the code.

File: openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/CuratedAssetsWidget/curated-assets-widget.less (hunk 2 above)
Comment (shah-harshit) [reply openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/CuratedAssetsWidget/curated-assets-widget.less]: We can remove this.

Comment (pranita09) [reply openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/CuratedAssetsWidget/curated-assets-widget.less]: Removed this and refactored the code.
