### PR TITLE
#22089: fix the table column selection not persisting for all action in dropdown

### LINKED ISSUE #22089: Table Column Customization not working on viewAll / hideAll action
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**

Table Column Customization not working on all action perform. Example below
- In Table page, I change the column to only name hiding other column one by one. I refresh, and can only see the name one, which works.
- Then I hit `ViewAll` button and can see other columns as well, but when I hit refresh, it get me back to that name column itself. Same with the `HideAll` button as well.

**To Reproduce**

Screenshots or steps to reproduce

https://github.com/user-attachments/assets/bf12d838-e995-4412-b990-423977ad93db

**Expected behavior**
- Bulk action should work same like single actions perform .

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes:

Fixes #22089

This pull request enhances the functionality of the `Table` component by introducing user preferences for column selection, improving test coverage, and refactoring related utilities. The changes include integrating user preferences for table column configurations, adding comprehensive tests for column selection behavior, and updating the `useCurrentUserStore` hook to support these preferences.

### Enhancements to `Table` Component:
* Integrated user preferences for managing selected table columns, replacing the previous reliance on `currentUser.fullyQualifiedName`. This includes updates to handle column selection, deselection, and bulk actions using the `setPreference` method from `useCurrentUserPreferences`. 

### Updates to `useCurrentUserStore` Hook:
* Added a `selectedEntityTableColumns` field to the `UserPreferences` interface and initialized it with default values. This enables the storage and retrieval of column preferences for different entity types.

### Test Coverage Improvements:
* Expanded the `Table.test.tsx` file with a new "Column Selection Functionality" test suite. This includes tests for initializing column selections, handling column selection/deselection, and verifying bulk actions like "View All" and "Hide All." Mock implementations were added for dependencies like `getTableColumnConfigSelections` and `handleUpdateTableColumnSelections`. 

### Utility Enhancements:
* Updated `TableUtils` to include new methods `getTableColumnConfigSelections` and `handleUpdateTableColumnSelections`, which are used to manage column preferences in the `Table` component. 

image

https://github.com/user-attachments/assets/9d4212ed-e01c-4549-8d6d-2a7f53c56825

#
### Type of change:

- [x] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx [hunk 1]
```diff
@@ -744,31 +745,24 @@ export const updateFieldDescription = <T extends TableFieldsInfoCommonEntities>(
...
-    return [];
-  }
-
-  const storageKey = `selectedColumns-${userFqn}`;
-  const selectedColumns = JSON.parse(localStorage.getItem(storageKey) ?? '{}');
-
   if (entityType) {
-    if (selectedColumns[entityType]) {
-      return selectedColumns[entityType];
+    if (selectedEntityTableColumns?.[entityType]) {
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx]: Since it's store now we can't be having it in utils

**Review by chirag-madlani — DISMISSED** [review]
@Ashish8689 one improvement suggestion

File: openmetadata-ui/src/main/resources/ui/src/components/common/Table/Table.tsx [hunk 2]
```diff
@@ -146,7 +144,36 @@ const Table = <T extends Record<string, unknown>>(
...
+    if (entityKey) {
+      if (selectedEntityTableColumns?.[entityKey]) {
+        return selectedEntityTableColumns[entityKey];
+      } else if (!isFullViewTable) {
+        setPreference({
+          selectedEntityTableColumns: {
+            ...selectedEntityTableColumns,
+            [entityKey]: defaultVisibleColumns ?? [],
+          },
+        });
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/common/Table/Table.tsx]: What's the reason for us to set it? Like we need to set in case of user changes anything on default right

Comment (Ashish8689) [reply openmetadata-ui/src/main/resources/ui/src/components/common/Table/Table.tsx]: yes, we don't require the setter here, reason while modifying any column. We already have the state data, which we take to perform the action. So at that time the initial localStorage set can happen.

**Review by chirag-madlani — APPROVED** [review]
