### PR TITLE
Fix #16471: Form validation message and alert bug fixes and improvements

### LINKED ISSUE #16471: Alerts bugs and improvements
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**

- [ ] Library styles overriding the spacing and alignment issue

Screenshot 2024-05-30 at 11 14 08 AM

- [ ] Alert form wrong error message (Scan through all forms for the same)

image (1)

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by aniketkatkar97**
Fixes #16471 

I worked on following:

- [x] Fixed the issues in #16471
- [x] Scanned through the application for the incorrect field name in the validation message

**Before:**

image (1)
Screenshot 2024-05-30 at 11 14 08 AM

**After:**

Screenshot 2024-06-21 at 5 12 21 PM
Screenshot 2024-06-21 at 5 13 53 PM

#
### Type of change:

- [x] Bug fix
- [x] Improvement

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/cypress/common/DomainUtils.ts [hunk 1]
```diff
@@ -49,7 +49,7 @@ export const validateDomainForm = () => {
     .type(INVALID_NAMES.MAX_LENGTH);
   cy.get('#name_help')
     .should('be.visible')
-    .contains(NAME_MAX_LENGTH_VALIDATION_ERROR);
+    .contains(NAME_MIN_MAX_LENGTH_VALIDATION_ERROR_1_128);
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/cypress/common/DomainUtils.ts:52]: this will not assert the value, this will only get the value, for assertion please use
`cy.get(<SELECTOR>).should("contain", <VALUE>)`

File: openmetadata-ui/src/main/resources/ui/cypress/common/GlossaryUtils.ts [hunk 2]
```diff
@@ -42,7 +42,7 @@ export const validateForm = () => {
     .type(INVALID_NAMES.MAX_LENGTH);
   cy.get('#name_help')
     .should('be.visible')
-    .contains(NAME_MAX_LENGTH_VALIDATION_ERROR);
+    .contains(NAME_MIN_MAX_LENGTH_VALIDATION_ERROR_1_128);
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/cypress/common/GlossaryUtils.ts:45]: same here

File: openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/UpdateDescriptionPage/UpdateDescriptionPage.tsx [hunk 3]
```diff
@@ -241,14 +243,7 @@ const UpdateDescription = () => {
                   data-testid="assignees"
                   label={`${t('label.assignee-plural')}:`}
                   name="assignees"
-                  rules={[
-                    {
-                      required: true,
-                      message: t('message.field-text-is-required', {
-                        fieldText: t('label.assignee-plural'),
-                      }),
-                    },
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/UpdateDescriptionPage/UpdateDescriptionPage.tsx:250]: I think after removing this message will contain "name" instead of translated value!

**Review by ShaileshParmar11 — COMMENTED** [review]
left few comment

File: openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/UpdateDescriptionPage/UpdateDescriptionPage.tsx (hunk 3 above)
Comment (aniketkatkar97) [reply openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/UpdateDescriptionPage/UpdateDescriptionPage.tsx:250]: We are passing the validation messages object in the form above. That will ensure that the label will be used in the message.

**Review by ShaileshParmar11 — APPROVED** [review]
