### PR TITLE
Fix #15809 : Update asset indexes on glossary term hierarchy change/ term rename

### LINKED ISSUE #15809: Losing assets after changing glossary terms hierarchy
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
backend

**Describe the bug**

- While changing glossary terms hierarchy which is having assets is not reflected after hierarchy/parent is being changed.
- After doing a re-index we can get it!

**Also Glossary parent renaming leads to all the assets being lost**

**To Reproduce**

Screenshots or steps to reproduce

https://github.com/open-metadata/OpenMetadata/assets/66266464/556cebbf-c2c5-4b1b-94d1-ac67228a4b83

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by sonika-shah**
### Describe your changes:

Fixes #15809

Cause -
The ES indexes of the associated assets were not getting updated with latest value of glossary term.

Changes-
added logic  to update the associated indexes in postMethod() of GlossaryTermRepository

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java [hunk 1]
```diff
@@ -532,6 +535,23 @@ public void postUpdate(GlossaryTerm original, GlossaryTerm updated) {
         closeApprovalTask(updated, "Rejected the glossary term");
       }
     }
+
+    // Update ES indexes of entity tagged with the glossary term to reflect its latest value.
```
[the remark this answers is not in the document]
Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java]: changes done as per feedback

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java [hunk 2]
```diff
@@ -99,6 +99,12 @@ public class GlossaryTermRepository extends EntityRepository<GlossaryTerm> {
   private static final String UPDATE_FIELDS = "references,relatedTerms,synonyms";
   private static final String PATCH_FIELDS = "references,relatedTerms,synonyms";
 
+  /*
```
Comment (mohityadav766) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java:102]: we cannot do it this way , this is not the right approach

Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java]: removed that change, currently  supports for changing the parent once in session
