### PR TITLE
fix(ui): modify activity feed icon and text

### LINKED ISSUE #12495: When the custom property value is too long, it can cause the Edit button to be inaccessible on the UI.
**Affected module**
UI

**Describe the bug**
 When the field value is too long, it can cause the Edit button to be inaccessible on the UI.
My field's length is 326.

**To Reproduce**

image

**Expected behavior**
It should show the "edit" button

**Version:**
OM 1.1.0

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes:

Issue : Closes #12495

- Change glossary term icon
- Change icon of activity feeds
- Modify activity feed text messages
- Fix text overflow issue in Custom Property.

image
image

image
image
image
image

image

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/Widgets/FeedsWidget/FeedsWidget.component.tsx [hunk 1]
```diff
@@ -131,19 +136,20 @@ const FeedsWidget = () => {
...
                 hidePopover={false}
                 isLoading={loading}
                 showThread={false}
+                tab={ActivityFeedTabs.TASKS}
               />
             ),
           },
         ]}
-        onChange={(key) => setActiveTab(key)}
+        onChange={(key) => setActiveTab(key as ActivityFeedTabs)}
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/src/components/Widgets/FeedsWidget/FeedsWidget.component.tsx:152]: Can we define a function outside the jsx? as this will create new function for each render.

**Review by aniketkatkar97 — COMMENTED** [review]
Left some comments. Also can we centre align the no data placeholders in the `Activity Feeds & Tasks` tab? as we are doing it in other places

**Comment by Ashish8689** [comment]
@aniketkatkar97  changes made as per comments!

File: openmetadata-ui/src/main/resources/ui/src/components/Widgets/FeedsWidget/FeedsWidget.component.tsx [hunk 2]
```diff
@@ -71,6 +71,8 @@ const FeedsWidget = () => {
     return getCountBadge(taskCount, '', activeTab === 'tasks');
   }, [taskCount, activeTab]);
 
+  const onTabChange = (key: string) => setActiveTab(key as ActivityFeedTabs);
+
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/src/components/Widgets/FeedsWidget/FeedsWidget.component.tsx:75]: Can we wrap this in useCallback? this is basically the same as before

**Review by aniketkatkar97 — COMMENTED** [review]
@Ashish8689 Left a minor comment
