### PR TITLE
Fixed UI sending incorrect timestep for fetching pipeline status #8050

### LINKED ISSUE #8050: UI sending incorrect timestep for fetching pipeline status
https://user-images.githubusercontent.com/71748675/194835751-11306768-768d-4b1b-8f3a-e3ffba78fa88.mov

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes :

I worked on fixing #8050
Closes #8050
- Fixed UI sending incorrect timestep for fetching pipeline status
- Flaky cypress test for bots

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :

https://user-images.githubusercontent.com/71748675/194844068-93af8bfd-9ab4-4c21-b2b1-9ddde13292a1.mov

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/cypress/common/common.js [hunk 1]
```diff
@@ -676,7 +681,7 @@ export const deleteSoftDeletedUser = (username) => {
 
 export const toastNotification = (msg) => {
   cy.get('.Toastify__toast-body').should('be.visible').contains(msg);
-  cy.wait(1000);
+  cy.wait(200);
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/cypress/common/common.js:684]: Why we are still using hardcoded values?

**Review by chirag-madlani — APPROVED** [review]

File: openmetadata-ui/src/main/resources/ui/cypress/common/common.js (hunk 1 above)
Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/cypress/common/common.js:684]: it might make the cypress flaky If the cypress tries to close the success toast as soon as it comes on screen! so we are showing the toast for 200mili sec. and after that, we closing the toast!
