### PR TITLE
Fix #10401 - Add Automations Workflow Resource & PUT service test connection result

### LINKED ISSUE #10401: Create Test Connection Workflow
Currently, the Test Connection endpoint is part of the Ingestion Pipeline Resource. However, the payload we send to the Test Connection endpoint, is not entirely related to an Ingestion Pipeline.

## Context

In https://github.com/open-metadata/OpenMetadata/pull/10383, we are adding greater support for Testing Connections to services, as well as a property in services to show their latest test connection results.

## Proposal

The goal is to separate the Test Connection from the Ingestion Pipeline into a new Workflow/Automations Resource.

The process will be as follows:
1. The UI triggers a new Test Connection Workflow, generating a workflow ID & the service name we are testing
2. OM receives the request, and passes it to the Ingestion Framework
3. The ingestion Framework flags the Workflow as RUNNING while it tests all the connection steps
4. The UI keeps polling the Workflow by ID to get the results until the state is SUCCESS/FAILED
5. When the Ingestion Framework finishes the processing, it updates the state of the Workflow and updates the services Test Connection Results.
6. OM will have a garbage collector to clean up old workflows -> Maybe we can reuse something from the Data Insights? I believe we might be cleaning some data already (or at least we wanted to) 🤔 

What happens if we test a workflow during service creation?
1. The UI triggers a new Test Connection workflow with a new ID and does not send a service name, but a set of credentials to test.
2. The Ingestion Framework receives the credentials. As there is no underlying service, creds cannot be fetched from the Ingestion Framework, they are received.
3. Polling from the UI + updates from the Ingestion side in the Workflow ID remain the same.
4. At the end, there is no service to update the Test Connection Results.

TBD: Add secrets manager logic

We'll create:
- Workflow Resource
- SQL table
- method in each service to PUT the Test Connection Results (similar to sending Sample Data to a table)
- We also need to add descriptions to steps in the Test Connection Definition

### PR DESCRIPTION
**Pull request by pmbrull**
### Describe your changes :

Fix #10401 

This PR prepares the backend logic to:
1. Create an Automations Workflow -> Next step is to use this to test the connection instead of the endpoint in the Ingestion Pipeline
2. The UI will create a workflow with a test connection request
3. The ingestion framework will async compute the test connection and keep pushing the response to the workflow
4. Once the computation is done, it will update the connection test result of the service (if any)
5. The UI just needs to poll the status of the workflow it created to get updated responses

#
### Type of change :

- [x] Bug fix
- [x] Improvement
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/clients/pipeline/airflow/AirflowRESTClient.java [hunk 1]
```diff
@@ -230,7 +230,7 @@ public Response getServiceStatus() {
   }
 
   @Override
-  public Response testConnection(TestServiceConnection testServiceConnection) {
+  public Response testConnection(TestServiceConnectionRequest testServiceConnection) {
```
Comment (pmbrull) [inline openmetadata-service/src/main/java/org/openmetadata/service/clients/pipeline/airflow/AirflowRESTClient.java:233]: For now we just align the imports. In a followup PR we'll update from a `testConnection` endpoint, to a `runOperationsWorkflow` one. This can then be developed in each pipeline service to execute the test or any other process

File: ingestion/src/metadata/ingestion/ometa/ometa_api.py [hunk 2]
```diff
@@ -333,6 +336,11 @@ def get_suffix(self, entity: Type[T]) -> str:  # pylint: disable=R0911,R0912
         ):
             return "/containers"
 
+        if issubclass(
+            entity, get_args(Union[Workflow, self.get_create_entity_type(Workflow)])
+        ):
+            return "/operations/workflow"
```
Comment (pmbrull) [inline ingestion/src/metadata/ingestion/ometa/ometa_api.py:342]: leave the ometa_api prepared

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java [hunk 3]
```diff
@@ -3442,4 +3446,166 @@ default String getNameColumn() {
...
+      return Workflow.class;
+    }
+
+    @Override
+    default String getNameColumn() {
+      return "name";
+    }
+
+    @Override
+    default List<String> listBefore(ListFilter filter, int limit, String before) {
```
Comment (pmbrull) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java:3467]: We allow to list worflows by type or status. Keeping things ready for when we add new operations in the backend

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ServiceEntityRepository.java [hunk 4]
```diff
@@ -101,6 +103,13 @@ public void storeRelationships(T service) {
     applyTags(service);
   }
 
+  public T addTestConnectionResult(UUID serviceId, TestConnectionResult testConnectionResult) throws IOException {
```
Comment (pmbrull) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ServiceEntityRepository.java:106]: generic method to add test connection results to all services

File: openmetadata-service/src/main/java/org/openmetadata/service/resources/services/dashboard/DashboardServiceResource.java [hunk 5]
```diff
@@ -210,6 +214,32 @@ public DashboardService getByName(
...
+      tags = "dashboardServices",
+      description = "Add test connection result to the service.",
+      responses = {
+          @ApiResponse(
+              responseCode = "200",
+              description = "Successfully updated the service",
+              content =
+              @Content(mediaType = "application/json", schema = @Schema(implementation = DatabaseService.class)))
+      })
+  public DashboardService addTestConnectionResult(
```
Comment (pmbrull) [inline openmetadata-service/src/main/java/org/openmetadata/service/resources/services/dashboard/DashboardServiceResource.java:231]: this has been added to all services

File: openmetadata-service/src/test/java/org/openmetadata/service/resources/services/DashboardServiceResourceTest.java [hunk 6]
```diff
@@ -153,6 +161,28 @@ void put_updateService_as_admin_2xx(TestInfo test) throws IOException, URISyntax
         dashboardConnection2, updatedService.getConnection(), updatedService.getServiceType(), ADMIN_AUTH_HEADERS);
   }
 
+  @Test
+  void put_testConnectionResult_200(TestInfo test) throws IOException {
```
Comment (pmbrull) [inline openmetadata-service/src/test/java/org/openmetadata/service/resources/services/DashboardServiceResourceTest.java:165]: validate all steps when adding the test connection result

File: openmetadata-spec/src/main/resources/json/schema/api/services/ingestionPipelines/testServiceConnection.json [hunk 7]
```diff
@@ -1,53 +0,0 @@
-{
-  "$id": "https://open-metadata.org/schema/api/services/ingestionPipelines/testServiceConnection.json",
-  "$schema": "http://json-schema.org/draft-07/schema#",
-  "title": "TestServiceConnectionRequest",
```
Comment (pmbrull) [inline openmetadata-spec/src/main/resources/json/schema/api/services/ingestionPipelines/testServiceConnection.json:4]: moving the test service connection to the operations directory

File: bootstrap/sql/com.mysql.cj.jdbc.Driver/v009__create_db_connection_info.sql [hunk 8]
```diff
@@ -60,3 +60,16 @@ CREATE TABLE IF NOT EXISTS test_connection_definition (
     PRIMARY KEY (id),
     UNIQUE (name)
 );
+
+CREATE TABLE IF NOT EXISTS operations_workflow (
```
Comment (harshach) [inline bootstrap/sql/com.mysql.cj.jdbc.Driver/v009__create_db_connection_info.sql:64]: shall we use automation workflow here. We want to go into automations post 1.0 release. We should be using the same workflows entities

Comment (pmbrull) [reply bootstrap/sql/com.mysql.cj.jdbc.Driver/v009__create_db_connection_info.sql:64]: thanks, will rename to `automations_workflow` & update API tags

**Review by nahuelverdugo — APPROVED** [review]

**Review by nahuelverdugo — APPROVED** [review]
