### PR TITLE
UI :- Added Redeploy option in Ingestion Pipeline action

### LINKED ISSUE #8226: UI: Redeploy option is not present in service ingestion pipeline actions.
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
Re Deploy button is not present for service ingestion pipelines

**To Reproduce**

Screenshots or steps to reproduce
Screenshot 2022-10-18 at 8 38 29 PM

**Expected behavior**
Deployed ingestion pipeline should have Re Deploy button after Run

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes :

- Issue : Closes #8226
- Added Redeploy option in Ingestion Pipeline action

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx [hunk 1]
```diff
@@ -352,41 +352,52 @@ const Ingestion: React.FC<IngestionProps> = ({
...
+      current.state === 'success' ? (
+        <FontAwesomeIcon icon="check" />
+      ) : (
+        <Loader size="small" type="default" />
+      )
+    ) : (
+      text
+    );
+  };
+
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx:370]: let's move it to utils and use it everywhere

**Review by ShaileshParmar11 — COMMENTED** [review]
left one comment

File: openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx (hunk 1 above)
Comment (Ashish8689) [reply openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx]: @ShaileshParmar11  Done!

File: openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx [hunk 2]
```diff
@@ -1040,3 +1043,20 @@ export const getIngestionFrequency = (pipelineType: PipelineType) => {
...
   }
 };
+
+//  return the ingestion state
+export const getIngestionStatusState = (
+  current: IngestionCurrentState,
+  ingestion: IngestionPipeline,
+  text: string
+) => {
+  return current.id === ingestion.id ? (
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx:1053]: use generic name instead of `getIngestionStatusState`, same for `ingestion` we only need ingestion id and not full object and make name accordingly

**Review by ShaileshParmar11 — DISMISSED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx [hunk 3]
```diff
@@ -355,38 +355,33 @@ const Ingestion: React.FC<IngestionProps> = ({
...
-          )}
-        </Button>
+        <>
+          <Button
+            data-testid="run"
+            type="link"
+            onClick={() =>
+              handleTriggerIngestion(ingestion.id as string, ingestion.name)
+            }>
+            {getLoadingStatus(currTriggerId, ingestion.id, 'Run')}
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx:365]: Localisation

File: openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx [hunk 4]
```diff
@@ -355,38 +355,33 @@ const Ingestion: React.FC<IngestionProps> = ({
...
+          </Button>
+          {separator}
+
+          <Button
+            data-testid="re-deploy-btn"
+            disabled={!isRequiredDetailsAvailable}
+            type="link"
+            onClick={() => handleDeployIngestion(ingestion.id as string)}>
+            {getLoadingStatus(currDeployId, ingestion.id, 'Re Deploy')}
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx:374]: Localisation

File: openmetadata-ui/src/main/resources/ui/src/components/TestSuitePipelineTab/TestSuitePipelineTab.component.tsx [hunk 5]
```diff
@@ -234,15 +237,7 @@ const TestSuitePipelineTab = () => {
...
-              {currTriggerId.id === ingestion.id ? (
-                currTriggerId.state === 'success' ? (
-                  <FontAwesomeIcon icon="check" />
-                ) : (
-                  <Loader size="small" type="default" />
-                )
-              ) : (
-                'Run'
-              )}
+              {getLoadingStatus(currTriggerId, ingestion.id, 'Run')}
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/TestSuitePipelineTab/TestSuitePipelineTab.component.tsx:240]: Localisation

File: openmetadata-ui/src/main/resources/ui/src/components/TestSuitePipelineTab/TestSuitePipelineTab.component.tsx [hunk 6]
```diff
@@ -255,15 +250,7 @@ const TestSuitePipelineTab = () => {
...
-              {currDeployId.id === ingestion.id ? (
-                currDeployId.state === 'success' ? (
-                  <FontAwesomeIcon icon="check" />
-                ) : (
-                  <Loader size="small" type="default" />
-                )
-              ) : (
-                'Re Deploy'
-              )}
+              {getLoadingStatus(currDeployId, ingestion.id, 'Re Deploy')}
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/TestSuitePipelineTab/TestSuitePipelineTab.component.tsx:253]: Localisation

**Comment by Ashish8689** [comment]
@chirag-madlani changes made as per comments

**Comment by chirag-madlani** [comment]
> @chirag-madlani changes made as per comments

Checks are failing can you check @Ashish8689

**Review by chirag-madlani — APPROVED** [review]
@Ashish8689 Did you test Re-deploy functionality fully functional?

**Comment by Ashish8689** [comment]
@chirag-madlani yes, it is tested and working perfectly.
