### PR TITLE
Fix #3160 UI Add support for deleting a post

### LINKED ISSUE #3160: UI: Add support for deleting a post
#3124 will bring in changes required to support the deletion of posts in the backend.

We need to support the same in the front end.

### LINKED ISSUE #3414: Activity Feed - User profiler teams, roles are extending the pop-over layer
**Affected module**
UI
**Describe the bug**
image

**Expected behavior**
1. Lets pop the hover not just on display but also on the username 
2. Make this clickable instead of hover over
3. wrap the content over to show the roles and teams properly

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### LINKED ISSUE #3444: UI: Conversation threads side drawer overlay is not overlaying all the components
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**

https://user-images.githubusercontent.com/1051198/158480592-0f6b300a-c960-4d90-b9d5-00d8836b9e40.mov

**To Reproduce**
Open conversation threads from a topic page.

**Expected behavior**
The overlay should properly overlay all the underlying components.

### LINKED ISSUE #3445: UI: Older replies user profile icon is incorrect in Activity Feed
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
The user profile icons displayed for older replies is not correct
Screen Shot 2022-03-15 at 3 59 30 PM

In the screen-shot above, notice that only the latest reply was by user "vivek", but the profile icon is shown for "2 older replies". 

**To Reproduce**
Add a reply to a thread 

**Expected behavior**
The user profile icons of correct users are displayed

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
Closes #3160
Closes #3444 
Closes #3445 
Closes #3414 

### Describe your changes :

I worked on issue #3160 

#
### Type of change :

- [x] Improvement
- [x] New feature

#
### Frontend Preview (Screenshots) :

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@shahsank3t, @darth-coder00 @vivekratnavel

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx [hunk 1]
```diff
@@ -569,6 +570,34 @@ const DashboardDetailsPage = () => {
...
+                ...thread,
+                posts: posts,
+                postsCount: thread.postsCount - 1,
+              };
+            });
+          });
+          getEntityFeedCount();
+          showToast({
+            variant: 'success',
+            body: 'Post got deleted successfully',
```
Comment (darth-coder00) [inline openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx:592]: Here message should be, `Message deleted successfully` or `Reply deleted successfully`

File: openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx [hunk 2]
```diff
@@ -569,6 +570,34 @@ const DashboardDetailsPage = () => {
...
+          });
+        }
+      })
+      .catch(() => {
+        showToast({ variant: 'error', body: 'Error while deleting post' });
```
Comment (darth-coder00) [inline openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx:597]: First of all, we should show error message from error response if we are getting any. If not then show fallback message like this.
Also message should be `Error while deleting message` or `Error while deleting reply`

File: openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx (hunk 1 above)
Comment (darth-coder00) [reply openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx:592]: Take care of similar changes everywhere else

File: openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx (hunk 2 above)
Comment (darth-coder00) [reply openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx:597]: Take care of similar changes everywhere else

**Review by darth-coder00 — CHANGES_REQUESTED** [review]
Minor changes required

**Review by darth-coder00 — APPROVED** [review]
LGTM!

File: openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityThreadPanel/ActivityThreadPanel.tsx [hunk 3]
```diff
@@ -351,12 +383,25 @@ const ActivityThreadPanel: FC<ActivityThreadPanelProp> = ({
...
               onThreadIdSelect={onThreadIdSelect}
               onThreadSelect={onThreadSelect}
             />
           </Fragment>
         )}
       </div>
+      {confirmationState.state && (
+        <ConfirmationModal
+          bodyClassName="tw-h-18"
+          bodyText="Are you sure you want to permanently remove this post?"
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityThreadPanel/ActivityThreadPanel.tsx:396]: Can we make this a component to avoid code duplication since we are using the same confirmation modal in at least 3 components?
So, that this can be replaced with 
```
{confirmationState.state && (
  <DeleteConfirmationModal onCancel={onDiscard} onConfirm={onDelete} />
)}
```

File: openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx [hunk 4]
```diff
@@ -569,6 +570,34 @@ const DashboardDetailsPage = () => {
...
+              const posts = thread.posts.filter((post) => post.id !== id);
+
+              return {
+                ...thread,
+                posts: posts,
+                postsCount: thread.postsCount - 1,
+              };
+            });
+          });
+          getEntityFeedCount();
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx:589]: Do we need to fetch feed count here for post deletion?

File: openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx [hunk 5]
```diff
@@ -569,6 +570,34 @@ const DashboardDetailsPage = () => {
...
+          showToast({
+            variant: 'success',
+            body: 'Reply deleted successfully',
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx:592]:
```suggestion
            body: 'Message deleted successfully',
```

File: openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx [hunk 6]
```diff
@@ -569,6 +570,34 @@ const DashboardDetailsPage = () => {
...
+          });
+        }
+      })
+      .catch(() => {
+        showToast({ variant: 'error', body: 'Error while deleting reply' });
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx:597]: We should show the error message for the user to understand why it failed.

File: openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx [hunk 7]
```diff
@@ -569,6 +570,34 @@ const DashboardDetailsPage = () => {
       });
   };
 
+  const deletePostHandler = (threadId: string, postId: string) => {
+    deletePostById(threadId, postId)
+      .then((res: AxiosResponse) => {
+        if (res.data) {
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx:576]: We should handle else case for any other response status

File: openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx [hunk 8]
```diff
@@ -763,18 +763,22 @@ const DatasetDetailsPage: FunctionComponent = () => {
...
+                posts: posts,
+                postsCount: thread.postsCount - 1,
+              };
             });
           });
           getEntityFeedCount();
           showToast({
             variant: 'success',
-            body: 'Post got deleted successfully',
+            body: 'Reply deleted successfully',
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx:776]:
```suggestion
            body: 'Message deleted successfully',
```

File: openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx [hunk 9]
```diff
@@ -763,18 +763,22 @@ const DatasetDetailsPage: FunctionComponent = () => {
...
           });
         }
       })
       .catch(() => {
-        showToast({ variant: 'error', body: 'Error while deleting post' });
+        showToast({ variant: 'error', body: 'Error while deleting reply' });
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx:781]:
```suggestion
        showToast({ variant: 'error', body: 'Error while deleting message' });
```

File: openmetadata-ui/src/main/resources/ui/src/pages/MyDataPage/MyDataPage.component.tsx [hunk 10]
```diff
@@ -189,17 +189,21 @@ const MyDataPage = () => {
...
           showToast({
             variant: 'success',
-            body: 'Post got deleted successfully',
+            body: 'Reply deleted successfully',
           });
         }
       })
       .catch(() => {
-        showToast({ variant: 'error', body: 'Error while deleting post' });
+        showToast({ variant: 'error', body: 'Error while deleting reply' });
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/pages/MyDataPage/MyDataPage.component.tsx:206]: Same comments as above. We should show error message.

File: openmetadata-ui/src/main/resources/ui/src/pages/PipelineDetails/PipelineDetailsPage.component.tsx [hunk 11]
```diff
@@ -514,6 +515,34 @@ const PipelineDetailsPage = () => {
       });
   };
 
+  const deletePostHandler = (threadId: string, postId: string) => {
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/pages/PipelineDetails/PipelineDetailsPage.component.tsx:518]: Can we avoid duplicating this deletePostHandler logic?

**Review by vivekratnavel — CHANGES_REQUESTED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedList/ActivityFeedList.tsx [hunk 12]
```diff
@@ -156,6 +160,31 @@ const ActivityFeedList: FC<ActivityFeedListProp> = ({
...
+  };
+
+  const onDelete = () => {
+    if (confirmationState.postId && confirmationState.threadId) {
+      deletePostHandler?.(confirmationState.threadId, confirmationState.postId);
+    }
+    onDiscard();
+  };
+
+  const onConfirmation = (data: ConfirmState) => {
```
[the remark this answers is not in the document]
Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedList/ActivityFeedList.tsx:186]: Yes, to set confirmation state.

File: openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedList/ActivityFeedList.tsx [hunk 13]
```diff
@@ -73,7 +73,9 @@ const FeedListBody: FC<FeedListBodyProp> = ({
           };
           const postLength = feed.posts.length;
           const replies = feed.postsCount - 1;
-          const repliedUsers = feed.posts.map((f) => f.from).slice(0, 2);
+          const repliedUsers = feed.posts
+            .map((f) => f.from)
+            .slice(0, postLength === 3 ? 2 : 1);
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedList/ActivityFeedList.tsx:78]: For postLength > 3, this will show only one user icon which is not ideal.

File: openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedPanel/ActivityFeedPanel.tsx [hunk 14]
```diff
@@ -157,6 +161,31 @@ const ActivityFeedPanel: FC<ActivityFeedPanelProp> = ({
   const [isLoading, setIsLoading] = useState<boolean>(false);
   const entityField = getEntityField(selectedThread.about);
 
+  const [confirmationState, setConfirmationState] = useState<ConfirmState>({
+    state: false,
```
[the remark this answers is not in the document]
Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedPanel/ActivityFeedPanel.tsx:165]: @vivekratnavel , we need that for an initial state.

File: openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx (hunk 4 above)
Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx:589]: @vivekratnavel , No, I will remove it.

File: openmetadata-ui/src/main/resources/ui/src/pages/PipelineDetails/PipelineDetailsPage.component.tsx (hunk 11 above)
Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/pages/PipelineDetails/PipelineDetailsPage.component.tsx:518]: @vivekratnavel,  We will need `deletePostHandler` in every page component, because we need to maintain internal state of that page component.

File: openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedList/ActivityFeedList.tsx (hunk 13 above)
Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedList/ActivityFeedList.tsx:78]: @vivekratnavel , we only get 3 latest posts right?

Comment (vivekratnavel) [reply openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedList/ActivityFeedList.tsx:78]: For now, we get 3 posts, but the length might change if the user replies. For instance, a thread can have 2 posts initially and when the user replies, I don't think we fetch the posts again. So, we should make sure we handle all the cases here to get a consistent UX. Also, please leave a comment on why we are slicing the posts here.

File: openmetadata-ui/src/main/resources/ui/src/pages/PipelineDetails/PipelineDetailsPage.component.tsx (hunk 11 above)
Comment (vivekratnavel) [reply openmetadata-ui/src/main/resources/ui/src/pages/PipelineDetails/PipelineDetailsPage.component.tsx:518]: We can write a utility method and pass a method to set state just like how we pass "onConfirmation" to child components. The signature of the utility method will be something like 
```
const deletePostHandler = (threadId: string, postId: string, onEntityThreadUpdate: )
```

File: openmetadata-ui/src/main/resources/ui/src/pages/MyDataPage/MyDataPage.component.tsx (hunk 10 above)
Comment (vivekratnavel) [reply openmetadata-ui/src/main/resources/ui/src/pages/MyDataPage/MyDataPage.component.tsx]: Can we make this error message a constant? So that if we want to update the error message, it will be a change in just one place.

File: openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedList/ActivityFeedList.tsx (hunk 13 above)
Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedList/ActivityFeedList.tsx:83]: @vivekratnavel , When we fetch a thread we only get 3 latest posts and when we add new replies that we get all the posts for that particular thread, but on the UI side we have some logic to get the latest 3 posts from that.

I'm slicing posts because we need to show the latest replied users avatat.

File: openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityThreadPanel/ActivityThreadPanel.tsx [hunk 15]
```diff
@@ -220,25 +217,29 @@ const ActivityThreadPanel: FC<ActivityThreadPanelProp> = ({
...
+    confirmStateInitialValue
+  );
 
-  const onDiscard = () => {
-    setConfirmationState({
-      state: false,
-      threadId: undefined,
-      postId: undefined,
+  const getThreads = () => {
+    getAllFeeds(threadLink).then((res: AxiosResponse) => {
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityThreadPanel/ActivityThreadPanel.tsx:225]: We should handle errors in a catch block

**Review by vivekratnavel — COMMENTED** [review]
Overall looks good to me. We just need to refactor deletePostHandler into a utility to avoid code duplication.

File: openmetadata-ui/src/main/resources/ui/src/pages/PipelineDetails/PipelineDetailsPage.component.tsx (hunk 11 above)
Comment (vivekratnavel) [reply openmetadata-ui/src/main/resources/ui/src/pages/PipelineDetails/PipelineDetailsPage.component.tsx:523]: @Sachin-chaurasiya Can you please take care of this refactoring?

**Review by vivekratnavel — APPROVED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityThreadPanel/ActivityThreadPanel.tsx (hunk 15 above)
Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityThreadPanel/ActivityThreadPanel.tsx:225]: Hey @vivekratnavel, sure will take care of this in the next patch.

File: openmetadata-ui/src/main/resources/ui/src/pages/PipelineDetails/PipelineDetailsPage.component.tsx (hunk 11 above)
Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/pages/PipelineDetails/PipelineDetailsPage.component.tsx:523]: @vivekratnavel , I already did, move out the API call to util method and calling the same method from deletePostHandler.
