### PR TITLE
Fix issue-4433 Delete action for glossary and teams page redirect to home page

### LINKED ISSUE #4433: Delete action for glossary and teams page redirect to home page

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes :

Closes #4433 
Delete action for glossary and teams page redirect to home page

#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :

https://user-images.githubusercontent.com/71748675/164978191-5fa81901-70ff-4e4e-b571-d5b27ec4c6bc.mov

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/pages/GlossaryPage/GlossaryPageV1.component.tsx [hunk 1]
```diff
@@ -666,6 +666,13 @@ const GlossaryPageV1 = () => {
     }
   };
 
+  const afterDeleteAction = () => {
+    setGlossariesList([]);
+    setIsLoading(true);
+    history.push(getGlossaryPath());
```
Comment (darth-coder00) [inline openmetadata-ui/src/main/resources/ui/src/pages/GlossaryPage/GlossaryPageV1.component.tsx:672]: Instead of always redirecting to Glossary path, can we check if deleted Glossary-Term has a parent, then that should be the active node after re-routing. 
In case of deleting Glossary, above redirection will work fine.

CC: @harshach @vivekratnavel

**Review by darth-coder00 — COMMENTED** [review]
Added one minor comment

File: openmetadata-ui/src/main/resources/ui/src/pages/GlossaryPage/GlossaryPageV1.component.tsx (hunk 1 above)
Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/pages/GlossaryPage/GlossaryPageV1.component.tsx:672]: Sure i Will check for that!

**Review by harshach — APPROVED** [review]
