### PR TITLE
GEN-1224: fixed Profiler is not displaying correct time for table profile

### LINKED ISSUE #17588: Profiler is not displaying correct time for table profile
**Affected module**
Ingestion

**Describe the bug**
UI is displays the time for DML queries in 12 hour instead of 24 hour.

### Example

The last query is in 14:20
Screenshot 2024-08-26 at 14 56 24](https://github.com/user-attachments/assets/caf97ad2-1577-4945-9f4e-005dee7ec65a)

Here it is registered as 2:20
Screenshot 2024-08-26 at 14 55 59

**To Reproduce**

1. Run the profiler on Snowflake after updating a table.
2. Observe the Table profile.

**Expected behavior**

Time labels in profiler charts should always be 24 hour unless configures otherwise by the use, in which case it should clearly state AM/PM.

**Version:**
 - OS: Macos
 - Python version: 3.11
 - OpenMetadata version: 3605d3d9da3e52ed6255a9f8406ee84862656531
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes:

Fixes #17588

image

image

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Comment by TeddyCr** [comment]
@ShaileshParmar11 have you checked the other graphs (Data Quality and Column Profiler)?

**Comment by ShaileshParmar11** [comment]
> @ShaileshParmar11 have you checked the other graphs (Data Quality and Column Profiler)?

Yes I have updated everywhere!

File: openmetadata-ui/src/main/resources/ui/src/utils/TableProfilerUtils.ts [hunk 1]
```diff
@@ -31,7 +34,10 @@ export const calculateRowCountMetrics = (
   const rowCountMetricData: MetricChartType['data'] = [];
 
   updateProfilerData.forEach((data) => {
-    const timestamp = customFormatDateTime(data.timestamp, 'MMM dd, hh:mm');
+    const timestamp = customFormatDateTime(
```
Comment (Sachin-chaurasiya) [inline openmetadata-ui/src/main/resources/ui/src/utils/TableProfilerUtils.ts:37]: @ShaileshParmar11 , can you add the unit test for customFormatDateTime with new format

**Review by Sachin-chaurasiya — APPROVED** [review]
