### PR TITLE
fix(ui): infinite scroll for tag listing inside term boost

### LINKED ISSUE #21762: Missing Infinite scroll for tag listing inside Search Settings
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
Limited tags are visible even if there are more tags available. 

**To Reproduce**

https://github.com/user-attachments/assets/41beed13-e25b-4993-93f8-d9d8303fb89d

**Expected behavior**

All tags should appear as user scrolls

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by pranita09**
### Describe your changes:

Fixes #21762

Worked on infinite scroll for tags listing inside Term Boost. Added optional infinite scroll functionality to AsyncSelect component, so that on scrolling api call should happen.

Affected areas: TermBoost, AddQueryPage, QueryUsedByOtherTables, IncidentManager - Verified all the other places for AsyncSelect behaviour.

https://github.com/user-attachments/assets/732e9149-f90b-4d7b-a03c-8d384fee4da4

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelect/AsyncSelect.tsx [hunk 1]
```diff
@@ -27,47 +36,138 @@ import Loader from '../Loader/Loader';
...
+  debounceTimeout = 400,
   ...restProps
 }: SelectProps & {
-  api: (queryString: string) => Promise<DefaultOptionType[]>;
+  api: (
+    queryString: string,
+    page?: number
+  ) => Promise<DefaultOptionType[] | PagingResponse<DefaultOptionType[]>>;
+  enableInfiniteScroll?: boolean;
+  debounceTimeout?: number;
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelect/AsyncSelect.tsx]: can we move this to the interface file?

File: openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelect/AsyncSelect.tsx [hunk 2]
```diff
@@ -27,47 +36,138 @@ import Loader from '../Loader/Loader';
...
+      try {
+        const response = await api(
+          value,
+          enableInfiniteScroll ? page : undefined
+        );
+
+        if (
+          enableInfiniteScroll &&
+          response &&
+          typeof response === 'object' &&
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelect/AsyncSelect.tsx]: can we use the lodash method here?

File: openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelect/AsyncSelect.tsx (hunk 1 above)
Comment (pranita09) [reply openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelect/AsyncSelect.tsx]: Moved this to interface file

File: openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelect/AsyncSelect.tsx (hunk 2 above)
Comment (pranita09) [reply openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelect/AsyncSelect.tsx]: Used lodash method

File: openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelect/AsyncSelect.tsx [hunk 3]
```diff
@@ -76,7 +70,7 @@ export const AsyncSelect = ({
         if (
           enableInfiniteScroll &&
           response &&
-          typeof response === 'object' &&
+          _.isObject(response) &&
```
Comment (ShaileshParmar11) [inline openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelect/AsyncSelect.tsx]: You are importing the full lodash library; instead, please import `isObject` fn.

Comment (pranita09) [reply openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelect/AsyncSelect.tsx]: Refactored the code, imported isObject only

**Review by ShaileshParmar11 — APPROVED** [review]
