### PR TITLE
Cypress: Fixed failing cypress for role page

### LINKED ISSUE #8417: UI : On explore page getting maxium depth error
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**

When we go to explore page we get maximum depth to exceed the error because the dependency in useEffect is changing too frequently.

**To Reproduce**

- Click on the discovery link on the navbar
- Now open the consoles and you will get to see the below error.

image

**Expected behavior**
We should remove the frequently changing dependency from useEffect and derive the state from another state.

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes :

I worked on the Fixed failing cypress for role page
fixed UI : On explore page getting maxium depth error #8417
Fixes #8417 
#
### Type of change :

- [x] Bug fix
- [x] Improvement
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/pages/RolesPage/RolesListPage/RolesList.tsx [hunk 1]
```diff
@@ -185,7 +185,7 @@ const RolesList: FC<RolesListProps> = ({ roles, fetchRoles }) => {
         data-testid="roles-list-table"
         dataSource={roles}
         pagination={false}
-        rowKey="id"
+        rowKey="name"
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/pages/RolesPage/RolesListPage/RolesList.tsx:188]: Is roleName will be unique?

Comment (ShaileshParmar11) [reply openmetadata-ui/src/main/resources/ui/src/pages/RolesPage/RolesListPage/RolesList.tsx:188]: Yes, it's unique!

**Review by chirag-madlani — APPROVED** [review]
