### PR TITLE
UI : Change the popover to hover on Type in table entity

### LINKED ISSUE #8346: Column name only display 20 characters and is cut off after that
**Affected module**
UI

**Describe the bug**
Full column name is not displayed but cut off after 20 characters

**To Reproduce**

image

**Expected behavior**
Display full column name

**Version:**
 - OS: Windows, Chrome
 - OpenMetadata version: 0.12.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes :

- Issue :- Closes #8346
- Change the popover to hover on on Type in table entity
- Increase the column width for name and type

#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx [hunk 1]
```diff
@@ -432,15 +432,16 @@ const EntityTable = ({
...
                 <div className="break-word">
                   <span>{lowerCase(dataTypeDisplay)}</span>
                 </div>
               }
               key="pop-over"
-              position="bottom"
+              position="top"
               theme="light"
-              trigger="click">
+              trigger="mouseenter">
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx:444]: Please use AntD `Popover`

Comment (Ashish8689) [reply openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx]: @chirag-madlani Updated to AntD `Popover`

**Review by chirag-madlani — APPROVED** [review]

**Review by ShaileshParmar11 — APPROVED** [review]

**Review by Sachin-chaurasiya — APPROVED** [review]
