### PR TITLE
Fixed #3475 for updated schema and fixed failing unit tests

### LINKED ISSUE #3475: Update Typescript interfaces from json schema

### PR DESCRIPTION
**Pull request by darth-coder00**
### Describe your changes :
Closes #3475 

I worked on the generating typescript interfaces from schema and fixed affected unit tests

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :
<p align="center">
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@shahsank3t @Sachin-chaurasiya @vivekratnavel @harshach

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/generated/entity/data/glossaryTerm.ts [hunk 1]
```diff
@@ -186,11 +190,11 @@ export interface EntityReference {
 
 export interface TermReference {
   /**
-   * Name that identifies the source of an external glossary term. Example `HealthCare.gov`
+   * Name that identifies the source of an external glossary term. Example `HealthCare.gov`.
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/generated/entity/data/glossaryTerm.ts:193]: This should be endpoint

File: openmetadata-ui/src/main/resources/ui/src/generated/entity/data/glossaryTerm.ts [hunk 2]
```diff
@@ -246,6 +254,14 @@ export enum LabelType {
   Propagated = 'Propagated',
 }
 
+/**
+ * Label is from Tags or Glossary.
+ */
+export enum Source {
```
Comment (vivekratnavel) [inline openmetadata-ui/src/main/resources/ui/src/generated/entity/data/glossaryTerm.ts:260]: We should rename this enum to `TagSource` to avoid confusion. Doesn't have to be in this patch. We can also take care of it in the next patches.

**Review by vivekratnavel — APPROVED** [review]
Minor comments inline

File: openmetadata-ui/src/main/resources/ui/src/generated/entity/data/glossaryTerm.ts (hunk 1 above)
Comment (darth-coder00) [reply openmetadata-ui/src/main/resources/ui/src/generated/entity/data/glossaryTerm.ts:193]: These are auto generated file from script, we do not change it manually

File: openmetadata-ui/src/main/resources/ui/src/generated/entity/data/glossaryTerm.ts (hunk 2 above)
Comment (darth-coder00) [reply openmetadata-ui/src/main/resources/ui/src/generated/entity/data/glossaryTerm.ts:260]: Auto generated from json schema as it is there

**Comment by harshach** [comment]
@darth-coder00  @kshinde2512 can we make sure the selenium tests are stable. Are these failed because of this PR or random test failure
```2022-03-16T20:00:37.8774048Z 20:00:37.863 [main] DEBUG org.apache.http.impl.conn.BasicClientConnectionManager - Connection can be kept alive indefinitely
2022-03-16T20:00:37.8774717Z [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.671 s - in org.openmetadata.catalog.selenium.pages.common.ApiTests
2022-03-16T20:00:38.4494582Z [INFO] 
2022-03-16T20:00:38.4497187Z [INFO] Results:
2022-03-16T20:00:38.4499532Z [INFO] 
2022-03-16T20:00:38.4502989Z [ERROR] Failures: 
2022-03-16T20:00:38.4503617Z [ERROR]   CommonTests.addMultipleTagsCheck:187 expected [11] but found [2]
2022-03-16T20:00:38.4504518Z [ERROR]   CommonTests.tagFilterCountCheck:351 expected [-1] but found [0]
2022-03-16T20:00:38.4506033Z [ERROR]   PaginationAndFilterTest.databaseFilterCountCheck:188 Tag not present
2022-03-16T20:00:38.4506712Z [ERROR]   DashboardDetailsPageTest.addChartTags:205 expected [3] but found [0]
2022-03-16T20:00:38.4508954Z [ERROR]   DashboardDetailsPageTest.removeChartTag:225 Tag not removed
2022-03-16T20:00:38.4509682Z [ERROR]   Explore.checkLastUpdatedSort:229 expected [This is a raw product catalog table contains the product listing, price, seller etc.. represented in our online DB.] but found [Updated Description]
2022-03-16T20:00:38.4510456Z [ERROR]   MyDataPageTest.checkFollowingTab:265 Following data not present
2022-03-16T20:00:38.4511036Z [ERROR]   TagsPageTest.addTagWithExistingName:245 expected [Not Used] but found [1]
2022-03-16T20:00:38.4511567Z [ERROR]   TagsPageTest.checkAddedTagToTableColumn:205 Tag not found
2022-03-16T20:00:38.4512088Z [ERROR]   TagsPageTest.removeTagFromTableColumn:218 Table is not present for the selected tag filter
2022-03-16T20:00:38.4512864Z [ERROR]   TagsPageTest.removeTagWithExistingName:272 Table is not present for the selected tag filter
2022-03-16T20:00:38.4513264Z [ERROR]   TeamsPageTest.addUser:136 User Not added
2022-03-16T20:00:38.4513628Z [ERROR]   TeamsPageTest.teamsWithSameDisplayNameCheck:265 2 teams with same name exists
2022-03-16T20:00:38.4514038Z [ERROR]   TopicDetailsPageTest.removeTags:152 Tag not found
2022-03-16T20:00:38.4514412Z [ERROR]   UsersPageTest.addAdminCheckCountCheck:74 expected [14] but found [15]```

**Comment by darth-coder00** [comment]
> @darth-coder00 @kshinde2512 can we make sure the selenium tests are stable. Are these failed because of this PR or random test failure
> 
> ```
> 2022-03-16T20:00:37.8774717Z [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.671 s - in org.openmetadata.catalog.selenium.pages.common.ApiTests
> 2022-03-16T20:00:38.4494582Z [INFO] 
> 2022-03-16T20:00:38.4497187Z [INFO] Results:
> 2022-03-16T20:00:38.4499532Z [INFO] 
> 2022-03-16T20:00:38.4502989Z [ERROR] Failures: 
> 2022-03-16T20:00:38.4503617Z [ERROR]   CommonTests.addMultipleTagsCheck:187 expected [11] but found [2]
> 2022-03-16T20:00:38.4504518Z [ERROR]   CommonTests.tagFilterCountCheck:351 expected [-1] but found [0]
> 2022-03-16T20:00:38.4506033Z [ERROR]   PaginationAndFilterTest.databaseFilterCountCheck:188 Tag not present
> 2022-03-16T20:00:38.4506712Z [ERROR]   DashboardDetailsPageTest.addChartTags:205 expected [3] but found [0]
> 2022-03-16T20:00:38.4508954Z [ERROR]   DashboardDetailsPageTest.removeChartTag:225 Tag not removed
> 2022-03-16T20:00:38.4509682Z [ERROR]   Explore.checkLastUpdatedSort:229 expected [This is a raw product catalog table contains the product listing, price, seller etc.. represented in our online DB.] but found [Updated Description]
> 2022-03-16T20:00:38.4510456Z [ERROR]   MyDataPageTest.checkFollowingTab:265 Following data not present
> 2022-03-16T20:00:38.4511036Z [ERROR]   TagsPageTest.addTagWithExistingName:245 expected [Not Used] but found [1]
> 2022-03-16T20:00:38.4511567Z [ERROR]   TagsPageTest.checkAddedTagToTableColumn:205 Tag not found
> 2022-03-16T20:00:38.4512088Z [ERROR]   TagsPageTest.removeTagFromTableColumn:218 Table is not present for the selected tag filter
> 2022-03-16T20:00:38.4512864Z [ERROR]   TagsPageTest.removeTagWithExistingName:272 Table is not present for the selected tag filter
> 2022-03-16T20:00:38.4513264Z [ERROR]   TeamsPageTest.addUser:136 User Not added
> 2022-03-16T20:00:38.4513628Z [ERROR]   TeamsPageTest.teamsWithSameDisplayNameCheck:265 2 teams with same name exists
> 2022-03-16T20:00:38.4514038Z [ERROR]   TopicDetailsPageTest.removeTags:152 Tag not found
> 2022-03-16T20:00:38.4514412Z [ERROR]   UsersPageTest.addAdminCheckCountCheck:74 expected [14] but found [15]```
> ```

Confirmed with @kshinde2512, it's not due to this PR

**Review by Sachin-chaurasiya — APPROVED** [review]
