### PR TITLE
Fix: #2938 Remove serviceType from service UI route

### LINKED ISSUE #2938: UI : Remove serviceType from service UI route
Currently, UI is sending serviceType with the service UI route. we don't require that anymore so UI can remove the serviceType from the route.
This will also help in UI feed thingy to redirect users from activity feed to corresponding service page.

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
Closes #2938 
### Describe your changes :

See #2938 

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@shahsank3t, @darth-coder00

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/pages/EntityVersionPage/EntityVersionPage.component.tsx [hunk 1]
```diff
@@ -155,15 +155,14 @@ const EntityVersionPage: FunctionComponent = () => {
...
                       ServiceCategory.DATABASE_SERVICES
                     )
                   : '',
                 imgSrc: serviceType ? serviceTypeLogo(serviceType) : undefined,
               },
               {
-                name: database.name,
-                url: getDatabaseDetailsPath(database.fullyQualifiedName),
+                name: getPartialNameFromFQN(database.name, ['database']),
+                url: getDatabaseDetailsPath(database.name),
```
Comment (darth-coder00) [inline openmetadata-ui/src/main/resources/ui/src/pages/EntityVersionPage/EntityVersionPage.component.tsx:165]: Why is this change required?

File: openmetadata-ui/src/main/resources/ui/src/pages/EntityVersionPage/EntityVersionPage.component.tsx [hunk 2]
```diff
@@ -381,8 +376,8 @@ const EntityVersionPage: FunctionComponent = () => {
                       : undefined,
                   },
                   {
-                    name: database.name,
-                    url: getDatabaseDetailsPath(database.fullyQualifiedName),
+                    name: getPartialNameFromFQN(database.name, ['database']),
+                    url: getDatabaseDetailsPath(database.name),
```
Comment (darth-coder00) [inline openmetadata-ui/src/main/resources/ui/src/pages/EntityVersionPage/EntityVersionPage.component.tsx:380]: Same here

**Review by darth-coder00 — COMMENTED** [review]
@Sachin-chaurasiya, Added some queries

File: openmetadata-ui/src/main/resources/ui/src/pages/EntityVersionPage/EntityVersionPage.component.tsx (hunk 2 above)
Comment (Sachin-chaurasiya) [reply openmetadata-ui/src/main/resources/ui/src/pages/EntityVersionPage/EntityVersionPage.component.tsx:380]: Because from backend we are not getting `fullyQualifiedName` and in `name` field we are getting fqn value.

**Review by darth-coder00 — APPROVED** [review]
LGTM!
