### PR TITLE
Fix #22422: Classification term count showing 0 in UI                …

### LINKED ISSUE #22422: Classification count in left panel showing 0 even contain multiple tags
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
backend

**Describe the bug**

- The `termCount` data in the Classification API seems missing which we are using in the UI to show the total tags counts in the classification.
- From t the API we are sending the `termCount`.
- `https://sandbox-beta.open-metadata.org/api/v1/classifications?fields=termCount%2Cowners%2Cdomain&limit=1000
`

**To Reproduce**

Image

Screenshots or steps to reproduce

**Expected behavior**

- API should return us the `termCount`

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by harshach**
- Added bulk fetch methods to ClassificationDAO for efficient term count retrieval                                                                                                     - Implemented proper batch fetching in ClassificationRepository.setFieldsInBulk                                                                                                        
- Added ConnectionAwareSqlQuery annotations for MySQL and PostgreSQL compatibility                                                                                                     
- Fixed duplicate key error in TagRepository.batchFetchUsageCounts                                                                                                                     
- Added Playwright test to verify classification term counts display correctly

### Describe your changes:

Fixes #22422 

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java [hunk 1]
```diff
@@ -3661,6 +3661,53 @@ default Class<Classification> getEntityClass() {
     default String getNameHashColumn() {
       return "nameHash";
     }
+
+    @ConnectionAwareSqlQuery(
+        value =
+            "SELECT SUBSTRING_INDEX(t.fqnHash, '.', 1) as classificationHash, COUNT(*) as termCount "
+                + "FROM tag t "
+                + "WHERE t.deleted = FALSE "
+                + "AND t.fqnHash LIKE CONCAT(:classificationHash, '.%') "
```
Comment (sonika-shah) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java]: Todo : we can use @BindConcat annotation , instead of directly using CONCAT in where clause which affects query performance

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java [hunk 2]
```diff
@@ -3661,6 +3661,53 @@ default Class<Classification> getEntityClass() {
...
+                + "AND t.fqnHash REGEXP :classificationHashPattern "
+                + "GROUP BY SUBSTRING_INDEX(t.fqnHash, '.', 1)",
+        connectionType = MYSQL)
+    @ConnectionAwareSqlQuery(
+        value =
+            "SELECT SPLIT_PART(t.fqnHash, '.', 1) as classificationHash, COUNT(*) as termCount "
+                + "FROM tag t "
+                + "WHERE t.deleted = FALSE "
+                + "AND t.fqnHash ~ :classificationHashPattern "
+                + "GROUP BY SPLIT_PART(t.fqnHash, '.', 1)",
```
Comment (sonika-shah) [inline openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java]: Todo :
- instead of calculating classification hash everytime in GROUP BY , we can have a separate column for it classification hash that will hold SPLIT_PART(t.fqnHash, '.', 1)
- Replace REGEXP-based heavy processing in WHERE clause with LIKE and @BindList (or @BindConcat)

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java (hunk 1 above)
Comment (harshach) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java]: @sonika-shah add your changes to PR and get it merged

File: openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java (hunk 2 above)
Comment (sonika-shah) [reply openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java]: **Resolved**

- Added a dedicated `classificationHash` column to the `tag` table (generated from `fqnhash` using `SPLIT_PART` in PostgreSQL and `SUBSTRING_INDEX` in MySQL) to avoid recomputing it in `GROUP BY`.
- Replaced expensive `REGEXP`-based (is not index friendly) filtering with an index-friendly `JOIN` on `classificationHash`:
  -  MySQL: `JSON_TABLE(:jsonHashes)`
  -  PostgreSQL: `UNNEST(:hashArray)`
- This approach eliminates full table scans and scales efficiently with 1000+ values.
- used optimization idea from here : https://medium.com/@mukul.chaware13/sql-query-optimization-for-large-in-queries-74f58dc524b6

**Review by sonika-shah — APPROVED** [review]
