### PR TITLE
Fix: #2352 Tooltip placement issue

### LINKED ISSUE #2352: Placement of tour tool tip is slightly off from the element it should be pointing to
image

@shahsank3t @Sachin-chaurasiya

### PR DESCRIPTION
**Pull request by darth-coder00**
### Describe your changes :
Closes #2352 

I worked on the bubble placement issues for tour feature. Now it supports position arrangements based on available space around focus rect

#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :
<p align="center">
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@shahsank3t @Sachin-chaurasiya

### CODE REVIEW

**Review by Sachin-chaurasiya — APPROVED** [review]

File: openmetadata-ui/src/main/resources/ui/src/utils/TourUtils.tsx [hunk 1]
```diff
@@ -210,7 +193,6 @@ export const getSteps = (value: string, clearSearchTerm: () => void) => {
           Click on the <strong>&quot;Manage&quot;</strong> tab
         </p>
       ),
-      position: [440, 240],
```
Comment (mithmatt) [inline openmetadata-ui/src/main/resources/ui/src/utils/TourUtils.tsx:213]: Is the positioning for each of theses handled from within the library?

Comment (darth-coder00) [reply openmetadata-ui/src/main/resources/ui/src/utils/TourUtils.tsx:213]: Yes

Comment (darth-coder00) [reply openmetadata-ui/src/main/resources/ui/src/utils/TourUtils.tsx:213]: Instead of giving absolute position, we are not just passing priority order to the component like `['top', 'bottom', 'left', 'right']` and library will take care of it based on available rect and offsets
