### PR TITLE
Fix #2464: PipelineRepository throws NPE when description is updated

### LINKED ISSUE #2464: PipelineRepository throws NPE when description is updated
Fix the following NPE:

```
PATCH /api/v1/pipelines/0f1e0e65-8b17-4129-b88a-a19b05caf12c] o.o.c.e.CatalogGenericExceptionMapper - exception  
java.lang.NullPointerException: null                                                                           
    at org.openmetadata.catalog.jdbi3.PipelineRepository$PipelineUpdater.updateTaskDescription(PipelineRepository.java:362)
    at org.openmetadata.catalog.jdbi3.PipelineRepository$PipelineUpdater.updateTasks(PipelineRepository.java:351)                    
    at org.openmetadata.catalog.jdbi3.PipelineRepository$PipelineUpdater.entitySpecificUpdate(PipelineRepository.java:319)                              
    at org.openmetadata.catalog.jdbi3.EntityRepository$EntityUpdater.update(EntityRepository.java:880)                                        
    at org.openmetadata.catalog.jdbi3.EntityRepository$EntityUpdater.update(EntityRepository.java:866)                                        
    at org.openmetadata.catalog.jdbi3.EntityRepository.patch(EntityRepository.java:410)
```

### PR DESCRIPTION
**Pull request by vivekratnavel**
### Describe your changes :
Fixed the NPE when pipeline description is updated

#
### Type of change :

- [x] Bug fix

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [ ] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

### CODE REVIEW

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/PipelineRepository.java [hunk 1]
```diff
@@ -359,7 +359,9 @@ private void updateTaskDescription(Task origTask, Task updatedTask) throws JsonP
         return;
       }
       // Don't record a change if descriptions are the same
-      if (!origTask.getDescription().equals(updatedTask.getDescription())) {
+      if (origTask != null
```
Comment (harshach) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/PipelineRepository.java:362]: @vivekratnavel we should also check if the updated task description is also null. There is no point in recordChange if the updatedTask doesn't have any description

File: catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/PipelineRepository.java [hunk 2]
```diff
@@ -359,7 +359,9 @@ private void updateTaskDescription(Task origTask, Task updatedTask) throws JsonP
...
+          && origTask.getDescription() != null
```
Comment (harshach) [inline catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/PipelineRepository.java:363]: it should be "Or" condition here, if the task doesn't have any description but the updatedTask has description we should set that

Comment (harshach) [reply catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/PipelineRepository.java:363]: Lets also add a unit test for this

**Review by harshach — APPROVED** [review]
