### PR TITLE
Fix #17742 - show sub domain assets to top level

### LINKED ISSUE #17742: Sub Domain assets do not inherit to top level Domains
**Affected module**
Impacts the UI

**Describe the bug**
Regarding Subdomains, if the subdomain owns assets, it seems the top-level domain does not own that asset automatically; our assumption is that it should

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
1.) Create a Top-Level Domain
2.) Create a Sub-Level domain that belongs to the Domain you created in the previous step.
3.) Add Data Assets to the Sub-Level Domain
4.) Go to the Top-Level Domain, the Assets tab is empty. It should inherit the sub domain assets.  

**Version:**
 - OS: Kubernetes
 - OpenMetadata version: 1.5.2
 - Helm : 1.5.2

### LINKED ISSUE #19573: Relating data assets to sub-domain not consistent / not working
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
--Backend

**Describe the bug**
-- Relating data assets from a sub-domain not working / consistent within "Domain" view but working from "Data asset" view
In other words if I enter any data asset and have permissions (Admin access to all) > I can relate the data asset to a sub-domain
If I however within "Domain" feature > Navigate to sub-domain > press "Relate assets" > I can only relate assets that are part of my Parent domain

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

--A user with full permissions should be able to related any data asset to a sub-domain through the "Domain" navigation. 
The behavior should be consistent no matter what interface you use to relate data assets to domains

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by karanh37**
### Describe your changes:

Fixes #17742 
Fixes #19573 

https://github.com/user-attachments/assets/3187b04c-e8f6-4ce6-ab20-f1be3f796d1d

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

File: openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainDetailsPage/DomainDetailsPage.component.tsx [hunk 1]
```diff
@@ -347,17 +347,17 @@ const DomainDetailsPage = ({
...
-          '',
-          SearchIndex.ALL
-        );
-
-        setAssetCount(res.data.hits.total.value ?? 0);
+        const res = await searchQuery({
+          query: '',
+          pageNumber: 0,
+          pageSize: 0,
+          queryFilter: queryFilter,
```
Comment (aniketkatkar97) [inline openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainDetailsPage/DomainDetailsPage.component.tsx:354]:
```suggestion
          queryFilter,
```

File: openmetadata-ui/src/main/resources/ui/src/components/NavBar/NavBar.tsx [hunk 2]
```diff
@@ -552,37 +580,38 @@ const NavBar = ({
...
+                <Col className="flex-center">
+                  <Typography.Text>
+                    {activeDomainEntityRef
+                      ? getEntityName(activeDomainEntityRef)
+                      : activeDomain}
+                  </Typography.Text>
+                </Col>
+                <Col className="flex-center">
+                  <DropDownIcon height={14} width={14} />
+                </Col>
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/NavBar/NavBar.tsx:611]: I guess we can use a button instead?

File: openmetadata-ui/src/main/resources/ui/src/components/common/DomainSelectableTree/DomainSelectableTree.tsx [hunk 3]
```diff
@@ -217,7 +247,9 @@ const DomainSelectablTree: FC<DomainSelectableTreeProps> = ({
           loading={isSubmitLoading}
           size="small"
           type="default"
-          onClick={() => handleSave()}>
+          onClick={() =>
+            isMultiple ? handleMultiDomainSave() : handleSingleDomainSave()
+          }>
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/common/DomainSelectableTree/DomainSelectableTree.tsx:252]:
```suggestion
          onClick={
            isMultiple ? handleMultiDomainSave : handleSingleDomainSave
          }>
```

File: openmetadata-ui/src/main/resources/ui/src/utils/DomainUtils.tsx [hunk 4]
```diff
@@ -269,3 +284,26 @@ export const convertDomainsToTreeOptions = (
...
   return treeData;
 };
+
+/**
+ * Recursively checks if a domain exists in the hierarchy
+ * @param domain The domain to search in
+ * @param searchDomain The domain to search for
+ * @returns boolean indicating if the domain exists
+ */
+export const isDomainExist = (
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/utils/DomainUtils.tsx:294]: can we add tests for utils?

File: openmetadata-ui/src/main/resources/ui/src/components/NavBar/NavBar.tsx (hunk 2 above)
Comment (karanh37) [reply openmetadata-ui/src/main/resources/ui/src/components/NavBar/NavBar.tsx:611]: DomainSelectableList is wrapping this row inside button only.

**Review by chirag-madlani — APPROVED** [review]
