### PR TITLE
Fixes #10543 : UI improvements and minor fixes

### LINKED ISSUE #10543: UI Feedback - 1.0
Let's add here all the feedback for the 1.0 release

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes:

Fixes :  #10543

- Fix collapse and expand for Linage in  DataModel - https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1506920717
- Fix the shadow on selected card of Explore cards - https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1506763129
- Added localization message for form input error - https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1501488509
- Fix the white background coming  before drawer while click on entity card in explore right panel - https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1501768075 
- Fix the url for storage service - https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1505271035

https://user-images.githubusercontent.com/66266464/231876080-51d0a6bd-e55b-45cc-b95c-f0d87a81b495.mov

https://user-images.githubusercontent.com/66266464/231877119-496a98fe-e3b6-4019-9494-0cbf4d544ac5.mov

https://user-images.githubusercontent.com/66266464/231877767-36c4cc59-6f9a-4bf2-8e74-ddba8b5ab871.mov

image

#
### Type of change:

- [x] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Review by harshach — APPROVED** [review]

File: openmetadata-ui/src/main/resources/ui/src/components/EntityLineage/EntityLineage.component.tsx [hunk 1]
```diff
@@ -1417,10 +1417,13 @@ const EntityLineageComponent: FunctionComponent<EntityLineageProp> = ({
...
       const allTableNodes = nodes.filter(
         (node) =>
-          node.type === EntityType.TABLE &&
-          isUndefined(tableColumnsRef.current[node.id])
+          [EntityType.TABLE, EntityType.DASHBOARD_DATA_MODEL].includes(
+            node.type as EntityType
+          ) && isUndefined(tableColumnsRef.current[node.id])
       );
 
+      console.log(allTableNodes);
```
Comment (chirag-madlani) [inline openmetadata-ui/src/main/resources/ui/src/components/EntityLineage/EntityLineage.component.tsx:1425]: remove

**Review by chirag-madlani — APPROVED** [review]
